initial CRA setup
threshold-network/token-dashboard pull request #1
Opened 2021-09-13 22:47 UTC by georgeweiler

major libraries installed with this PR:

- create-react-app
- eslint / prettier
- husky / lint-staged
- storybook
- chakra-ui

2021-09-14 07:50 UTC, michalsmiarowski requested changes
Looking good! 👍 Left some comments to look at before the merge

2021-09-14 07:50 UTC, michalsmiarowski commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
I think we can separate this into two different scripts where one will only show the eslint issues and the other one will fix them:

```suggestion
    "lint": "eslint '*/**/*.{js,ts,tsx}'",
    "lint:fix": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
```

We have similar code in the token dapp: 
https://github.com/keep-network/keep-core/blob/5d2a9f5361d924624994a68bc4f7efac9728feb6/solidity/dashboard/package.json#L48-L49

2021-09-14 07:50 UTC, michalsmiarowski commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
Similary to the code in dapp we can also add prettier scripts to execute with lint scripts:

```suggestion
    "lint": "eslint '*/**/*.{js,ts,tsx}'",
    "lint:fix": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
    "format": "npm run lint && prettier --check .",
    "format:fix": "npm run lint:fix && prettier --write ."
```

Thoughts?

2021-09-14 07:50 UTC, michalsmiarowski commented on src/stories/Button.stories.tsx
> +import React from 'react';
Correct me if I'm wrong but these are the files generated automatically by storybook, right?

I think we can remove them for now, unless we want to have them at the beginning to have some kind of example when writing our own stories (and the remove them later 😛 ).

I just like keeping it clean, so if we decide to remove it let's remove those files:
- `Button.stories.tsx`
- `Button.tsx`
- `Header.stories.tsx`
- `Header.tsx`
- `Page.stories.tsx`
- `Page.tsx`
- `button.css`
- `header.css`
- `page.css`

Thoughts?

2021-09-14 07:50 UTC, michalsmiarowski commented on .gitignore
> +.eslintcache
I would also like to point some things about commit messages. We should follow the best practices when writing a commit message/title. Here is a good article about it: https://chris.beams.io/posts/git-commit/

So the main thing I want you to look at is:
- Capitalize the subject line
- Use the imperative mood in the subject line

For example:
`testing the husky pre-commit hook` -> `Test the husky pre-commit hook`

2021-09-14 10:11 UTC, r-czajkowski requested changes
Good job! 👍. Left few comments to look at before merge.

2021-09-14 10:11 UTC, r-czajkowski commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
Since we have auto-formatting tools, adding the [`.git-blame-ignore-revs `](https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame) file is a good practice. What do you guys think about it?

2021-09-14 10:11 UTC, r-czajkowski commented on .eslintrc.js
> +        "plugin:prettier/recommended" // Enables eslint-plugin-prettier and eslint-config-prettier. This will display prettier errors as ESLint errors. Make sure this is always the last configuration
Can we move comment text above to wrap long text? I mean:
```
// Enables eslint-plugin-prettier and eslint-config-prettier...
//......
//....
"plugin:prettier/recommended"
```

2021-09-14 10:22 UTC, michalsmiarowski commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
I agree, we are using it in dapp and it works wonderful 💎

2021-09-14 14:10 UTC, georgeweiler commented on .eslintignore
> +src/stories
yep works for me

2021-09-14 14:28 UTC, georgeweiler commented on src/stories/Button.stories.tsx
> +import React from 'react';
Yeah agreed. How should we organize our stories? Should we just remove this entire stories folder and write storybook files in the same directories as their components?

2021-09-14 14:29 UTC, georgeweiler commented on .eslintrc.js
> +        "plugin:prettier/recommended" // Enables eslint-plugin-prettier and eslint-config-prettier. This will display prettier errors as ESLint errors. Make sure this is always the last configuration
I'm happy to just remove these comments actually, unless you think they're super helpful?

2021-09-14 14:34 UTC, georgeweiler commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
good idea. any issues using yarn here instead of npm?

2021-09-14 17:44 UTC, georgeweiler commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
wow I did not even know this existed. Could have been very useful for previous projects.

2021-09-14 18:06 UTC, georgeweiler commented on .env
> +SKIP_PREFLIGHT_CHECK=true
setting a resolution for `babel-loader` seems to have worked 👍

2021-09-14 18:08 UTC, georgeweiler commented on package.json
> +  },
good catch. Decided just to remove those rules, as I think the rules in our `.eslintrc.js` are good enough

2021-09-14 18:10 UTC, georgeweiler commented on .husky/.gitignore
> +_
yes, auto-generated. not quite sure what it's purpose is 🤔

2021-09-14 20:02 UTC, michalsmiarowski commented on src/stories/Button.stories.tsx
> +import React from 'react';
I think we should keep it in a separate directory (`stories`) as it is by default. But that's just my personal preference, I'm open to discuss if you prefer the other way 😉

2021-09-16 11:41 UTC, r-czajkowski requested changes

2021-09-16 13:09 UTC, r-czajkowski requested changes
Hooks works like a charm! 🚀

I've run `yarn format:fix` on my local machine and seems like some files need to be formatted. Once we commit auto-formatted changes, remember about adding this commit hash to the `.git-blame-ignore-revs` file.

2021-09-16 13:09 UTC, r-czajkowski commented on commitlint.config.js
> +  extends: ['@commitlint/config-conventional'],
We never used this convention and it seems more useful for automated tools rather than us (IMO) but maybe it's a good opportunity to dig into it and discuss with rest of the team. By adding `commit-msg` hook, I meant setting [`header-case`](https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md#header-case), [`header-max-length`](https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md#header-max-length)(I guess GH displays 80 chars as a title) and maybe other rules. Thoughts? 🤔

2021-09-18 21:02 UTC, georgeweiler commented on commitlint.config.js
> +  extends: ['@commitlint/config-conventional'],
I'm happy to go either way - I doubt the conventional config will get in our way

2021-09-18 21:03 UTC, georgeweiler commented on .lintstagedrc
> +  "*.js": "eslint --cache --fix"
good catch this must have been copy/paste leftover.

2021-09-19 12:02 UTC, mhluongo commented on commitlint.config.js
> +  extends: ['@commitlint/config-conventional'],
FWIW I follow a 50-char summary and 80-char body and I think a few others on the Keep side do as well

2021-09-21 11:33 UTC, r-czajkowski approved these changes
LGTM 👍. We can discuss the commit rules later and address it in a follow-up PR. Leaving final approval to @michalsmiarowski.

2021-09-21 15:12 UTC, nkuba commented on .eslintrc.js
> +module.exports = {
Do we need to add empty files like:
`.eslintignore`
`.git-blame-ignore-revs`
`.prettierignore`
?

2021-09-21 15:29 UTC, nkuba commented on commitlint.config.js
> +module.exports = {
We haven't been using commitlint in our projects yet. I'm afraid of it causing confusion for the team (it already did for me). Could we try to introduce and discuss it in a separate PR?

2021-09-21 20:07 UTC, georgeweiler commented on .eslintrc.js
> +    "plugin:prettier/recommended",
great suggestion

2021-09-21 20:07 UTC, georgeweiler commented on .eslintrc.js
> +module.exports = {
Good point. I think there may be some value to the `.git-blame-ignore-revs` file, but I've removed the others. I started a discussion on flowdoc for this

2021-09-22 07:54 UTC, nkuba commented on .eslintrc.js
> +module.exports = {
I'm fine with leaving the `.git-blame-ignore-revs`.

2021-09-22 07:55 UTC, r-czajkowski commented on .eslintrc.js
> +module.exports = {
I think we need `.eslintignore` and ` .prettierignore` files and we should ignore `/storybook-static` dir generated by `yarn build-storybook`. I've run `yarn build-storybook` and then `yarn format:fix`- the eslint and prettier were unable to format the code. Also, these two files should probably ignore `build` dir generated by `yarn build`.

Regarding `.git-blame-ignore-revs`: I'm good to keep this file even w/o any commit hash. Also, I think config files describe our standards. So if eg. a new developer(or community contributor) sees this file they will remember to add commit hash with bulk changes and will think like  "OK! In this project, developers don't want bulk changes in git blame" 😄.

2021-09-22 08:21 UTC, r-czajkowski commented on package.json
> +    "format:fix": "npm run lint:fix && prettier --write .",
Hope it's not too late in the game 😄. Shouldn't we use `yarn` instead of `npm`?

2021-09-22 10:50 UTC, pdyraga commented on commitlint.config.js
> +  extends: ['@commitlint/config-conventional'],
We should follow 50/80 rule but I think it is worth a separate PR to make sure the config presented in `commitlint.config.js` meets our guidelines.

2021-09-22 16:39 UTC, georgeweiler commented on package.json
> +    "format:fix": "npm run lint:fix && prettier --write .",
good catch, i've updated.

2021-09-22 16:42 UTC, pdyraga approved these changes
I did a quick pass, looks good to me, and I see all commits from other reviewers were addressed just like they requested. Let's 🚢

2021-09-22 16:42 UTC, pdyraga commented on package.json
> +{
We need to add a license and I think it should be GPLv3.

2021-09-22 16:43 UTC, merged

2021-09-22 16:43 UTC, pdyraga commented on commitlint.config.js
> +module.exports = {
Fixed in https://github.com/threshold-network/token-dashboard/pull/1/commits/ca82e0f50d7d203069b2e1e4d482bb5386f0bbde

2021-09-22 16:43 UTC, pdyraga commented on commitlint.config.js
> +  extends: ['@commitlint/config-conventional'],
Done in https://github.com/threshold-network/token-dashboard/pull/1/commits/ca82e0f50d7d203069b2e1e4d482bb5386f0bbde.