Bonus rewards
threshold-network/token-dashboard pull request #107
Opened 2022-05-09 16:17 UTC by r-czajkowski

WIP...

2022-05-12 17:51 UTC, michalsmiarowski requested changes
Left some comments to look at 👀

2022-05-12 17:51 UTC, michalsmiarowski commented on src/components/Modal/StakingBonus/EligibilityCard.tsx
> +  const isSecondRequirementMet = stake.bonusEligibility.hasPREConfigured
Based on [nucypher docs](https://docs.nucypher.com/en/latest/pre_application/running_a_node.html#qualify-node):

`
Nodes must be fully qualified: funded with ETH and bonded to an operator address, in order to fully start. Nodes that are launched before qualification will pause until they have a balance greater than 0 ETH, and are bonded to an Operator address.
`

Tthis means that to have a PRE node configured **and working** they need to have balance greater than 0 ETH. So maybe we should also check here if operator has more than 0 ETH and add it to second requirement?

2022-05-12 17:51 UTC, michalsmiarowski commented on src/components/StakingBonus/Title.tsx
> +  // TODO: Update dark mode colors.
Just pointing out this TODO here ☝️

2022-05-12 17:51 UTC, michalsmiarowski commented on src/hooks/useCheckBonusEligibility.ts
> +            ?.operatorConfirmedAt <= stakingBonus.BONUS_DEADLINE_TIMESTAMP
Could also check here if operator has more than 0 ETH and change the name to `hasPREConfiguredAndRunning`.

See two comments above for more info.

2022-05-13 06:43 UTC, r-czajkowski commented on src/components/Modal/StakingBonus/EligibilityCard.tsx
> +  const isSecondRequirementMet = stake.bonusEligibility.hasPREConfigured
Confirmed with David from NU that an `OperatorConfirmed` event is enough as a bonus requirement. cc @cygnusv.

2022-05-13 06:43 UTC, r-czajkowski commented on src/hooks/useCheckBonusEligibility.ts
> +            ?.operatorConfirmedAt <= stakingBonus.BONUS_DEADLINE_TIMESTAMP
Please see https://github.com/threshold-network/token-dashboard/pull/107#discussion_r872050139

2022-05-13 08:43 UTC, r-czajkowski commented on src/store/staking/stakingSlice.ts
> +      state.totalRewardsBalance = calculateTotalRewardsBalance(state)
6c34ea5f3d10072c329e53ced73e94cd7674309f

2022-05-13 08:44 UTC, r-czajkowski commented on src/store/staking/stakingSlice.ts
> +      state.totalRewardsBalance = calculateTotalRewardsBalance(state)
6c34ea5f3d10072c329e53ced73e94cd7674309f

2022-05-13 08:44 UTC, r-czajkowski commented on src/store/staking/stakingSlice.ts
> +      state.totalRewardsBalance = calculateTotalRewardsBalance(state)
6c34ea5f3d10072c329e53ced73e94cd7674309f

2022-05-13 11:25 UTC, michalsmiarowski requested changes
Left some more comments to look at

2022-05-13 11:25 UTC, michalsmiarowski commented on src/store/staking/stakingSlice.ts
>        state.stakes = [newStake, ...state.stakes]
Wouldn't it be better to add this `newStake` at the end? I think the stakes are show in chronilogical order when fetched from the chain.

```suggestion
      state.stakes = [...state.stakes, newStake]
```

2022-05-13 11:25 UTC, michalsmiarowski commented on src/utils/stakingBonus.ts
> +  dateToUnixTimestamp(date) <= stakingBonusConstants.BONUS_DEADLINE_TIMESTAMP
Non-blocking:

I think this function could be named better since it checks if it's before **or** equal. I was thinking about `isBeforeOrEqualBonusDeadline` but I'm not sure. Maybe we should name it event more precise which would be `isCurrentDateBeforeOrEqualBonusDeadline`? What do you think?

2022-05-13 12:01 UTC, r-czajkowski commented on src/utils/stakingBonus.ts
> +  dateToUnixTimestamp(date) <= stakingBonusConstants.BONUS_DEADLINE_TIMESTAMP
The date doesn't always point to the current date. You can pass any date as a param. It sets the current date by default. So I think `isBeforeOrEqualBonusDeadline` is better.

2022-05-13 12:09 UTC, r-czajkowski commented on src/store/staking/stakingSlice.ts
>        state.stakes = [newStake, ...state.stakes]
Tbh from my point of view is better to see the added record at the top of the list. So we should probably reverse the staked events array here https://github.com/threshold-network/token-dashboard/blob/main/src/hooks/useFetchOwnerStakes.ts#L28.

2022-05-13 12:27 UTC, r-czajkowski commented on src/store/staking/stakingSlice.ts
>        state.stakes = [newStake, ...state.stakes]
6c1ec13

2022-05-13 12:27 UTC, r-czajkowski commented on src/utils/stakingBonus.ts
> +  dateToUnixTimestamp(date) <= stakingBonusConstants.BONUS_DEADLINE_TIMESTAMP
4ad0551

2022-05-13 12:34 UTC, michalsmiarowski approved these changes
LGTM

2022-05-13 12:35 UTC, merged