Adds tbtc page template
threshold-network/token-dashboard pull request #120
Opened 2022-06-01 21:57 UTC by georgeweiler

2022-08-01 16:37 UTC, georgeweiler commented on scripts/start_dashboard.sh
> +# cd $RANDOM_BEACON_CONTRACTS_PATH
We should make sure to simplify this start script once we switch to Görli 👍

2022-08-01 16:39 UTC, georgeweiler commented on src/App.tsx
> +            !featureFlagsContext[FeatureFlag.TBTCV2].isActive &&
what do you think about creating a hook for easily accessing the feature flag context? I am thinking of a nice variable like:

```
 const showTbtcPage = useFeatureFlags(FeatureFlag.TBTCV2v)
```

and it could be used in the JSX. Just a thought.

2022-08-10 13:20 UTC, michalinacienciala commented
There's a problem with using `tbtc-v2.ts` dependency on Node.js `v16`/`v18`. Let's change the version of Node.js that we use in `dashboard-ci.yaml` and `dashboard-mainnet.yml` workflows from `16` to `14`. Also, let's add the upgrade of `tbtc-v2` and `tbtc-v2.ts` packages to the step ` Resolve latest goerli contracts` in `dashboard-ci.yaml`.

2022-08-11 14:05 UTC, r-czajkowski requested changes

2022-08-15 10:09 UTC, michalinacienciala commented
Let's also update https://github.com/threshold-network/token-dashboard/blob/tBTC-template/README.md#install-g%C3%B6rli-contracts

2022-08-22 13:28 UTC, michalsmiarowski commented on src/App.tsx
> +        })}
Fixed in 0e7f34fca9b3b89f6501dbfb56cab74b134660ed

2022-08-22 13:28 UTC, michalsmiarowski commented on src/App.tsx
> +            <FeatureFlagsContextProvider>
I refactored it so it now uses env variables: 0e7f34fca9b3b89f6501dbfb56cab74b134660ed

Let me know what you think

2022-08-23 09:29 UTC, michalsmiarowski commented on src/components/Modal/TbtcRecoveryFileModal/index.tsx
> +  const [isOnConfirmStep, setIsOnConfirmStep] = useState(false)
Fixed in efa8e347862a9a75557ed947569f7dd5698bb1eb

2022-08-23 09:30 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/components/TransactionDetailsTable.tsx
> +import { Skeleton, Stack } from "@chakra-ui/react"
I think this would be better to address in separate PR. I can take care of that after we merge this one. What do you think?

2022-08-24 10:09 UTC, r-czajkowski approved these changes

2022-08-24 13:48 UTC, michalsmiarowski approved these changes

2022-08-24 15:35 UTC, pdyraga approved these changes
Looked only at the change in `.github/workflows/dashboard-mainnet.yml` as it's protected by [CODEOWNERS](https://github.com/threshold-network/token-dashboard/blob/3aac913ebc207e2b270f70cd17a7c7651f4d26c2/CODEOWNERS#L1).

2022-08-24 15:40 UTC, merged