Add support for deployment on Goerli testnet
threshold-network/token-dashboard pull request #138
Opened 2022-07-21 13:53 UTC by michalinacienciala

Görli became a recommended test network after Ropsten's deprecation
notice (https://blog.ethereum.org/2022/06/21/testnet-deprecation/).
We're modifying our GitHub Actions workflows for deploying contracts
and dashboards to support the deployment on Görli. In this commit we're
modifying workflow for building/publishing T dabshoard for testing
purposes.

TODO:
- [ ] switch Ropsten-related code in `token-dashboard` repo to Goerli

2022-07-26 09:38 UTC, michalinacienciala commented on src/enums/web3.ts
> +  // Ropsten = 3,
I commented this out. Would it be better to remove it completely? (Same applies to other similar changes)

2022-07-27 08:36 UTC, r-czajkowski requested changes

2022-07-27 08:36 UTC, r-czajkowski commented on README.md
> +  @keep-network/keep-core@goerli \
Shouldn't we use `@keep-network/keep-core@1.8.1-goerli.0` as described in the workflow?

> We provide explicit version of the `keep-core` package, because using `goerli` tag results in `expected manifest` error - probably caused by bug in Yarn: https://github.com/yarnpkg/yarn/issues/4731.

2022-07-27 08:36 UTC, r-czajkowski commented on package.json
> +    "@keep-network/tbtc": "development",
Why do we use `development`? Shouldn't we use a range?

2022-07-27 08:36 UTC, r-czajkowski commented on package.json
> +    "@threshold-network/solidity-contracts": "development",
Same as above.

2022-07-27 08:36 UTC, r-czajkowski commented on src/enums/web3.ts
> +  // Ropsten = 3,
I think we can remove it completely. We can always use `git revert` if we want to restore the ropsten config.

2022-07-27 12:00 UTC, michalinacienciala commented on package.json
> +    "@keep-network/tbtc": "development",
Generally, we want the dependencies to be resolved to the latest packages meant for the development environment during `yarn install`. In the past we've been using ranges (which had a disadvantage of need of often updates - every time a version got bumped up), but since we started to tag the latest `-dev` packages with `development` tag, we can use that in the `package.json`. We use similar notation for example for `random-beacon`'s dependencies: https://github.com/keep-network/keep-core/blob/main/solidity/random-beacon/package.json#L38.

2022-07-27 12:01 UTC, michalinacienciala commented on package.json
> +    "@threshold-network/solidity-contracts": "development",
Same as above :)

2022-07-27 12:09 UTC, michalinacienciala commented on src/enums/web3.ts
> +  // Ropsten = 3,
78c0db2e6e804ff86b9b7ff9b74022e60d067fe9

2022-07-27 12:10 UTC, michalinacienciala commented on README.md
> +  @keep-network/keep-core@goerli \
You're right. I wrote README before realizing that the command does not work properly and forgot to update it later. Fixed in 59e2529426118ebe85ec635a338a5861adf8b43d.

2022-07-27 12:57 UTC, r-czajkowski commented on package.json
> +    "@keep-network/tbtc": "development",
Ahh I see, the `development` is the tag name. Nice 🚀.

2022-07-28 10:53 UTC, r-czajkowski approved these changes
LGTM! Tested on preview and it works! :shipit:

2022-07-28 10:53 UTC, merged