Adds the min-mid-max radio group for MAS
threshold-network/token-dashboard pull request #141
Opened 2022-07-29 15:44 UTC by georgeweiler

This selector/radio component will be used for the multi-app-staking feature. It includes a simple API with an `onRadioClick` function that accepts enum `MinMidMaxValue` to catch click events and update necessary parent state.

![Screen Shot 2022-07-29 at 9 42 04 AM](https://user-images.githubusercontent.com/15269424/181795620-3c49e430-60c2-42ad-92eb-0f444cfd0987.png)
.

2022-08-03 16:58 UTC, michalsmiarowski requested changes
Left some comments to look at

2022-08-03 16:58 UTC, michalsmiarowski commented on src/components/MinMidMaxRadio/index.tsx
> +  const _onRadioClick = (value: MinMidMaxValue) => {
Can we change the name of the prop to `val`, because right now it has the same name as the `value` from `useState`. Would prefer to not mix that.

```suggestion
  const _onRadioClick = (val: MinMidMaxValue) => {
```

2022-08-03 16:58 UTC, michalsmiarowski commented on src/components/MinMidMaxRadio/index.tsx
> +        <Radio size="lg" colorScheme="brand" defaultChecked value={value}>
Why we use `defaultChecked` prop here? Is it really needed?

2022-08-08 15:37 UTC, sashatanase commented
@georgeweiler we will change this component so please do not focus on it.

2022-08-15 14:30 UTC, michalsmiarowski commented
@georgeweiler This component did not make it to the final version, so I think we should close this PR

2022-08-15 14:37 UTC, closed without merging