Top Nav & Wallet connection modal
threshold-network/token-dashboard pull request #15
Opened 2021-10-12 23:04 UTC by georgeweiler

- Adds top navbar with mobile designs & darkmode switcher, network button and connect walllet button
- Adds wallet connection modal with support for Metamask, Ledger and WalletConnect

2021-10-13 15:04 UTC, r-czajkowski commented on src/utils/chainIdToNetworkName.ts
> +import { ChainID } from "../types"
It's a general comment for all utils files- I think would be good to unit test utils. I know we mainly focus on the integration test but unit test for utils, services or external lib wrappers(eg. `connectors/ledger.ts`) is always a good idea. Just a thought.

2021-10-13 18:47 UTC, michalsmiarowski requested changes
Left some comments to look at below:

2021-10-13 18:47 UTC, michalsmiarowski commented on src/static/icons/Ethereum.tsx
> +    </svg>
Do we have those icons on Figma? If yes, then I think we should download them and keep them in `static/icons` directory as `.svg` files.

In the KEEP Token Dashboard we are keeping all the icon components inside one file - `Icons.tsx` component.

If we have svgs we can turn them into components easily by doing:
`export { ReactComponent as Ethereum } from "../static/svg/ethereum-logo.svg"`
in the `Icons.tsx` file. More complicated Icons component could also be created and exported there.

Finaly I would create a constant for Icons. For this we would need a new directory `constants` and new file - `icons.ts`. There I would import all the icons from `Icons.tsx` component:
`import * as icons from '(...)/Icons.tsx'`

and export it as constant:
`export const ICONS = {...icons}`

**Note**: The code was not tested so you might need to change something, but I think this should work.

Thanks to this, we will be able to use icons as `ICONS.Ethereum` or `ICONS.Ledger`.

I'm not sure about naming convention for the constants in TypeScript tho 🤔 

Thoughts about this @georgeweiler @r-czajkowski ?

2021-10-13 18:47 UTC, michalsmiarowski commented on src/stories/navbar.stories.tsx
> +      description: "The connected ethereum network",
Can we also add a description for `openModal`, `account`, and `deactivate` props?

2021-10-13 18:47 UTC, michalsmiarowski commented on src/web3/connectors/ledger.ts
> +    console.log("activating@! ", this.provider)
I think those console.logs are unnecessary. Let's remove all of them from this file before merging.

2021-10-13 19:13 UTC, georgeweiler commented on src/components/Modal/SelectWalletModal/index.tsx
> +        <Text fontSize="24px">Connect a Wallet</Text>
resolving so we can discuss further: https://github.com/threshold-network/token-dashboard/pull/15#discussion_r728358623

2021-10-13 19:15 UTC, georgeweiler commented on .env
> +HTTPS=true
alright this is fine for me. I created a ticket for the readme here: https://keepnetwork.atlassian.net/browse/DAPP-269

2021-10-13 19:41 UTC, georgeweiler commented on src/components/Navbar/NavbarComponent.tsx
> +          )}
oooh yeah I like this idea, but let's hold off on this one. [Designs are still in flux](https://discord.com/channels/893441201628405760/893457138079399936/897880718124920884) and it's messy to pass the network icon into the button. Once we have mobile designs figured out I think it will be obvious how to pull it out. Thoughts?

2021-10-13 19:57 UTC, georgeweiler commented on src/components/Navbar/NavbarComponent.tsx
> +}) => {
no problem ;)

2021-10-13 23:40 UTC, georgeweiler commented on src/components/Navbar/WalletButton.tsx
> +    </>
Designs are still in flux on this, so let's wait until we know exactly what Liz and Sasha want.

2021-10-14 07:18 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/InitialSelection.tsx
> +    <VStack divider={<StackDivider margin="0 40px !important" />}>
What about `as` prop? So it could be:
```
<Vstack as="ul"....>
 <Box as="li">
  ...
 <Box/>
<Vstack>
```

2021-10-15 20:29 UTC, georgeweiler commented on package.json
> +    "@types/ledgerhq__hw-transport-node-hid": "^4.22.2",
remove this

2021-11-11 16:09 UTC, Battenfield submitted a review, later dismissed

2021-11-11 16:09 UTC, Battenfield commented
Ticketing out small items, merging to get everyone on the same branch

2021-11-15 21:37 UTC, michalsmiarowski requested changes
Left some comments to look at 😇

2021-11-15 21:37 UTC, michalsmiarowski commented on src/components/TokenBalanceInput/index.tsx
> +  icon: any
I think we should avoid using 'any' type as much as possible, because it is [similar to putting an @ts-ignore around every single use of the variable](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any). Because of that by the quick look I'm not able to tell if we should use string here or Icon component or something else.

I think we are using the Icons that we created from `createElement` function from Chakra (correct me if I'm wrong) so we can define type like this:
```suggestion
  icon: ReturnType<typeof createIcon>
```

2021-11-15 21:37 UTC, michalsmiarowski commented on src/stories/tokenBalanceInput.stories.tsx
> +  const Icon = iconMap[icon]
Continuing my thought from the previous comment - we can create a new interface in `utils.ts`:

```
import { createIcon } from "@chakra-ui/icons"

export interface ChakraIconMap {
  [key: string]: ReturnType<typeof createIcon>
}
```

and then we can use it here and get rid of `@ts-ignore`:
```suggestion
const iconMap: ChakraIconMap = {
  Nu: Nu,
  Keep: Keep,
}

const Template: Story<TokenBalanceInputProps> = ({ icon, max, label }) => {
  const [amount, setAmount] = useState<string | number>("")
  const Icon = iconMap[icon]
```

2021-11-15 21:37 UTC, michalsmiarowski commented on src/enums/web3.ts
> +}
Can we also add chain ID for the local Ganache?

```suggestion
export enum ChainID {
  Ethereum = 1,
  Ropsten = 3,
  Localhost = 1337,
}
```

2021-11-15 21:37 UTC, michalsmiarowski commented on src/utils/isSupportedNetwork.ts
> +const supportedChainIds = [ChainID.Ethereum, ChainID.Ropsten]
Based on comment above:

```suggestion
const supportedChainIds = [ChainID.Ethereum, ChainID.Ropsten, ChainID.Localhost]
```

2021-11-15 21:37 UTC, michalsmiarowski commented on src/utils/chainIdToNetworkName.ts
> +}
Based on comment above:

```suggestion
const networkMap: NetworkMap = {
  [ChainID.Ethereum]: "Ethereum",
  [ChainID.Ropsten]: "Ropsten Test",
  // 4: "Rinkeby",
  // 5: "Goerli",
  // 42: "Kovan",
  [ChainId.Localhost]: "Localhost",
}
```

2021-11-15 21:37 UTC, michalsmiarowski commented on src/web3/connectors/ledger_subprovider.ts
> +    const path = this._baseDerivationPath.replace("x", index)
`getPath()` is a public method that returns `_baseDerivationPath` so we should use it:

```suggestion
    const path = this.getPath().replace("x", index.toString())
```

2021-11-15 21:37 UTC, michalsmiarowski commented on src/web3/connectors/ledger_subprovider.ts
> +        this._shouldAlwaysAskForConfirmation,
For now I'm not sure how to get rid of those `@ts-ignore`s, so let's keep it as it is 😅

2021-11-17 10:47 UTC, r-czajkowski approved these changes

2021-11-17 10:48 UTC, r-czajkowski approved these changes

2021-11-17 11:10 UTC, michalsmiarowski approved these changes
LGMT :shipit:

2021-11-17 11:14 UTC, merged