[WiP] Multi app staking - authorize applications
threshold-network/token-dashboard pull request #156
Opened 2022-08-15 14:28 UTC by michalsmiarowski

2022-08-24 16:22 UTC, michalsmiarowski commented on .env
> +REACT_APP_ETH_HOSTNAME_WS=wss://goerli.infura.io/ws/v3/33593948cb074eea8e65ae716fc61afd
@georgeweiler I think it would be better to put goerli contracts integration in a separate PR. For now I'm gonna revert the changes made in [this PR](https://github.com/threshold-network/token-dashboard/pull/156/commits/3280681efe9d87535f87062246a5f766aa79f34f) in `.env`, `package.json` and `yarn.lock` files because it makes it harder to resolve conflicts when merging `main` into this branch.

2022-08-26 10:40 UTC, michalsmiarowski commented on src/components/CopyToClipboard/index.tsx
> +          mr={2}
I removed the margin in this commit a1cbb1c9e84d64601e9906871b5ee4f76d449c0d

Let me know if the margin is needed and i'll revert it back :)

2022-08-26 11:19 UTC, michalsmiarowski commented on src/theme/Checkbox.ts
> +}
Non-blocking:

We export Checkbox from chakra components so i believe this should be placed in `components` repo.

There is also similar issue with Radio theme in https://github.com/threshold-network/token-dashboard/pull/162 (see comment - https://github.com/threshold-network/token-dashboard/pull/162#discussion_r953956585)

Let's merge this and #162 to the main and i'll move it to `components` repo in separate PR.

2022-08-26 11:23 UTC, michalsmiarowski commented
@georgeweiler I see that you've also added 4 png images in this PR:

- [andomBeaconDecrease.png](https://github.com/threshold-network/token-dashboard/pull/156/commits/3280681efe9d87535f87062246a5f766aa79f34f#diff-79455b1527fb7062885b9414c21ef685eb0b6370c7882e62dec9ed88d4bb4f30)
- [randomBeaconIncrease.png](https://github.com/threshold-network/token-dashboard/pull/156/commits/3280681efe9d87535f87062246a5f766aa79f34f#diff-1263b17d116ef80dbffdb2085708c19c3379c93c878ebb5ed6d789a2b6cdcfe1)
- [tbtcDecrease.png](https://github.com/threshold-network/token-dashboard/pull/156/commits/3280681efe9d87535f87062246a5f766aa79f34f#diff-bd36172fcf44603e1d13a76e90b85ccf5c534a75e2d02408873c58dfc8ad242e)
- [tbtcIncrease.png](https://github.com/threshold-network/token-dashboard/pull/156/commits/3280681efe9d87535f87062246a5f766aa79f34f#diff-0c4259098fb941d40727df207c8abc0c636d1e08fd91d3a85b5617dbad0e87c6)

I don't see we are using them anywhere though. Are they needed for some future features? Can you give me a link to Figma when we are using those images?

2022-08-26 17:20 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +              colorScheme={isInActiveStake ? "gray" : "green"}
nit: let's update this var name to `isInactiveStake`

2022-08-26 18:12 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +          isSelected={selectedApps.map((app) => app.label).includes("tBTC")}
What do you think about writing these repeated maps as a useMemo?

```
  const { isTbtcSelected, isPreSelected, isRandomBeaconSelected } =
    useMemo(() => {
      const labels = selectedApps.map((app) => app.label)

      return {
        isTbtcSelected: labels.includes("tBTC"),
        isPreSelected: labels.includes("Random Beacon"),
        isRandomBeaconSelected: labels.includes("PRE"),
      }
    }, [selectedApps])
```

2022-08-26 18:15 UTC, georgeweiler commented on src/components/CopyToClipboard/index.tsx
> +          mr={2}
The margin separates the icon from the text when you hover.

2022-08-29 13:48 UTC, r-czajkowski requested changes

2022-08-29 13:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +  const tBalance = useTokenBalance(Token.T)
We should use the staked amount for a given staking provider. We can get this value from `StakeData` interface- `totalInTStake` field. We should probably pass it as a prop.

2022-08-29 13:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +  const minStakeAmount = useMinStakeAmount()
It should be `minAuthAmount` and we should pass the value as a prop. Each application can have a different minimum authorization amount.

2022-08-29 13:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +            helperText={`Minimum 40,000 T for ${appAuthData.label}`}
We should render this text using `minAuthAmount` prop see comment above.

2022-08-29 13:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +            }`}
Not sure if we should duplicate this info in a placeholder- we have almost the same text in `helperText` prop. Based on the Figma views it should be `Enter Amount` 🤔.

2022-08-29 13:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  const stakes = useSelector((state: RootState) => state.staking.stakes)
We can use `selectStakes` from `./stpre/staking/selectors`.

2022-08-29 13:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +    <H5>Please connect your wallet</H5>
Maybe we should update the text to include an authorizer address?

2022-08-29 13:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  path: "authorize/:authorizerAddress",
Shouldn't be the `stakingProviderAddress` here? Based on the staking provider address we should check if the authorizer address of this stake is the same as the currently logged account(owner account because we navigate to this view from the owner's perspective). If the authorizer address is different than currently logged account we should display `Please connect your wallet as an authorizer <authorizer address here>`.

2022-08-29 13:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +      return isSameETHAddress(stake.authorizer, authorizerAddress)
We should compare the currently logged account with `stake.authorizer`. Please see comment above.

2022-08-29 14:20 UTC, r-czajkowski requested changes

2022-08-29 14:20 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/StakeApplications/AuthorizeApplicationRow.tsx
> +        </Button>
Let's add `as` prop `as={RouterLink}` to render `a` tag instead of button. We can build the link to the `auth` page based on the staking provider address.

2022-08-29 14:20 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
> +  }
Please see comment above.

2022-08-29 14:20 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
> +  }
It should also be `stake.stakingProvider`.

2022-08-29 14:20 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
> +      </Button>
We can render the link that looks like a button. Let's use `as` prop. See some comments above.

2022-08-29 14:20 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/index.tsx
> +          <StakeApplications stake={stake} />
I think we can create a context for a `StakeCard` so we can avoid props drilling. Also we can pass to the context  these values:
- `isInActiveStake`,
- `canTopUpKepp`,
- `canTopUpNu`,
- `hasLegacyStakes`.

What do you think?

2022-08-29 14:20 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/index.tsx
> +      <StakeAddressInfo stake={stake} />
Same as above.

2022-08-29 14:20 UTC, r-czajkowski commented on src/types/page.ts
> +  hideFromMenu?: boolean
See this comment https://github.com/threshold-network/token-dashboard/pull/156#discussion_r957282843 .

2022-08-29 14:31 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +          isSelected={selectedApps.map((app) => app.label).includes("tBTC")}
Still, this will be triggered on every render because the `selectedApps` is an array so to achieve this we would have to memoize the `selectedApps` prop. Also, there are only 3 apps in an array so I think we shouldn't worry about the optimization 🤔.

2022-08-29 14:58 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +          isSelected={selectedApps.map((app) => app.label).includes("tBTC")}
sounds good

2022-08-30 12:56 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/index.tsx
> +          <StakeApplications stake={stake} />
I agree! But I think such change can easily break something if we overlook something so I would prefer to address this in a separate PR. After I address all the comments in this PR I will create new one from this branch

2022-08-30 13:04 UTC, michalsmiarowski commented on .env
> +REACT_APP_FEATURE_FLAG_MULTI_APP_STAKING=false
Fixed in 3a31568929df8c6fe2fcff6761e24f6a2ee776da

2022-08-30 13:04 UTC, michalsmiarowski commented on .env.production
> +REACT_APP_FEATURE_FLAG_MULTI_APP_STAKING=false
Fixed in 3a31568929df8c6fe2fcff6761e24f6a2ee776da

2022-08-30 13:05 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/StakeInfo.tsx
> +import { VStack, HStack, Badge, StackProps, Icon } from "@chakra-ui/react"
Fixed in fdaf7432c5a2a1e37aa3a5bfde4bb3895cc3e1fd

2022-08-30 13:05 UTC, michalsmiarowski commented on src/App.tsx
> +        })}
I agree! Good idea!

Fixed in 7928feba8b86d2e36e0433c4770382cd6f19fa49

2022-08-30 13:05 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/StakeInfo.tsx
> +export const StakeInfo: FC<StakeInfoProps> = ({
Fixed in 1cbbd18d4b9b5a00c7743dac5398ccb347845e54

2022-08-30 13:08 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +            }`}
Fixed in c96d18857996fd63cc6616acabaf6ea2d1208ec9

2022-08-30 13:09 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  const stakes = useSelector((state: RootState) => state.staking.stakes)
Fixed in 901897101beb5336eb66c9d7bc7c61f0a81af939. I've used `selectStakeByStakingProvider` selector.

2022-08-30 13:11 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +    <H5>Please connect your wallet</H5>
Fixed in 901897101beb5336eb66c9d7bc7c61f0a81af939 partially, because I'm not sure how can I get authorizer address here, if the user is not connected and there are no stakes fetched in the store.

2022-08-30 13:11 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  path: "authorize/:authorizerAddress",
Fixed in 901897101beb5336eb66c9d7bc7c61f0a81af939

2022-08-30 13:11 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +      return isSameETHAddress(stake.authorizer, authorizerAddress)
Fixed in 901897101beb5336eb66c9d7bc7c61f0a81af939

2022-08-30 13:12 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  const { authorizerAddress } = useParams()
Fixed in 978992826ed6a4e0623594e68914959ec96eb826

2022-08-30 13:13 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/Header/index.tsx
> +  isActive,
Fixed in d001a194ce02312c6428aa928017c6f151cb7a77

2022-08-30 13:13 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/Header/index.tsx
> +      <Switcher onClick={onSwitcherClick} isActive={isActive} />
Fixed in aff87a53bab5ee8289d87ddbe1ef32a5535a0c2b

2022-08-30 13:13 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/StakeAddressInfo/index.tsx
> +import { Flex } from "@chakra-ui/react"
Fixed in e1a75ab11020cb0c84a25071f15cf096d3d91698

2022-08-30 13:13 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/Header/index.tsx
> +import { Flex } from "@chakra-ui/react"
Fixed in e1a75ab11020cb0c84a25071f15cf096d3d91698

2022-08-30 13:13 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/StakeApplications/AuthorizeApplicationRow.tsx
> +        </Button>
Fixed in 6e739ee013cf5fd8eae1a43e284ca82a239361c2

2022-08-30 13:14 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
> +  }
Fixed in 6e739ee013cf5fd8eae1a43e284ca82a239361c2

2022-08-30 13:14 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
> +      </Button>
Fixed in 6e739ee013cf5fd8eae1a43e284ca82a239361c2

2022-08-30 13:28 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +  const tBalance = useTokenBalance(Token.T)
`totalInTStake` -> `maxAuthAmount` ? I think the `maxAuthAmount` fits better here.

2022-08-30 13:38 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +    <H5>Please connect your wallet</H5>
We should fetch data on mount:
- the authorizer address- we can get the authorizer address by staking provider using [`rolesOf`](https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/TokenStaking.sol#L1253-L1269) function
- the authorization data for a given staking provider.

Ofc we can address it later.

2022-08-30 13:45 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +            helperText={`Minimum 40,000 T for ${appAuthData.label}`}
Fixed in 3bb1885826d3e0086c7f88b0bbcf780a8946e4fc

2022-08-30 13:46 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  const { authorizerAddress } = useParams()
I'm ok with `stakingProviderAddress` name instead of `addressFromUrl` but up to you. Non-blocking comment ofc 😄.

2022-08-30 13:52 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/Header/index.tsx
> +      <Switcher onClick={onSwitcherClick} isActive={isActive} />
I think now we can get rid of the `pages/Staking/Switcher.tsx` component.

2022-08-30 14:45 UTC, r-czajkowski commented on src/pages/PageLayout.tsx
I think we can assume that if the `PageComponet` doesn't include the `title` prop in `route` field we won't display the navigation link to this page in the header rendered by [`PageLayout`](https://github.com/threshold-network/token-dashboard/blob/main/src/pages/PageLayout.tsx#L18) component. Then we can create page components for:
- `staking/<provider>`- this link will automatically redirect to `staking/<provider>/overview` or `staking/<provider>/authorization` and this page component should render the header with navigation links to `Overview` and `Authorization` pages,
- `staking/<provider>/overview`- overview page for a staking provider,
- `staking/<provider>/authorization`- authorization page for a given staking provider,

```tsx
const StakingProviderDetails: PageComponent = (props) => {
  return (
    <>
      <Box as="header">Header here with links: Overview/Authorization</Box>
      <Outlet />
    </>
  )
}

const Overview: PageComponent = () => {
  const { stakingProvider } = useParams()

  return <H1>Staking provider {stakingProvider} overview</H1>
}

const Auth: PageComponent = () => {
  const { stakingProvider } = useParams()

  return <H1>Staking provider {stakingProvider} auth</H1>
}

const MainStakingPage: PageComponent = (props) => {
  return <PageLayout {...props} />
}

StakingProviderDetails.route = {
  path: ":stakingProvider",
  index: false,
  pages: [Overview, Auth],
  isPageEnabled: true,
}

Overview.route = {
  path: "overview",
  index: true,
  isPageEnabled: true,
}

Auth.route = {
  path: "auth",
  index: false,
  isPageEnabled: true,
}

MainStakingPage.route = {
  path: "staking",
  index: true,
  pages: [StakingPage, HowItWorksPage, StakingProviderDetails],
  title: "Staking",
  isPageEnabled: true,
}
```

2022-08-30 14:48 UTC, r-czajkowski commented on src/pages/PageLayout.tsx
![obraz](https://user-images.githubusercontent.com/57687279/187468247-65adfc37-3b66-4f62-af76-e943ea008cfc.png)
![obraz](https://user-images.githubusercontent.com/57687279/187468390-321db547-a4d1-4dfd-a1fc-e716ff4d9394.png)

2022-08-30 14:52 UTC, r-czajkowski commented on src/pages/PageLayout.tsx
The "only" thing we have to improve is rendering the navigation links in the first navigation header(we shouldn't display the divider for the last element see `How it Works` link) and making `Staking` link active for nested routes. Let me know what you think.

2022-08-31 12:06 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/Header/index.tsx
> +      <Switcher onClick={onSwitcherClick} isActive={isActive} />
Fixed in 22b0abdce082f528e1c69e535e0cb6e215234b5e

2022-08-31 13:11 UTC, r-czajkowski submitted a review, later dismissed
Looking good 👍. Let's address routing and unresolved comments in a separate PRs to unblock others.

2022-08-31 14:50 UTC, r-czajkowski approved these changes
:shipit:

2022-08-31 14:52 UTC, merged