test
threshold-network/token-dashboard pull request #159
Opened 2022-08-17 20:34 UTC by nkuba

2022-09-05 10:19 UTC, michalinacienciala requested changes

2022-09-05 10:19 UTC, michalinacienciala commented on .github/workflows/build-and-publish.yml
> +          bucket-path: ${{ github.head_ref }}
Have you tested if deployment works ok when the reusable workflow gets executed by the parent job that got triggered by the `workflow_dispatch` or `push` events? Normally (for non-reusable workflows) the `github.head_ref` variable is available only when event triggering workflow is `pull_request`. For other triggers, the variable resolves to an empty value and the `bucket-path` input won't get passed to the runner, causing the mixup in the parameters in the `thesis/gcp-storage-bucket-action` action. I would expect to see similar behaviour here in the step executed via reusable workflow. If this doesn't work correctly, we can do a workaround similar to what we had in the code previously, as got introduce in this PR: https://github.com/threshold-network/token-dashboard/pull/160/.

2022-09-05 10:19 UTC, michalinacienciala commented on .github/workflows/build-and-publish.yml
> +      gcpBucketPath:
We define the input, but never use it.

2022-09-05 16:08 UTC, michalinacienciala commented on .github/workflows/build-and-publish.yml
> +      # @keep-network/tbtc-v2 once they'll be added as dashboard's dependencies.
Also, there's an open PR that adds `random-beacon` and `ecdsa` dependency to the dashboard: #165. If it gets merged before #159 we'll need to include the new dependencies here as well.

2022-09-07 12:46 UTC, michalsmiarowski commented on .github/workflows/build-and-publish.yml
> +      # @keep-network/tbtc-v2 once they'll be added as dashboard's dependencies.
#165 was merged today @michalinacienciala

2022-09-13 13:47 UTC, michalinacienciala commented on .github/workflows/build-and-publish.yml
> +      gcpBucketPath:
We now use the input, see [eae00fb](https://github.com/threshold-network/token-dashboard/pull/159/commits/eae00fb73671914a1d690a761b14e4584c1d2a04).

2022-09-13 13:49 UTC, michalinacienciala commented on .github/workflows/build-and-publish.yml
> +          bucket-path: ${{ github.head_ref }}
I confirmed that using `bucket-path: ${{ github.head_ref }}` does not work when parent workflow gets triggered via `workflow_dispatch` or `push` events. Addressed in [eae00fb](https://github.com/threshold-network/token-dashboard/pull/159/commits/eae00fb73671914a1d690a761b14e4584c1d2a04).

2022-09-13 13:50 UTC, michalinacienciala commented on .github/workflows/build-and-publish.yml
> +      # @keep-network/tbtc-v2 once they'll be added as dashboard's dependencies.
I added the support for new dependencies when resolving merge conflicts (see [9f8c600](https://github.com/threshold-network/token-dashboard/pull/159/commits/9f8c600e270fee13ee9c6c2e6f60d0a68fc356db)).

2022-09-13 13:52 UTC, michalinacienciala commented
@nkuba, please review my additions. I verified the `workflow_dispatch` path in https://github.com/threshold-network/token-dashboard/actions/runs/3045394375/jobs/4907017216 - it failed because the `-wip` suffixed bucket that I used for testing was non-existing, but it can be seen in the logs that correct command was executed.

2022-09-20 06:55 UTC, michalinacienciala approved these changes
I'm marking the PR as approved, to unblock the merging. But before we merge let's have a :+1: from @nkuba on changes that I've added.

2022-09-20 08:34 UTC, nkuba commented
✅ LGTM

2022-09-20 08:35 UTC, merged