New apps authorize modal
threshold-network/token-dashboard pull request #162
Opened 2022-08-18 21:59 UTC by georgeweiler

Creates the modal that will display for users who have not authorized any applications yet.

designs:
https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=4872%3A387918

2022-08-24 15:39 UTC, michalsmiarowski requested changes
Looks good! 👍  Left some comments to look at before the merge

2022-08-24 15:39 UTC, michalsmiarowski commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +          disabled={selectedAuthorizeAddress === ""}
I think we can simplify it to just:

```suggestion
          disabled={!selectedAuthorizeAddress}
```

2022-08-24 15:39 UTC, michalsmiarowski commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +    if (selectedAuthorizeAddress.length > 0) {
Same as above I'm pretty sure this can be simplified to:

```suggestion
    if (selectedAuthorizeAddress) {
```

2022-08-24 15:39 UTC, michalsmiarowski commented on src/theme/Radio.ts
> +}
Non-blocking: 

I think this should probably be moved to the `components` repo, but maybe let's merge this like this first, and them move it to `components` repo in separate PRs

2022-08-24 15:39 UTC, michalsmiarowski commented on src/pages/Overview/Network/StakingOverview.tsx
> +      </Button>
Let's remember to remove that before the merge

2022-08-24 17:12 UTC, georgeweiler commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +            ))}
🙈

2022-08-24 17:15 UTC, georgeweiler commented on src/theme/Radio.ts
> +}
why move to components? This feels like a pure theme file to me

2022-08-25 14:25 UTC, michalsmiarowski commented on src/theme/Radio.ts
> +}
I think it suits the `components` repository better because it's a theme for a Radio component from chakra, and we export all chakra components form the `components` lib.

2022-08-30 18:44 UTC, georgeweiler commented on src/theme/Radio.ts
> +}
Ah, yes I misread - thought you wanted to move to the `/src/components` directory. Yes, I agree this should be in the `@threshold-network/components` repo. I do wonder if it's a simple task to "extend" the theme for imports from chakra like this one 🤔

2022-08-31 22:39 UTC, michalsmiarowski requested changes
Left some more comments to look at 👀

2022-08-31 22:39 UTC, michalsmiarowski commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +      navigate(`/authorize/${selectedAuthorizerAddress}`)
Is this route correct? Shouldn't it be:

```suggestion
      navigate(`/staking/authorize/${selectedAuthorizerAddress}`)
```

2022-08-31 22:43 UTC, michalsmiarowski commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +            {stakes.map((stake, i) => (
I think this modal is displayed from the banner on the Overview page. We can probably hide the banner for not connected users but like you said, the modal itself should not care about when or why it's rendered 😃

2022-09-01 15:28 UTC, georgeweiler commented
Hey @michalsmiarowski  I just fixed up those small issues. Thanks for catching

2022-09-01 18:18 UTC, michalsmiarowski requested changes
@georgeweiler Found additional issue after the changes. See comment below

2022-09-01 18:18 UTC, michalsmiarowski commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +        </Button>
Since the button is now wrapped as `RouterLink` the additional bug showed up. When there are no stakes, or there aren't any selected stakes, the Continue button, even though it looks disabled, still works when you click it.

I found a workaround in [this issue](https://github.com/remix-run/react-router/issues/1082#issuecomment-160348163) but it seems little dirty. For our case it will look like this:

```suggestion
        <Button
          mr={2}
          as={RouterLink}
          to={`/staking/authorize/${selectedAuthorizerAddress}`}
          onClick={closeModal}
          disabled={!selectedAuthorizerAddress}
          style={{ pointerEvents: selectedAuthorizerAddress ? "auto" : "none" }}
        >
          Continue
        </Button>
```

Let me know what you think. Feel free to search for another solution because, like I said, this one is not pretty 😅

2022-09-05 16:59 UTC, georgeweiler commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +        </Button>
great catch. I don't mind the css to disable it.

2022-09-06 11:50 UTC, michalsmiarowski commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +  const [selectedAuthorizerAddress, setSelectedAuthorizerAddress] = useState("")
That's actually a great catch! I think we should check `stakingProvider`, not `authorizer`, because when there are multiple stakes with same `authorizer` then when we select one of them, then all of them are being selected:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/40306834/188627455-a6060bf4-af77-4d00-8652-d6028059e795.png">

Stake 1 and Stake 3 have the same authorizer

2022-09-06 11:58 UTC, michalsmiarowski commented on src/components/Modal/NewAppsToAuthorizeModal/index.tsx
> +  const [selectedAuthorizerAddress, setSelectedAuthorizerAddress] = useState("")
That's actually a great catch! I think we should check `stakingProvider`, not `authorizer`, because when there are multiple stakes with same `authorizer` then when we select one of them, then all of them are being selected:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/40306834/188627455-a6060bf4-af77-4d00-8652-d6028059e795.png">

Stake 1 and Stake 3 have the same authorizer

2022-09-08 14:19 UTC, michalsmiarowski approved these changes
LGTM

2022-09-09 12:11 UTC, michalsmiarowski approved these changes
LGTM 🚀

2022-09-09 12:12 UTC, merged