Deauthorization Modal - Step 1
threshold-network/token-dashboard pull request #163
Opened 2022-08-19 15:54 UTC by georgeweiler

Adds the confirmation modal for deauthorizing an application

![Screen Shot 2022-08-19 at 9 54 12 AM](https://user-images.githubusercontent.com/15269424/185658611-5f90744a-41fb-449a-810e-88c3be9393c6.png)

2022-08-26 14:07 UTC, michalsmiarowski requested changes
Looking good 👍 Left some comments to look at before the merge

2022-08-26 14:07 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +              {numeral(decreaseAmount).format("0,0")} T
Didn't test but maybe we can use `TokenAmount` component here?

2022-08-26 14:07 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +import { FC } from "react"
(line above not related)

Let's try to avoid naming commits without any context like this one - 31ac478e49317519ca982396c4ec8b4bad66a9d3

Commit names should be generic, but associated with changes and if needed then additional, more detailed, description should be added where you can describe why you did such change in this way and add any additional important notes. This really helps when doing a review to understand the author's thinking faster and better 😄

2022-08-26 14:34 UTC, michalsmiarowski requested changes
Did second part of the review after testing it out locally. Left some more comments, mostly related to UI.

2022-08-26 14:34 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +          </FlowStep>
Flow step does not match the designs on Figma.

Figma:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/40306834/186926501-bb6bd55c-c67e-4994-85c8-6d149e71d3a1.png">

Your version:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/40306834/186926585-737f3d5e-5d75-43f8-9a2f-864afb74c7ca.png">

What's your version missing:
- no margin-bottom between "Step x" and the rest of the flow step
- "Step x" has different color
- it looks like the flow step title is too big? I think it uses `LabelSm` in the Figma version
- arrow icon next to `This is 1 transaction` is smaller than in Figma designs

2022-08-26 14:34 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +  const decreaseAmount = 500000
This should probably be passed to the modal

2022-08-26 14:34 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/index.tsx
> +const DeauthorizeApplicationModal: FC<
When opening modal there is an error in the console:

`react-remove-scroll-bar: cannot calculate scrollbar size because it is removed (overflow:hidden on body`

Not sure if it's related to this PR but can you check it out? I don't remember seeing it earlier.

2022-08-30 21:18 UTC, georgeweiler commented on src/components/StakingApplicationIcon/index.tsx
> +    increaseOrDecrease: "increase" | "decrease"
yeah great idea. Was trying to come up with a better variable name myself. `operation` sounds great.

2022-08-30 21:31 UTC, georgeweiler commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +          </FlowStep>
see: https://github.com/threshold-network/components/pull/21

2022-08-30 21:34 UTC, georgeweiler commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +  const decreaseAmount = 500000
What do you think about waiting until we have a better idea of the data interface and store? I think we might be able to pull this from a context or store depending on how we set it up. For now, this PR was just meant to build the UI components. Wdyt?

2022-08-31 18:15 UTC, georgeweiler commented on src/components/Modal/DeauthorizeApplicationModal/index.tsx
> +const DeauthorizeApplicationModal: FC<
I did some debugging. There's this issue with chakra: https://github.com/chakra-ui/chakra-ui/issues/6213


Looks like the modal is adding "overflow: hidden" to the body and complains when it tried to add it again?

in any case, it's only a warning in the development env: https://github.com/theKashey/react-remove-scroll-bar/blob/3dd80e28c92b8aac025e41f4258ff926cdc88af9/src/utils.ts#L22

So I think it's okay to ignore. WDYT?

2022-09-01 20:37 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +          </FlowStep>
@georgeweiler I merged that PR and updated the `components` version to test it but the issue still persist when i test it

2022-09-01 20:39 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +  const decreaseAmount = 500000
Ok. Let's keep this conversation as unresolved, just in case. Will be easier to find this discussion if we decide to check all MAS-related PRs one day to see if we missed something.

2022-09-01 20:48 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/index.tsx
> +const DeauthorizeApplicationModal: FC<
@georgeweiler 
Oh so it looks like this error occurs [when opening more than one modal](https://github.com/chakra-ui/chakra-ui/issues/6213). It's happening because we've got `DeauthorizeApplicationModal`, which is exported as `withBaseModal(DeauthorizeApplicationModal)` and it returns `InitiateDeauthorization` which is also exported as `withBaseModal(InitiateDeauthorization)`. So when we open `DeauthorizeApplicationModal` we have two modals opened (DeauthorizeApplicaitonModal and InitiateDeauthorization).

Is there a reason we separate those two like this?

2022-09-05 17:37 UTC, georgeweiler commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +          </FlowStep>
![Screen Shot 2022-09-05 at 11 36 36 AM](https://user-images.githubusercontent.com/15269424/188496124-d7ac6fe3-79e5-4805-bf2f-56023bf0644b.png)

interesting. my local components are updated. I'll try to reproduce

2022-09-05 17:50 UTC, georgeweiler commented on src/components/Modal/DeauthorizeApplicationModal/index.tsx
> +const DeauthorizeApplicationModal: FC<
Warning removed 👍

2022-09-06 12:04 UTC, michalsmiarowski approved these changes
🚀 🌔

2022-09-09 09:09 UTC, michalsmiarowski approved these changes
LGTM 🦉

2022-09-09 09:09 UTC, merged