Adds MAS content to stake flow (pre txn submit)
threshold-network/token-dashboard pull request #164
Opened 2022-08-19 17:04 UTC by georgeweiler

![Screen Shot 2022-08-19 at 11 02 45 AM](https://user-images.githubusercontent.com/15269424/185670541-43731f14-3b40-468d-ba34-3c1d89f5163b.png)

The multi-app staking feature includes some more content in the staking modal transaction flow. This PR adds the pre-submission content for informing the user about approving apps and running nodes

2022-08-26 16:09 UTC, michalsmiarowski requested changes
Left some comments to look at:

2022-08-26 16:09 UTC, michalsmiarowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +          <BodyLg>Staking requires 2 transactions.</BodyLg>
We should add some top padding to it:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/40306834/186947309-dd7cbc62-1af1-4ddc-b085-a1fb18df3306.png">

It's too close to the Header in comparison with Figma designs

2022-08-30 17:24 UTC, georgeweiler commented on src/components/Modal/SubmitStake/index.tsx
> +            authorizer: account as string,
I've updated to use the correct values for `stakingProvider`, `beneficiary`, `authorizer`. Pulled them from state instead of passing as props.

2022-08-30 18:31 UTC, georgeweiler commented on src/components/StakingTimeline/index.tsx
> +      </FlowStep>
Great catch, I've updated the component here: https://github.com/threshold-network/components/pull/21

2022-08-30 18:32 UTC, georgeweiler commented on src/components/StakingTimeline/index.tsx
> +      </FlowStep>
If you approve that PR, let's merge it & deploy, then I'll upgrade the components version in this PR so I can QA the new changes. (same for https://github.com/threshold-network/token-dashboard/pull/163#discussion_r956105418)

2022-08-31 02:27 UTC, liz-shinn commented on src/components/StakingTimeline/index.tsx
> +        Enter the Provider, Beneficiary, and Authorizer addresses. These will be
This is the Oxford comma; it can be omitted in a series but imo it should be kept there for clarity.

2022-08-31 02:28 UTC, liz-shinn commented on src/components/StakingTimeline/index.tsx
> +        Set up and run a node for any of the applications authorized.
Yes, I think this makes more sense to switch the order here.

2022-09-01 21:24 UTC, michalsmiarowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +          <BodyLg>Staking requires 2 transactions.</BodyLg>
@georgeweiler  I think this one is still unresolved so I unresolved the conversation

2022-09-01 21:47 UTC, michalsmiarowski requested changes
Left some more comments to look at before the merge

2022-09-01 21:47 UTC, michalsmiarowski commented on src/pages/Staking/HowItWorks/NewTStakesCard.tsx
> +      <StakingTimeline />
We probably should use feature flag here. We've renamed `StakingChecklist` component to `StakingTimeline`, but maybe we should keep both components for now, until we remove feature flag (which means we deploy Multi App Staking to the production)? This way we can still show `StakingChecklist` when the MAS feature flag is set to false, and `StakingTimeline` when the MAS featuer flag is set to true.

For this we would need to have newest changes from `main` on this branch. The MAS feature flag was introduced in this PR - https://github.com/threshold-network/token-dashboard/pull/156.

Let's make sure if there are not any more situations like this one in this PR. When something is changes in a way that show some info about authorizing an app for the stake, we should wrap it in `featureFlag` to make sure it is not showed on `main` branch until the feature is fully released on production.

Thoughts?

2022-09-01 21:47 UTC, michalsmiarowski commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +      {isSameETHAddress(authorizer, account as string) && (
The Alert says `Authorizer address is different than your wallet address` but based on this consition, the alert is shown when the addresses are the same. I think it should be:

```suggestion
      {!isSameETHAddress(authorizer, account as string) && (
```

or maybe I've missed something?

2022-09-01 21:47 UTC, michalsmiarowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +          <BodyLg>Staking requires 2 transactions.</BodyLg>
(Above line not related, but file is related)

Maybe we could also addres this section in this PR:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/40306834/188017931-2dcf99f6-b1cb-4505-8a28-248f9290ec74.png">

I think this is not displayed anymore. Based no Figma this section is changed to:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/40306834/188018131-b6b0cd8d-3acd-4eaa-80cc-437e30cc0c64.png">

Figma link: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=5658%3A336987

Link to code section:
https://github.com/threshold-network/token-dashboard/blob/5d49bf39c70b920f60d112cc4b89064c6024d2c6/src/components/Modal/ConfirmStakingParams/index.tsx#L79-L85

2022-09-05 19:17 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +      {isSameETHAddress(authorizer, account as string) && (
🙈

2022-09-05 20:26 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/NewTStakesCard.tsx
> +      <StakingTimeline />
Agreed. I've added some flags where the pull requests refers to authorizing.  We can keep the same `StakingTimeline` component, I just added a condition for the feature flag.

2022-09-05 23:20 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +          <BodyLg>Staking requires 2 transactions.</BodyLg>
Sorry about that. Should be resolved now. I've updated our InfoBox component so the margin props will work now.

2022-09-06 14:56 UTC, michalsmiarowski requested changes
Some additional comment:

2022-09-06 14:56 UTC, michalsmiarowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +        </Alert>
Based on Figma views the Alert should have status Info and it should be "small".

We should probalby add `sizes` property to the theme in `components` repo and add two sized - large and small (these are the only two we have in Threshold designs). Although' I've tried doing that in Alert theme:

```
sizes: {
    sm: {
      fontSize: "sm",
    },
    lg: {
      fontSize: "lg",
    },
  },
  ```

and it didn't work when i add `size=sm` to the Alert (but it worked when I added fontSize="sm" to the Alert).

We should also reduce the size of the Alert Icon for small size.

We can just add:

```suggestion
        <Alert my={6} status="info" fontSize="sm">
          <AlertIcon />
          Take note! These addresses cannot be changed later.
        </Alert>
```

for now if the there will be any problems with above solution.

2022-09-12 12:45 UTC, georgeweiler commented
closing because I've opened https://github.com/threshold-network/token-dashboard/pull/185 which has signed commits.

2022-09-12 12:46 UTC, closed without merging