Data access layer for authorization functions
threshold-network/token-dashboard pull request #165
Opened 2022-08-22 06:54 UTC by r-czajkowski

Closes: #134

WIP...

2022-08-22 13:27 UTC, georgeweiler commented on src/threshold-ts/applications/index.ts
> +export interface IApplication {
Is it worth defining this as a "StakingApplication"? I think `Application` is a very generic term

2022-08-22 13:32 UTC, georgeweiler commented on src/threshold-ts/applications/index.ts
> +    const isInPool: boolean = await this._application.isOperatorInPool(operator)
Will this work for PRE app?

2022-08-22 13:32 UTC, georgeweiler commented on src/threshold-ts/index.ts
> +export const Threhosld = {}
Typo

2022-08-22 13:34 UTC, georgeweiler commented on src/threshold-ts/mas/index.ts
> +    this.ecdsa = new Application(this._staking, {
I feel like there's a naming mismatch between ecdsa and tbtc in this class. We should leave some comments explaining the relationship between them. or maybe ecsda is just a stub for now before tbtc is ready?

2022-08-29 10:54 UTC, r-czajkowski commented on src/threshold-ts/applications/index.ts
> +    const isInPool: boolean = await this._application.isOperatorInPool(operator)
Nope, we will have to create a new impl of `Application` interface for PRE but I think we can skip the PRE implementation for now because the PRE app doesn't require authorization and the `SimplePreApplication` contract doesn't even implement the `IApplication`interface required by the Threshold staking contract.

2022-08-29 10:59 UTC, r-czajkowski commented on src/threshold-ts/applications/index.ts
> +export interface IApplication {
Both options work for me, but I kept the same convention as on the contract side. See https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/IApplication.sol. I am curious about @michalsmiarowski  opinion here.

2022-08-31 23:31 UTC, michalsmiarowski requested changes
Overall looks awesome 🔥 

I checked the code and it looks fantastic! 🎖️ Left some comments to look at.

I haven't reviewed the tests yet but I'll do it soon.

2022-08-31 23:31 UTC, michalsmiarowski commented on src/threshold-ts/applications/index.ts
> +   * decrease request can not be overwritten until the endire
Typo?

```suggestion
   * decrease request can not be overwritten until the entire
```

2022-08-31 23:31 UTC, michalsmiarowski commented on src/threshold-ts/applications/index.ts
> +   * uses the multicall interface to aggragate contract calls into a single one.
```suggestion
   * uses the multicall interface to aggregate contract calls into a single one.
```

2022-08-31 23:31 UTC, michalsmiarowski commented on src/threshold-ts/applications/index.ts
> + * Represents an applciation.
Typo:

```suggestion
 * Represents an application.
```

2022-08-31 23:31 UTC, michalsmiarowski commented on src/threshold-ts/mas/index.ts
> +  }
I'm not a master in solidity so I might be wrong here, but are you sure `tbtc` and `randomBeacon` that are returned from the function are `BigNumbers`?

The [authorizationParameters function in randomBeacon contract](https://github.com/keep-network/keep-core/blob/main/solidity/random-beacon/contracts/RandomBeacon.sol#L1457) returns three values not one.

We could probably benefit from a tests for that function. I think there are not any right now.

2022-08-31 23:31 UTC, michalsmiarowski commented on src/threshold-ts/multicall/index.ts
> +} as Record<number | string, string>
Maybe we could extract those two variables to a separate file, like `config.ts` and keep it in the same directory?

What do you think?

2022-09-01 08:09 UTC, r-czajkowski commented on src/contexts/ThresholdContext.tsx
> +const getThresholdLib = (providerOrSigner?: Provider) => {
We can pass the provider instance or signer to the Contract instance please see https://docs.ethers.io/v5/api/contract/contract/#Contract--creating so that's why there is a `provixerOrSigner`. I'll update type.

2022-09-01 10:33 UTC, r-czajkowski commented on src/threshold-ts/multicall/index.ts
> +} as Record<number | string, string>
Those two variables are strictly related to the Multicall contract and IMO here, is the best place for them.

2022-09-01 10:39 UTC, r-czajkowski commented on src/threshold-ts/mas/index.ts
> +  }
Good catch! We should use `SupportedAppAuthorizationParameters` type. Will update.

2022-09-01 11:07 UTC, r-czajkowski commented on src/contexts/ThresholdContext.tsx
> +const getThresholdLib = (providerOrSigner?: Provider) => {
4a49da7

2022-09-01 11:08 UTC, r-czajkowski commented on src/threshold-ts/mas/index.ts
> +  }
Types: 79f29ee
Unit tests: d40342d

2022-09-02 14:38 UTC, michalsmiarowski submitted a review, later dismissed
I haven't found any more issues with this PR so I'm gonna approve this.

Not gonna merge this one yet in case @pdyraga would like to take a look on it too.

2022-09-05 15:52 UTC, michalinacienciala commented on package.json
> +    "@keep-network/random-beacon": "development",
Adding dependency to the `random-beacon` and `ecdsa` packages means that we also need to update CI (so that the correct version of contracts would be used when testing/deploying).
There is couple of PRs in works that change the CI workflows, and depending on when #165 is going to be merged, we may need to do different changes.
No matter what, we need to upgrade the new dependencies in this step: https://github.com/threshold-network/token-dashboard/blob/main/.github/workflows/dashboard-ci.yml#L69-L78.

If #165 were to be merged now, we would also need to update the https://github.com/threshold-network/token-dashboard/blob/main/.github/actions/build-and-deploy-to-bucket/action.yml#L69-L103 in the action that builds and publishes the dashboard (similarly to how `solidity-contracts` are handled).
If before merge of #165, the https://github.com/threshold-network/token-dashboard/pull/159 gets merged, then as part of #165 we would need to update the `.github/workflows/build-and-publish.yml`.

2022-09-07 09:33 UTC, michalsmiarowski approved these changes
🌳 🦌

2022-09-07 09:45 UTC, merged