Adds a MAS banner to the overview page
threshold-network/token-dashboard pull request #167
Opened 2022-08-22 13:54 UTC by georgeweiler

Designs here:
https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=4872%3A365499

This PR adds a simple CTA for the user to authorize their apps. Also includes mobile responsiveness and dark mode designs.

![Screen Shot 2022-08-22 at 7 52 29 AM](https://user-images.githubusercontent.com/15269424/185938000-fc66bb77-9b82-4e27-89d9-c761b66cdd77.png)

2022-08-24 11:30 UTC, r-czajkowski requested changes

2022-08-24 11:30 UTC, r-czajkowski commented on src/pages/Overview/AuthorizeApplicationsBanner.tsx
> +        </Button>
Let's use `as` prop to render `a` tag instead of `button`.
```
import { Link as RouterLink } from "react-router-dom"
...
<Button
 as={RouterLink} 
 to="/staking"
 w={{ base: "100%", xl: "auto" }}
 mt={{ base: 12, xl: "auto" }}
 marginInlineStart={{ base: "8", xl: "auto !important" }}
 px={{ base: 4, md: 12 }}
>
 Start Staking
</Button>
```

2022-08-26 16:16 UTC, michalsmiarowski requested changes
Looking good! You have to resolve conflicts before the merge

2022-08-26 16:16 UTC, michalsmiarowski commented on .env
> +REACT_APP_FEATURE_FLAG_TBTC_V2=false
I think this is unnecessary change since the flag is already on `main` branch and it creates a conflict with `.env` version from main becuase there is no new line between the flag and the other env variables.

Let's remove it

2022-09-01 20:03 UTC, michalsmiarowski requested changes
Left one more comment:

2022-09-05 23:28 UTC, georgeweiler commented on src/pages/Overview/index.tsx
> +      <AuthorizeApplicationsBanner />
done 👍

2022-09-08 14:31 UTC, michalsmiarowski submitted a review, later dismissed
LGTM 🏎️ 

For me it's ready to merge but it requires @r-czajkowski approval too

2022-09-09 06:37 UTC, r-czajkowski approved these changes
:shipit:

2022-09-09 07:40 UTC, r-czajkowski approved these changes

2022-09-09 07:40 UTC, merged