Extends input interfaces to allow JSX as helper/error messages
threshold-network/token-dashboard pull request #168
Opened 2022-08-22 18:28 UTC by georgeweiler

New designs have some links and alerts as the helper text for a few inputs, so this PR extends the interface to allow for custom components

2022-09-14 07:33 UTC, r-czajkowski requested changes

2022-09-14 07:33 UTC, r-czajkowski commented on src/components/Forms/HelperErrorText.tsx
> +    return typeof errorMsgText === "string" ? (
Why can't we render the `JSX.Element` inside `FormErrorMessage` or `FormHelperText`? It would simplify this component.

```jsx
if(hasError) {
 return (
  <FormErrorMessage>
   {errorMsgText || "Please enter a valid value"}
  </FormErrorMessage>
 )
}

return helperText && (
 <FormHelperText>
  {helperText}
 </FormHelperText>
)
```

2022-09-15 00:51 UTC, georgeweiler commented on src/components/Forms/HelperErrorText.tsx
> +    return typeof errorMsgText === "string" ? (
My thinking is that the `FormErrorMessage`/`FormHelperText` would be an unnecessary dom node and might apply unintended styles to its children but I guess it's not a big deal. The code you suggested is cleaner so I changed it, but I'm returning null if there's no text to render since it's a JSX component.

https://github.com/threshold-network/token-dashboard/pull/168/commits/1c822323b3bc62ed52588bb1d678486179409535

2022-09-15 08:53 UTC, r-czajkowski approved these changes

2022-09-15 09:38 UTC, michalsmiarowski approved these changes
LGTM 🐔

2022-09-15 09:39 UTC, merged