Update validation for min stake
threshold-network/token-dashboard pull request #169
Opened 2022-08-22 19:33 UTC by georgeweiler

Fixes two small bugs in the gorli development env: 

1. The min stake is set to 0 for Gorli, so the input incorrectly shows "min stake loading"
2. The input no longer validates on Gorli, fixing the "value must be less than 0" bug

2022-08-25 10:55 UTC, r-czajkowski requested changes

2022-08-25 10:55 UTC, r-czajkowski commented on src/pages/Staking/StakedPortfolioCard.tsx
> +        }
TBH I don't understand why we need this. Could you please explain? I tested locally w/o this prop and T dapp works as expected.

2022-08-25 10:55 UTC, r-czajkowski commented on src/hooks/useMinStakeAmount.ts
>      if (minStakeAmount === "0" && tStakingContract) fetchMinStakeAmount()
I've noticed that if the minimum stake is `0` this hook triggers the `fetchMinStakeAmount` function every time we visit the `staking` page. So my suggestion is:
- set the `minimumStake` in store as `undefined` as the default value- it means that the dapp has not fetched the minimum stake amount yet,
- condition in hook change to `if (minStakeAmount === undefined && tStakingContract)`,
- change the initial value for `isLoading` to `false`: `const [isLoading, setLoading] = useState(false)`.

2022-08-25 10:55 UTC, r-czajkowski commented on src/pages/Staking/StakedPortfolioCard.tsx
> +  }, [isLoading, hasError])
Missing `minStakeAmount` dependency.

2022-08-25 13:54 UTC, cygnusv commented
Note there's an upcoming change to the staking contract that changes how the stake amount is validated:

https://github.com/threshold-network/solidity-contracts/pull/122

In particular, staking 0 tokens is disallowed

2022-08-25 18:41 UTC, georgeweiler commented on src/pages/Staking/StakedPortfolioCard.tsx
> +        }
Whoops, good catch. Removing.

2022-08-26 05:38 UTC, r-czajkowski requested changes
Let's remove unnecessary console log and :shipit:

2022-08-26 05:38 UTC, r-czajkowski commented on src/hooks/useMinStakeAmount.ts
> +      console.log("rendering the hook")
console log.

2022-08-31 09:41 UTC, r-czajkowski approved these changes
🚢

2022-08-31 09:42 UTC, merged