Updates the detailed link component
threshold-network/token-dashboard pull request #172
Opened 2022-08-25 17:34 UTC by georgeweiler

- Updates the detailed link list item component to include an image with fallback
- Adds staking provider logos

2022-09-14 07:07 UTC, r-czajkowski requested changes

2022-09-14 07:07 UTC, r-czajkowski commented on src/components/DetailedLinkListItem/index.tsx
> +    <HStack sx={styles.container}>
Let's add `as="li"` because it's a list item.

2022-09-14 07:07 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/ProvidersCard.tsx
> +  <DetailedLinkListItem
Regarding a comment above- or we should wrap the `DetailedLinkListItem` component with `ListItem`. The component name is `...ListItem` so prop `as="li"` in `DetailedLinkListItem` should be OK. Otherwise, we have list like this:
```html
<ul>
 <div>
 <div>
 <div>
 ...
</ul>
```

2022-09-14 07:11 UTC, r-czajkowski requested changes

2022-09-14 07:11 UTC, r-czajkowski commented on src/pages/tBTC/HowItWorks/AuditsCard.tsx
> +          <DetailedLinkListItem {...contract} />
Same here as in here https://github.com/threshold-network/token-dashboard/pull/172#discussion_r970408565

2022-09-14 07:11 UTC, r-czajkowski commented on src/pages/tBTC/HowItWorks/ContractsCard.tsx
> +          <DetailedLinkListItem {...contract} />
Same as above.

2022-09-14 07:11 UTC, r-czajkowski commented on src/components/DetailedLinkListItem/index.tsx
> +        <Stack spacing={0}>
If you agree with https://github.com/threshold-network/token-dashboard/pull/172/files#r970403167 we should add:
`mr="auto !important"`.

2022-09-14 07:11 UTC, r-czajkowski commented on src/theme/DetailedLinkListItem.ts
> +}
We should improve styles for smaller screens:
![obraz](https://user-images.githubusercontent.com/57687279/190085823-a7e11252-c74a-46f9-8501-6914a93e0b6b.png)

2022-09-14 07:14 UTC, r-czajkowski commented
@georgeweiler the latest merge commit is not signed 05fa000. Let's fix it before we push any updates to this branch.

2022-09-14 20:07 UTC, georgeweiler commented
@r-czajkowski Really helpful review, thanks so much! I've made all of your suggested changes in https://github.com/threshold-network/token-dashboard/pull/172/commits/05a59712fb4f33bd7debaaab832a003dc18978a2

2022-09-15 08:48 UTC, r-czajkowski approved these changes

2022-09-15 09:30 UTC, michalsmiarowski approved these changes
LGTM 🐻

2022-09-15 09:35 UTC, merged