MAS UI <-> data access layer integration
threshold-network/token-dashboard pull request #178
Opened 2022-09-05 15:47 UTC by r-czajkowski

Depends on: #165

WIP...

2022-09-07 11:49 UTC, michalsmiarowski requested changes
First part of review done:

2022-09-07 11:49 UTC, michalsmiarowski commented on src/hooks/store.ts
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
Wouldn't it be better to keep the rule of one hook in one file and naming the file as the hook? We could put those two hook inside a `store` directory, and also fours hooks inside 'hooks/application.ts' to separate directory:


```
hooks
├── application
│   ├── useApplicationState.ts
│   ├── useAppParameters.ts
│   ├── useAppMinAuthorizationAmount.ts
│   └── useAppDataByStakingProvider.ts
├── store
│   ├── useAppDispatch.ts
│   └── useAppSelector.ts
├── useAddErc20ToMetamask.ts
├── useChakraBreakpoint.ts
{...rest of the hooks}
```

Also if you agree with aboce comments then don't forget to change `application` to `stakingApplication` in proper places

2022-09-07 11:49 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  )
~~I understand the idea but don't you think this might be a little bit over-engineered? We could simply just get the state with:~~

~~useSelector((state: RootState) => state.applications)~~

~~and then get the data we want and assign it to `appsAuthData` variable few lines below.~~

EDIT:

I read a little more about this and actually I think your solution makes more sense. Here is a good thread on this subject on stack overflow: [https://stackoverflow.com/a/63277926](https://stackoverflow.com/a/63277926). Gonna keep this comment anyway if you would like to add some more about it

2022-09-07 11:49 UTC, michalsmiarowski commented on src/utils/percentage.ts
> +    .toUnsafeFloat()
Why we use `FixedNumber` here instead of `BigNumber`?

2022-09-07 11:49 UTC, michalsmiarowski commented on src/pages/Staking/index.tsx
> +  }, [dispatch])
Does that mean that we are gonna fetch the app data only on `Staking` page? We've got a banner on overview page that says about the app authorization and which let the user choose the stake he wants to authorize. We might need this data there too.

2022-09-07 11:49 UTC, michalsmiarowski commented on src/store/applications/slice.ts
> +      }
Unnecessary `@ts-ignore`?

2022-09-07 11:55 UTC, r-czajkowski commented on src/utils/percentage.ts
> +    .toUnsafeFloat()
Because `BigNumber` doesn't support decimals.

2022-09-07 11:57 UTC, michalsmiarowski commented on src/utils/percentage.ts
> +    .toUnsafeFloat()
Ahh, that's true! 🤦 😅

2022-09-08 10:53 UTC, r-czajkowski commented on src/store/applications/slice.ts
> +export type AppName = "tbtc" | "randomBeacon"
In terms of threshold staking applications, we have only tbtc v2 app so I think from code's/T dapp's perspective is ok to use `tbtc` w/o `v-2` because it's obvious that only tbtc-v2 works on threshold network. So maybe let's use suffix for `tbtc-v1`? What do you think? We only added the `tbtc v1` token to the `TokenContext` to get the token price in usd and calculate tvl.

2022-09-08 11:35 UTC, r-czajkowski commented on src/hooks/application.ts
> +export const useApplicationState = (appName: AppName) => {
367be12

2022-09-08 11:35 UTC, r-czajkowski commented on src/hooks/store.ts
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
367be12

2022-09-08 11:35 UTC, r-czajkowski commented on src/hooks/store.ts
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
5b96c75

2022-09-12 13:30 UTC, georgeweiler commented on src/App.tsx
> +  useSubscribeToAuthorizationIncreasedEvent("tbtc")
do you think we should use enums for these? And in other places in the d'app?

2022-09-12 13:31 UTC, georgeweiler commented on src/contexts/ThresholdContext.tsx
> +    if (active && library && account) {
do we need a cleanup function here if the user disconnects?

2022-09-12 13:33 UTC, georgeweiler commented on src/App.tsx
> +  useSubscribeToAuthorizationIncreasedEvent("tbtc")
nevermind I see the type `StakingAppName`

2022-09-12 13:36 UTC, georgeweiler commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
>    const appsAuthData = {
I think it makes sense to store all of this information in the redux slice, rather than rebuilding these objects here. wdyt?

2022-09-14 02:01 UTC, georgeweiler commented
@r-czajkowski I see this error when pulling changes. Is there a special setup I need?

```
Could not fetch supported apps auth parameters Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="authorizationParameters()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
    at Logger.makeError (index.ts:261:1)
    at Logger.throwError (index.ts:273:1)
    at Interface.decodeFunctionResult (interface.ts:427:1)
    at index.ts:66:1
    at Array.map (<anonymous>)
    at Multicall.aggregate (index.ts:64:1)
    at async MultiAppStaking.getSupportedAppsAuthParameters (index.ts:58:1)
    at async Object.getSupportedAppsEffect [as effect] (effects.ts:25:1)
```

2022-09-14 02:21 UTC, georgeweiler commented on src/hooks/staking-applications/useStakingAppDataByStakingProvider.ts
> +) => {
Do we have an interface defined somewhere for the return value of this?

2022-09-15 08:29 UTC, michalsmiarowski commented on src/store/applications/slice.ts
> +export type AppName = "tbtc" | "randomBeacon"
@r-czajkowski  I think we might do it that way. It's still might get confusing since we use the terms `tbtc` and `tbtc-v2` outside of the project, but since we don't use `tbtc-v1` that much in the project (as you said) I think your solution is also very good 👍

2022-09-15 13:22 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
>    const appsAuthData = {
Based on the docs https://redux.js.org/usage/deriving-data-selectors:
> should keep the Redux state minimal, and derive additional values from that state whenever possible

I think it's better eg. calculate percentage in selector because less logic is needed to calculate this value because it depends on the total staked amount of a given stake- so we can keep them it sync with the staking data.

Regarding `appsAuthData` and `AppAuthDataProps`, I'm going to refactor this interface because it's problematic and gives a lot of unnecessary logic (see my PR #189). But I would like to address it in a separate PR.

2022-09-15 13:32 UTC, r-czajkowski commented on src/contexts/ThresholdContext.tsx
> +    if (active && library && account) {
5ac843f

2022-09-16 09:45 UTC, michalsmiarowski requested changes
Found 1 bug, see comment below

2022-09-16 09:45 UTC, michalsmiarowski commented on src/pages/Staking/index.tsx
> +  }, [dispatch])
There is a bug with getting minimum amount that is required to authorize for TBTC and Random Beacon. We fetch the data here in `Staking/index.tsx` and it works fine when you go to the authorize apps page through the staking page:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/40306834/190605076-dc396e8c-e914-47c4-a629-707612e65533.png">

Ther problem is when you refresh the page (or simply go straight to authorize apps url) and connect the wallet:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/40306834/190605333-16522a0a-b0a0-473b-b538-f0678ff08231.png">

The minimum amount for TBTC and Random Beacon is not fetched properly as it shows `0`

2022-09-16 12:03 UTC, michalsmiarowski approved these changes
I'm gonna approve it since i haven't found any other issues. 

Let's not forget about this bug: https://github.com/threshold-network/token-dashboard/pull/178#discussion_r972830485 and address it in a separate PR @r-czajkowski 

Let's goo 🤙

2022-09-16 12:07 UTC, merged