MAS UI integration v2
threshold-network/token-dashboard pull request #189
Opened 2022-09-12 14:55 UTC by r-czajkowski

WIP...

2022-09-20 08:14 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +      console.log("open increase authroziation modal")
Done in #196.

2022-09-20 11:42 UTC, michalsmiarowski requested changes
First part of the review done. Left some comments below 👀

2022-09-20 11:42 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +          )}
Maybe we could specify here which transaction is which by displaying the name of the app? For example:

`View TBTC authorization transaction and Random Beacon transaction on Etherscan`

2022-09-20 13:19 UTC, michalsmiarowski requested changes

2022-09-20 13:19 UTC, michalsmiarowski commented on src/store/staking-applications/effects.ts
> +  }
I think this, or even the whole function should be wrapped with `MULTI_APP_STAKING` feature flag

2022-09-20 13:19 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +            {numberOfApps > 1 ? "s" : ""} to use your stake.
Just pointing out that on Figma it says:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/40306834/191267151-dc5f0375-1399-4996-a0e8-8530833d454c.png">

Link: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A178394

2022-09-20 13:19 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +      </ModalBody>
Are you gonna add the alerts that are in Figma designs?

<img width="508" alt="image" src="https://user-images.githubusercontent.com/40306834/191267406-2f273984-c39b-4384-8a76-a535a98a0368.png">


Link: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A178394

And also:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/40306834/191267524-c90a4565-3520-42a4-b69c-525873560009.png">


Link: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A178369

2022-09-20 13:19 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +      </ModalBody>
And also this one in stake Card:

Link: https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A178187

2022-09-20 20:40 UTC, georgeweiler commented on src/components/ExternalLink/index.tsx
> -        <Icon boxSize="12px" ml="1" as={FiArrowUpRight} color={finalColor} />
Is this just a code cleanup change because the Icon inherits the final color?

2022-09-20 20:46 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +      authorizedStake: stake.totalInTStake,
This crashes the app if you try to access a URL such as `/staking/0xF408dE50D788183d9F4F46fbb34E3EbAC9D90d50/authorize` when the wallet is not connected, or when stakes are not loaded. It happens when you do a simple page refresh so I think we should create a fallback page (or redirect?) to capture this edgecase

2022-09-20 20:53 UTC, georgeweiler commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  }
```suggestion
  const onAuthorize = useCallback(async () => {
    await authorizeMultipleApps(
      applications.map((_) => ({
        address: _.address,
        amount: _.authorizationAmount,
      })),
      stakingProvider
    )
  }, [authorizeMultipleApps, applications, stakingProvider])
```

2022-09-20 21:28 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/AppAuthorizationInfo.tsx
> +      {isAuthorizationRequired && isAuthorized && (
I'm running into an issue where my `authorizedStake` value is `undefined` for a moment before it loads. This causes `formatTokenAmount` to crash the app because BigNumber can't handle `undefined`. Maybe it's a local config issue? The value eventually loads for me, so adding this fixed the issue. Up to you if you think it's worth it. Do you think we we see this bug in production?

```
{isAuthorizationRequired && isAuthorized && !!authorizedStake && <>content</>}
```

2022-09-20 21:36 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +    const isTbtcSelected = isAppSelected("tbtc")
if think you pull these out into their own variables in the component state such as:

```
    const isTbtcSelected = useMemo(() => isAppSelected("tbtc"))
```

then you can reference them in this function and in the JSX below without re-rendering the component an 2 extra times when that value is calculated.

2022-09-20 21:36 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +          isSelected={isAppSelected("tbtc")}
see comment above about extracting this to a variable

2022-09-20 21:40 UTC, georgeweiler commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +    navigate(`/staking/${stakingProvider}/authorize`)
I think this is OK for now because I am doing the same in many modals, and I don't have a good solution to implement before the launch. But it's going to throw a warning, see: 

https://dev.to/jexperton/how-to-fix-the-react-memory-leak-warning-d4i

2022-09-21 12:11 UTC, r-czajkowski commented on src/store/staking-applications/effects.ts
> +    )
That's weird. I use VSC as well and looks OK.

<img width="890" alt="obraz" src="https://user-images.githubusercontent.com/57687279/191500502-f172be8e-3883-448d-9824-dff825f28576.png">

2022-09-21 12:17 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  )
Good catch! I'll ping @sashatanase and @liz-shinn to make sure this solution will be ok.

2022-09-21 12:22 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +          )}
Implemented based on Figma views https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6098%3A141093 but I'll ping @sashatanase and @liz-shinn as well 😆.

2022-09-21 12:32 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +      </ModalBody>
Yep, I'm going to add alerts in a separate PR- there are too many files to review now.

2022-09-21 12:35 UTC, r-czajkowski commented on src/components/ExternalLink/index.tsx
> -        <Icon boxSize="12px" ml="1" as={FiArrowUpRight} color={finalColor} />
Yes exactly. The previous impl won't work in a case like that:
```jsx
<Button
  variant="outline"
  as={ExternalLink}
  mr={2}
  href={link}
  text="text"
  color="red"
  withArrow
/>
```
This will render the arrow in default color even if we pass `color` prop- the icon won't inherit color from parent.

2022-09-21 12:41 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +      authorizedStake: stake.totalInTStake,
Added conditional props in https://github.com/threshold-network/token-dashboard/pull/197/commits/34cf8066e1c72e3648df164e5f689d6202411d0d so the `authorizedStake` is not required if the `isAuthRequired` is set to `false`. But yeah we need to add support for fetching data when the user goes to `/staking/{some_provider}/authorize` directly and I'm going to add it in a separate PR. Does it work for you?

2022-09-21 13:03 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  }
It won't memoize the submit function because the `applications` props is an array. You can check with simple test:
```jsx
const [increment, setIncrement] = useState(1) // run `setIncrement((i) => i+1)` on button click
  console.log("increment", increment)
  const onAuthorize = useCallback(async () => {
    await authorizeMultipleApps(
      applications.map((_) => ({
        address: _.address,
        amount: _.authorizationAmount,
      })),
      stakingProvider
    )
  }, [authorizeMultipleApps, applications, stakingProvider])

  useEffect(() => {
    console.log("updated")
  }, [onAuthorize])
```
Also I noticed that we use `openModal` in `useAuthorizeMultipleAppsTransaction` and in `useSendTranacion` which is not memoized and hook always returns a new instance of function on every render. See https://github.com/threshold-network/token-dashboard/blob/main/src/hooks/useModal.ts#L15-L16. We need to update it but I would address it in a separate PR.

2022-09-21 13:06 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/AppAuthorizationInfo.tsx
> +      {isAuthorizationRequired && isAuthorized && (
I think it will be addressed once we add support for fetching data when a  user goes to the auth page directly see https://github.com/threshold-network/token-dashboard/pull/189#discussion_r976455968. Does it work for you if I address it in a separate PR?

2022-09-21 13:08 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +    navigate(`/staking/${stakingProvider}/authorize`)
Yeah we need to get rid of the warning some day. Reagrding async- it is unnecessary. I'll remove.

2022-09-21 14:47 UTC, sashatanase commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  )
I agree with this solution. They both make sense to me.

2022-09-21 19:13 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +      authorizedStake: stake.totalInTStake,
yes works for me!

2022-09-21 19:13 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/AppAuthorizationInfo.tsx
> +      {isAuthorizationRequired && isAuthorized && (
yes that works

2022-09-21 21:13 UTC, georgeweiler approved these changes

2022-09-22 08:13 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +    const isTbtcSelected = isAppSelected("tbtc")
The same thing as here https://github.com/threshold-network/token-dashboard/pull/189#discussion_r976480676. It won't be memoized value because `isAppSelected` function uses the `selectedApps` array. To achieve that we should refactor this component to be more "static"- I mean store the boolean for each app in a separate variable like that instead of storing selected apps in an array:
```jsx
const [isTbtcAppSelected, setTbtcAppSelected] = useState(false)
const [isRandomBeaconAppSelected, setRandomBeaconAppSelected] = useState(false)
...

<AuthorizeApplicationsCardCheckbox
 <...otherProps>
 onCheckboxClick={(_, isChecked: boolean) => setTbtcAppSelected(isChecked)}
 isSelected={isTbtcAppSelected}
/>
```

I think this approach is OK, at least for now, because we have only 2 staking apps. Let me know what you think and maybe let's refactor in a separate PR.

2022-09-22 08:14 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  )
da5ad3e

2022-09-22 08:14 UTC, r-czajkowski commented on src/store/staking-applications/effects.ts
> +  }
9e4e044

2022-09-22 08:16 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +    navigate(`/staking/${stakingProvider}/authorize`)
fec8758

2022-09-22 08:55 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +          )}
@michalsmiarowski let's update that once we get the final copy, ok?

2022-09-22 08:56 UTC, r-czajkowski commented on src/store/staking-applications/effects.ts
> +  const hasAnyUnauthroizedStakes = Object.values(
bd465ca

2022-09-22 08:57 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +            {numberOfApps > 1 ? "s" : ""} to use your stake.
303b6ab

2022-09-22 09:03 UTC, michalsmiarowski commented on src/store/staking-applications/effects.ts
> +    )
Yup, works for me as well, maybe it was synchronizing or something 🤔

2022-09-22 09:14 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  )
@r-czajkowski Can we also change it in stake card?

<img width="506" alt="image" src="https://user-images.githubusercontent.com/40306834/191707745-c5048129-20fd-404b-b96d-d8a690d0f013.png">

https://github.com/threshold-network/token-dashboard/blob/c8622a7b096223909045a26953b2bb5d563324ef/src/pages/Staking/StakeCard/StakeApplications/AuthorizeApplicationRow.tsx#L51

2022-09-22 09:17 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +      </ModalBody>
Gonna keep this convo as unresolved to not lost the track of it

2022-09-22 10:06 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  )
@r-czajkowski Sorry, but I just noticed another error related to this:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/40306834/191719353-94dd9f4a-e783-46f1-a987-68abc2786cf7.png">

App is `>99%` authorized but it doesn't have checkbox as if it were 100% authorized

2022-09-22 10:11 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  )
And also it shows `>99%` and `<1%` for maximum T staked and 0 T staked. I think we should upgrade `formatPercentage` function:

https://github.com/threshold-network/token-dashboard/blob/c8622a7b096223909045a26953b2bb5d563324ef/src/utils/percentage.ts#L21-L30

to something like this (note: i did not test this, but I think it should work):

```
if (percentage < 1 && percentage > 0 && displayLessThanGreaterThanSigns) {
    return "<1%"
  } else if (percentage > 99 && percentage < 100 && displayLessThanGreaterThanSigns) {
    return ">99%"
  }
```

2022-09-22 10:11 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  )
Based on the Figma views, my understanding is that we only want to display checkboxes when applications are not authorized eg here https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A175881. Let's clarify with @sashatanase and @liz-shinn.

2022-09-22 10:41 UTC, michalsmiarowski requested changes
Left few minor comments that I would like to be addressed before the merge

2022-09-22 10:41 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +            <ListItem>
Should have unique `key` or warning will appear after authorazing both apps

2022-09-22 10:41 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +            <ListItem>
After authorizing both apps I alos see the warning with ref, but I can't figure out why it appears as of now

<details>
<summary>Screenshot</summary>
<br>
<img width="979" alt="image" src="https://user-images.githubusercontent.com/40306834/191725362-f4bc1000-1d6c-422f-9286-a008c8daffcd.png">
</details>

2022-09-22 11:12 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/StakingApplicationsAuthorized.tsx
> +            <ListItem>
1c939e8 0ca4fe5

2022-09-22 11:41 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizeStakingApps.tsx
> +  )
> And also it shows `>99%` and `<1%` for maximum T staked and 0 T staked. I think we should upgrade `formatPercentage` function:
> 
> https://github.com/threshold-network/token-dashboard/blob/c8622a7b096223909045a26953b2bb5d563324ef/src/utils/percentage.ts#L21-L30
> 
> to something like this (note: i did not test this, but I think it should work):
> 
> ```
> if (percentage < 1 && percentage > 0 && displayLessThanGreaterThanSigns) {
>     return "<1%"
>   } else if (percentage > 99 && percentage < 100 && displayLessThanGreaterThanSigns) {
>     return ">99%"
>   }
> ```

37a06fb

2022-09-22 12:18 UTC, michalsmiarowski approved these changes
LGTM 🏋️

2022-09-22 12:35 UTC, merged