Adds the stake details card
threshold-network/token-dashboard pull request #192
Opened 2022-09-12 19:40 UTC by georgeweiler

2022-09-22 16:04 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge 👀

2022-09-22 16:04 UTC, michalsmiarowski commented on src/pages/Staking/StakeDetailsPage/index.tsx
> +  const rewardsForStake = useFetchRewardsForSingleStake(stake?.stakingProvider)
To be honest I don't understand why we create hook for fetching rewards for single stake 🤔 We have `useFetchStakingRewards` hook that fetches rewards for all stakes and is executed in the `App.tsx`. Do we really need that hook? Can't we just pull the data from the store?

2022-09-22 18:54 UTC, georgeweiler commented on src/pages/Staking/StakeDetailsPage/StakeDetailRow.tsx
> +        </CopyToClipboard>
Let's fix after launch. There are a lot of small tech debt and design debt items like that that I would like to tackle.

2022-09-23 08:05 UTC, r-czajkowski requested changes

2022-09-23 08:05 UTC, r-czajkowski commented on src/pages/Staking/index.tsx
> +
We need to figure out a better solution for the next nested level of navigation in page components. The same pattern we are going to use in the `how it works` page and probably in other places in the future. Ofc non-blocking comments, just pointing this out.

2022-09-23 11:07 UTC, georgeweiler commented on src/pages/Staking/StakeDetailsPage/NodeStatusLabel.tsx
> +    </BoxLabel>
👍  updated.

2022-09-23 11:16 UTC, georgeweiler commented on src/pages/Staking/index.tsx
> +
I agree. The filter tabs need a way to recognize when they are link components so they can automatically handle this. You're right - I've implemented this same pattern in the how-it-works page here: https://github.com/threshold-network/token-dashboard/pull/198/files#diff-2662b5a0473a36cacbb7559a3fa2ac27daef984cdb79caf6fb2d9825add8d479R34-R45 


I am not a fan of this pattern but I think we should fix the filter tab after launch.

2022-09-23 11:45 UTC, georgeweiler commented on src/pages/Staking/StakeDetailsPage/StakeDetailRow.tsx
> +  isPrimary?: boolean
1b2d18542868b038ccc933e1f14470d22e9d3b5e

2022-09-23 11:58 UTC, r-czajkowski approved these changes
LGTM! 🚀

2022-09-23 12:08 UTC, michalsmiarowski approved these changes
LGTM 🤸‍♂️

2022-09-23 12:09 UTC, merged