WIP Authorization modal flow for new staker
threshold-network/token-dashboard pull request #195
Opened 2022-09-15 15:28 UTC by georgeweiler

depends on https://github.com/threshold-network/token-dashboard/pull/178

Adds the authorization flow for a first time staker. Stakers need to enter an amount of their stake for the tbtc and random beacon apps to be authorized. This PR adds support for authorizing the apps immediately after the stake transaction is completed. 

Designs:

https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A172838

![Screen Shot 2022-09-13 at 7 53 38 AM](https://user-images.githubusercontent.com/15269424/190444540-2c1403dc-3fe8-4b70-8369-e31bf9b54eb7.png)

2022-09-27 14:22 UTC, r-czajkowski requested changes
Nice form solution with formik, good job 👍. Left a few comments to take a look at.

2022-09-27 14:22 UTC, r-czajkowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/index.tsx
> +      </ModalBody>
Let's add `ModalFooter` for better readability. We can have the submit button outside the form component eg. here:

https://github.com/threshold-network/token-dashboard/blob/7eb2c322c1cec16e85d0962959c03a28fce7d5e3/src/components/Modal/ConfirmStakingParams/index.tsx#L103-L109

https://github.com/threshold-network/token-dashboard/blob/7eb2c322c1cec16e85d0962959c03a28fce7d5e3/src/components/Modal/ConfirmStakingParams/index.tsx#L118-L120

2022-09-27 14:22 UTC, r-czajkowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/index.tsx
> +    })
Unnecessary `console.log`.

2022-09-27 14:22 UTC, r-czajkowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/index.tsx
> +  BaseModalProps & { stake: StakeData }
I think the `stake` prop is unnecessary.

2022-09-27 14:22 UTC, r-czajkowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationFormNewStaker.tsx
> +          </Alert>
I think we can use `BundledRewards` alert from #200 once we merge #200.

2022-09-27 14:22 UTC, r-czajkowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +    return 0
I think we can use `formatPercentage` and `calculatePercenteage` from `utils/percentage`.

2022-09-27 14:22 UTC, r-czajkowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +  }, [max, inputValue])
same as above.

2022-09-27 14:22 UTC, r-czajkowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +    return numeral(formatUnits(max)).format("0,0.00")
Let's use `formatTokenAmount` fn. I believe the amount from `FormikTokenBalanceInput` component is in a `raw` format.

2022-09-27 14:22 UTC, r-czajkowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +      >
just wondering if we need a `Grid` here. Ofc non-blocking.

2022-09-27 16:41 UTC, georgeweiler commented on src/components/Modal/TbtcRecoveryFileModal/index.tsx
> +    jsonData: any
Whoops, sorry. I didn't mean to push this. I have to make this change locally because I cannot install the `tbtc-v2.ts` library

2022-09-28 09:42 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/index.tsx
> +    })
98530c3678409d4e941e0c25891bf5883832350b

2022-09-28 09:49 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/AppAuthorizationInfo.tsx
> +  separatePercentAuthorized?: boolean
This prop was added here 5c078f0d5713b66c13a20141c09041c8594cc2d5
And remove in the merge commit here 31caf44aaccffefb0349e0a4a2e851b6dc8d4490

So I don't think we need it anymore. I'll remove it but let us know @georgeweiler  if it's needed

2022-09-28 12:19 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/AppAuthorizationInfo.tsx
> +  separatePercentAuthorized?: boolean
Removed in 39ae0bb18117528100bc85c06609f9956183fd90

2022-09-28 12:19 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/AppAuthorizationInfo.tsx
> +  separatePercentAuthorized,
39ae0bb18117528100bc85c06609f9956183fd90

2022-09-28 12:22 UTC, michalsmiarowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  })
I agree that in the long run we should do as you said, but since we will probably remove this feature flag completely pretty soon, with this aproach we can just remove the whole modal instead of picking out the code fragments from one file.

2022-09-28 12:22 UTC, michalsmiarowski commented on src/components/Modal/StakingSuccessModal/StakeSuccessOld.tsx
> +const StakeSuccessOld: FC<BaseModalProps & { transactionHash: string }> = ({
https://github.com/threshold-network/token-dashboard/pull/195#discussion_r982334673

2022-09-28 12:24 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/index.tsx
> +      </ModalBody>
Great idea, but I had some problems with keeping the button `disabled` when both apps are not selected and when button is outside of form as you propose. 

I didn't want to waste more time on it so I kept it as it is for now. We can look more closely to it after the release

2022-09-28 12:24 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/index.tsx
> +  BaseModalProps & { stake: StakeData }
39ae0bb18117528100bc85c06609f9956183fd90

2022-09-28 12:25 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +    return 0
48c8cbd9ebcd710e77f7dda46525286c7d160fcc

2022-09-28 12:25 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +  const percentToBeAuthorized = useMemo(() => {
48c8cbd9ebcd710e77f7dda46525286c7d160fcc

2022-09-28 12:25 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +    return numeral(formatUnits(max)).format("0,0.00")
48c8cbd9ebcd710e77f7dda46525286c7d160fcc

2022-09-28 12:43 UTC, michalsmiarowski requested changes
Left some comments below

2022-09-28 12:43 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationFormNewStaker.tsx
> +    )
Validation for random beacon does not work. Should be:

```suggestion
    errors.randomBeaconAmountToAuthorize = validateAmountInRange(
      values?.randomBeaconAmountToAuthorize?.toString(),
      props.randomBeaconInputConstraints.max.toString(),
      props.randomBeaconInputConstraints.min.toString()
    )
```

2022-09-28 12:43 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +export const AuthorizationCardNewStaker: FC<AuthorizationCardProps> = ({
Non-blocking:

I think we should keep the word, that has the main meaning of what this component is, at the end of it's name. I mean the words like Form, Card, Modal etc.

I would propose to change the names:
`AuthorizationCardNewStaker` -> `NewStakerAuthorizationCard`
`AuthorizationFormNewStaker` -> `NewStakerAuthorizationForm`

and directory:
`ApplicationModalNewStaker` -> `NewStakerApplicationModal`

2022-09-28 12:45 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationFormNewStaker.tsx
> +    )
Fixed in ad1d9a5259b7a38cc9f1d99e5b50c671a0d6abb2

2022-09-28 12:58 UTC, michalsmiarowski commented on src/components/Modal/AuthorizeApplicationModalNewStaker/AuthorizationCardNewStaker.tsx
> +export const AuthorizationCardNewStaker: FC<AuthorizationCardProps> = ({
Addressed in 246c24b1a82775454c865b4d94994dfb49d0c922

2022-09-28 13:06 UTC, michalsmiarowski approved these changes
LGTM 🦢

2022-09-28 13:44 UTC, georgeweiler commented on src/components/Modal/AuthorizeApplicationModalNewStaker/index.tsx
> +      </ModalBody>
yep.. I like that idea but it's a tricky component because you need access to the onSubmit handler to place on the button. Let's look to clean this up after the launch

2022-09-28 14:33 UTC, r-czajkowski approved these changes

2022-09-28 14:35 UTC, merged