Increase staking application authorization flow
threshold-network/token-dashboard pull request #196
Opened 2022-09-16 07:16 UTC by r-czajkowski

Depends on: #189 

This PR adds support for increasing the authorization for staking applications.

<details>
  <summary>Screenshots</summary>
  
  
![obraz](https://user-images.githubusercontent.com/57687279/190579131-746c7d63-25c7-42b8-bca1-7c1b142a3936.png)
![obraz](https://user-images.githubusercontent.com/57687279/190579318-531409b6-eac5-49a6-8fc0-351030041757.png)

  
</details>

2022-09-16 14:27 UTC, georgeweiler commented on src/components/Modal/StakingApplications/AuthorizationIncreased.tsx
> +export const AuthorizationIncreased = withBaseModal(AuthorizationIncreasedBase)
How do you feel about renaming this component and file to `AuthorizationIncreaseSuccess`? It's easy for me to misread this this file and component name, and it would make searching for it easier.

2022-09-16 14:28 UTC, georgeweiler commented on src/components/Modal/StakingApplications/AuthorizationIncreased.tsx
> +export const AuthorizationIncreased = withBaseModal(AuthorizationIncreasedBase)
I would be happy with `IncreaseAuthorizationSuccess` as another option, so it matches the other files.

2022-09-16 14:29 UTC, georgeweiler commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +  const { sendTransaction } = useIncreaseAuthorizationTransacion(
typo

2022-09-16 14:32 UTC, georgeweiler commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +  const onAuthorizeIncrease = () => {
Should we consider `useCallback` for this method since it relies on `stakingProvider` and `increaseAmount` that are passed as props?

2022-09-16 14:34 UTC, georgeweiler commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +  }
```suggestion
  const onAuthorizeIncrease = useCallback(() => {
    sendTransaction(stakingProvider, increaseAmount)
  }, [stakingProvider, increaseAmount])
```

2022-09-16 14:55 UTC, georgeweiler commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +        <Image src={IncreaseAuthIcon} mb="6" mx="auto" />
I think we should create a dynamic Image for this because right now the IncreaseAuth icon is only valid for tBTC.

2022-09-16 14:58 UTC, georgeweiler commented on src/enums/modal.ts
> +  AuthorizationIncreased = "AUTHORIZATION_INCREASED",
if you agree with my comment above about the component name, consider changing the emums to include success. `AuthorizationIncreaseSuccess = "AUTHORIZATION_INCREASE_SUCCESS`

2022-09-20 08:46 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +        <Image src={IncreaseAuthIcon} mb="6" mx="auto" />
Yeah, good point! I'll update in #197 or create a separate PR after merging the #197 because in 208b5f5 I updated the `StakingApplicationOperationIcon` component.

2022-09-20 08:52 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +  }
8c3fc7a

2022-09-20 08:53 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +  const { sendTransaction } = useIncreaseAuthorizationTransacion(
cf0e42d

2022-09-20 08:53 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizationIncreased.tsx
> +export const AuthorizationIncreased = withBaseModal(AuthorizationIncreasedBase)
668c8a5

2022-09-23 12:43 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/AuthorizationIncreased.tsx
> +export const AuthorizationIncreased = withBaseModal(AuthorizationIncreasedBase)
@r-czajkowski I think you renamed wrong file. I think George meant that `AuthorizationIncreased` should be renamed to either `AuthorizationIncreaseSuccess` or `IncreaaseAuthorizationSuccess`. The second option would fit better since we already had `IncreaseAuthorization` modal (this is not a success modal so it should not have succes word in it's name!)

Based on the current code you should:

rename `IncreaseAuthorizationSuccess` -> `IncreaseAuthorization`
rename `AuthorizationIncreased` -> `IncreaseAuthorizationSuccess`

2022-09-23 12:47 UTC, michalsmiarowski requested changes
Left one comment in the discussion here: https://github.com/threshold-network/token-dashboard/pull/196#discussion_r978596704

Other than that I think we are good to go

2022-09-23 13:07 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizationIncreased.tsx
> +export const AuthorizationIncreased = withBaseModal(AuthorizationIncreasedBase)
🤦 will update.

2022-09-23 13:20 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/AuthorizationIncreased.tsx
> +export const AuthorizationIncreased = withBaseModal(AuthorizationIncreasedBase)
Fixed in 0d60fd5 and 71847ae.

2022-09-23 13:26 UTC, michalsmiarowski approved these changes
LGTM 🏰

2022-09-23 13:42 UTC, georgeweiler approved these changes

2022-09-23 13:44 UTC, merged