MAS deauthorization flow
threshold-network/token-dashboard pull request #197
Opened 2022-09-16 13:49 UTC by r-czajkowski

Depends on: #196 
WIP...

2022-09-27 13:34 UTC, michalsmiarowski requested changes

2022-09-27 13:34 UTC, michalsmiarowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationDecreaseApprovedEvent.ts
> +  )
We should dispatch this action only if `stakingProvider` is curretn connected address. Or we can keep the dispatch like this to fire the `displayDeauthrizationCompletedModalEffect` and then check it inside the effect!
Yeah, I think the second approach will be better.

Right now the modal will appear for all users if one of the user will do deauthorization. You can test it out runnin one account on Chrome and one on Firefox

2022-09-27 13:34 UTC, michalsmiarowski commented on src/store/staking-applications/effects.ts
> +  )
Related to the comment above - I think this is the right place to check if staking provider is equal to currently connected wallet

2022-09-28 08:14 UTC, r-czajkowski commented on src/store/staking-applications/selectors.ts
> +      ),
I think I fixed this issue in #202.

2022-09-28 08:31 UTC, r-czajkowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationDecreaseApprovedEvent.ts
> +  )
We should check if the staking provider from the event exists in `stakes` array not if the `stakingProvider` is the currently logged account. We can assume if the stake for a given staking provider exists in `stakes` array this event is related to the currently logged account.

2022-09-28 08:55 UTC, r-czajkowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationDecreaseApprovedEvent.ts
> +  )
ee0d1a6

2022-09-28 08:55 UTC, r-czajkowski commented on src/store/staking-applications/effects.ts
> +  )
ee0d1a6

2022-09-29 11:39 UTC, michalsmiarowski requested changes
Added some comments - one I think is pretty important to address (unless it is already addressed in different PR) so I mark it as `Request changes`. The rest of the comment are non-blocking

2022-09-29 11:39 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +          </BodySm>
Non-blocking:

This `InfoIcon` and `Box` doesn't seem to be aligned well:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/40306834/193016847-f8b4fb75-f3a4-4861-9e99-f47f953a0e41.png">


I would propose to wrap it in `VStack` with middle align:

```suggestion
          <BodySm mt="4" color="gray.500">
            <HStack alignItems={"middle"}>
              <InfoIcon />{" "}
              <Box as="span">
                Increasing or decreasing the authorization amount is suspended
                until the pending deauthorization is confirmed.
              </Box>
            </HStack>
          </BodySm>
```

Result:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/40306834/193016709-2ff7577e-782e-426b-a790-7a0174e8e651.png">

2022-09-29 11:39 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +                <BodySm>
Non-blocking:

This text is to close to the `Progress` component:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/40306834/193017639-2025175e-3018-4d43-afd4-4918203b1144.png">

I would add some margin top to improve the look:

```suggestion
                <BodySm mt={"2"}>
```

Effect:

<img width="241" alt="image" src="https://user-images.githubusercontent.com/40306834/193017574-b0153c5b-a926-4a17-b262-8ec30780ed2b.png">

2022-09-29 11:39 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +      remainingAuthorizationDecreaseDelay?: string
Non-blocking:

I think we a comment saying what unit is this would come very handy. Or even adding "InSeconds" at the end of the variable. I assume it's seconds, since it's fetched from contract

2022-09-29 11:39 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +      remainingAuthorizationDecreaseDelay: string
Non-blocking:

Same as above

2022-09-29 11:39 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +                    )}
Non-blokcing:

From the fimga design it look like when it's completed it should still show the `Available: <date>`. But I think `Completed` looks better so I'm gonna mark it as non-blocking.

https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A181257

2022-09-29 11:39 UTC, michalsmiarowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationDecreaseRequestedEvent.ts
> +      })
I think we should add some kind of condition here to check if the authorizer === currently logged account (and probably also is an owner). When i did deauthorization this modal opened for an account that was completely unrelated to the stake

2022-09-29 11:44 UTC, r-czajkowski commented on src/threshold-ts/staking/index.ts
> +    ](stakingProvider, application, amount)
Because in the `TokenStaking` contract there are 2 functions with the same name- function overloading. Ethers lib must know which function we exactly want to trigger.

See:
- https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/TokenStaking.sol#L535
- https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/TokenStaking.sol#L1292

2022-09-29 12:48 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +          </BodySm>
5a629cd

2022-09-29 12:49 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +                <BodySm>
29d49d4

2022-09-29 12:49 UTC, r-czajkowski commented on src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
> +      remainingAuthorizationDecreaseDelay: string
b81d7a0

2022-09-29 12:49 UTC, r-czajkowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationDecreaseRequestedEvent.ts
> +      })
5070e9a

2022-09-29 13:42 UTC, michalsmiarowski commented on src/threshold-ts/staking/index.ts
> +    ](stakingProvider, application, amount)
Ahh, i see! Thanks!

2022-09-29 13:49 UTC, michalsmiarowski approved these changes
LGTM 🌜

2022-09-29 14:01 UTC, merged