MAS - how it works page
threshold-network/token-dashboard pull request #198
Opened 2022-09-19 19:54 UTC by georgeweiler

Updates the staking "How it works" page to have 3 sections:

- Applications
- Overview
- Providers

Includes the new filter tabs component with routing enabled.

designs:  https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A176394

2022-09-26 14:21 UTC, michalsmiarowski requested changes
Left copule of comments to look at

2022-09-26 14:21 UTC, michalsmiarowski commented on src/pages/Staking/HowItWorks/index.tsx
>  }
Non-blocking **but would be very happy if it was addressed before the merge**:

I believe adding new `pathOverride` is unnecessary (although I'm not sure, you would have to get deeper into it). I think we could specify the routes similar as we did to the authorization page. You can see the full code in `src/pages/Staking/index.tsx`:

```
StakingProviderDetails.route = {
  path: ":stakingProviderAddress",
  index: false,
  pages: [Details, Auth],
  isPageEnabled: true,
}

Details.route = {
  path: "details",
  index: true,
  isPageEnabled: true,
}

Auth.route = {
  path: "authorize",
  index: false,
  isPageEnabled: true,
}

StakingPage.route = {
  path: "",
  index: false,
  title: "Staking",
  isPageEnabled: true,
}

MainStakingPage.route = {
  path: "staking",
  index: true,
  pages: [HowItWorksPage, StakingPage, StakingProviderDetails],
  title: "Staking",
  isPageEnabled: true,
}
```

I think the situation with AuthorizationPage is exactly the same as with the How it works page and we don't need `pathOverride` property there. Unless this has some specific function and you think we should keep it.

2022-09-26 14:21 UTC, michalsmiarowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +  isPageEnabled: true,
We should disable this page with feature flag

```suggestion
  isPageEnabled: featureFlags.MULTI_APP_STAKING,
```

2022-09-26 14:21 UTC, michalsmiarowski commented on src/pages/Staking/HowItWorks/StakingProviders/index.tsx
> +  isPageEnabled: true,
Same as above

2022-09-27 04:10 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          description="The Random Beacon application provides a trusted source of randomness for the process of trustless group election in the Threshold Network."
yes you can read more about it here: https://academy.binance.com/en/glossary/trustless

2022-09-27 05:01 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/LearnAboutStakingHero.tsx
> +export const LearnAboutStakingHero: FC<
I'm happy with either. Will update.

2022-09-27 12:35 UTC, r-czajkowski requested changes

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          />
IMO using just `List` and `ListItem` components would be better. The readability will be better. The array of elements is messy and confusing. I prefer the components tree, the `CustomList` doesn't bring much benefits.

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +              : stakingApplicationsIllustrationLight
For images we could create the map:
```jsx
import { ColorMode } from "@threshold-network/components" 
const iconMap: { [iconName: string]: Record<ColorMode,string>} = {
stakingAppFlow: { dark: stakingApplicationsIllustrationDark, light:  stakingApplicationsIllustrationLight},
...
}

// inside component
const { colorMode } = useColorMode()
<Image src={iconMap.stakingAppFlow[colorMode]}
```

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          }
Same as above. We could use the pattern from above for all images.

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +              </Link>
We shouldn't put button inside `a` tag. Let's use `<Button as={ExternalLink/InternalLink} ... />`

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          ]}
Let's hoist it up outside the component scope- it could live outside the component.
```jsx
const tbtcNodeSteps = [...]
const randomBeconNodeSteps = [...]
const preSteps = [...]

// inside component
rewardsStep={tbtcNodeSteps} // etc
```

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          ]}
Same as above.

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          rewardSteps={["Run a PRE node", "Have a staked balance"]}
Same as above.

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +              </Link>
We shouldn't put button inside `a` tag. Let's use `<Button as={ExternalLink/InternalLink} ... />`.

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +            </Link>
We shouldn't put button inside `a` tag. Let's use `<Button as={ExternalLink/InternalLink} ... />`

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingOverview/AuthorizingApplicationsCard.tsx
> +import { Stack, useColorMode } from "@chakra-ui/react"
Let's import from `"@threshold-network/components"`.

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingOverview/AuthorizingApplicationsCard.tsx
> +        }
Let's use `useColorModValue(AuthorizingApplicationsIllustrationLight, AuthorizingApplicationsIllustrationDark)`.

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingOverview/index.tsx
> +            "new-t-stakes      authorizing-apps"
If we add this line one more time we get rid of the space inside `new threshold stakes` card.

![obraz](https://user-images.githubusercontent.com/57687279/192525837-29ae674b-b9a0-4180-96ab-25a9ef63aa5a.png)

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingProviders/index.tsx
> +]
We have the same code inside the `ProvidersCardNonMAS` component. Let's maybe move this to a separate file inside the `src/components` dir and reuse it.

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingProviders/index.tsx
> +          </List>
Maybe we could also extract this to a separate component to the same file as I mentioned above:
```jsx
const AllAppsProvidersList: FC<ListProps> = (props) => {
 return (
  <List mt="6" spacing="4" {...props}>
            {providers.map(renderProviderListItem)}
          </List>
 )
}

const PreOnlyProvidersList: FC<ListProps> = (props) => {
 return (
  <List mt="6" spacing="4" {...props}>
            {preOnlyProviders.map(renderProviderListItem)}
          </List>
 )
}
```

2022-09-27 12:35 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingProviders/index.tsx
> +          </List>
Same as above.

2022-09-27 12:53 UTC, georgeweiler commented on src/components/AnnouncementBanner/index.tsx
> +
be14c070e893747f29e3c4d43a271d1f72be9282

2022-09-27 13:02 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +  isPageEnabled: true,
4e39e2de7f67e3ebc1c8dbccc2b0dac560cf325b

2022-09-27 13:02 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingProviders/index.tsx
> +  isPageEnabled: true,
4e39e2de7f67e3ebc1c8dbccc2b0dac560cf325b

2022-09-27 13:57 UTC, georgeweiler commented on src/components/InternalLink/index.tsx
> +}
I thought about this, but I don't like `text` prop on the `ExternalLink` and did not want to do a full-app refactor of the component right now.  I could go either way but personally I don't mind the extra component. In fact I think we could use more of them such as `ButtonLink` `ButtonExternalLink`, etc. However I can see why the prop could be useful here because there is a lot of shared code.

If it's okay with you let's address in a later PR? I think some discussion about the best approach is better than quickly making changes in this PR. wdyt?

2022-09-27 14:07 UTC, georgeweiler commented on src/components/StakingTimeline/index.tsx
> +          <InternalLink to={STAKING_PROVIDER_URL} withArrow>
![Screen Shot 2022-09-27 at 8 01 01 AM](https://user-images.githubusercontent.com/15269424/192547759-0ece919a-fb9a-4cc7-bb03-88ed160de2c5.png)

This one is weird -I think the designs require an arrow for this internal link. Or did you mean there is a better way to add the arrow?

2022-09-27 14:07 UTC, georgeweiler commented on src/components/StakingTimeline/index.tsx
> +            <InternalLink to={STAKING_PROVIDER_URL} withArrow>
same as above

2022-09-27 15:54 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingProviders/index.tsx
> +          </List>
Fixed.

2022-09-27 15:54 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingProviders/index.tsx
> +          </List>
Fixed.

2022-09-27 15:54 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingProviders/index.tsx
> +]
Fixed.

2022-09-27 15:54 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingOverview/index.tsx
> +            "new-t-stakes      authorizing-apps"
I was looking for a solution to this! Amazing! Thank you

2022-09-27 15:54 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingOverview/AuthorizingApplicationsCard.tsx
> +        }
Fixed.

2022-09-27 15:54 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingOverview/AuthorizingApplicationsCard.tsx
> +import { Stack, useColorMode } from "@chakra-ui/react"
Fixed.

2022-09-27 15:55 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +            </Link>
Fixed.

2022-09-27 15:55 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +              </Link>
Fixed.

2022-09-27 15:55 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          rewardSteps={["Run a PRE node", "Have a staked balance"]}
Fixed.

2022-09-27 15:55 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          ]}
Fixed.

2022-09-27 15:55 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +              </Link>
Fixed.

2022-09-27 15:55 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          }
Fixed.

2022-09-27 15:55 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +              : stakingApplicationsIllustrationLight
Cool pattern. Updated.

2022-09-27 15:56 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          />
No problem. Updated

2022-09-27 15:56 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/ApplicationDetailsCard.tsx
> +          <InfoBox bg={colorMode === "light" ? "gray.50" : "gray.900"}>
Fixed.

2022-09-27 15:56 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/ApplicationDetailsCard.tsx
> +    <Card boxShadow="none">
Fixed.

2022-09-27 16:02 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/LearnAboutStakingHero.tsx
> +export const LearnAboutStakingHero: FC<
Good catch

2022-09-27 16:02 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/ApplicationDetailsCard.tsx
> +import { Icon, useColorMode } from "@chakra-ui/react"
Fixed

2022-09-27 16:02 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/StakingApplications/ApplicationDetailsCard.tsx
> +          xl: `"providers   providers   pre-providers"`,
Good point, updated.

2022-09-27 16:12 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/index.tsx
>  }
Actually, I was thinking the opposite 🙈  The pathOverride prop is for the "active" state on the nav pill. The authorization page and the how-it-works page has a nested route design that breaks the design of the pill. I was planning to update the auth route with a pathOverride variable if this was approved.

![Screen Shot 2022-09-27 at 10 10 54 AM](https://user-images.githubusercontent.com/15269424/192579084-5d579521-f855-4231-86c2-b87570360afb.png)

2022-09-27 16:13 UTC, georgeweiler commented on src/pages/Staking/HowItWorks/index.tsx
>  }
I'm happy to brainstorm a new way to get this to work without a nasty override prop, but I think we should tackle after launch.

2022-09-28 06:47 UTC, r-czajkowski commented on src/components/InternalLink/index.tsx
> +}
Yeah sure, let's address it in later PR. Good point about the `text` prop but I would leave it to avoid too many changes so we could do something like this:
```
{text ?? children}
```
So the Link will work with `text`(old style) and children prop.

2022-09-28 06:52 UTC, r-czajkowski commented on src/components/StakingTimeline/index.tsx
> +          <InternalLink to={STAKING_PROVIDER_URL} withArrow>
I thought we had a rule that we display an arrow only for external links 🤔.

2022-09-28 06:59 UTC, r-czajkowski commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          />
Thank you sir 🙏 !

2022-09-28 07:07 UTC, r-czajkowski commented on src/theme/AnnouncementBanner.ts
> +  ],
We can use `parts.keys`. Will update.

2022-09-28 07:15 UTC, r-czajkowski commented on src/theme/AnnouncementBanner.ts
> +  ],
a030fa6

2022-09-28 07:16 UTC, r-czajkowski approved these changes
LGTM! 👍

2022-09-28 08:23 UTC, michalsmiarowski approved these changes
LGTM 🦾

2022-09-28 08:24 UTC, merged

2022-09-30 12:19 UTC, r-czajkowski commented on src/components/StakingTimeline/index.tsx
> +          <InternalLink to={STAKING_PROVIDER_URL} withArrow>
Fixed in https://github.com/threshold-network/token-dashboard/pull/214.