Map operator to staking provider feature
threshold-network/token-dashboard pull request #199
Opened 2022-09-22 09:08 UTC by michalsmiarowski

2022-09-29 09:00 UTC, r-czajkowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +import { isAddressZero, isSameETHAddress } from "../../../web3/utils"
Related to the comment above- let's add `AddressZero` here.

2022-09-29 09:05 UTC, r-czajkowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +      }
we can pass onError to the `useRegisterOperatorTransaction`.

2022-09-29 09:05 UTC, r-czajkowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +      }
Same as above.

2022-09-29 09:05 UTC, r-czajkowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +  const dispatch = useDispatch()
Let's use `useAppDispatch`.

2022-09-29 09:08 UTC, r-czajkowski requested changes

2022-09-29 09:08 UTC, r-czajkowski commented on src/App.tsx
> +  useSaveConnectedAddressToStore()
See https://github.com/threshold-network/token-dashboard/pull/199#discussion_r983220907 I think this hook is unnecessary.

2022-09-30 19:00 UTC, georgeweiler approved these changes
Approving so we can merge before launch but we should remember to address the comments that were flagged for code quality

2022-09-30 19:11 UTC, r-czajkowski approved these changes

2022-09-30 19:13 UTC, merged

2022-10-04 14:19 UTC, michalsmiarowski commented on src/hooks/useRolesOf.ts
> +  const rolesOf = useSelector(
I know that TypeScript set those types automatically so you can mouse over the variable and see the type in your IDE, but wouldn't it be a good idea to keep the types wrote as well? I think this would help to understand code more when for example doing the "raw" review of the code on GItHub.