Add alert to the auth page
threshold-network/token-dashboard pull request #200
Opened 2022-09-22 15:30 UTC by r-czajkowski

WIP

Add alert saying: `Not earning rewards. tBTC + Random Beacon earn bundled rewards. In order to earn rewards you need to authorize both apps.` if only one app is authorized.

2022-09-23 14:02 UTC, georgeweiler commented on src/components/BundledRewardsAlert/index.tsx
> +      <BodySm as={AlertDescription}>{text}</BodySm>
I believe the figma designs use `BodyXs` for this

2022-09-23 14:24 UTC, georgeweiler commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  const shouldRenderBundledRewardsAlert = () => {
I think we can leverage `useMemo` hook here to make this a boolean variable instead of a function that needs to be invoked in the JSX.

2022-09-26 06:28 UTC, r-czajkowski commented on src/components/BundledRewardsAlert/index.tsx
> +      <BodySm as={AlertDescription}>{text}</BodySm>
9611b68

2022-09-28 13:19 UTC, michalsmiarowski requested changes
Left one small comment to llok at before we dicide to merge it

2022-09-28 13:19 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
> +      )}
The alert display at the beginning for 1 seconds after connecting to a wallet. It happends before the data is fetching and the `isAuthorized` property is set to `true` as default. We should think about but i thinks it's pretty important issue to tackle.

We discussed about this here too: https://github.com/threshold-network/token-dashboard/pull/201#discussion_r978691770

2022-09-29 11:32 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/StakeApplications/index.tsx
> +      )}
d971bf9

2022-09-29 11:47 UTC, michalsmiarowski approved these changes
LGTM 🦘

2022-09-29 11:57 UTC, michalsmiarowski approved these changes

2022-09-29 12:13 UTC, merged