Update auth/dauth form validation
threshold-network/token-dashboard pull request #220
Opened 2022-09-30 15:07 UTC by r-czajkowski

We need to update the validation for authorize/deauthorize form to match the validation on the smart contract side. There are 3 scenarios:

1. Application is unauthorized- first-time authorization:
- the authorization amount should be greater than the minimum authorization amount for a given application and less than/equal to the total staked balance of the stake.

2. Increase authorization- an application is already authorized:
- the increase amount should be greater than 0 and less than/equal to the remaining stake amount: Eg:
  - total staked balance in T: 100 000 T,
  - first authorization amount: 40 000 T,
  - max increase amount is 60 000 T.

3. Deatuhorization:
- the decrease amount should be grater than 0 and the authorization amount after deauthorization should be greater than/equal to the minimum authorization amount eg:
  - minimum authorization amount: 40 000 T,
  - authorization amount: 100 000 T,
  - the authorizer can deauthorize the staking application by up to 60 000 T. An authorizer can also fully deauthorize, so the value can be 100 000T.

Ref:
https://github.com/keep-network/keep-core/blob/4df5ceb01fd1bd2d55a39eb65db6c14d5a275d18/solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol#L278-L281
https://github.com/keep-network/keep-core/blob/main/solidity/ecdsa/contracts/libraries/EcdsaAuthorization.sol#L281-L284
https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/TokenStaking.sol#L1305-L1313

2022-09-30 19:39 UTC, georgeweiler commented on src/components/StakingApplicationForms/index.tsx
> +          remainigAmount={remainigAmount}
typo

2022-09-30 19:48 UTC, georgeweiler commented
left 2 very small comments. OK to merge otherwise.

2022-10-03 04:55 UTC, r-czajkowski commented on src/components/StakingApplicationForms/index.tsx
> +      <BodySm as="span" color="gray.500" float="right">
As I can see on Figma https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=6028%3A175671 the color is `gray.500` in dark mode as well.

2022-10-03 04:59 UTC, r-czajkowski commented on src/components/StakingApplicationForms/index.tsx
> +          remainigAmount={remainigAmount}
03163e6

2022-10-03 08:41 UTC, michalsmiarowski requested changes
Left some comments to look at before merge

2022-10-03 08:41 UTC, michalsmiarowski commented on src/components/StakingApplicationForms/index.tsx
> +  }
There is an error when you remove the value from the deauthorization form. It happend because `tokenAmount` is `undefined` so it can't be changed to `BigNumber`.

We have a check in `validateAmountInRange` that displays the "Required" message but here, since the valued is undefined, it doesn't go inside the if and the check is not done

2022-10-03 08:41 UTC, michalsmiarowski commented on src/components/StakingApplicationForms/index.tsx
> +  }, [tokenAmount, authorizedAmount, totalStake, maxAmount])
Non-blocking:

Do we need `authorizedAmount` here since it's not used in `useEffect()`?

2022-10-03 08:41 UTC, michalsmiarowski commented on src/components/StakingApplicationForms/index.tsx
> +  const _minimumAuthorizationAmount = BigNumber.from(minimumAuthorizationAmount)
Non-blocking:

I think we usually name BigNumber variables as `<variable_name>InBN` and not `_<variable_name>`. Check for example `validateAmountInRange` method in `utils/forms.ts`. I think we should keep the naming convention similar throught the whole project.

2022-10-03 08:41 UTC, michalsmiarowski commented on src/components/StakingApplicationForms/index.tsx
> +    const _max = BigNumber.from(maxAmount)
Non-blocking:

See above comment

2022-10-03 08:41 UTC, michalsmiarowski commented on src/components/StakingApplicationForms/index.tsx
> +  const _tokenAmount = BigNumber.from(tokenAmount)
Non-blocking:

See above comment

2022-10-03 08:41 UTC, michalsmiarowski commented on src/components/StakingApplicationForms/index.tsx
> +}
Non-blocking but I think it's pretty important:

Max button on deauthorization flow sets max amount of the token staked in that stake instead of max amount that the user can deauthorize.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/40306834/193534388-d8cb4e17-0197-47aa-88e1-0b40b9c4ea60.png">

I've had a 83,000 T stake and i authorized 42,000T. When i want to deauthorize and click `MAX` it sets the value to 83,000 and says `The vlaue should be less or equal than 2,000`. It should be set up to 42,000 T.

And also the validation message might be misleading, because it says that you can only deauthorize the value to less or equal 2,000 when in reality, in this case, you can deauthorize less or equal 2,000 or 42,000 T.

2022-10-03 09:35 UTC, r-czajkowski commented on src/components/StakingApplicationForms/index.tsx
> +}
6910e97

2022-10-03 09:35 UTC, r-czajkowski commented on src/components/StakingApplicationForms/index.tsx
> +}
Max button: 84ba3bd

2022-10-03 09:36 UTC, r-czajkowski commented on src/components/StakingApplicationForms/index.tsx
> +  }
098b64f

2022-10-03 09:36 UTC, r-czajkowski commented on src/components/StakingApplicationForms/index.tsx
> +  const _tokenAmount = BigNumber.from(tokenAmount)
5054679

2022-10-03 09:36 UTC, r-czajkowski commented on src/components/StakingApplicationForms/index.tsx
> +    const _max = BigNumber.from(maxAmount)
5054679

2022-10-03 09:36 UTC, r-czajkowski commented on src/components/StakingApplicationForms/index.tsx
> +  const _minimumAuthorizationAmount = BigNumber.from(minimumAuthorizationAmount)
5054679

2022-10-03 09:47 UTC, michalsmiarowski commented on src/components/StakingApplicationForms/index.tsx
> +            authorizedAmount.toString()
I think this would be more readable:

```suggestion
        lessThanValidationMsg(amount) {
          return `${defaultLessThanMsg(amount)} or equal to ${formatTokenAmount(
            authorizedAmount.toString()
```

In your case it might indicate that the value should be less than or equal `amount` or less than or equal `authorized` amount.

2022-10-03 10:04 UTC, michalsmiarowski approved these changes
LGTM 🌌

2022-10-03 10:17 UTC, merged