Operator mapping - code cleaning
threshold-network/token-dashboard pull request #223
Opened 2022-10-03 07:15 UTC by michalsmiarowski

2022-10-05 16:58 UTC, georgeweiler commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> -  const operatorMappedToStakingProviderHelpers =
why remove this helper hook? seems like it saved some duplicate code. What if we added the tbtc & random beacon addresses as parameters so we don't have to rewrite the logic?

2022-10-05 16:59 UTC, georgeweiler commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
>              "The operator address doesn't match the one used in tbtc app"
let's use tBTC

2022-10-05 17:07 UTC, georgeweiler commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
>            <List spacing="2" mb={"4rem"}>
minor suggestion, but can we use `16` instead of `4rem` since we have to touch this file to update the typo below anyway

2022-10-05 17:07 UTC, georgeweiler commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
> +            <ListItem key="map_operator_succes_modal__operator">
same as above

2022-10-05 17:48 UTC, georgeweiler commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
> +                  id={`map_operator_transaction_${transactions[0].txHash}`}
how does this work? Doesn't the `ViewInBlockExplorer` pass this `id` along as the hash to create the link?

2022-10-05 17:53 UTC, georgeweiler commented on src/hooks/staking-applications/useRegisterMultipleOperatorsTransaction.ts
> +        const isOperatorMappedOnlyInTbtc =
see my comment about about the helper hook that we removed. I think it could be nice to consolidate

2022-10-05 18:01 UTC, georgeweiler commented on src/pages/Staking/OperatorAddressMappingCard.tsx
> +//TODO: Fix this
Could we leave a better explanation for what's wrong & how we should fix? Or maybe just fix now? tbh I don't see any issues, so maybe this comment can be deleted?

2022-10-05 18:17 UTC, georgeweiler commented on src/store/connected-account/connectedAccountSlice.ts
> +  if (featureFlags.MULTI_APP_STAKING) {
maybe we don't need this flag anymore since we launched MAS.

2022-10-05 18:19 UTC, georgeweiler commented on src/store/index.ts
> +          isSuccessfullLoginModalClosed: true,
small typo should be `isSuccessfulLoginModalClosed`

2022-10-05 18:27 UTC, georgeweiler requested changes
Overall the state changes look good! I'm not a fan of the modalQueue as it is implemented right now. I think we should prioritize a real queue so we aren't making specific exceptions in the `closeModal` method.  I think this is non-blocking though because it's a larger update that we can do in a future PR.

I left a few small nits that we should cover before merging

2022-10-06 12:16 UTC, r-czajkowski commented on src/store/staking-applications/effects.ts
> +  if (address && connectedAccount.operatorMapping.isInitialFetchDone) {
Let's remove this nested if for better readability:
```ts
if(!address || !connectedAccount.operatorMapping.isInitialFetchDone) return

...rest here
```

2022-10-06 12:17 UTC, r-czajkowski commented on src/store/staking-applications/effects.ts
> +  if (address && connectedAccount.operatorMapping.isInitialFetchDone) {
Do we need this condition `connectedAccount.operatorMapping.isInitialFetchDone`? We run this effect on `operatorMappingInitialFetchDone` so we can assume it is set to `true`.

2022-10-06 12:22 UTC, r-czajkowski commented on src/store/staking-applications/effects.ts
> +    await listenerApi.condition((action, currentState: RootState) => {
Do we need the `RootState` type here? The `listenerApi` has our custom type with our state type so I believe it's unnecessary.

2022-10-06 12:29 UTC, r-czajkowski commented on src/store/index.ts
>    connectedAccount: connectedAccountSlice.reducer,
Can we rename to `account/user/app`?

2022-10-06 12:29 UTC, r-czajkowski commented on src/store/connected-account/index.ts
>  export * from "./connectedAccountSlice"
Same as above.

2022-10-06 12:35 UTC, r-czajkowski commented on src/store/connected-account/effects.ts
> +      listenerApi.dispatch(operatorMappingInitialFetchDone())
I believe this action is unnecessary. We can set a flag to true in `setMappedOperator` slice.

2022-10-06 12:36 UTC, r-czajkowski commented on src/store/connected-account/effects.ts
>        await listenerApi.extra.threshold.staking.rolesOf(address)
This effect will be triggered on `setStakes` action so it means we should have available stakes if the user is an owner. We can check if the stake where `stakingprovider === connected account` exists in the `stakes` array. If that stake exists there is no need to make the `rolesOf` request.

2022-10-06 12:37 UTC, r-czajkowski commented on src/store/connected-account/effects.ts
> +    if (isUsedAsStakingProvider) {
Can we `if(!isUsedAsStakingProvider) return`? There is a lot of code inside the `if` statement so IMO it will improve readability.

2022-10-06 12:42 UTC, r-czajkowski commented on src/store/connected-account/connectedAccountSlice.ts
> +        isUsedAsStakingProvider: false,
I think we should't keep it in the `operatorMapping` object. It's not only related to the operator mapping it could be useful in other places. So I would keep it outside the `operatorMapping` object.
```
initialState: {
 address: string,
 isStakingProvider: boolean
}
```

2022-10-06 12:43 UTC, r-czajkowski commented on src/store/connected-account/connectedAccountSlice.ts
> +    },
Can't we set the `isInitialFetchDone` and `isFetching` in the `setMappedOperator`?

2022-10-06 12:45 UTC, r-czajkowski commented on src/store/connected-account/connectedAccountSlice.ts
>  export const connectedAccountSlice = createSlice({
Let's rename to `account/user/app` as I mentioned somewhere above.

2022-10-06 12:47 UTC, r-czajkowski commented on src/pages/Staking/index.tsx
> +  } = useSelector((state: RootState) => state.connectedAccount.operatorMapping)
Let's use `useAppSelector`.

2022-10-06 12:47 UTC, r-czajkowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
> +// import { useOperatorMappedtoStakingProviderHelpers } from "../../hooks/staking-applications/useOperatorMappedToStakingProviderHelpers"
Unnecessary import ?

2022-10-06 12:49 UTC, r-czajkowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
>  import { LabelSm } from "@threshold-network/components"
We already import components from `@threshold-network/components` so let's import from @threshold-network/components` only once.

2022-10-06 12:52 UTC, r-czajkowski commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
> +                  <Fragment key={`map_operator_transaction_${index}`}>
We could use `_.txHash` as a key.

2022-10-06 19:37 UTC, georgeweiler commented
@michalsmiarowski can you take on https://github.com/threshold-network/token-dashboard/issues/232 in this PR as well? Should be a simple commit.

2022-10-07 22:01 UTC, michalsmiarowski commented on src/store/connected-account/connectedAccountSlice.ts
> +    },
I think in this case we can't because the `operatorMapping` property contains:
- `isUsedAsStakingProvider` boolean value
- `mappedOperators` object
and `isInitialFetchDone` and `isFetching` is associated with the `operatorMapping` object as a whole, and `setMappedOperator` sets only `mappedOperators` and not fully - only for specific app. So we can't say the initial fetch is fully done.

2022-10-07 22:04 UTC, michalsmiarowski commented on src/store/connected-account/effects.ts
> +      listenerApi.dispatch(operatorMappingInitialFetchDone())
I think it's not possible that way. See https://github.com/threshold-network/token-dashboard/pull/223#discussion_r990523464

2022-10-07 22:10 UTC, michalsmiarowski commented on src/store/connected-account/connectedAccountSlice.ts
> +        isUsedAsStakingProvider: false,
I think this one is also related to https://github.com/threshold-network/token-dashboard/pull/223#discussion_r990523464

I need to know that `isStakingProvider` is fully fetched (and same with mapped operators). This way I can print the Operator Address Mapping Card (PR for it's refactor here - https://github.com/threshold-network/token-dashboard/pull/261) in Staking Page without if displaying for one sec at the beginning (when `isStakingProvider` is set to `true` and the opreator addresses are still fetching). 

But tbh now when I think of it I think we could just check if the mapping operators are initially fetched and that should also work without any problems 🤔

2022-10-10 12:53 UTC, michalsmiarowski commented on src/store/index.ts
>    connectedAccount: connectedAccountSlice.reducer,
Fixed in 47639bf858c8fb04be780e3eed636d8e742526b2

2022-10-10 12:53 UTC, michalsmiarowski commented on src/store/connected-account/index.ts
>  export * from "./connectedAccountSlice"
Fixed in 47639bf858c8fb04be780e3eed636d8e742526b2

2022-10-10 12:55 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
> +            <ListItem key="map_operator_succes_modal__staking_provider">
Fixed in 45a5009ea7eb56c44fdb0e2846bb33c11a955c07

2022-10-10 12:56 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
>            <List spacing="2" mb={"4rem"}>
Fixed in 0de4912594f5fd6521aa3345b3308a75abcdd607

2022-10-10 12:57 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
> +                  id={`map_operator_transaction_${transactions[0].txHash}`}
Great catch! I've mistaken it with a `key` prop 🤦‍♂️ Fixed in ae4231d832c00e4cc353d633c1189e4e18ef0382

2022-10-10 12:57 UTC, michalsmiarowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
> +//TODO: Fix this
This was fixed earlier and i forgot to remove the TODO. Removed it in 08e6e157803311e44c512bc77cce4c93fedd31dd

2022-10-10 12:58 UTC, michalsmiarowski commented on src/store/connected-account/connectedAccountSlice.ts
> +  if (featureFlags.MULTI_APP_STAKING) {
I'll address it in separate PR. Let's keep it for a while after release just in case something breaks after newest changes.

2022-10-10 12:59 UTC, michalsmiarowski commented on src/store/index.ts
> +          isSuccessfullLoginModalClosed: true,
FIxed in d35e967400e6c49cf6c8b8f23ddb6667fb84f61d

2022-10-10 12:59 UTC, michalsmiarowski commented on src/store/staking-applications/effects.ts
> +  if (address && connectedAccount.operatorMapping.isInitialFetchDone) {
Fixed in 88603134d545e9164e5c2de371435ea44441091d

2022-10-10 13:00 UTC, michalsmiarowski commented on src/store/staking-applications/effects.ts
> +  if (address && connectedAccount.operatorMapping.isInitialFetchDone) {
Fixed in 88603134d545e9164e5c2de371435ea44441091d

2022-10-10 13:01 UTC, michalsmiarowski commented on src/store/staking-applications/effects.ts
> +    await listenerApi.condition((action, currentState: RootState) => {
Fixed in 530837e2820eff1546685b441fe3dddd7c680b02

2022-10-10 13:02 UTC, michalsmiarowski commented on src/store/connected-account/effects.ts
>        await listenerApi.extra.threshold.staking.rolesOf(address)
Fixed in d3c637b990b9f530b560e94054ff0dd3261d06f9

I couldn't get the stakes from the state using already created selector because even though the effect is called on `setStakes` action they are not set in state yet. Fortunately all the stakes are transferred via payload so that's how i search i any of the stakes there have `stakingProvider === connected account`.

2022-10-10 13:03 UTC, michalsmiarowski commented on src/store/connected-account/effects.ts
> +    if (isUsedAsStakingProvider) {
Fixed in 45c0b72fa274f3314d3c3bd6e471aa5a49a53475

2022-10-10 13:04 UTC, michalsmiarowski commented on src/store/connected-account/connectedAccountSlice.ts
>  export const connectedAccountSlice = createSlice({
Fixed in 47639bf858c8fb04be780e3eed636d8e742526b2

2022-10-10 13:04 UTC, michalsmiarowski commented on src/pages/Staking/index.tsx
> +  } = useSelector((state: RootState) => state.connectedAccount.operatorMapping)
Fixed in 4fd84b4c7f1e0a5910ec6a557540305d823d1789

2022-10-10 13:04 UTC, michalsmiarowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
> +// import { useOperatorMappedtoStakingProviderHelpers } from "../../hooks/staking-applications/useOperatorMappedToStakingProviderHelpers"
Fixed in 369c9c908018a9448a3c5a543197d6d8e9bba994

2022-10-10 13:05 UTC, michalsmiarowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
>  import { LabelSm } from "@threshold-network/components"
Fixed in 369c9c908018a9448a3c5a543197d6d8e9bba994

2022-10-10 13:05 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
> +                  <Fragment key={`map_operator_transaction_${index}`}>
Fixed in cdf31809bb34c6f8ea30553d4a91ec44644c5010

2022-10-10 13:23 UTC, michalsmiarowski commented on src/store/index.ts
> +          isSuccessfullLoginModalClosed: true,
Actually it's not dispatched 🤔 And because of that I'm thinking how to resolve this issue. `resetStoreAction` is aclled only when we change the metamas account while we have the account connected. It is not dispatched when we disconnect and then connect again.

2022-10-11 08:13 UTC, michalsmiarowski commented
> @michalsmiarowski can you take on #232 in this PR as well? Should be a simple commit.

Fixed in 64677b39e1b6c5234354bcdb5adb933bf3d191bf

2022-10-13 06:56 UTC, r-czajkowski commented on src/store/index.ts
> +          isSuccessfullLoginModalClosed: true,
It's because the injected connector doesn't emit the `Deactivated` event in `deactivate` function https://github.com/Uniswap/web3-react/blob/v6/packages/injected-connector/src/index.ts#L181-L188 but the WalletConnect connector emits this event see https://github.com/Uniswap/web3-react/blob/v6/packages/walletconnect-connector/src/index.ts#L136. So maybe we could override the `deactivate` in InjectedConnector in this way:
```ts
class CustomInjectedConnector extends InjectedConnector {
  deactivate = (): void => {
    super.deactivate()
    this.emitDeactivate()
  }
}

const injectedConnector = new CustomInjectedConnector({})
```

We probably should do the same for `WalletLinkConnector` in `web3/connectors/coinbaseWallet.ts`.

2022-10-13 07:05 UTC, r-czajkowski commented on src/store/connected-account/connectedAccountSlice.ts
> +        isUsedAsStakingProvider: false,
> But tbh now when I think of it I think we could just check if the mapping operators are initially fetched and that should also work without any problems

yeah, I think the same. Also the `isStakingProvider` flag will be `false` by default, so to display operator mapping card we will have a condition like this `isStakingProvider && isInitialFetchDone`.

2022-10-13 07:26 UTC, r-czajkowski commented on src/store/connected-account/connectedAccountSlice.ts
> +        isUsedAsStakingProvider: false,
If we move the `isStakingProvider` outside the `operatorMapping` object can we also simplify to:
```
operatorMapping: FetchingState<Record<StakingAppName, string>>
```

I believe the `mappedOperators` is unnecessary because it's inside the `operatorMapping`- `operatorMapping` is clear enough and will be simpler
```
state.operatorMapping.data.tbtc/randomBeacon
vs
state.operatorMapping.data.mappedOperator.tbtc/randomBeacon
```

2022-10-13 08:14 UTC, r-czajkowski requested changes

2022-10-13 08:14 UTC, r-czajkowski commented on src/store/account/effects.ts
> +import { isZeroAddress } from "ethereumjs-util"
Let's import from `web3/utils`

2022-10-13 08:14 UTC, r-czajkowski commented on src/store/account/slice.ts
> +    setAccountAddress: (state: AccountState, action: PayloadAction<string>) => {
maybe `walletConnected`?

2022-10-13 08:19 UTC, r-czajkowski requested changes

2022-10-13 08:19 UTC, r-czajkowski commented on src/store/account/slice.ts
> +          action.payload
Let's just `const { stakingProvider } = action.payload`

2022-10-17 09:39 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
> +          values.operator !== mappedOperatorRandomBeacon
Fixed in 7ed1d17e9e0707d79ad3b49c2ef80816c2c48092

2022-10-17 09:40 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
>      errors.operator = validateETHAddress(values.operator)
Fixed in 7ed1d17e9e0707d79ad3b49c2ef80816c2c48092

2022-10-17 09:40 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
> +            <ListItem key="map_operator_success_modal__staking_provider">
Fixed in 676058f0e90ae34a6d3350b34261fcc5fb1524be

2022-10-17 09:40 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderSuccessModal/index.tsx
> +            <ListItem key="map_operator_success_modal__operator">
Fixed in 676058f0e90ae34a6d3350b34261fcc5fb1524be

2022-10-17 09:40 UTC, michalsmiarowski commented on src/store/account/effects.ts
> +import { isZeroAddress } from "ethereumjs-util"
Fixed in 009344de756a6593c914dec921f15bdd2ce13b55

2022-10-17 09:41 UTC, michalsmiarowski commented on src/store/account/slice.ts
> +    setAccountAddress: (state: AccountState, action: PayloadAction<string>) => {
Fixed in c5453fdba5eb88c51259e8c60a66bc010648f832

2022-10-17 09:41 UTC, michalsmiarowski commented on src/store/account/slice.ts
> +          action.payload
Fixed in 2fd71544f69bea87569f98eb62149aa93f710ee2

2022-10-19 08:13 UTC, michalsmiarowski commented on src/store/connected-account/connectedAccountSlice.ts
> +        isUsedAsStakingProvider: false,
Fixed in f754bc4f0a0f1f626255c1279d8f7ccdfca703c8 and 390eaea8ac74313b2a48458ab44c8b234971ef15

2022-10-19 08:13 UTC, michalsmiarowski commented on src/store/connected-account/connectedAccountSlice.ts
> +    },
Fixed in 7cf4736f217ed8dfb9a84c0fdc262a242f064d7d

2022-10-19 08:17 UTC, michalsmiarowski commented on src/store/index.ts
> +          isSuccessfullLoginModalClosed: true,
This does not work for me. Even though the `deactivate` event is emited it is not catched in the `AppBody`'s `useEffect`. It's probably because the events are cleared/removed before the event is fired 🤔

2022-10-19 12:40 UTC, r-czajkowski commented on src/store/index.ts
> +          isSuccessfullLoginModalClosed: true,
Let's address in a separate PR.

2022-10-21 08:11 UTC, r-czajkowski approved these changes
LGTM! :shipit:

2022-10-21 12:27 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> -  const operatorMappedToStakingProviderHelpers =
This will be addressed in https://github.com/threshold-network/token-dashboard/pull/278

2022-10-24 09:00 UTC, r-czajkowski approved these changes

2022-10-24 09:13 UTC, merged