Posthog
threshold-network/token-dashboard pull request #260
Opened 2022-10-05 09:11 UTC by r-czajkowski

2022-10-05 18:52 UTC, georgeweiler commented on src/posthog/index.ts
> +    // manually. It also prevents sending the `pageview` event on postohog
I think we should use `persistence: "memory"` configuration here because we don't want to store cookies on the user's browser. See: https://posthog.com/tutorials/cookieless-tracking

2022-10-06 11:54 UTC, r-czajkowski commented on src/posthog/index.ts
> +    // manually. It also prevents sending the `pageview` event on postohog
Good catch! Thanks George! 🦅 👁️

2022-10-06 19:34 UTC, georgeweiler approved these changes
lgtm

2022-10-07 21:43 UTC, michalsmiarowski requested changes
Left some more comments to look at before the merge:

2022-10-07 21:43 UTC, michalsmiarowski commented on src/posthog/index.ts
> +const POSTHOG_API_HOST = "https://app.posthog.com"
Shouldn't we move these to `.env` file?

2022-10-07 21:43 UTC, michalsmiarowski commented on src/hooks/posthog/index.ts
> +export * from "./usePosthog"
Non-blocking but I think it would be benefical:

Posthog can be seen as a pretty separated feature which is not really dependent on any other features in our dashboard. So I think that the best thing would be to keep all the code in one folder - `stc/posthog`. I would move all the hooks to the `/src/posthog/hooks` directory instead of keeping them in `src/hooks/posthog`. 

Anothre argument for this option is that we don not keep all the hooks in `src/hooks` file - for `web3` we keep them in `src/web3/hooks`.

2022-10-07 21:43 UTC, michalsmiarowski commented on src/posthog/index.ts
> +}
Non-blocking:

Coudl we create a class for that maybe? Instead of separating it to just functions  and the `import * as posthog`?

2022-10-07 21:43 UTC, michalsmiarowski commented on src/hooks/posthog/useCapturePageview.ts
> +  }, [location])
I think `capturePageView()` does not work as intended in some of our cases. For example - when we click `Staking` page on the left menu, this `useEffect` fires two times for two pathnames:

pathname 1: `/staking/how-it-works`
pathname 2: `/staking/how-it-works/overview`

Then in the posthog dashboard it is showed as:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/40306834/194661885-d62e392f-59c4-4fb9-b34e-5d186af9d256.png">

So it looks that user went into the same page two times, when in reality he visited it once. We should either try to reduce this event to one in such cases or make sure it catches the url correcttly.

2022-10-07 21:43 UTC, michalsmiarowski commented on src/hooks/posthog/useCapturePageview.ts
> +  }, [location])
I think we should specify the property of the object in the dependency array instead of passing the whole object. We only need pathname so I think that should work:

```suggestion
  useEffect(() => {
    if (featureFlags.POSTHOG) posthog.capturePageview()
  }, [location.pathname])
```

2022-10-10 07:27 UTC, r-czajkowski commented on .env.production
> +REACT_APP_FEATURE_FLAG_POSTHOG=$POSTHOG_SUPPORT
I was thinking about it as additional protection for running the dapp locally. I mean we only want to run the T dapp with posthog on prodaction.

2022-10-10 07:30 UTC, r-czajkowski commented on src/hooks/posthog/useIdentify.ts
> +    if (!featureFlags.POSTHOG) return
https://github.com/threshold-network/token-dashboard/pull/260#discussion_r990979213

2022-10-10 07:30 UTC, r-czajkowski commented on src/hooks/posthog/useIdentify.ts
> +    if (!featureFlags.POSTHOG) return
https://github.com/threshold-network/token-dashboard/pull/260#discussion_r990979213

2022-10-10 07:30 UTC, r-czajkowski commented on src/App.tsx
> +  usePosthog()
https://github.com/threshold-network/token-dashboard/pull/260#discussion_r990979213

2022-10-10 07:39 UTC, r-czajkowski commented on src/posthog/index.ts
> +const POSTHOG_API_HOST = "https://app.posthog.com"
Yeah, we can move to the `.env` file.

2022-10-10 07:44 UTC, r-czajkowski commented on src/hooks/posthog/index.ts
> +export * from "./usePosthog"
It actually depends on other features like web3 react and react-router. Posthog hooks can't exist w/o other libs. TBH I don't have a strong opinion on that, both places work for me.

2022-10-10 08:11 UTC, r-czajkowski commented on src/hooks/posthog/useCapturePageview.ts
> +  }, [location])
Yeah I was thinking about it but it only returns the url w/o `?` and `#` see https://github.com/remix-run/history/blob/main/docs/api-reference.md#location. So if a path will be `<url>#something` or `<url>?query` this hook skip it and does not register the url change. Currently, we don't use the `#` and `?` in our dapp but maybe someday we will and probably we forget to update this hook. So not sure in which direction we should go 🤷

2022-10-26 13:25 UTC, michalsmiarowski submitted a review, later dismissed
LGTM 🚀

2022-10-26 13:53 UTC, pdyraga commented on .env.production
> +REACT_APP_POSTHOG_API_HOST=https://app.posthog.com
Shouldn't we take it from repository secrets instead of hardcoding?

2022-10-28 08:11 UTC, r-czajkowski commented on .env.production
> +REACT_APP_POSTHOG_API_HOST=https://app.posthog.com
d532b76

2022-10-28 10:53 UTC, michalsmiarowski approved these changes
LGTM

2022-10-31 09:10 UTC, pdyraga approved these changes

2022-10-31 09:11 UTC, merged