Add success state to OperatorAddressMappingCard
threshold-network/token-dashboard pull request #261
Opened 2022-10-05 13:15 UTC by michalsmiarowski

Closes: #259 
Depends on: #223

2022-10-05 20:04 UTC, georgeweiler commented on src/pages/Staking/OperatorAddressMappingCard.tsx
> +                ? "One application from the tBTC + Random Beacon Rewards Bundle Suite requires the Operator Address mapped."
I know that this matches designs, but I think it might be more clear to tell the user which app needs to be mapped. wdyt? worth bringing up?

2022-10-06 14:20 UTC, georgeweiler commented
@michalsmiarowski It looks like the designs have been re-updated. Do you want to implement the newest changnes here before we merge?

2022-10-17 12:54 UTC, michalsmiarowski commented
@r-czajkowski @georgeweiler This one is ready to be reviewed.

I will address the info about PRE app in a separate PR, because it will require a lot of changes.

2022-10-25 10:49 UTC, r-czajkowski requested changes
Left two minor comments. Overall looks good 👍

2022-10-25 10:49 UTC, r-czajkowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
> +  }
Let's use a function from https://github.com/threshold-network/token-dashboard/commit/ea991e2232121d13ff6cbc86f1f08de64753f96d.

2022-10-25 10:49 UTC, r-czajkowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
> +            <Box key={`mapped_operator_${appName}_${operator}`}>
I think we can get rid of the `Box` component and use `Hstack` directly. Also adding the `divider` prop to the `HStack` we can get rid of the logic for rendering the line divider, I mean this code snippet: 
```jsx
 {Object.keys(mappedOperators)[
                Object.keys(mappedOperators).length - 1
              ] !== appName && <LineDivider />}
```

2022-10-26 12:17 UTC, michalsmiarowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
> +  }
Fixed in d818bfae1f4bd8a655c2e27cfb31000d7a7c13e3

2022-10-26 13:14 UTC, r-czajkowski approved these changes

2022-10-26 13:15 UTC, merged