Updates spacing between several components
threshold-network/token-dashboard pull request #265
Opened 2022-10-06 21:15 UTC by georgeweiler

Resolves https://github.com/threshold-network/token-dashboard/issues/237

There were also a few places where I think `SimpleGrid` worked better than making our own grid with Stacks and widths.

2022-10-10 13:43 UTC, r-czajkowski requested changes

2022-10-10 13:43 UTC, r-czajkowski commented on src/pages/Upgrade/UpgradeToken.tsx
> +    <SimpleGrid columns={{ base: 1, xl: 2 }} spacing={4}>
Now we have two columns 50/50 are we sure it's ok?

PR impl
![obraz](https://user-images.githubusercontent.com/57687279/194879092-bf231b13-a85e-42c6-9015-03561a2b9816.png)

Current prod impl:
![obraz](https://user-images.githubusercontent.com/57687279/194879053-e5acd8f2-2ca1-466c-a652-946e6de7d62a.png)

2022-10-10 13:43 UTC, r-czajkowski commented on src/pages/Upgrade/UpgradeToken.tsx
> -      direction={{ base: "column-reverse", md: "row" }}
We set the `column-reverse` to see the token balances on the top on smaller screens instead of upgrade form which IMO makes more sense. Are we sure this order is ok?

PR impl
![obraz](https://user-images.githubusercontent.com/57687279/194879903-a963c2f0-6e21-4e38-99c3-282ab521c55f.png)

Current prod impl:
![obraz](https://user-images.githubusercontent.com/57687279/194879834-c4526a31-ab47-48d9-a395-b7423d5a55ea.png)

2022-10-26 11:38 UTC, r-czajkowski approved these changes

2022-10-26 12:09 UTC, r-czajkowski commented on src/pages/Upgrade/UpgradeToken.tsx
> +    <SimpleGrid columns={{ base: 1, xl: 2 }} spacing={4}>
4463ce5

2022-10-26 12:09 UTC, r-czajkowski commented on src/pages/Upgrade/UpgradeToken.tsx
> -      direction={{ base: "column-reverse", md: "row" }}
4463ce5

2022-10-26 13:20 UTC, michalsmiarowski approved these changes
LGTM

2022-10-26 13:21 UTC, merged