Update copy: tBTC
threshold-network/token-dashboard pull request #273
Opened 2022-10-13 12:15 UTC by r-czajkowski

Closes: #249 
The convention should be `tBTC` in every case.

2022-10-19 09:15 UTC, michalsmiarowski requested changes
Left one small comment

2022-10-19 09:15 UTC, michalsmiarowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +}
I've created something similar in #261 

https://github.com/threshold-network/token-dashboard/pull/261/files#diff-3fa8603c049ef8353a7dd98f5e20aa5a41453162f5100edee663a8b186ea152bR38-R41

Since this is used in many places I think we should export it and move it to some other place - maybe to `src/types`?

2022-10-19 11:12 UTC, r-czajkowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +}
ea991e2

2022-10-24 12:15 UTC, michalsmiarowski approved these changes
LGTM 🏒

2022-10-24 12:15 UTC, merged