Adds connect wallet CTA to upgrade card
threshold-network/token-dashboard pull request #29
Opened 2021-11-23 19:30 UTC by georgeweiler

2021-12-02 15:15 UTC, r-czajkowski requested changes

2021-12-02 15:15 UTC, r-czajkowski commented on src/components/UpgradeCard/UpgradeCardTemplate.tsx
> +        )}
Can we extract it to a separate component? My point is we will probably need the same solution for other transactions so I believe we should create a reusable component. Eg `SubmitTxButton`? Maybe you will have a better idea of the name of this component 🙂.

2021-12-08 16:48 UTC, georgeweiler commented on src/components/UpgradeCard/UpgradeCardTemplate.tsx
> +        )}
good call, i've updated.

2021-12-08 17:24 UTC, r-czajkowski requested changes

2021-12-08 17:24 UTC, r-czajkowski commented on src/components/SubmitTxButton.tsx
> +        Upgrade
Can we add eg. `text` prop and render here? Or maybe pass rest props to the `Button` so we will be able to pass any button props(w/o `onClick` prop) and children. eg

`SubmitTxButton.tsx`
```
if(active){
 return (
  <Button ...restProps onClick={onSubmit} />
 )
}
```

`AnyComponent.tsx`
```
<SubmitTxButton isFullWidth mt={6} onSubmit={} <other Chakra Button prosp> >
 Upgrade
</SubmitTxButton>
```

What do you think?

2021-12-08 17:59 UTC, r-czajkowski approved these changes
LGTM!

2021-12-08 17:59 UTC, merged