Rewards allocation for Nov 1st 2022
threshold-network/token-dashboard pull request #293
Opened 2022-11-03 08:44 UTC by r-czajkowski

This PR adds a merkle tree computed in https://github.com/threshold-network/merkle-distribution/pull/37 to Threshold Token Dashboard.

2022-11-03 22:41 UTC, michalsmiarowski requested changes
I think values here don't match the values in https://github.com/threshold-network/merkle-distribution/pull/37. Let's verify it before the merge. See the comment below.

2022-11-03 22:41 UTC, michalsmiarowski commented on src/merkle-drop/rewards.json
> +  "merkleRoot": "0x4ce540139e54d66475fa40f5f4bf5398c17937b54960852cb56734c023112dc3",
I think the values are not correct 🤔  There are differenv values for `totalAmount` and `merkleRoot` in https://github.com/threshold-network/merkle-distribution/pull/37 (`MerkleDIst.json` file)

Your values:
```
"totalAmount": "256480309535848311798474676",
"merkleRoot": "0x4ce540139e54d66475fa40f5f4bf5398c17937b54960852cb56734c023112dc3",
```
  
Values in `merkle-distribution`:
```
"totalAmount": "256710294590339327077459526",
"merkleRoot": "0xf2616aeb5f4ddf8e53afdbc49bb24d628dd4a7bbb6e9d16df39dc9b1a6419fc6",
```

2022-11-04 11:23 UTC, michalsmiarowski approved these changes
LGTM! 👍

2022-11-04 11:24 UTC, manumonti approved these changes
LGTM ✌️

2022-11-04 12:25 UTC, merged