Generate QR code for the deposit address
threshold-network/token-dashboard pull request #297
Opened 2022-11-08 22:28 UTC by michalsmiarowski

Closes: #287

2022-11-11 09:57 UTC, r-czajkowski requested changes
Left two minor comments.

2022-11-11 09:57 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +import QRCode from "react-qr-code"
Can we create our wrapper for this external component? If we changed the lib for generating QR code we would change only our wrapper component and keep the same interface.

2022-11-11 09:57 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +        <Flex direction={"column"} alignItems={"center"}>
Do we need flex wrapper?

2022-11-15 07:41 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +import QRCode from "react-qr-code"
Fixed in 0bbe4fbc41e7953f1b58180c6e87c946bce03e9f

2022-11-15 07:42 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +        <Flex direction={"column"} alignItems={"center"}>
Fixed in 5ae4f2febbc0c63b29f243f60d66a8a90da59b39

2022-11-15 08:37 UTC, r-czajkowski approved these changes

2022-11-15 08:37 UTC, merged