Adds chakra theme to storybook with Button component as an example
threshold-network/token-dashboard pull request #3
Opened 2021-09-15 21:31 UTC by georgeweiler

2021-09-15 21:33 UTC, georgeweiler commented
I'm open to discussion about how to better manage our storybook. This PR is mostly for the config and to get us chatting. There may be other examples of how we've used storybook in past projects that we should adopt.

2021-09-22 11:54 UTC, nkuba requested changes
I reviewed the workflow only and left some minor comments.

2021-09-22 11:54 UTC, nkuba commented on .github/workflows/chromatic.yml
> +jobs:
Can we remove the comments?

```suggestion
name: "Chromatic"

on: push

jobs:
```

2021-09-22 11:54 UTC, nkuba commented on .github/workflows/chromatic.yml
> +      - uses: actions/checkout@v1
There is a newer version available.

```suggestion
      - uses: actions/checkout@v2
```

2021-09-22 11:54 UTC, nkuba commented on .github/workflows/chromatic.yml
> +          # Should set this up from a secret: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
I configured the `CHROMATIC_PROJECT_TOKEN` secret for this repository, you're good to use it.

2021-09-22 11:54 UTC, nkuba commented on .github/workflows/chromatic.yml
> +          autoAcceptChanges: true
If `autoAcceptChanges` is the only difference in these two steps we could combine them:

```suggestion
      - name: Publish to Chromatic and auto accept changes
        if: 
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          projectToken: adb814d4adb6
          # Auto accept changes for main branch commits.
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
```

2021-09-22 15:23 UTC, georgeweiler commented
Great suggestions @nkuba! I've pushed some updates. I had to make some additional changes to support v2: https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code

2021-09-22 23:41 UTC, georgeweiler commented
I'm going to merge this into the chakra-theming branch so we are only working with 1 pull request for our theme & storybook

2021-09-22 23:42 UTC, merged