Add a supported chain id to the env
threshold-network/token-dashboard pull request #30
Opened 2021-11-23 21:54 UTC by georgeweiler

2021-12-15 10:13 UTC, r-czajkowski requested changes

2021-12-15 10:13 UTC, r-czajkowski commented on .gitignore
> +.env
Can we add the `.env` file with default values for local development?

```
REACT_APP_SUPPORTED_CHAIN_ID=1337
REACT_APP_RPC_URL=http://localhost:8545
REACT_APP_WS_URL=ws://localhost:8545
```

2021-12-15 10:13 UTC, r-czajkowski commented on .gitignore
> +.env
I think we can add `.env.production` file as well which will be used during the build process and the file might look like:

`.env.production`
```
REACT_APP_SUPPORTED_CHAIN_ID=$chain_id
REACT_APP_RPC_URL=$rpc_url
REACT_APP_WS_URL=$ws_url
```

where environment variables(`chain_id`, `rpc_url`, `ws_url`) will be set in CI side.

2021-12-15 10:13 UTC, r-czajkowski commented on src/utils/isSupportedNetwork.ts
> +import * as net from "net"
I think it is unnecessary import.

2021-12-17 14:38 UTC, r-czajkowski commented on src/web3/connectors/walletConnect.ts
> +})
Do we need this?

2021-12-17 14:39 UTC, r-czajkowski approved these changes
LGTM!

2021-12-28 09:58 UTC, nkuba commented
@georgeweiler having a PR description provided would be super helpful.

2021-12-29 15:23 UTC, r-czajkowski commented on src/web3/connectors/walletConnect.ts
> +})
Addressed in https://github.com/threshold-network/token-dashboard/pull/30/commits/2dcbcea3fabbb2e8818d9b6ada43dca2c1b83ad7

2021-12-29 15:26 UTC, r-czajkowski approved these changes
LGTM! Ropsten preview looks good and I was able to test the migration flow so let's :shipit:

2021-12-29 15:27 UTC, merged