Builds the analytics banner and modals
threshold-network/token-dashboard pull request #309
Opened 2022-11-15 20:57 UTC by georgeweiler

depends on

- Adds SecondaryAnnouncementBanner component per design system: https://www.figma.com/file/zZi2fYDUjWEMPQJWAt8VWv/Threshold-DS?node-id=3234%3A24113&t=JOeGnkOEmiegQJ2k-0

- Adds Analytics banner to the overview page with feature flag

- Adds 3 modal screens for signing up for analytics

2022-11-17 14:39 UTC, r-czajkowski requested changes
Left few minor comments.

2022-11-17 14:39 UTC, r-czajkowski commented on src/components/AnnouncementBanner/SecondaryAnnouncementBanner.tsx
> +import { BoxProps, useMultiStyleConfig } from "@chakra-ui/react"
Can we import from `@threshold-network/components`?

2022-11-17 14:39 UTC, r-czajkowski commented on src/components/Modal/AnalyticsModal/AnalyticsConfirmation.tsx
> +            <FeedbackInfoItem {...detail} />
Missing `key` prop.

2022-11-17 14:39 UTC, r-czajkowski commented on src/theme/SecondaryAnnouncementBanner.ts
> +      top: "12px",
Are we ok with using fixed units here instead of a relative (`14px->3.5` `12px ->3`)? Just flagging.

2022-11-17 14:39 UTC, r-czajkowski commented on src/theme/SecondaryAnnouncementBanner.ts
> +      // maxW: "460px",
If it is unnecessary let's remove.

2022-11-17 14:39 UTC, r-czajkowski commented on src/theme/SecondaryAnnouncementBanner.ts
> +    bg: mode("brand.50", "#2B3036")(props),
Maybe we should add this color(`#2B3036`) to the components repo?

2022-11-17 20:12 UTC, georgeweiler commented on src/theme/SecondaryAnnouncementBanner.ts
> +    bg: mode("brand.50", "#2B3036")(props),
good idea. Mind if we update in another PR so it's not blocking while we wait for the change in the components repo?

2022-11-18 12:49 UTC, r-czajkowski commented on src/theme/SecondaryAnnouncementBanner.ts
> +    bg: mode("brand.50", "#2B3036")(props),
Sure let's just leave a `TODO` comment 👍

2022-11-18 12:52 UTC, r-czajkowski approved these changes
LGTM. Leave final approval to @michalsmiarowski.

2022-11-20 14:46 UTC, merged