Installs posthog capture event on close modal events
threshold-network/token-dashboard pull request #313
Opened 2022-11-17 23:39 UTC by georgeweiler

I noticed that our posthog event list had many click events such as "Clicked Path" or "Clicked SVG" when the user closes a modal.

 This PR fixes the problem by:

- Adding `className="ph-no-capture"` to prevent those useless events
- Adding a capture event to the `closeModal` method that logs the modal type

2022-11-18 12:35 UTC, r-czajkowski requested changes

2022-11-18 12:35 UTC, r-czajkowski commented on src/hooks/useModal.ts
> +    capture(`Closed Modal`, { modalType })
Maybe we should create type in `src/posthog/index.ts` for our custom events? eg. `export type PosthogEvents = "modal-closed" | "other-event-here" ....`

2022-11-18 12:35 UTC, r-czajkowski commented on src/posthog/index.ts
> +  posthog.capture(event, params)
shouldn't we check here if the feature flag is enabled? On the other hand, would be great if we could keep a wrapper for posthog independent of our feature flags. So maybe we should create a hook eg:
```tsx
import * as posthog from "../../posthog"
import { featureFlags } from "../../constants"

const useCapture(eventName: PosthogEvents) => {
 return useCallback((params) => {
  if (!featureFlags.POSTHOG) return
  posthog.capture(eventName, params)
 }, [eventName])
}
``` 

and then in a component:

```tsx
const capture = useCapture("modal-closed")

const closeModal = () => {
 capture({ modalType } )
}

```

2022-11-18 16:40 UTC, georgeweiler commented
All very good suggestions @r-czajkowski . I've implemented your change requests

2022-11-18 16:40 UTC, georgeweiler commented on src/hooks/useModal.ts
> +    capture(`Closed Modal`, { modalType })
I decided to use an enum in `src/types/posthog`. let me know if that works for you

2022-11-18 19:58 UTC, r-czajkowski requested changes

2022-11-18 19:58 UTC, r-czajkowski commented on src/types/types.ts
> +export enum posthogEvent {
Shouldn't be `PosthogEvent`(starting with a capital letter)?

2022-11-18 19:58 UTC, r-czajkowski commented on src/types/types.ts
> +export enum posthogEvent {
Maybe let's rename the file to `src/types/posthog.ts`.

2022-11-18 19:58 UTC, r-czajkowski commented on src/posthog/index.ts
> +  console.log("identifying the eth address: ", ethAddress)
Do we need this console log?

2022-11-18 19:58 UTC, r-czajkowski commented on src/hooks/posthog/useCapture.ts
> +export const useCapture = (eventName: posthogEvent) => {
Can we export this hook from `src/hooks/posthog/index.ts` ?

`src/hooks/posthog/index.ts`
```
export * from "./usePosthog"
export * from "./useCapture"
```

2022-11-18 19:58 UTC, r-czajkowski commented on src/hooks/useModal.ts
> +import { useCapture } from "./posthog/useCapture"
If you agree with a comment from above let's import from `./posthog`.

2022-11-19 22:39 UTC, georgeweiler commented on src/types/types.ts
> +export enum posthogEvent {
whoops 🙈

2022-11-22 14:11 UTC, r-czajkowski approved these changes

2022-11-22 14:20 UTC, merged