Opt-In analytics + Hashed analytics ID
threshold-network/token-dashboard pull request #317
Opened 2022-11-22 20:07 UTC by georgeweiler

2022-11-30 17:29 UTC, michalsmiarowski requested changes
Left some comments too look at before the merge 👇

2022-11-30 17:29 UTC, michalsmiarowski commented on src/utils/hashString.ts
> +  algorithm?: string
I think we should specify either union literal string type or string enum for this one. Reading from the docs the available types are:

- "SHA-1"
- "SHA-256"
- "SHA-384"
- "SHA-512".

docs: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#parameters

2022-11-30 17:29 UTC, michalsmiarowski commented on src/utils/hashString.ts
> +  string: string
Maybe `value` would be a better name to avoid the duplacte of string word in different context? We can keep the function name as `hashString`

2022-11-30 17:29 UTC, michalsmiarowski commented on src/utils/hashString.ts
> +const hashString = async ({
Can we rename the file from `hashString.ts` to `crypto.ts`? We could create all the crypto related utility functions here.

Also let's export this function in `utils/index.ts` to simplify the imports

2022-11-30 17:29 UTC, michalsmiarowski commented on src/store/analytics/analyticsSlice.ts
> +})
Do we actually want to save this info in a redux store? 🤔 Wouldn't that mean that after refresh the user would have accept/decline the `AnalyticsConfirmation` modal again?

Maybe the better idea would be to store it in local storage, associated with given account?

2022-11-30 17:29 UTC, michalsmiarowski commented on src/store/analytics/analyticsSlice.ts
> +    },
I think `optIn` and `optOut` are too generic in my opinion. We often export all the actions from the slice. For example in staking slice: 

```
export const {
  updateState,
  setStakes,
  providerStaked,
  providerStakedForStakingProvider,
  toppedUp,
  unstaked,
  setMinStake,
} = stakingSlice.actions
```

If we just have `optIn` and `optOut` then it doesn't really say anything what those action changes. I would change them to something like `analyticsEnabled` and `analyticsDisabled`

2022-12-03 00:52 UTC, georgeweiler commented
closing because the changes in https://github.com/threshold-network/token-dashboard/pull/323 better implement the local storage functionality.

2022-12-03 00:52 UTC, closed without merging