Missing path when decreasing authorization
threshold-network/token-dashboard pull request #318
Opened 2022-11-28 12:35 UTC by r-czajkowski

Closes: #266 

This PR adds support for decreasing authorization for non-beta operators. The operator who is not a beta operator could not join the pool. If they are deauthorizing to 0, from the sortition pool's perspective, their status is up to date (see [`RandomBeacon.isOperatorUpToDate`](https://github.com/keep-network/keep-core/blob/4e940f02b8bebeafcae2727016e00ea70355a709/solidity/random-beacon/contracts/libraries/BeaconAuthorization.sol#L551) and [`WalletRegistry.isOperatorUpToDate`](https://github.com/keep-network/keep-core/blob/4049dc0153c33c3c4cbb2e9a1808581bf76144fb/solidity/ecdsa/contracts/libraries/EcdsaAuthorization.sol#L554)). The client will not attempt to update the pool if the status is up to date. The new deauthorization flow is: when the authorization decrease is requested, we check if there is a staking provider <> operator mapping. If such mapping exists, we check if the operator is in the pool. If not, we execute a call to `RandomBeacon.updateOperatorStatus / WalletRegistry.updateOperatorStatus` to activate the authorization decrease delay.

## Main changes
### Threshold-ts lib
1. Updates the `getStakingProviderAppInfo` function- add additional fields to returned object:
   - `operator`- operator address that will operate application node,
   - `isOperatorInPool`- determines if the operator is in the sortition pool. If this is `undefined` it means that the operator for a given staking provider is not set.
2. Adds `updateOperatorStatus` function- updates the status of the operator in the sortition pool. If there was an authorization decrease requested, it is activated by starting the authorization decrease delay. Function reverts if the operator is not known. From the T dapp perspective, it should be called when the authorizer requests the authorization decrease and the operator is not in the sortition pool.

### UI
Updates the application card to render the `deauthorization initiation needed` status- this status means that the operator is not in the sortition pool and the deauthorization request is not active. The user must call `updateOperatorStatus` function to activate the authorization decrease delay.

<details>
  <summary>Screenshots</summary>
  
  
![obraz](https://user-images.githubusercontent.com/57687279/204278840-74e990c1-4657-421a-8b41-69e8bc37667b.png)

</details>

2022-12-01 09:43 UTC, michalsmiarowski reviewed
First round of review done! Gonna test it out locally now, so bear in mind that new comments can arrive soon

2022-12-01 09:43 UTC, michalsmiarowski commented on src/hooks/staking-applications/useInitiateDeauthorization.ts
> +      updateOperatorStatus.toString,
Can you explain why we added `toString` to this (and only this) function in the dependency array? 🤔

2022-12-01 10:22 UTC, r-czajkowski commented on src/hooks/staking-applications/useInitiateDeauthorization.ts
> +      updateOperatorStatus.toString,
I can't 😆. Added it by accident 😬

2022-12-01 11:28 UTC, r-czajkowski commented on src/types/staking-applications.ts
> +  | "deauthorization-initiation-needed"
The auto-completion should work for literal string type 🤔 at least works with my IDE.

2022-12-01 11:41 UTC, r-czajkowski commented on src/hooks/staking-applications/useInitiateDeauthorization.ts
> +  shouldUpdateOperatorStatusAfterInitiation: boolean,
3e16cc8

2022-12-01 11:41 UTC, r-czajkowski commented on src/hooks/staking-applications/useInitiateDeauthorization.ts
> +      updateOperatorStatus.toString,
4f08cd9

2022-12-01 14:14 UTC, michalsmiarowski requested changes

2022-12-01 14:14 UTC, michalsmiarowski commented on package.json
> +    "@keep-network/tbtc-v2.ts": "1.0.0-dev.11",
I think we don't need this change anymore after we merged this one : https://github.com/threshold-network/token-dashboard/pull/322

Let's merge main into this branch and see if it resolves the issue

2022-12-05 06:12 UTC, r-czajkowski commented on src/components/Modal/DeauthorizeApplicationModal/InititateDeauthorization.tsx
> +                <Box as="p">1 transaction- Deauthorization Initiation.</Box>
I think yes, because the `updateOperatorStatus` function activates the authorization decrease delay. See: https://github.com/keep-network/keep-core/blob/main/solidity/ecdsa/contracts/libraries/EcdsaAuthorization.sol#L263-L264 and https://github.com/keep-network/keep-core/blob/main/solidity/ecdsa/contracts/libraries/EcdsaAuthorization.sol#L539-L547

2022-12-05 06:31 UTC, r-czajkowski commented on src/hooks/staking-applications/useInitiateDeauthorization.ts
> +      if (!shouldUpdateOperatorStatusAfterInitiation) return
62d3baa

2022-12-05 06:31 UTC, r-czajkowski commented on package.json
> +    "@keep-network/tbtc-v2.ts": "1.0.0-dev.11",
643707e

2022-12-06 11:32 UTC, michalsmiarowski approved these changes
LGTM 👍

2022-12-06 11:38 UTC, merged