Test hooks
threshold-network/token-dashboard pull request #32
Opened 2021-12-07 15:14 UTC by r-czajkowski

WIP

2022-01-10 15:40 UTC, michalsmiarowski commented
@r-czajkowski I noticed some warning in the console not related to the code changed in this PR, but related to the hooks, so maybe we could include them here. Or we can also create new PR for that to make it more clear.

First one displays when you navigate from any page (other than `Network`) to `Network`:
`React has detected a change in the order of Hooks called by NavPill. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: `https://reactjs.org/link/rules-of-hooks

Seconds one displays when you navigate form `Network` to any other page:
`React has detected a change in the order of Hooks called by NavItem. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: `https://reactjs.org/link/rules-of-hooks

It looks like it's better to call hooks on top of the components instead of calling them conditionally inside `return`.

So in `NavPill` i would assign `useColorModeValue("brand.500", "white")` to a variable and then assing it in return based on `isActive` value. For example:

`const colorModeValueForLink = useColorModeValue("brand.500", "white")`

and then in `<Link>` component:
`color={isActive ? colorModeValueForLink : undefined}`

The similiar problem is in `NavItem` but this might need a little smarter approach since we use `useColorMode` a LOT of times there.

Thoughts?

2022-01-10 18:08 UTC, michalsmiarowski reviewed
First part of the review done! Probably more comments to come 😅 but overall great job 💪

2022-01-10 23:02 UTC, michalsmiarowski requested changes
Second part of review is done! Still didn't change my mind and think this code is awesome 🚀 🌔  Left some comments to look at before merge

2022-01-10 23:02 UTC, michalsmiarowski commented on src/web3/hooks/useSubscribeToContractEvent.ts
> +      }
I think this `if` statement is unnecesary, because we have

```
if (!contract) {
  return
}
```
on top of the `useEffect()`

2022-01-11 09:07 UTC, r-czajkowski commented on src/hooks/useLocalStorage.ts
> +    // eslint-disable-next-line
Currently, it's unnecessary but I believe we should add this `eslint` rule in the future because there are lots of missing dependencies in hooks. We should be sure when we want to skip one of the dependencies.

In this case, we actually don't skip the dependency but convert it to the `string` because react hooks don't use deep equality for dependencies- so if we pass here an object this hook will be triggered every render. Regarding using `JSON.stringify` in dependency array please see: https://github.com/facebook/react/issues/14476#issuecomment-471199055

This PR is out of the scope of adding this `eslint` rule but I left this comment for the future.

2022-01-11 09:07 UTC, r-czajkowski commented on src/hooks/useLocalStorage.ts
> +    // eslint-disable-next-line
Please see https://github.com/threshold-network/token-dashboard/pull/32#discussion_r781923148.

2022-01-11 09:49 UTC, r-czajkowski commented on src/web3/hooks/useVendingMachineRatio.ts
> +class Mutex {
When you use this hook multiple times, `contract.ratio` fn will also be called multiple times. Eg. we render two components on a given page, and each of them uses this hook with `useVendingMachineRatio(Token.Keep)`- in that case `contract.ratio` fn will also be called 2 times. To avoid this situation we lock "mutex" and a hook fetches data from the chain only once.

2022-01-11 09:52 UTC, r-czajkowski commented on src/web3/hooks/__tests__/useContract.test.ts
> +    })
When an address is not defined [`useContract` returns `null`](https://github.com/threshold-network/token-dashboard/blob/main/src/web3/hooks/useContract.ts#L14-L16) and this scenario is covered [here](https://github.com/threshold-network/token-dashboard/blob/c5995d0ae073e0a85c6424ff0fee42479a3787f1/src/web3/hooks/__tests__/useContract.test.ts#L29-L33).

2022-01-11 10:00 UTC, r-czajkowski commented on src/web3/hooks/useVendingMachineRatio.ts
>  export const useVendingMachineRatio = (token: UpgredableToken) => {
I don't think so it's necessary because TypeScript can infer the type of your hooks itself without your help. In this case, we have a clear situation and TS knows that this hook will return `string`. eg. when this hook would return only 2 strings eg. `"0"` and `"1"` we should add type. Greate example of when we should type hook is `useLocalStorage` hook- TS can't infer what type the function will return.

2022-01-11 10:02 UTC, r-czajkowski commented on src/hooks/useTConvertedAmount.ts
>    const ratio = useVendingMachineRatio(token)
Same as above. I believe it's unnecessary because everything is inferred for you- please see https://devtrium.com/posts/react-typescript-how-to-type-hooks#how-to-type-usememo-and-usecallback

2022-01-11 10:07 UTC, r-czajkowski commented on src/hooks/useTConvertedAmount.ts
I don't think it's necessary. We don't export these values and are strongly related to this hook so I recommend keeping these values in the same file.

2022-01-11 10:09 UTC, r-czajkowski commented on src/web3/hooks/__tests__/useSendTransaction.test.ts
> +import { renderHook } from "@testing-library/react-hooks"
Same as here https://github.com/threshold-network/token-dashboard/pull/32#discussion_r781990261.

2022-01-11 10:15 UTC, r-czajkowski commented on src/web3/hooks/__tests__/useSendTransaction.test.ts
> +      useSendTransaction(mockedContract, methodName)
> Also non-blocking:
> 
> Since we are mockedContract in a lot of tests we could also consider creating `Contract` mock in a separate `__mocks__` folder as stated in the link that I provided above. But this is just something to think about, not really needed to get my approve for this PR 😎

Yeah, great idea! Can we address it in a separate PR because I think we need a more flexible solution. We should be able to add more than one function to the `MockedContract` and we should cover other fields from  `Contract` from "@ethersproject/contracts`.

2022-01-11 10:34 UTC, r-czajkowski commented on src/web3/hooks/__tests__/useUpgradeToT.test.ts
> +import { act, renderHook } from "@testing-library/react-hooks"
Same as here https://github.com/threshold-network/token-dashboard/pull/32#discussion_r781990261

2022-01-11 10:44 UTC, r-czajkowski commented on src/hooks/usePrevious.ts
> -}
I removed this hook because I've noticed that it exists in `@chakra-ui/react`.

2022-01-11 10:56 UTC, r-czajkowski commented on src/web3/hooks/__tests__/useSubscribeToERC20TransferEvent.test.ts
> +import { act, renderHook } from "@testing-library/react-hooks"
The main idea behind this is to pass all arguments separately not in an array. I mean:
```
 useSubscribeToContractEvent(contract, "Transfer", (from, to, amount)
```

instead of
```
const from = args[0]
const to = args[1]
const amount = args[2]
```

Ideally would be great if we could create dynamic types for a given contract but I don't know how to achieve it.

2022-01-12 08:05 UTC, michalsmiarowski commented on src/web3/hooks/useVendingMachineRatio.ts
> +class Mutex {
Just flagging - I think this would be a good case for a unit test. We could check if it's behave properly when `useVendingMachineRatio` is called multiple times.

2022-01-12 08:15 UTC, michalsmiarowski requested changes
Added some final comments

2022-01-12 08:15 UTC, michalsmiarowski commented on src/web3/hooks/__tests__/useVendingMachineRatio.test.ts
> +    })
Can we use `localStorageDefaultValue` as second argument here?

2022-01-12 08:15 UTC, michalsmiarowski commented on src/web3/hooks/__tests__/useVendingMachineRatio.test.ts
> +    })
And here

2022-01-12 11:16 UTC, michalsmiarowski approved these changes
🔥  LGMT 🔥

2022-01-12 11:17 UTC, merged