Unspent transactions check & deposit reveal
threshold-network/token-dashboard pull request #321
Opened 2022-11-29 10:22 UTC by michalsmiarowski

2023-01-09 15:04 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +        : new MockBitcoinClient())
Can't we simplify?
```
this._bitcoinClient = bitcoinConfig.client ?? new ElectrumClient(bitcoinConfig.credentials)
```

2023-01-09 15:19 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +  bitcoinNetwork: BitcoinNetwork
I believe we should use `readOnly` or save `bitcointConfig` in a private field and create a getter for `bitcoinNetwork` eg:
```
private _bitcoinConfig;

constructor(...){
 this._bitcoinConfig = bitcoinConfig
}

get bitcoinNetwork() {
    return this._bitcoinConfig.network;
  }
```

2023-01-09 15:30 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +    return this.bitcoinNetwork
Can't we use the same type for `bitcoinNetwork` as is used in `import { validate as isValidBtcAddress } from "bitcoin-address-validation"`? I mean `Network` from `bitcoin-address-validation`?

2023-01-09 15:36 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +    return walletPublicKey
Let's remove the unnecessary `if` statement:

`return this._bridge.activeWalletPublicKey()`

2023-01-09 15:46 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +    if (!isValidBtcAddress(btcRecoveryAddress, this.bitcoinNetwork as any)) {
We use the `import { validate as isValidBtcAddress } from "bitcoin-address-validation"` in TBTC wrapper and in `src/utils/forms.ts`. Can we create our wrapper for this external function in`threshold-ts/utils/bitcoin` use this wrapper?

2023-01-09 15:55 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.interface.ts
>  export interface ITBTC {
imo `tbtc.interfac` file is unnecessary and it's not consistent with other. Also the file structure looks weird when we have
```
threshold-ts
 tbtc
  tbtc
```

we are already in the context of tbtc so it's unnecessary to repeat the `tbtc` word so better will be just `interface.ts` but I think its OK to keep the interface and implementation in the same file and just have `index.ts`.

2023-01-09 15:56 UTC, r-czajkowski commented on src/tbtc/mock-bitcoin-client.ts
> +// export default connect(mapStateToProps)(MockBitcoinClient)
Let's remove if its unnecessary.

2023-01-10 11:35 UTC, r-czajkowski requested changes

2023-01-10 11:35 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingFlowRouter.tsx
> +          </Button>
Maybe we can use `SibmitTxButton`?

2023-01-10 11:35 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
>    }
Do we need this if we already display an empty state in `MintingFlowRouter` component?

2023-01-10 11:35 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +    const utxos = await threshold.tbtc.findAllUnspentTransactionOutputs(
I believe we probably need to call this more than once. Currently, it works well because we use the mock bitcoin client and it returns the mocked utxos immediately. We could create a listener that will query the `findAllUnspentTransactionOutputs` for `depositAddress` for example every 10 seconds until we find utxo. Once we find the utxo we should unblock the `I sent the BTC` button or automatically redirect to the next step.

2023-01-10 11:35 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/InitiateMinting.tsx
> +
I don't understand why we have this in each step if we already created an empty state in `MintingFlowRouter` 🤔.

2023-01-10 11:35 UTC, r-czajkowski commented on src/hooks/tbtc/useTBTCDepositDataFromLocalStorage.ts
> +    deleteFromStorage("tBTCDepositData")
Can't we use `setTBTCDepositData(undefined)`? Or maybe we could add `delete` function to our wrapper of  `useLocalStorage` to keep a local storage API in one place?

2023-01-10 11:35 UTC, r-czajkowski commented on src/hooks/tbtc/useRevealMultipleDepositsTransaction.ts
> +}
Looks like we use this pattern in a few places so maybe we could try to create `useSendMultipleTransactions` hook?

2023-01-10 11:35 UTC, r-czajkowski commented on src/hooks/tbtc/useRevealMultipleDepositsTransaction.ts
> +          return true
Why `return true`?

2023-01-10 11:35 UTC, r-czajkowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +    )
We do the same in `MakeDeposit.tsx`. Can we create a common function? Or maybe we should just pass "calculated" deposit address and utxos as a props to this component.

2023-01-10 11:37 UTC, r-czajkowski commented on src/hooks/tbtc/useTBTCDepositDataFromLocalStorage.ts
> +    deleteFromStorage("tBTCDepositData")
We can get `delete` function from hook as the third element of the array returned from `useLocalStorage` hook. Please see https://github.com/rehooks/local-storage/blob/master/src/use-localstorage.ts#L110

2023-01-11 12:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +        btcRecoveryAddress={"tb1q0tpdjdu2r3r7tzwlhqy4e2276g2q6fexsz4j0m"}
I think we should remove this prop, so this field should be empty by default.

2023-01-11 12:46 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
>        <Button type="submit" form="tbtc-minting-data-form" isFullWidth>
Generating a deposit address takes some time so would be great if we could add any loading indicator eg. we can add `isLoading` prop to the `Button` component.

2023-01-11 13:02 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +
I think its unnecessary we can pass `btcDepositAddress` to the `findAllUnspentTransactionOutputs`.

2023-01-11 13:16 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
>  export const MakeDeposit: FC = () => {
It would be great if we could add a loading indicator to indicate that the dapp is looking for utxo for the given `btcDepositAddress`. I think on main network it takes a while.

2023-01-12 12:16 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
>  export const MintingSuccess: FC = () => {
The `dismiss` button doesn't work.

2023-01-12 12:19 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
>  export const MintingSuccess: FC = () => {
The last step doesn't clean up deposit data from the local storage so after refreshing page and connecting to a wallet the deposit flow starts from step 2.

2023-01-13 08:21 UTC, michalsmiarowski commented on src/web3/hooks/useSendTransaction.ts
> +          returnedTransaction = await library.getTransaction(tx)
@r-czajkowski Since this change required lot of changes (so it's more chance of getting some errors that we won't notice) I addresed this in a separate PR: #348

2023-01-13 10:33 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.ts
> +    return this.bitcoinNetwork
There is a difference in namings - in TBTC we use `main` for mainnet and `bitcoin-address-validation` uses `mainnet`. So we would probably have to refactor the TBTC lib.

Taking your previous comment into consideration we have two methods right now:
- `_getBitcoinNetworkForTBTCLib` (private) - used only to get the proper network inside the `TBTC` class to use with TBTC lib (so `main` instead of `mainnet`)
- `getBitcoinNetwork` (public) - used on the front end side to do a validation with `bitcoin-address-validation` lib

I'm not sure if having those two methods is ok. I have mixed feelings. If you have any ideas on how to improve this I would love to hear them 😄 

Here is a commit: f04b7c0e5c6a08ef25fa8d7b64d5136683927742

2023-01-13 10:33 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.ts
> +  bitcoinNetwork: BitcoinNetwork
f04b7c0e5c6a08ef25fa8d7b64d5136683927742

2023-01-13 10:34 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.ts
> +        : new MockBitcoinClient())
ee76852385406582a25bd5f845eeb3be995b1919

2023-01-13 10:36 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.ts
> +      ) as any,
Fixed in c8d0a6b0d4fcc95a2c06e2ffffcacd7dfddb5dad

Not sure how to get rid of `any` next to `ethereumConfi.providerOrSigner`. Probaly would have to refactor whole `getProviderOrSigner` method flow.

We also use `any` in similar situation here:
https://github.com/threshold-network/token-dashboard/blob/7b15fcd11513cf092c9f5c88d249a686bf78ecef/src/threshold-ts/utils/contract.ts#L33

2023-01-13 11:10 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +// export default connect(mapStateToProps)(MockBitcoinClient)
7dce0eeacc728c1a48c5b5fc47954e5ca7a88924

2023-01-13 11:10 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.interface.ts
>  export interface ITBTC {
I agree. Fixed in 1641787433729d4c3d3b5e38596be96be5a4a455

2023-01-13 11:11 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.ts
> +    return walletPublicKey
a9c5abbb8cf59886923c204cfcef66f28fd90201

2023-01-13 11:37 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
>      return new Promise<UnspentTransactionOutput[]>((resolve, _) => {
fed6fd3cfad979f3ed9f82c9be9cd051135c41b6

2023-01-13 11:37 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +        // TODO: pass proper values for walletPubKey and refundPubKey
fed6fd3cfad979f3ed9f82c9be9cd051135c41b6

2023-01-13 11:38 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +    if (!this.isDepositTransactionMocked) {
Right now we mock the deposit transaction each time user clicks `i sent btc`. I refactored it here: fed6fd3cfad979f3ed9f82c9be9cd051135c41b6

2023-01-13 11:38 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +      resolve(this._confirmations.get(transactionHash.toString()) as number)
fed6fd3cfad979f3ed9f82c9be9cd051135c41b6

2023-01-13 11:48 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
>    }
I've added it just in case so that we know for sure that this component shouldn't be rendered without the wallet connected.

2023-01-13 12:35 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +      ) as any,
> Not sure how to get rid of any next to ethereumConfi.providerOrSigner. Probably would have to refactor whole getProviderOrSigner method flow.

We can dig into it later 👍

2023-01-13 12:46 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +  bitcoinNetwork: BitcoinNetwork
We can just:
```
get bitcoinNetwork() {
    return this._bitcoinConfig.network
  }
}
```

2023-01-13 12:55 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +    return this.bitcoinNetwork
Regarding `_getBitcoinNetworkForTBTCLib` we can create a map(maybe even outside a class or keep it as a private read-only field :thinking:) that will map our naming convention(`mainnet/testnet)` into the tbtc-v2.ts lib.

```ts
// Find a good name for this variable.
const map: Record<BitcoinNetwork, "main" | "testnet"> = {
  testnet: "testnet",
  mainnet: "main",
} 

class TBTC {

 get bitcoinNetwork() {
  return this._bitcoinConfig.network
 }
 
 calculateDepositAddress = async (
    depositScriptParameters: DepositScriptParameters
  ): Promise<string> => {
    const network = map[this.bitcoinNetwork]
    return await calculateDepositAddress(depositScriptParameters, network, true)
  }
}
```

2023-01-13 12:59 UTC, r-czajkowski commented on src/tbtc/mock-bitcoin-client.ts
> +      resolve(this._confirmations.get(transactionHash.toString()) as number)
Maybe let's update for other methods as well for consistency?

2023-01-13 13:23 UTC, r-czajkowski requested changes

2023-01-13 13:23 UTC, r-czajkowski commented on src/tbtc/mock-bitcoin-client.ts
> +    if (isDepositTransactionMocked) {
I'm not sure but I think if w've already created a mocked tx for a given deposit address we should return it from the cache.

2023-01-13 13:23 UTC, r-czajkowski commented on src/tbtc/mock-bitcoin-client.ts
> +    const isDepositTransactionMocked = !utxos || utxos.length === 0
The condition or name is misleading. If we want to keep `isDepositTransactionMocked` name the condition should be: `utxos?.length > 0`.

2023-01-13 13:23 UTC, r-czajkowski commented on src/tbtc/mock-bitcoin-client.ts
> +    // })
Unnecessary comments.

2023-01-13 13:23 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
>    }
Given that we are going to refactor the deposit form I think it's unnecessary but if we want to keep it let's do it with HOC. We do this quite often so I propose a HOC `withOnlyConnectedWallet` which will handle all this logic.

2023-01-13 16:31 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +    const utxos = await threshold.tbtc.findAllUnspentTransactionOutputs(
Fixed in a460cbe1a8781ab4220ee6b7ccf5534c36a7f487 and 150751bb39a6bb02f2556a2d4753866650a4d468

2023-01-13 16:31 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
>    }
e5c7cd8ac89ac115ef8b0f9be0f002cb0f9a3e21

2023-01-13 16:32 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/InitiateMinting.tsx
> +
e5c7cd8ac89ac115ef8b0f9be0f002cb0f9a3e21

https://github.com/threshold-network/token-dashboard/pull/321#discussion_r1069446785

2023-01-13 16:32 UTC, michalsmiarowski commented on src/hooks/tbtc/useTBTCDepositDataFromLocalStorage.ts
> +    deleteFromStorage("tBTCDepositData")
0c19c75cf8ad2e29e195131378b969c199b42664

2023-01-13 16:34 UTC, michalsmiarowski commented on src/hooks/tbtc/useRevealMultipleDepositsTransaction.ts
> +          return true
I need to return something so I can print the success modal if only user reveal only one transaction (in case there are multiple utxo's). Since returning true is not readable I changed it so that it now returns successfullTxs: 5dcd0004815dc3af7090fe347997b80d8b5686ae

2023-01-16 08:16 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.ts
> +  bitcoinNetwork: BitcoinNetwork
22ac99386e4cb5a34ec729b43c3cb3de3720f10d

2023-01-16 08:16 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.ts
> +    return this.bitcoinNetwork
22ac99386e4cb5a34ec729b43c3cb3de3720f10d

2023-01-16 08:17 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +      resolve(this._confirmations.get(transactionHash.toString()) as number)
41035279bb0c2335f61717f2eed498dbb724e3db

2023-01-16 08:18 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
>        <TbtcMintingCardTitle previousStep={MintingStep.InitiateMinting} />
c0eb2993b535b076c2d5ee92c41ac46681a3db8a

2023-01-16 08:18 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
>        <Button type="submit" form="tbtc-minting-data-form" isFullWidth>
1e15f7b6a3d7aaa63741ffe7600e32f6a87516f1

2023-01-16 08:20 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +
FIxes this in one of the previous commits already, can't find which one tho because it's too many of them 😅 You can see the change in `File changes` tab.

2023-01-16 09:13 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/components/TbtcMintingCardTitle.tsx
> +
c3d3bf2c77120f4e6ff4e634191e0ca8fd4f1e8a

2023-01-16 11:25 UTC, r-czajkowski commented on src/hooks/tbtc/useRevealMultipleDepositsTransaction.ts
> +          return true
What about `onSucces/onError` callbacks pattern? I think using callbacks is more readable.

2023-01-16 12:00 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +    // })
Removed

2023-01-16 12:07 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +    const isDepositTransactionMocked = !utxos || utxos.length === 0
You are right. Fixed in fc904aa0074c5508095fe25fc5434d6f877c7f51

2023-01-16 12:08 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +    if (isDepositTransactionMocked) {
I think I've named the condition wrong. It should be `!isDepositTransactionMocked` so the utxo is returned when the deposit tx is not mocked yet. I've fixed it in fc904aa0074c5508095fe25fc5434d6f877c7f51

2023-01-16 12:10 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +        btcRecoveryAddress={"tb1q0tpdjdu2r3r7tzwlhqy4e2276g2q6fexsz4j0m"}
I will remove it before the merge because it makes the testing faster when I don't have to copy/paste the address each time. Let's keep this convo as unresolved.

2023-01-16 12:12 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
>  export const MakeDeposit: FC = () => {
Fixed there: a8da3b9bfd9b63ee8c0b7e028c6745d1cbbe0ab8

Also added the functionality to check if the utxo was already revealed.

2023-01-16 12:54 UTC, michalsmiarowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +    )
We already had `depositAddress` saved in redux store so we don't have to calculate it here. I've fixed it in 2eaee6042450723eebb8bf69f198dafcaa062d68

2023-01-17 09:53 UTC, r-czajkowski requested changes

2023-01-17 09:53 UTC, r-czajkowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +    )
Just wondering why we need to call `findAllUnspentTransactionOutputs` here. To go to step 3 the dapp must find utxo so we can pass it as a prop or save it in the redux store.

2023-01-17 09:53 UTC, r-czajkowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +      closeModal()
As I mentioned here https://github.com/threshold-network/token-dashboard/pull/321#discussion_r1071132246  I think using callbacks is more readable.

2023-01-17 09:53 UTC, r-czajkowski commented on src/hooks/tbtc/useBridgeContract.ts
> +import BridgeContract from "../../../node_modules/@keep-network/tbtc-v2/artifacts/Bridge.json"
Shouldn't we import from `@keep-network/tbtc-v2/artifacts/Bridge.json`?

2023-01-17 09:53 UTC, r-czajkowski commented on src/hooks/tbtc/useTBTCDepositDataFromLocalStorage.ts
> +}
What about this?
```ts
export type TBTCDepositDataLocalStorage {
 [address: string]: {
    blindingFactor: string
    btcRecoveryAddress: string
    walletPublicKeyHash: string
    refundLocktime: string
    btcDepositAddress: string
  }
}
```

In that case, we will have one record in local storage.

2023-01-17 09:53 UTC, r-czajkowski commented on src/hooks/tbtc/useSubsribeToDepositRevealedEvent.ts
> +        console.log("depositor", account)
Maybe let's leave a TODO comment here? We probably need to dispatch an action here to update the redux store.

2023-01-17 09:53 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +  }, [utxos?.length])
Can't we do it in a single `useEffect` ? Once we find utxo in the first hook we can then check if a given utxo is already revealed.

2023-01-17 09:53 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +    }
Maybe let's simplify a little?
```tsx
if (!utxos) return

const deposits = await Promise.all(
 utxos.map(threshold.tbtc.getRevealedDeposit)
)

setHasAnyUnrevealedDeposits(
 deposits.some((deposit) => deposit.revealedAt === 0)
)
```

What do you think?

2023-01-17 09:53 UTC, r-czajkowski commented on src/threshold-ts/tbtc/tbtc.ts
> +export interface ITBTC {
As I mentioned here https://github.com/threshold-network/token-dashboard/pull/321#discussion_r1064799391 shouldn't we rename this file to `index.ts`?

2023-01-17 10:28 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +  }, [utxos?.length])
This was refactored in https://github.com/threshold-network/token-dashboard/pull/350 so I don't think I can do it in one hook.

Please see 2b24e2e476ff5a35f65bf872d4d5cb7e4c77c6c4

2023-01-17 10:37 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.ts
> +export interface ITBTC {
a4af8bd387da9f13aa51823dfc9e7d5fbdfaf60a

2023-01-17 10:37 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/tbtc.interface.ts
>  export interface ITBTC {
And in a4af8bd387da9f13aa51823dfc9e7d5fbdfaf60a

2023-01-17 10:38 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +    }
Wonderful piece of code 🤩  Fixed in eeef9d4601430991f273a26953547ffb7d8fbedf

2023-01-17 10:38 UTC, michalsmiarowski commented on src/hooks/tbtc/useBridgeContract.ts
> +import BridgeContract from "../../../node_modules/@keep-network/tbtc-v2/artifacts/Bridge.json"
a9b9d2b2fd06146bacf0fed87872b8f0fdd7cca6

2023-01-17 10:39 UTC, michalsmiarowski commented on src/components/Modal/TbtcRecoveryFileModal/index.tsx
> +        <Button onClick={() => handleDownloadClick(depositScriptParameters)}>
d7b436f6c7fab515c556ef5e272c35f6f74a007a

2023-01-17 10:41 UTC, michalsmiarowski commented on src/hooks/tbtc/useTBTCDepositDataFromLocalStorage.ts
> +}
8bd48635ff42455c77e46014eed1f6a81e188406

2023-01-17 10:59 UTC, michalsmiarowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +      closeModal()
3a5a52a57c536a2dc9dc0c15f8e76bfbb952b63c

2023-01-17 10:59 UTC, michalsmiarowski commented on src/hooks/tbtc/useRevealMultipleDepositsTransaction.ts
> +          return true
Great idea, fixed in 3a5a52a57c536a2dc9dc0c15f8e76bfbb952b63c

2023-01-17 11:02 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +        btcRecoveryAddress={"tb1q0tpdjdu2r3r7tzwlhqy4e2276g2q6fexsz4j0m"}
9aca1e722520e234c2d7e979aa934d45d23cfe7f

2023-01-17 11:18 UTC, merged

2023-01-18 07:42 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +  private _depositRefundLocktimDuration = 23328000
This change was dictated by the changes in https://github.com/keep-network/tbtc-v2/pull/452

The `calculateDepositRefundLocktime` function was modified by adding a mandatory `depositRefundLocktimeDuration` argument so we need to provide a proper `depositRefundLocktimeDuration`` value while computing the `refundLocktime` hex for `calculateDepositAddress`. The proper value is `23328000` - this is 9 months in seconds, assuming 1 month = 30 days.

For more info please see https://github.com/keep-network/tbtc-v2/issues/432