Refactors analytics succes modals
threshold-network/token-dashboard pull request #323
Opened 2022-11-30 18:12 UTC by georgeweiler

- The analytics success and decline modals were very similar so have been combined into one modal with props.
- They are also both used in the "settings" page, so their location should not have been tied directly to the analytics modal. A new modal was created to be shared.
- The Analytics "info" had the same problem, so it was moved to a new sharable component
- Other feedback forms use the same modal style, so their content was added

2022-12-08 08:59 UTC, r-czajkowski requested changes
Looks good 👍 . Left few minor comments.

2022-12-08 08:59 UTC, r-czajkowski commented on src/hooks/useAnalytics.ts
> +import { useLocalStorage } from "@rehooks/local-storage"
I'll refactor our custom implementation of `useLocalStorage` and use hook from `@rehooks/local-storage` so we will use the new implementation in all places and we will have a nice wrapper for external lib.

2022-12-08 11:56 UTC, r-czajkowski commented on src/hooks/useAnalytics.ts
> +import { useLocalStorage } from "@rehooks/local-storage"
#328

2022-12-08 15:28 UTC, georgeweiler commented on src/components/Modal/FeedbackSubmissionModal/index.tsx
> +    </>
I agree. let's tackle this refactor in another PR. happy to take that on.

2022-12-08 16:48 UTC, michalsmiarowski approved these changes
Looking good 🔥 

I left some comments to look at. They ar non-blocking so I'm giving an approve but let's look at them as I believe some of them might be pretty important.

2022-12-08 16:48 UTC, michalsmiarowski commented on src/pages/Overview/index.tsx
> +        !hasUserResponded && <AnalyticsBanner />}
Non- blocking, but something to think about:

Because of `!hasUserResponded` condition we won't display the `AnalyticsBanner` after use decline it (unless he removes the proper data from local storage manually). Maybe the better idea would be to display the banner anyway even if `isAnalyticsEnabled` is set to false?

For a quick solution i propose to remove `!hasUserResponded` from this condition. This way the AnalyticsBanner will display always until the user accepts it. He can click "X" on the right corner if he doesn't want to see the banner. What do you think @georgeweiler ?

2022-12-08 16:48 UTC, michalsmiarowski commented on src/hooks/useAnalytics.ts
> +  >("isAnalyticsEnabled", undefined)
I think it's pretty important but I mark it as non-blocking:

I think we should add the info about analytics enabled for each account separately. The key should have the address in it's name. For example:

`0x888467263A7384D1ce4eFf7eF4623D32d838eF6E-isAnalyticsEnabled`: `true`
`0xE432f97B4EfEc07166150a5F013b53a215ffFc3A-isAnalyticsEnabled`: `false`

I'm marking this as non-blocking since I would like to have your opinion first @r-czajkowski @georgeweiler. We can address it in separate PR if needed.

2022-12-08 16:48 UTC, michalsmiarowski commented on src/components/Modal/AnalyticsModal/index.tsx
> +          </BodyXs>
Non-blocking UI issue:

Horizontal line is missing under this text. Based on the figma views:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/40306834/206512608-f87c65df-539f-4c59-a536-3cc77f71323f.png">

2022-12-09 12:00 UTC, r-czajkowski approved these changes

2022-12-09 15:33 UTC, michalsmiarowski approved these changes
LGTM

2022-12-09 15:33 UTC, merged