tBTC v2 UI updates
threshold-network/token-dashboard pull request #329
Opened 2022-12-09 14:01 UTC by r-czajkowski

WIP...

2022-12-14 06:28 UTC, michalsmiarowski requested changes
Looking good 🔥 

Left some comments to look at down below 👇

2022-12-14 06:28 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +          </BodyMd>
I've made some of the changes you removed here to make it "acceptable-looking" on smaller resolution. We should remove the modal that ask user to use the designs on desktop devide (especially since it is appearing below 1280px so it's not even close to mobile resolution 😨 ):

https://github.com/threshold-network/token-dashboard/blob/ffd16547207ad6f7b59e82817f2450b1c011632b/src/pages/tBTC/Bridge/index.tsx#L18-L26

I made some of the changes above to make the tbtc page look good-ish on all resolutions, but right now the step 2 does not look good on ~750-980px width:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/40306834/207520827-b9bbeed4-e72f-4bc5-8ab7-661760b5e9dc.png">

As you can see the timeline content goes out of the card's border.

I think the main issue is with `btcDepositAddress` and it's container, because it goes out of the container (in the background) and push the timeline to the right.

Do you mind if we address this issue in this PR and comment out the display of the `DesktopModal`? Can you also test it out in all resolution if nothing is "off"?

2022-12-14 17:24 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingFlowRouter.tsx
> +        />
As I remember we decided that all external links should have an arrow. Ref #214

2022-12-14 17:34 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +          </BodyMd>
Good point, but I think we should ask designers for mobile views first and implement them once we get the final views. cc @liz-shinn

2022-12-14 17:39 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingFlowRouter.tsx
> +        />
Unless this link redirects to our internal `How it Works` page 🤔

2022-12-15 02:10 UTC, liz-shinn commented on src/pages/tBTC/Bridge/MintingCard/MintingTimeline.tsx
> +        <Icon as={TimeIcon} alignSelf="center" /> 1-3 hours minting time
Yup I can add this. Agreed that the tilda (~) would be appropriate here.

2022-12-15 02:15 UTC, liz-shinn commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +          </BodyMd>
So early on there was a product decision here to not allow tBTC to work responsive screens. 

We had planned to show a modal that says something along the lines of "The tBTC minting experience is best conducted on a desktop." Or something to that effect. However, I don't see this modal designed in Figma (cc/ @sashatanase ) so I will go ahead and do that. 

At what screen width does this Step 2 really stop working? Can we still show the design at around screen width ~1080px, or do we need to show this modal at another resolution?

2022-12-15 02:42 UTC, liz-shinn commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +          </BodyMd>
https://discord.com/channels/893441201628405760/948910281323610192/984382378539642892 and
https://discord.com/channels/893441201628405760/961640844912382042/1047166414517178448

2022-12-19 16:27 UTC, liz-shinn commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +          </BodyMd>
Talked today with Michal on the product sync -- he demo-ed the responsive design. It looks good enough to be clear to users. However, we want to:
- shift the "Unmint / Mint" tabs since its a navigational element and the "tbtc - minting process" whole card to the be the first thing the user sees on mobile screens, since it's the actionable element.

If this turns out to be too time-consuming, we can introduce the modal element on smaller screens and disable it on tablet and mobile, like we do on the Keep dashboard dapp.

2022-12-20 11:43 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingTimeline.tsx
> +        <Icon as={TimeIcon} alignSelf="center" /> 1-3 hours minting time
3ba54df

2022-12-20 11:43 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MakeDeposit.tsx
> +          </BodyMd>
a4fbb9c

2022-12-29 07:12 UTC, r-czajkowski commented on src/components/Modal/TbtcRecoveryFileModal/index.tsx
> +        days.
383334f

2023-01-02 15:10 UTC, michalsmiarowski approved these changes
LGTM 🏄

2023-01-02 15:13 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/index.tsx
>  const TBTCBridge: PageComponent = (props) => {
https://github.com/threshold-network/token-dashboard/pull/338

2023-01-03 12:34 UTC, merged