How it works tbtc v2 updates
threshold-network/token-dashboard pull request #335
Opened 2022-12-20 09:58 UTC by r-czajkowski

Depends on: #329 

This PR updates the tBTC how it works page according to the Figma views.

2023-01-03 11:17 UTC, michalsmiarowski requested changes
Overall looks good 👍 Left some comments to look at before the merge

2023-01-03 11:17 UTC, michalsmiarowski commented on src/pages/tBTC/HowItWorks/MintingTimelineCard.tsx
> +export const MintingTimelineCard: FC<ComponentProps<typeof Card>> = ({
Minting timeline on How It Works page needs some polishing. This is how step 1 looks now:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/40306834/210346577-36df10e1-39b3-4b2d-9b43-b08299960f84.png">

Notice the `off-chain` label that is next to Step 1 (not above), image is centerd and also it looks like the description of the step is bigger on Figma. Similar differences are in other steps too

And this is how it should look based on Figma:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/40306834/210346625-8f4112ad-472b-4462-b1cf-775c4aa06295.png">

2023-01-04 12:54 UTC, r-czajkowski commented on src/pages/tBTC/HowItWorks/MintingTimelineCard.tsx
> +export const MintingTimelineCard: FC<ComponentProps<typeof Card>> = ({
8541d44 c831851

2023-01-04 12:54 UTC, r-czajkowski commented on src/pages/tBTC/HowItWorks/AuditsCard.tsx
>            <DetailedLinkListItem {...contract} />
b918470db8d65bf9d5cae4b56b4fd7c27ec84c4a

2023-01-04 12:55 UTC, r-czajkowski commented on src/enums/externalHref.ts
> +  spearbitAudit = "SOME_URL",
85b6d23- updated `btcRecoveryAddress` and `tbtcBridgeGithub`. Waiting for other from designers.

2023-01-05 08:08 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-01-05 08:52 UTC, r-czajkowski commented on src/enums/externalHref.ts
> +  spearbitAudit = "SOME_URL",
91fb144

2023-01-05 09:32 UTC, michalsmiarowski approved these changes
LGTM v2 🔥

2023-01-05 09:32 UTC, merged