Update unstake flow
threshold-network/token-dashboard pull request #336
Opened 2022-12-22 15:02 UTC by r-czajkowski

This PR updates the unstake flow. The maximum unstake amount depends on the authorized apps for example suppose the given staking provider has 10T, 20T worth of KEEP and 30 T worth of NU- all staked. The maximum application authorization is 40 T, then the maximum available amount to unstake is:
- 10T from T stake because: `10T(T stake) - min(0, 40T(authorization) - 20T(KEEP stake) - 30T(NU stake)) = 10`,
- 20T from KEEP stake because: `20T(KEEP stake) - min(0, 40T(authorization) - 30T(NU stake) - 10T(T stake)) = 20`,
- 20T from NU stake because: `30T(NU stake) - min(0, 40T(authorization) - 20T(KEEP stake) -10T(T stake)) = 20`,
- An owner can't unstake all stake(KEEP+NU+T) because has authorized applications. To unsktake all the staking provider cannot have any authorized apps.

Here we also updates a copy in the unstaking and top-up modals.

2023-02-02 14:33 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge but overall I think it looks good 🔥  I also need to test it with legacy stakes little more, so I might do another round of review soon.

2023-02-02 14:33 UTC, michalsmiarowski commented on src/store/staking/selectors.ts
> +          : "0",
Why do we put `0` here and not `BigNumber.from(stake.keepInTStake).sub(keepInTMintStake).toString()` like in `nuInT` or `t`? 

Note: (I used `keepInTMintStake` in this example instead of `keepInT`. See )

2023-02-02 14:33 UTC, michalsmiarowski commented on src/threshold-ts/utils/math.ts
> +}
I think it would be better to return the value with the same type as it was passed. This will make it more reusable:

```suggestion
import { BigNumber, BigNumberish } from "ethers"

export const min = (a: BigNumberish, b: BigNumberish) => {
  return BigNumber.from(a).lt(b) ? a : b
}
```

What do you think? (P.S I did not test it)

2023-02-02 14:33 UTC, michalsmiarowski commented on src/threshold-ts/utils/math.ts
> +}
Same as above if you agree

2023-02-07 14:57 UTC, r-czajkowski commented on src/store/staking/selectors.ts
> +          : "0",
Because you can unstake only the full KEEP stake, you can't unstake KEEP partially.

2023-02-07 15:00 UTC, r-czajkowski commented on src/threshold-ts/utils/math.ts
> +}
Hmm hard to say because you can pass `a` as `number` and `b` as `string`- in that case, function returns `a` as `number` but `b` as `string`. Maybe let's convert result to `BigNumber`?

2023-02-15 13:56 UTC, michalsmiarowski requested changes
Overall looks good. I tested it out with legacy Keep stake and it works wonderful. Left some small comments to look at before the merge

2023-02-15 13:56 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/index.tsx
> +          maxTokenAmount={isStakeAction ? tBalance : availableAmountToUnstake.t}
Maybe we could add a tooltip next to the maximum amount to unstake?:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/40306834/219042390-c44ce950-2f61-4831-9f73-59b1cf0ada6e.png">

This is a 45k T stake with 40k T authorized. We could add a questionmark-like icon next to the `5,000` and display a tooltip that says "If you want to unstake more T deauthorize the apps for this stake first".

What do you think and how hard do you think it would be? We should display the tooltip only if any app is authorized with some value.

2023-02-15 13:56 UTC, michalsmiarowski commented on src/store/staking/selectors.ts
> +          : "0",
Ahh i see now, makes sense.

What about nu? Can we unstake it partially?

2023-02-15 13:56 UTC, michalsmiarowski commented on src/store/staking/selectors.ts
> +    )
Non-blocking:

To be honest it took me a while to figure out what's going on here. Right now it seems easy but i assume if I ever had to go back to this piece of code after 1+ year it could take a while again to figure this out. Maybe we could write a comment that this calcultions are based on the `getMinStaked` method in `TokenStaking` contract? I think it have a nice explanation in the comment.

2023-02-15 15:28 UTC, r-czajkowski commented on src/store/staking/selectors.ts
> +    )
bb18553

2023-02-15 15:29 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/index.tsx
> +          maxTokenAmount={isStakeAction ? tBalance : availableAmountToUnstake.t}
8f8bd99

2023-02-15 15:47 UTC, merged

2023-02-15 15:51 UTC, michalsmiarowski reviewed
Forgot to gave an approve but I've tested out the new changes before the merge and they look great 🔥