Overview page
threshold-network/token-dashboard pull request #34
Opened 2021-12-10 23:04 UTC by georgeweiler

2021-12-15 12:32 UTC, r-czajkowski requested changes
Did a first pass and left some thoughts. I would like to flag that almost the entire HTML tree contains only `divs`- I believe we should pay more attention to semantic tags. Eg side bar component doesn't contain `nav` tag, we don't use `ul` tag to list item(eg. to list navigation items), we don't use the `header` tag in NavBar component etc.

2021-12-15 12:32 UTC, r-czajkowski commented on src/pages/Overview/index.tsx
> +  const { path } = useRouteMatch()
I think we can use a similar pattern as we used in KEEP token dashboard for pages components. In KEEP token dashboard the page component has an additional field `route` where you can define:
- title- title of the page,
- path- path to the page,
- pages- a sub pages, an array of page components.

And the main page component should be wrapped with `PageWrapper` component which render the sub pages. Please see how it works in the KEEP dapp and let me know what do you think. Main routing components in KEEP dapp:
- https://github.com/keep-network/keep-core/blob/main/solidity-v1/dashboard/src/components/Routing.jsx
- https://github.com/keep-network/keep-core/blob/main/solidity-v1/dashboard/src/components/PageWrapper.jsx
- https://github.com/keep-network/keep-core/blob/main/solidity-v1/dashboard/src/components/Header.jsx
- example of main page https://github.com/keep-network/keep-core/blob/main/solidity-v1/dashboard/src/pages/threshold/index.js
- example of sub page https://github.com/keep-network/keep-core/blob/main/solidity-v1/dashboard/src/pages/threshold/ThresholdUpgradePage.jsx#L320-L324

In T dapp we could add an additional field indicating which sub navigation component should be rendered in `PageWrapper`. Based on the Figma views we need 2 types of navigation:

<details>
  <summary>First type</summary>
  
  ![image](https://user-images.githubusercontent.com/57687279/146182136-13cf8aef-bdbe-464b-9780-6578a5dae839.png)

</details>

<details>
  <summary>Second type</summary>
  
![image](https://user-images.githubusercontent.com/57687279/146182480-4de51135-7a46-475d-a267-722015492264.png)

</details>

eg. `Overview` page in T dapp:
```
OverviewPage.route = {
 path: "/overview",
 pages: [Network, tBTC, Pre],
 subNavigationStrategy: FirstTypeOfNavigation or SecondTypeOfNavigation
}
```

2021-12-15 17:58 UTC, Battenfield reviewed
<img width="516" alt="Screen Shot 2021-12-15 at 9 57 12 AM" src="https://user-images.githubusercontent.com/7051522/146239956-ea909a5f-030e-46b3-a8a6-c79478aa5933.png">

subnav needs a dark mode text

2021-12-17 01:31 UTC, georgeweiler commented on src/pages/Overview/index.tsx
> +  const { path } = useRouteMatch()
I like this idea! here are a few thoughts:

- 100% agree that we need to create a smarter Route component. Listing the Routes in App.jsx is fine for now, but will only get us so far. The pattern of including some routing metadata on the component is really cool.

- I think we could drop the subNavigation strategy because the designs have changed a bit. Hopefully we only need one design.

- I'm not sure if we need the page wrapper component that defines styling for the header and subnavs. Worried that designs for other pages will change for other pages and we'll be have trouble extending the component to fit the new page designs. 


 Would you be ok with taking on this sub-navigation in a separate PR?

2021-12-17 14:15 UTC, r-czajkowski commented on src/pages/Overview/index.tsx
> +  const { path } = useRouteMatch()
> I'm not sure if we need the page wrapper component that defines styling for the header and subnavs. Worried that designs for other pages will change for other pages and we'll be have trouble extending the component to fit the new page designs.

Yeah, that's one of the cons...

> Would you be ok with taking on this sub-navigation in a separate PR?
sure!

2021-12-20 18:27 UTC, georgeweiler commented on src/components/Sidebar/index.tsx
> +  const isOverview = useRouteMatch("/overview")
@r-czajkowski what do you think about keeping useRouteMatch here? The issue is that the icon may depend on the route match. We could pass `passiveIcon` and `activeIcon`?

2021-12-27 11:00 UTC, r-czajkowski commented on src/components/Sidebar/index.tsx
> +  const isOverview = useRouteMatch("/overview")
I think we should use the `useRouteMatch` per `NavItem`, because the element should be responsible for recognizing the current active path. I believe it will better work with the routing metadata approach. Also if we add a new page we will have to remember to use `useRouteMatch`.

2021-12-27 12:20 UTC, r-czajkowski requested changes

2021-12-27 12:20 UTC, r-czajkowski commented on src/components/SubNavigationPills/index.tsx
> +    isActive: boolean
Let's use `useRouteMatch` instead of `isActive` prop.

2021-12-27 12:20 UTC, r-czajkowski commented on src/components/SubNavigationPills/index.tsx
> +        spacing={4}
Can we `as="ul"` and then for children `as="li"`?

2021-12-27 12:20 UTC, r-czajkowski commented on src/pages/Overview/Network/Interest.tsx
> +import { Label3 } from "../../../components/Typography"
Unnecessary import.

2021-12-27 12:20 UTC, r-czajkowski commented on src/pages/Overview/Network/Nodes.tsx
> +import { Stack, useMediaQuery, HStack } from "@chakra-ui/react"
Unnecessary imports `Stack, useMediaQuery`.

2021-12-27 12:20 UTC, r-czajkowski commented on src/pages/Overview/Network/UpgradeBanner.tsx
> +  HStack,
Unnecessary import.

2021-12-27 12:20 UTC, r-czajkowski commented on src/pages/Overview/Network/UpgradeBanner.tsx
> +          </Link>
same as above about `button` inside `a` tag.

2021-12-27 12:20 UTC, r-czajkowski commented on src/pages/Overview/Network/WalletBalances.tsx
> +        <H5>{numeral(balance).format("0,00.00")}</H5>
Could we use `TokenBalance` component?

2021-12-27 12:20 UTC, r-czajkowski commented on src/pages/Overview/index.tsx
> +  Switch,
Unnecessary import.

2021-12-27 12:20 UTC, r-czajkowski commented on src/pages/Overview/index.tsx
> +    { text: "tBTC", href: "/tBTC", isActive: pathname.includes("/tBTC") },
let's remove `isActive`. The `SubNavigationPills` should be responsible for this.

2021-12-27 12:20 UTC, r-czajkowski commented on src/pages/Overview/index.tsx
> +      <Redirect from="/overview" to="/overview/network" />
Should't we wrap routes with `Switch` component from `react-router-dom`?

2021-12-27 12:26 UTC, r-czajkowski commented on src/pages/Overview/Network/WalletBalances.tsx
> +        <H3>{numeral(conversionToTAmount).format("0,00.00")}</H3>
Let's create a util function that format amount eg:

`utils/formatAmount.ts`
```
import { formatUnits } from "@ethersproject/units"

export formatTokenAmount = (rawAmount, format = "0,00.00", decimals= 18) => {
 return numeral(formatUnits(rawAmount, decimals).format("0,00.00")
}

export formatFiatCurrencyAmount = (amount, format = "0,00" currencySymbol="$") => {
 return numeral(amount).format(`${currencySymbol}${format}`)
}
```

2021-12-27 12:33 UTC, r-czajkowski requested changes

2021-12-27 12:33 UTC, r-czajkowski commented on src/pages/Overview/Network/WalletBalances.tsx
> +  const formattedKeep = Number(formatUnits(keep.balance, 6))
Let's remove 6.

2021-12-30 16:14 UTC, georgeweiler commented on src/pages/Overview/Network/WalletBalances.tsx
> +  const formattedKeep = Number(formatUnits(keep.balance, 6))
Don't we need the decimal identifier for KEEP here?

2021-12-30 16:22 UTC, georgeweiler commented on src/pages/Overview/index.tsx
> +      <Redirect from="/overview" to="/overview/network" />
I think switch is not needed here because they are sub routes, and we want the path to match inclusively. https://v5.reactrouter.com/web/api/Switch

The sub routing doesn't work if you add a switch wrapper.

2021-12-30 16:22 UTC, georgeweiler commented on src/pages/Overview/index.tsx
> +    { text: "tBTC", href: "/tBTC", isActive: pathname.includes("/tBTC") },
👍  Ok I will add the activeIcon and passiveIcon props.

2021-12-31 06:23 UTC, r-czajkowski commented on src/pages/Overview/Network/WalletBalances.tsx
> +  const formattedKeep = Number(formatUnits(keep.balance, 6))
KEEP token has 18 decimals and `formatUnits` fn uses `18` by default. So I think we can get rid of `6` 🤔

2021-12-31 06:53 UTC, r-czajkowski requested changes

2021-12-31 06:53 UTC, r-czajkowski commented on src/utils/formatAmount.ts
> +  return numeral(formatUnits(rawAmount, decimals)).format(format)
Let's use `formatNumeral` fn here.
```
export const formatTokenAmount = (
  rawAmount: number | string,
  format = "0,00.00",
  decimals = 18
) => {
 return formatNumeral(formatUnits(rawAmount,decimals), format)
}
```

2021-12-31 06:53 UTC, r-czajkowski commented on src/utils/formatAmount.ts
> +  return numeral(amount).format(`${currencySymbol}${format}`)
Same as above.

2021-12-31 06:53 UTC, r-czajkowski commented on src/store/tokens/tokenSlice.ts
> +      decimals: 6,
KEEP/NU/T token has 18 decimals.

2021-12-31 08:06 UTC, r-czajkowski commented on src/pages/Overview/index.tsx
> +      <Redirect from="/overview" to="/overview/network" />
Based on the [docs](https://v5.reactrouter.com/web/example/nesting ) we should probably use the `Switch` statement for sub routes.

Regarding `The sub routing doesn't work if you add a switch wrapper`- because the `<Redirect from="/overview" to="/overview/network" />` is first. From docs:
>Renders the first child <Route> or <Redirect> that matches the location.

So If we use `<Redirect from="/overview" to="/overview/network" />` or pass `exact` prop it works.

I still don't understand why we use `const subroute = pathname.slice(url.length); const isActive = link.href === subroute` in `SubNavigationPills` component 😆. Here is my suggestion:

`src/pages/Overview/index.tsx`
```
import { Container } from "@chakra-ui/react"
import { Redirect, Route, useRouteMatch, Switch } from "react-router-dom"
import { H1, H3, Label1 } from "../../components/Typography"
import SubNavigationPills from "../../components/SubNavigationPills"
import Network from "./Network"
import TBTC from "./tBTC"
import Pre from "./Pre"
import useChakraBreakpoint from "../../hooks/useChakraBreakpoint"

const subNavLinks = [
  {
    text: "Network",
    path: "/network",
  },
  { text: "tBTC", path: "/tBTC" },
  { text: "PRE", path: "/pre" },
]

const Overview = ({}) => {
  const { path } = useRouteMatch()

  const isMobile = useChakraBreakpoint("md")

  return (
    <Container maxW={{ base: "2xl", xl: "6xl" }} mt={16}>
      <Label1>Threshold</Label1>
      {isMobile ? <H3>Network Overview</H3> : <H1>Network Overview</H1>}
      <SubNavigationPills parentPath={path} links={subNavLinks} />
      <Switch>
        <Route path={`${path}/network`}>
          <Network />
        </Route>
        <Route path={`${path}/tBTC`}>
          <TBTC />
        </Route>
        <Route path={`${path}/pre`}>
          <Pre />
        </Route>
        <Redirect from="/overview" to="/overview/network" />
      </Switch>
    </Container>
  )
}

export default Overview

```

`src/components/SubNavigationPills/index.tsx`
```
import { FC, createContext, useContext } from "react"
import {
  Box,
  Divider,
  HStack,
  Link,
  Stack,
  useColorModeValue,
} from "@chakra-ui/react"
import { Link as RouterLink, useRouteMatch } from "react-router-dom"

interface NavPillProps {
  path: string
  text: string
}

interface Props {
  links: NavPillProps[]
  parentPath: string
}

const SubNavigationPillContext = createContext({ parentPath: "" })

const useSubNavigationPillContext = () => {
  return useContext(SubNavigationPillContext)
}

const SubNavigationPills: FC<Props> = ({ parentPath, links }) => {
  return (
    <SubNavigationPillContext.Provider value={{ parentPath }}>
      <Box
        w="100%"
        borderBottom="1px solid"
        borderColor="gray.100"
        padding={6}
        as="nav"
      >
        <HStack
          spacing={4}
          divider={<Divider orientation="vertical" borderColor="gray.300" />}
          height="28px"
          as="ul"
        >
          {links.map(renderPill)}
        </HStack>
      </Box>
    </SubNavigationPillContext.Provider>
  )
}

const NavPill: FC<NavPillProps> = ({ path, text }) => {
  const { parentPath } = useSubNavigationPillContext()
  const _path = `${parentPath}${path}`
  const isActive = useRouteMatch({ path: _path, exact: true })

  return (
    <Stack position="relative" padding={2} as="li">
      <Link
        fontWeight={isActive ? "700" : undefined}
        color={isActive ? useColorModeValue("brand.500", "white") : undefined}
        as={RouterLink}
        to={_path}
        _hover={{
          textDecoration: "none",
        }}
      >
        {text}
      </Link>
      {isActive && (
        <Divider
          borderColor="brand.500"
          border="2px solid"
          top="47px"
          position="absolute"
          left={0}
        />
      )}
    </Stack>
  )
}

const renderPill = (pill: NavPillProps) => <NavPill key={pill.path} {...pill} />

export default SubNavigationPills

```

2022-01-03 20:15 UTC, georgeweiler commented on src/pages/Overview/Network/WalletBalances.tsx
> +      ["#7D00FF"]: {
great point. The [{}, {}] interface is much nicer. I've updated

2022-01-03 20:57 UTC, georgeweiler commented on src/pages/Overview/index.tsx
> +      <Redirect from="/overview" to="/overview/network" />
thanks @r-czajkowski you were right. Good catch.

2022-01-04 12:51 UTC, r-czajkowski commented on src/utils/formatAmount.ts
> +  return formatNumeral(formatUnits(amount), `${currencySymbol}${format}`)
Shouldn't be just an `amount` instead of `formatUnits(amount)`?

2022-01-04 13:08 UTC, r-czajkowski requested changes
Overview page looks awesome. Great job George 🚀. Left some notes.

2022-01-04 13:08 UTC, r-czajkowski commented on src/pages/Overview/Network/WalletBalances.tsx
> +        <H3>{formatNumeral(conversionToTAmount)}</H3>
Here we should use `formatTokenAmount` or `TokenBalance` component because `conversionToTAmount ` is in  "raw" format.

2022-01-04 13:08 UTC, r-czajkowski commented on src/pages/Overview/Network/WalletBalances.tsx
> +          conversionRate={keep.conversionRate}
Let's use `useVendingMachineRatio` hook.

```
const keepRatio = useVendingMachineRatio(Token.Keep)
```

2022-01-04 13:08 UTC, r-czajkowski commented on src/pages/Overview/Network/WalletBalances.tsx
> +          conversionRate={8.26}
Same as above

```
const nuRatio = useVendingMachineRatio(Token.NU)
```

2022-01-04 13:08 UTC, r-czajkowski commented on src/store/tokens/tokenSlice.ts
> +      conversionRate: 4.87,
We can use `useVendingMachineRatio` hook in component so let's remove it.

2022-01-04 13:08 UTC, r-czajkowski commented on src/store/tokens/tokenSlice.ts
> +      conversionRate: 2.66,
Same as above.

2022-01-04 13:08 UTC, r-czajkowski commented on src/store/tokens/tokenSlice.ts
> +      conversionRate: 1,
It's probably unnecessary 🤔

2022-01-04 13:23 UTC, r-czajkowski commented on src/pages/Overview/Network/WalletBalances.tsx
> +          textDecoration="underline"
Let's add href to the link and `rel="noopener noreferrer" target="_blank"` to open link in the new tab. Not sure where we should redirect users but this link https://github.com/threshold-network/solidity-contracts/blob/main/docs/rfc-2-vending-machine.adoc seems reasonable.

2022-01-04 17:38 UTC, georgeweiler commented on src/store/tokens/tokenSlice.ts
> +      conversionRate: 4.87,
what do you think about using the `useVendingmachineRatio` hook in the tokenContext to set these values in the store? That way we can keep the store as our source of truth for token info.

2022-01-04 17:40 UTC, georgeweiler commented on src/pages/Overview/Network/UpgradeBanner.tsx
> +    "Have KEEP or NuCircleBrand tokens? Upgrade them to T and harness the power of ThresholdCircleBrand."
Whoops, this must have been a findAndReplace bug

2022-01-04 17:47 UTC, georgeweiler commented on src/pages/Overview/Network/WalletBalances.tsx
> +          conversionRate={keep.conversionRate}
see my comment about using that hook to set values in the store.

2022-01-04 17:47 UTC, georgeweiler commented on src/pages/Overview/Network/WalletBalances.tsx
> +          conversionRate={8.26}
see my comment about using that hook to set values in the store.

2022-01-04 17:47 UTC, georgeweiler commented on src/store/tokens/tokenSlice.ts
> +      conversionRate: 2.66,
see my comment about using that hook to set values in the store.

2022-01-04 17:47 UTC, georgeweiler commented on src/store/tokens/tokenSlice.ts
> +      conversionRate: 1,
see my comment about using that hook to set values in the store.

2022-01-04 19:18 UTC, r-czajkowski commented on src/store/tokens/tokenSlice.ts
> +      conversionRate: 4.87,
hmm... tbh conversion rate makes only sense for KEEP and NU token and it's not something common for other tokens- eg. I've added TBTC token to context in #36 and this field it doesn't make sense for this token. Also, the vending machine defines ratio not token- actually token doesn't care about the exchange rate. So I'm not sure if we should do it this way. But up to you :) just left my thoughts.

2022-01-04 19:21 UTC, r-czajkowski approved these changes
LGTM! :shipit: Just small note. Could you please provide PR description and some screenshots how the overview page looks like?

2022-01-05 00:59 UTC, Battenfield commented
Merging - we can adjust the conversion rate after we ship, I'll ticket it out 🚀

2022-01-05 00:59 UTC, merged