UseSendTransaction hook refactor
threshold-network/token-dashboard pull request #348
Opened 2023-01-13 08:18 UTC by michalsmiarowski

See related discussion here: https://github.com/threshold-network/token-dashboard/pull/321#discussion_r1064674070

We are changing the return type of a `useSendTransaction` hook from `TransactionResponse` to `TransactionReceipt. Thanks to that we can simplifu the code a little bit and improve the API of this hook, because since we SEND the transaction returning the receipt (for this transaction) makes more sense.

2023-01-13 09:06 UTC, r-czajkowski requested changes

2023-01-13 09:06 UTC, r-czajkowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +import { TransactionReceipt } from "@ethersproject/providers"
If you agree with the comment above we should import the callback type and pass to the `useCallback`:
```ts
const onSuccess = useCallback<OnSuccessCallback>((receipt) => {...},[...])
```

2023-01-13 09:06 UTC, r-czajkowski commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +    (tx: TransactionReceipt) => {
same as above and let's update in other places.

2023-01-18 10:37 UTC, michalsmiarowski commented on src/web3/hooks/useSendTransaction.ts
> +  onSuccess?: (tx: TransactionReceipt) => void | Promise<void>,
Fixed in dd8dfe92dbec3dca902420fe33dc48f03ee66376

2023-01-18 10:37 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +import { TransactionReceipt } from "@ethersproject/providers"
dd8dfe92dbec3dca902420fe33dc48f03ee66376

2023-01-18 10:37 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +    (tx: TransactionReceipt) => {
dd8dfe92dbec3dca902420fe33dc48f03ee66376

2023-01-18 11:15 UTC, r-czajkowski approved these changes
LGTM

2023-01-18 12:32 UTC, r-czajkowski requested changes

2023-01-18 12:32 UTC, r-czajkowski commented on src/components/Modal/ClaimingRewards/index.tsx
> +    (receipt: TransactionReceipt) => {
Type is unnecessary here because we have type in `useCallback`.

2023-01-18 12:32 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  const { stake } = useStakeTransaction((receipt: TransactionReceipt) => {
Same as above.

2023-01-18 12:32 UTC, r-czajkowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +    (receipt: TransactionReceipt) => {
Same as above.

2023-01-19 07:29 UTC, michalsmiarowski commented on src/components/Modal/ClaimingRewards/index.tsx
> +    (receipt: TransactionReceipt) => {
e6014e2d5f304bc5f3e01d099914e58adc9b1bcf

2023-01-19 07:30 UTC, michalsmiarowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  const { stake } = useStakeTransaction((receipt: TransactionReceipt) => {
e6014e2d5f304bc5f3e01d099914e58adc9b1bcf

2023-01-19 07:30 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +    (receipt: TransactionReceipt) => {
e6014e2d5f304bc5f3e01d099914e58adc9b1bcf

2023-01-19 07:30 UTC, michalsmiarowski commented on src/components/Modal/StakingApplications/IncreaseAuthorization.tsx
> +    (receipt: TransactionReceipt) => {
e6014e2d5f304bc5f3e01d099914e58adc9b1bcf

2023-02-06 14:32 UTC, r-czajkowski approved these changes

2023-02-22 12:34 UTC, r-czajkowski approved these changes
LGTM!

2023-02-22 14:35 UTC, r-czajkowski approved these changes

2023-02-22 14:49 UTC, merged