tBTCv2 improvements
threshold-network/token-dashboard pull request #358
Opened 2023-01-23 12:54 UTC by r-czajkowski

This PR adds support for updating the tBTC v2 token balance and the bridge tx history by updating the `status` from `PENDING` to `MINTED` for a given deposit after finalizing the optimistic minting.

2023-01-23 16:19 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge, but overall looking great 🔥

2023-01-23 16:19 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +  }
I think that we should not reverse the txHash inside the `buildDepositKey` methods. I believe that we are reversing it because the transaction hash returned from `DepositRevealed` event is already reversed so we have to "unreverse" it, because it's gonna be reversed inside `EthereumBridge.buildDepositKey` function. This is specific situation that is related more to a `_findAllRevealedDeposits` function than `buildDepositKey` function. In the future we could use the `buildDepositKey` many times and the tx hash is not gonna be reversed. I think we could pass a `TransactionHash` instance here:

```suggestion
  buildDepositKey = (
    fundingTxHash: TransactionHash,
    fundingOutputIndex: number
  ): string => {
    return EthereumBridge.buildDepositKey(fundingTxHash, fundingOutputIndex)
  }
```

and then reverse it in `_findAllRevealedDeposits`:
```
  const depositKey = this.buildDepositKey(
          TransactionHash.from(fundingTxHash).reverse(),
          fundingOutputIndex
        )
```

Let me know what you think.

2023-01-23 16:19 UTC, michalsmiarowski commented on src/hooks/tbtc/useSubsribeToDepositRevealedEvent.ts
> +          ),
If you agree with the above then I think we should also reverse the `_fundingThHash` here. Or maybe stored is as reversedDepositKey 🤔 

Let's also add proper comments of why we are reversing it in the first place. Maybe we should figure out why it's reversed in the first place.

2023-01-24 11:36 UTC, r-czajkowski commented on src/hooks/useTBTCBridgeContractAddress.ts
>  export const useTBTCBridgeContractAddress = () => {
Link on Figma redirects to [BitcoinTx library](https://github.com/keep-network/tbtc-v2/blob/853bc8ff0601c82bb02cfaa0c904ba98d7d92fe5/solidity/contracts/bridge/BitcoinTx.sol#L81). Please [see](https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=7336%3A199127&t=3g8wplhD0EQglPhE-4). Also I'm not sure if this link is OK- IMO it should redirect to Bridge contract instead of BitcoinTx library. Currently, in dapp the GitHub link redirects to bridge contract.

2023-01-24 12:20 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +  }
> Can we move getters all the way to the top of the class just after the constructor?

Yeah sure. Is there any convention about where to put the getters? 🤔

> Also, i think all private methods should come before the public ones so we could also move the private methods to be just under getters.

I don't think so. Usually, private methods, are placed below the "parent method". The `_findAllRevealedDeposits` `_findAllMintedDeposits` and `_findAllCancelledDeposits` are related to `bridgeTxHistory` public function so they are placed below this method. So IMO this is a common convention. Another one is all public methods first, then all private methods at the bottom. Examples in our repos:
- https://github.com/keep-network/tbtc-v2/blob/19eeb508eb147bc7868112cb49ef8b95f2169004/typescript/src/ethereum.ts#L230-L296
- https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/TokenStaking.sol

2023-01-24 12:41 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +  }
The main idea was to not repeat `TransactionHash.from(fundingTxHash).reverse()`. In the Ethereum world, we can only get the `fundingTxHash` in [native Bitcoin little-endian format](https://github.com/keep-network/tbtc-v2/blob/main/solidity/contracts/bridge/Deposit.sol#L227-L228) from an event so that's why I wrapped the `EthereumBridge.buildDepositKey` into our implementation. But on the other hand, maybe someone wants to build a deposit key from the bitcoin tx hash and this wrapper won't work. So I'm not sure which direction we should go 🤔.

2023-01-24 13:41 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +  }
19ba5b4

2023-01-24 13:41 UTC, r-czajkowski commented on src/hooks/tbtc/useSubsribeToDepositRevealedEvent.ts
> +          ),
19ba5b4

2023-01-24 13:42 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +  }
> Can we move getters all the way to the top of the class just after the constructor?

fdd7eea

2023-01-24 13:47 UTC, r-czajkowski commented on src/hooks/useTBTCBridgeContractAddress.ts
>  export const useTBTCBridgeContractAddress = () => {
b3cbb67

2023-01-25 14:31 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +  }
I think you are right about the private methods. I found an interesting comment in stack overflow about that: https://stackoverflow.com/a/1760877

2023-01-25 14:48 UTC, michalsmiarowski approved these changes
LGTM :neckbeard:

2023-01-25 14:48 UTC, merged