Sentry-based deposit telemetry
threshold-network/token-dashboard pull request #361
Opened 2023-01-25 19:26 UTC by lukasz-zimnoch

Closes: #356

Here we add a telemetry mechanism based on Sentry. Responsibilities of this telemetry are:
- Recording all generated deposit data sets in order to facilitate further reveals that haven't happened automatically as well as possible refunds
- Recording all unhandled errors thrown by the dashboard. This is an out-of-the-box feature of Sentry SDK

We are also integrating Sentry switches with the existing CI workflows, in order to enable it on production and test environments automatically.

**Important note**: Popular ad blockers and privacy-focused browsers (e.g. Brave) may block requests targeting Sentry servers and cause some blind spots in the collected data.

2023-01-25 21:40 UTC, mhluongo approved these changes
Hell yeah. I haven't tested it locally but strong concept ACK

2023-01-25 21:40 UTC, mhluongo commented on src/hooks/sentry/useSentry.ts
> +  useEffect(() => {
Not necessary for this PR, but it's a little annoying that multiple uses of `useSentry()` throughout the component tree will call `sentry.init()` multiple times.

2023-01-25 21:41 UTC, mhluongo commented
Leaving the merge to someone more familiar with the rest of the codebase.

2023-01-26 09:13 UTC, lukasz-zimnoch commented on src/hooks/sentry/useSentry.ts
> +  useEffect(() => {
Looks like `[]` we pass as `useEffect`'s second param prevents that. I checked that during development.

2023-01-26 10:03 UTC, r-czajkowski requested changes
Left minor comments. Overall 🔥

2023-01-26 10:03 UTC, r-czajkowski commented on src/sentry/index.ts
> +    }
What do you think about this?
```ts
Object.entries(params).forEach(([key, value]) => scope.setExtra(key, value))
```
This way we can get rid of the`// eslint-disable-next-line guard-for-in`.

2023-01-26 10:26 UTC, lukasz-zimnoch commented on src/hooks/tbtc/useDepositTelemetry.ts
> +    []
Hasn't an empty array `[]` the same effect in this case?

2023-01-26 10:27 UTC, lukasz-zimnoch commented on src/sentry/index.ts
> +    }
I was thinking about it but the for-loop looks far more readable so decided to go that way.

2023-01-26 11:17 UTC, michalsmiarowski requested changes
Looking good! Left some comments to look at before the merge!

I tested out if the sentry catches the message and it works wonderful!

2023-01-26 11:17 UTC, michalsmiarowski commented on src/sentry/index.ts
> +    tracesSampleRate: 0.5,
I tested it out locally and it looks that 100% of the messages are captured anyway. So I'm not sure what this options exactly does 🤔

2023-01-26 11:32 UTC, lukasz-zimnoch commented on src/sentry/index.ts
> +    tracesSampleRate: 0.5,
`tracesSampleRate` determines what percentage of transactions is collected for performance tracing. A transaction in Sentry is for example a page load, page navigation, or an asynchronous task. This data is collected out of the box by enabling the `BrowserTracing` plugin. 

The errors and messages (the thing we use to capture deposits) are something different though. The percentage of collected errors/messages is set using the [`sampleRate`](https://docs.sentry.io/platforms/javascript/guides/react/configuration/options/#sample-rate) parameter whose default value is `1.0` so `100%` of events is collected.

2023-01-26 11:34 UTC, mhluongo commented on src/hooks/sentry/useSentry.ts
> +  useEffect(() => {
I believe the empty array only prevents that at a single call-site with `useEffect`... so this won't get called every render. If it appears multiple times in the component hierarchy, you'll still have multiple calls.

To get full idempotency, I think we'd need to use a context provider or global state. I can share a proof of concept layer, but again, not a blocker right now.

2023-01-26 11:38 UTC, mhluongo commented on src/sentry/index.ts
> +    tracesSampleRate: 0.5,
Trace sampling is for full stacktracesand performance stuff. If we send everything it can get expensive / slow.

I believe explicit events like deposits will be sent regardless.

2023-01-26 12:49 UTC, r-czajkowski approved these changes

2023-01-26 12:53 UTC, r-czajkowski commented on src/sentry/index.ts
> +    }
I think we can also use `scope.setExtras(params)` but I'm not sure because I can't find `setExtras` in docs. Ofc non-blocking.

2023-01-26 14:34 UTC, michalsmiarowski approved these changes
LGTM 🐉

2023-01-26 14:37 UTC, r-czajkowski approved these changes

2023-01-26 14:44 UTC, pdyraga approved these changes

2023-01-26 14:45 UTC, merged