Cosmetic improvements of the minting flow
threshold-network/token-dashboard pull request #383
Opened 2023-01-27 17:27 UTC by michalsmiarowski

Closes: #365 
Closes: #368

2023-01-27 17:56 UTC, r-czajkowski requested changes

2023-01-27 17:56 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintingCard/ProvideData.tsx
> +        label="ETH Address"
We should update in `MintingCard/ProvideData.tsx`.

2023-01-27 17:56 UTC, r-czajkowski commented on public/index.html
> +      }
I still have small `x` in address in some places:

![obraz](https://user-images.githubusercontent.com/57687279/215159559-f435884c-2703-44c1-b033-a6a42b6e75b9.png)

![obraz](https://user-images.githubusercontent.com/57687279/215159600-963ab675-fdd8-4008-a743-48a046e19f8a.png)

But looks ok in bride tx history table

![obraz](https://user-images.githubusercontent.com/57687279/215159706-d2644885-9327-49d3-875d-4e15bed5cab7.png)

2023-01-30 09:38 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintingCard/ProvideData.tsx
> +        label="ETH Address"
Fixed in 63bead5b250d14852adee433a48e27576e7262da

Looks like the whole `Unminting Card` needs to be refactored (cause there are so much code that repeats) so I don't think it's necessary to remove this change from `UnmintingCard` anyway.

2023-01-30 14:13 UTC, r-czajkowski approved these changes

2023-01-30 14:31 UTC, merged