Staking flow
threshold-network/token-dashboard pull request #39
Opened 2022-01-11 00:09 UTC by georgeweiler

2022-01-13 15:58 UTC, r-czajkowski requested changes
Left few thoughts. Overall looks very good! 🚀 I tested staking flow locally and works very well.

2022-01-13 15:58 UTC, r-czajkowski commented on src/web3/hooks/useStakeTransaction.ts
> +  )
This hook should be responsible for checking if a `TStaking` contract can spend a given amount of T token. So we should use`useApproveTStaking`(as is defined as above) here. Eg.:
```
const { approve } = useApproveTStaking()

const stake = useCallback(({ amount, operator, beneficiary, authorizer }: StakeRequest ) => {
 await approve(amount)
 await await sendTransaction(operator, beneficiary, authorizer, amount)
}, [<deps here>])
```

What do you think? One advantage of this is that the component does not have to take care of the staking logic as we do in:
`/ConfirmStakingParams/index.ts`
```
const onSubmit = isApprovedForAmount
    ? () => stake(operator, beneficiary, authorizer, stakeAmount)
    : approveTStaking
```

2022-01-13 15:58 UTC, r-czajkowski commented on src/web3/hooks/useTStakingAllowance.ts
> +export const useTStakingAllowance = () => {
Let's create something similar to the `useApproval` as I suggested above. Eg.:

```
const useTokenAllowance = (tokenContract, spender, account?: string) => {
 const { account: currentAccount } = useWeb3React()
 const _account = account || currentAccount
  const [allowance, setAllowance] = useState("0")

  useEffect(() => {
    const checkAllowance = async () => {
      setAllowance(
        await tokenContract?.allowance(_account, spender)
      )
    }

    if (token?.allowance && _account && spender) {
      checkAllowance()
    }
  }, [_account, spender, tokenContract])

  return { allowance }
}
```

then in `useTStakingAllowance`

```
const useTStakingAllowance = () => {
 const tTokenContract = useToken(Token.T)
 const tStakingContract = useTStakingContract()
 
 return useTokenAllowance(tTokenContract, tStakingContract?.address)
}
```

2022-01-13 16:23 UTC, r-czajkowski commented on src/web3/hooks/useTStakingAllowance.ts
> +export const useTStakingAllowance = () => {
I would consider to return function from this hook instead of fetching data in `useEffect`- this value will be fetched each time the component is mounted but maybe it would be better if we return function that fetches the allowance amount.🤔

2022-01-13 16:32 UTC, georgeweiler commented on src/hooks/useReduxStaking.ts
> +import { useSelector, useDispatch } from "react-redux"
yeah I'm happy to rename. Including "Redux" in the  filename does feel a bit awkward now that you mention it. No problem

2022-01-13 17:13 UTC, georgeweiler commented on src/hooks/useReduxStaking.ts
> +  )
nice idea. I exported a more simple "udpateState" action too instead of hard coding each setter in the redux store

2022-01-13 19:52 UTC, georgeweiler commented on src/web3/hooks/useTStakingAllowance.ts
> +export const useTStakingAllowance = () => {
I like the useEffect because we can run a check like 

```
if (tokenContract?.allowance && account && spender) {
      checkAllowance()
    }
```

in the hook to make sure the method won't fail. We don't have to repeat that logic in other places that use the allowance method

2022-01-13 20:59 UTC, Battenfield commented on src/web3/hooks/useApproveTStaking.ts
> +    await sendTransaction(tStakingContract?.address, MaxUint256.toString())
Good point @r-czajkowski. I've created a feature ticket to take on in a future sprint so we don't block this PR.

2022-01-14 11:12 UTC, r-czajkowski commented on src/web3/hooks/useTStakingAllowance.ts
> +export const useTStakingAllowance = () => {
Yeah, I like it too! But my point is that this value will be fetched when the component is mounted, not when the user triggers an `approve` transaction. so e.g. we use the `useApprove` hook in modal and the user opens this modal (the allowance amount is fetching), then closes and re-opens (the allowance amount is fetching again) etc. Ofc non-blocking comment- just flagging 🙂

2022-01-19 14:57 UTC, r-czajkowski requested changes

2022-01-19 14:57 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  const setAuthorizer = (value: string) => updateState("authorizer", value)
Why do we need store this values in redux store? I think it should be ok if we store this values in component state.

2022-01-19 14:57 UTC, r-czajkowski commented on src/components/Modal/StakingSuccessModal/StakingStats.tsx
> +  )
We already have similar component in `src/components/Modal/UpgradeToTModal/TransactionStats.tsx` so we should think about creating a reusable component.

2022-01-19 14:57 UTC, r-czajkowski commented on src/components/Modal/StakingSuccessModal/index.tsx
> +  } = useStakingState()
Same question as above. I think we can pass these values as a props. Especially if we display this modal in `useSubscribeToOperatorStakedEvent` hook- we could get these values from the `OperatorStaked` event.

2022-01-19 14:57 UTC, r-czajkowski commented on src/components/Modal/StakingSuccessPreNeededModal/index.tsx
> +            You'll need to run a PRE node to receive rewards. You can this this
double `this`.

2022-01-19 14:57 UTC, r-czajkowski commented on src/components/StakingChecklist/index.tsx
> +      key: 3,
we can get these value from the `map` function:

```
{stakingChecklistItems.map((item, index) => (
        <ChecklistItem {...item} key={index} />
      ))}
```

2022-01-19 14:57 UTC, r-czajkowski commented on src/hooks/useStakingState.ts
> +    stakingState,
Why `stakingState` not `... stakingState `? In this way the staking state is under `stakingState` field : `const { stakingState: { operator, beneficiary, stakeAmount <other> } } = useStakingState()`

2022-01-19 14:57 UTC, r-czajkowski commented on src/hooks/useStakingState.ts
> +    stakes,
If you agree with comment above we can skip this and this: `const stakes = useSelector((state: RootState) => state.staking.stakes)`. Eg:
```
const stakingState = useSelector((state: RootState) => state.staking)

const dispatch = useDispatch()

const updateState = (key: StakingStateKey, value: any) =>
 dispatch(updateStateAction({ key, value }))

return {
 ...stakingState,
  updateState
}
```

2022-01-19 14:57 UTC, r-czajkowski commented on src/store/modal/modalSlice.ts
> +    },
Do we really need this? As I can see we don't use it anywhere.

2022-01-19 14:57 UTC, r-czajkowski commented on src/store/index.ts
> +        ],
Same as above.

2022-01-19 14:57 UTC, r-czajkowski commented on package.json
> +    "ts-essentials": "^9.1.2"
why do we need `ts-essentials`?

2022-01-19 15:07 UTC, r-czajkowski requested changes

2022-01-19 15:07 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +  return (
We should probably add validation to check if the text from input is ETH address.

2022-01-19 15:07 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +            />
We should probably add a validation to check if the amount is greater than `minTStake`.

2022-01-19 15:50 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  const setAuthorizer = (value: string) => updateState("authorizer", value)
It's because this state is used in several different modals. Redux is the easiest way to share the state between them. I tried to implement an "updateModalProps" function at first to avoid using redux but the state was very inconsistent and would not update in many situations.

2022-01-19 15:52 UTC, georgeweiler commented on src/components/StakingChecklist/index.tsx
> +      key: 3,
I've always heard that using the index is an anti pattern.

https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318

what do you think?

2022-01-19 18:21 UTC, r-czajkowski commented on src/components/StakingChecklist/index.tsx
> +      key: 3,
I agree it's an anti-pattern, but I believe for dynamic values- like fetching data from API where we don't know how many values there will be. In this case, actually, we have a fixed number of items and they will be always in the same order. Don't have a strong opinion- up to you 🙂.

2022-01-20 13:08 UTC, r-czajkowski approved these changes
Looks very good, great job! :shipit: We will create tickets for non-blocking stuff and resolve them in follow-up work. Left final approval to @Battenfield.

2022-01-20 13:13 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
>  }
Non-blocking: it should be as a separate component.

2022-01-20 13:13 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  }, [])
Non-blocking: maybe separate hook? or fetch this data only once and save in redux store?

2022-01-20 13:13 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  const isZero = stakeAmount == 0
Non-blocking: We probably should use lib for forms eg. `formik` and create common validators.

2022-01-20 19:09 UTC, Battenfield approved these changes

2022-01-20 19:11 UTC, merged