feat: Create custom divider component with Icon prop
threshold-network/token-dashboard pull request #4
Opened 2021-09-20 21:46 UTC by georgeweiler

2021-09-27 14:36 UTC, r-czajkowski requested changes

2021-09-27 14:36 UTC, r-czajkowski commented on src/components/Divider.tsx
> +export const Divider = ({ icon, ...props }: DividerProps & { icon?: any }) => (
Shouldn't we build a custom component in the "Chakra way"? Please see docs https://chakra-ui.com/docs/theming/advanced#multipart-or-composite-component ? Then we can define styles eg for different sizes and we will be consistent with theming API provided by Chakra. eg. of custom Button from the [Chakra docs](https://chakra-ui.com/docs/theming/component-style#styling-single-part-components):
```
  sizes: {
    sm: {
      fontSize: "sm",
      px: 4, // <-- px is short for paddingLeft and paddingRight
      py: 3, // <-- py is short for paddingTop and paddingBottom
    },
    md: {
      fontSize: "md",
      px: 6, // <-- these values are tokens from the design system
      py: 4, // <-- these values are tokens from the design system
    },
  },
```

2021-09-27 14:36 UTC, r-czajkowski commented on src/components/Divider.tsx
> +    )}
I would consider extract it to a separate component eg. `DividerIcon` so we can easily change default props. Also if we need a divider only we will use `<Divider />`. If we need a divider w/  an icon we will use:
```
<Divider>
 <DividerIcon {...ourProps} />
</Divider>
```

But maybe it's too complicated for this simple component. What do you think?

2021-09-27 14:36 UTC, r-czajkowski commented on src/components/Divider.tsx
> +export const Divider = ({ icon, ...props }: DividerProps & { icon?: any }) => (
I believe we should omit the `orientation` prop from the `DividerProps` because this component only makes sense with `orientation="horizontal"` prop. Or we should support this prop in our custom component.

2021-09-27 14:59 UTC, r-czajkowski reviewed
There is a warning: `Line 3: 3: 'Box' is defined but never used` in react console. In `files changed` in GH I can't see any changes in `App.tsx` file. Also the `App.tsx` doesn't contain `Box` import in `chakra-theming` branch. So I don't know how it is possible 😄

2021-09-28 00:09 UTC, georgeweiler commented on src/components/Divider.tsx
> +    )}
I like this idea!

2021-09-28 01:09 UTC, georgeweiler commented on src/components/Divider.tsx
> +    )}
On second thought, the Divider component from  Charka [renders an <hr> tag](https://chakra-ui.com/docs/data-display/divider#usage) which does not accept children. I think i'd prefer to extend with an `Icon` prop like we're doing now instead of trying to rebuild the divider. Thoughts?

2021-09-28 01:31 UTC, georgeweiler commented on src/components/Divider.tsx
> +export const Divider = ({ icon, ...props }: DividerProps & { icon?: any }) => (
tried for a bit to see if we can support the vertical orientation but it's pretty ugly and unlikely that we'd need a vertical divider with an icon anyway. Decided just to omit the prop

2021-09-28 01:38 UTC, georgeweiler commented on src/components/Divider.tsx
> +export const Divider = ({ icon, ...props }: DividerProps & { icon?: any }) => (
normally I agree this is the way to adjust styling for a component in Chakra, but we aren't actually changing the styles of the Divider, just wrapping in a relative div & adding an Icon. The Divider itself doesn't have many props besides orientation, which I've omitted. Did you have an idea of how we could do it with the theme?

2021-09-29 00:19 UTC, georgeweiler commented
I've updated to pull in the changes from the storybook config branch and added more strict types.

2021-09-30 10:00 UTC, r-czajkowski commented on src/components/Divider.tsx
> +    )}
Yes, a good point! I'm just afraid we can't manipulate icon props. I don't think that we will always use e.g. `bg ="white"`.

2021-09-30 11:22 UTC, r-czajkowski commented on src/components/Divider.tsx
> +export const Divider = ({ icon, ...props }: DividerProps & { icon?: any }) => (
Oh sorry, I provided the wrong link. I meant a `Menu` example from this [link](https://www.youtube.com/watch?v=rwjmyZUA2O8). My understanding of building components in "Chakra way":

`components/Divider.tsx`
```
import {
  Icon,
  Box,
  Divider as ChakraDivider,
  DividerProps,
  useMultiStyleConfig,
} from "@chakra-ui/react"

export const Divider = ({
  icon,
  ...props
}: Omit<DividerProps, "orientation"> & { icon?: any }) => {
  const styles = useMultiStyleConfig("Divider", {})

  return (
    <Box __css={styles.dividerWrapper}>
      {icon && <Icon as={icon} __css={styles.icon} />}
      <ChakraDivider {...props} />
    </Box>
  )
}

```

`theme/Divider.ts`

```
const baseIconSize = 24
const mdIconSize = 40

export const Divider = {
  parts: ["dividerWrapper", "divider", "icon"],
  baseStyle: (props: any) => ({
    dividerWrapper: {
      position: "relative",
      my: props.icon ? 3 : undefined,
    },
    icon: {
      bg: "white",
      color: "yellow.50",
      position: "absolute",
      left: 0,
      right: 0,
      margin: "auto",
      top: `${(-1 * baseIconSize) / 2}px`,
      zIndex: 1,
      w: `${baseIconSize}px`,
      h: `${baseIconSize}px`,
    },
  }),
  sizes: {
    md: {
      icon: {
        top: `${(-1 * mdIconSize) / 2}px`,
        w: `${mdIconSize}px`,
        h: `${mdIconSize}px`,
      },
    },
  },
  defaultProps: {
    size: "md",
  },
}

```

So in this way, we can add easily `variants`, `sizes` and `colors` of this component if needed and we are consistent with Chakra. I'm not sure how we can change the `baseStyles` via props instead of a creating another variant in the `theme/Divider.ts` file - I mean something like this `<Divider baseStyle={{ icon: {bg: "red" }  }} />`.

2021-09-30 11:28 UTC, r-czajkowski commented on src/components/Divider.tsx
> +export const Divider = ({ icon, ...props }: DividerProps & { icon?: any }) => (
An example of the flexibility of this solution would be a divider with icon on the `left` or `right` side(it's just an example I know we don't need it based on the TDS). So to support that we will add variants: `left` and `right` and dedicated styles for these variants.

2021-09-30 12:48 UTC, r-czajkowski commented on src/components/Divider.tsx
> +export const Divider = ({ icon, ...props }: DividerProps & { icon?: any }) => (
Oh sorry, I provided the wrong link. I meant a `Menu` example from this [link](https://chakra-ui.com/docs/theming/component-style). My understanding of building components in "Chakra way":

`components/Divider.tsx`
```
import {
  Icon,
  Box,
  Divider as ChakraDivider,
  DividerProps,
  useMultiStyleConfig,
} from "@chakra-ui/react"

export const Divider = ({
  icon,
  ...props
}: Omit<DividerProps, "orientation"> & { icon?: any }) => {
  const styles = useMultiStyleConfig("Divider", {})

  return (
    <Box __css={styles.dividerWrapper}>
      {icon && <Icon as={icon} __css={styles.icon} />}
      <ChakraDivider {...props} />
    </Box>
  )
}

```

`theme/Divider.ts`

```
const baseIconSize = 24
const mdIconSize = 40

export const Divider = {
  parts: ["dividerWrapper", "divider", "icon"],
  baseStyle: (props: any) => ({
    dividerWrapper: {
      position: "relative",
      my: props.icon ? 3 : undefined,
    },
    icon: {
      bg: "white",
      color: "yellow.50",
      position: "absolute",
      left: 0,
      right: 0,
      margin: "auto",
      top: `${(-1 * baseIconSize) / 2}px`,
      zIndex: 1,
      w: `${baseIconSize}px`,
      h: `${baseIconSize}px`,
    },
  }),
  sizes: {
    md: {
      icon: {
        top: `${(-1 * mdIconSize) / 2}px`,
        w: `${mdIconSize}px`,
        h: `${mdIconSize}px`,
      },
    },
  },
  defaultProps: {
    size: "md",
  },
}

```

So in this way, we can add easily `variants`, `sizes` and `colors` of this component if needed and we are consistent with Chakra. I'm not sure how we can change the `baseStyles` via props instead of a creating another variant in the `theme/Divider.ts` file - I mean something like this `<Divider baseStyle={{ icon: {bg: "red" }  }} />`.

2021-09-30 12:48 UTC, r-czajkowski commented on src/components/Divider.tsx
> +export const Divider = ({ icon, ...props }: DividerProps & { icon?: any }) => (
An example of the flexibility of this solution would be a divider with icon on the `left` or `right` side(it's just an example I know we don't need it based on the TDS). So to support that we will add variants: `left` and `right` and dedicated styles for these variants.

2021-09-30 18:58 UTC, georgeweiler commented
Hey @r-czajkowski check the latest updates - Based on your suggestions I decided to go with an `<IconDivider />` component and chakra theme implementation.

2021-10-01 06:12 UTC, r-czajkowski commented on src/components/Divider.tsx
> +      {children}
I think we should use `StylesProvider` and in the `DividerIcon` component use `useStyles` hook instead of  `useMultiStyleConfig`. An advantage of this is a `useStyle` hook reads **computed** (in the parent component by  `useMultiStyleConfig("Divider", {})`) `icon` styles from styles provider. Please see an [example](https://chakra-ui.com/docs/theming/component-style#return-values).

`DividerIcon`
```
const styles = useStyles()
return <Icon as={as} __css={{ ...styles.icon, ...propStyles }} />}
```
`Divider`
```
<Box ...>
 <StylesProvider value={styles}>
  {children}
  <ChakraDivider {...props} />
 </StylesProvider>
</Box>
```

2021-10-01 21:31 UTC, georgeweiler commented on src/components/Divider.tsx
> +      {children}
👀  this is super sleek, just updated.

2021-10-04 10:02 UTC, r-czajkowski requested changes
Left a tiny comment. Once we fix that, we can merge! Looks very good! 🚀

2021-10-04 14:36 UTC, r-czajkowski submitted a review, later dismissed
LGTM! 👍 @michalsmiarowski's 👀 would be appreciated.

2021-10-05 12:45 UTC, michalsmiarowski requested changes
Some comments to look at below.

2021-10-05 12:45 UTC, michalsmiarowski commented on src/theme/Button.ts
> +          ...ghostStyles._hover,
I think you already noticed that I'm not a fan of using @ts-ignore 😅 

But here I'm not sure why it displays the error 🤔 But when i `console.log` the `ghostStyles` it seems that the `_hover` property has only one property which is `bg`, and we are already defining that. So i think we can safely remove .`..ghostStyles._hover`, `...ghostStyles._active` and .`..ghostStyles._disabled`.

2021-10-06 08:56 UTC, michalsmiarowski approved these changes
LGTM!

2021-10-06 09:39 UTC, r-czajkowski approved these changes
:shipit:

2021-10-06 09:40 UTC, merged