Tally Ho! support
threshold-network/token-dashboard pull request #425
Opened 2023-01-31 13:16 UTC by r-czajkowski

Closes: #115 

WIP

2023-03-17 13:52 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge.

2023-03-17 13:52 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectTallyHo.tsx
> +        defaul wallet and try again.
Maybe we could add a tutorial how to do it? I found something here: https://tahowallet.notion.site/Taho-is-interfering-with-Metamask-or-another-wallet-6005819d4e8748f5b7d1ed788da8826c. Maybe we could add it here as an external link?

2023-03-17 13:52 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/components/MetamaskStatusAlert.tsx
> +        installed or MetaMask is your default wallet.
I would chang it to:

```suggestion
        installed and MetaMask is your default wallet.
```

2023-03-17 13:52 UTC, michalsmiarowski commented on src/static/icons/TallyHo.tsx
Remember to also change the file names to `Taho.tsx`

2023-03-17 13:52 UTC, michalsmiarowski commented on src/web3/connectors/tallyHo.ts
Same as above. Change it to `taho.ts`

2023-03-17 13:52 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectTallyHo.tsx
> +      )}
Non-blocking:

Maybe we could put it all into a render function (called `renderConnectTahoData` or something) and change those statements into normal ifs? I think it would look more readable, but I'm leaving this up to you to decide.

2023-03-27 13:42 UTC, r-czajkowski commented on src/enums/externalHref.ts
> +  installTallyHo = "https://tallyho.org/",
d65fa39

2023-03-27 13:43 UTC, r-czajkowski commented on src/static/icons/TallyHo.tsx
d65fa39

2023-03-27 13:43 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/ConnectTallyHo.tsx
> +        </Link>
4c30193

2023-03-31 07:51 UTC, michalsmiarowski requested changes
I've added two more comments but overal looks good. Let me know if you want to fix them

2023-03-31 07:51 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectTaho.tsx
> +        and try again.
Non-blocking:

After setting the Taho as a default wallet you have to refresh the page to make it work. Maybe we should add that information here?

My proposition

`Taho is not set as default wallet. Please make sure Taho is your default wallet, refresh the page and try again.`

2023-03-31 07:51 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectTaho.tsx
> +        </Link>
Non-blocking:

Same here. After installing the Taho extension you have to also refresh the page. My proposition:

`Taho is not installed. Please install the Taho extension on their website, refresh the page and try again.`

2023-03-31 08:13 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/ConnectTaho.tsx
> +        </Link>
7a7dde9

2023-03-31 09:11 UTC, michalsmiarowski approved these changes
LGTM 🪨

2023-03-31 09:11 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectTaho.tsx
> +import Link from "../../Link"
Non-blocking:

We might want to move this custom Link component to a `@threshold-network/components` in the future.

2023-03-31 09:12 UTC, merged