Tbtc tests
threshold-network/token-dashboard pull request #442
Opened 2023-02-09 12:18 UTC by michalsmiarowski

Refs: #439

2023-03-06 16:04 UTC, mhluongo commented
Can we get a PR description that might make this easier to review?

2023-03-13 18:54 UTC, r-czajkowski requested changes
Some tests fail because of `Cannot find module 'bcrypto.node'` error, even the tests in the `tbtc.test.ts` file. Can we fix it?

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    test("should get revealed deposit", () => {
Same as above.

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    console.log("mock t hash!: ", mockTransactionHash)
Do we need this console log?

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    test("should estimate fees", () => {
Same as above.

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    })
Let's add empty lines between `test` and `beforeEach` statements.

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should throw", async () => {
Same as above.

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should throw", async () => {
Let's add an empty line.

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should create proper deposit script parameters", async () => {
Same as above.

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +  let token: Contract
Unused variables: `tBTCMainnet`,` tbtcVault`, `bitcoinClient`, `bridgeContract`, `token`.

2023-03-13 18:54 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should throw", async () => {
maybe should throw an error?

2023-04-01 17:06 UTC, mhluongo commented
Are we planning to merge this, or should it be closed? Looks like it's danging right now

2023-04-03 09:11 UTC, michalsmiarowski commented
> Are we planning to merge this, or should it be closed? Looks like it's danging right now

Yes. It did fall back a little since it wasn't that high of a priority, but I'm fixing it right now and we will try to push it out soon

2023-04-05 07:10 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    describe("with mocked bitcoin clinet", () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:11 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      beforeEach(() => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      beforeEach(() => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    test("should suggest a desposit wallet correctly", async () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      jest
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should call proper functions with proper arguments", async () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    test("should get revealed deposit", () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    test("should get revealed deposit", () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    test("should reveal deposit properly", () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    test("should estimate fees", () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    })
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    })
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:12 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should throw", async () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:13 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should throw", async () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:13 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should create proper deposit script parameters", async () => {
3e72a34d95575a7bd5e753700917f29cfa27832d

2023-04-05 07:13 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +  let token: Contract
a4a6ff1eefe5b6aa081aef63628fc2fc7b4ad88a

2023-04-05 07:13 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should throw", async () => {
7372eb86e267322da3686c50496aba647396c7ba

2023-04-05 07:13 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +      test("should throw", async () => {
7372eb86e267322da3686c50496aba647396c7ba

2023-04-05 07:14 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +  })
b84b9a22357583146e5e131ff13eb19e1a2a66b0

2023-04-05 07:14 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    })
b84b9a22357583146e5e131ff13eb19e1a2a66b0

2023-04-05 07:14 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    test("should create the bridge history properly", () => {
d3ac52443a61fca59f4aee1f1118c41d9e58ba1e

2023-04-05 07:14 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +    console.log("mock t hash!: ", mockTransactionHash)
f8fa81307ced055059c5035980d5e9a46114c02d

2023-04-05 13:04 UTC, r-czajkowski requested changes

2023-04-05 13:04 UTC, r-czajkowski commented on src/posthog/index.ts
> +  const apiHost = "https://app.posthog.com"
I believe this is an unnecessary change.

2023-04-05 13:04 UTC, r-czajkowski commented on src/posthog/index.ts
> +  console.log("page view captured!")
Same as above. Unnecessary console log.

2023-04-05 13:04 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +}))
We have the same code in `setupTests.js`. Do we need this here?

2023-04-05 13:04 UTC, r-czajkowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +}))
Same as above.

2023-04-07 10:33 UTC, r-czajkowski requested changes
Let's fix `useFetchTvl` tests. The issue here is that the `Multicall` class from `threshold-ts` uses the zero address for chain id `1337`(chain id fetched from `.env` file) because the `REACT_APP_MULTICALL_ADDRESS` env is missed and then the `getContract` function throws an error if the address is zero. See:
- https://github.com/threshold-network/token-dashboard/blob/main/src/threshold-ts/multicall/index.ts#L51-L60
- https://github.com/threshold-network/token-dashboard/blob/main/src/threshold-ts/utils/contract.ts#L27-L29

So we can fix test in 2 ways:
- mock the `supportedChainId` variable(because this variable is passed to the `Threshold` class constructor.
   `useFetchTvl.test.tsx`
   ```ts
   jest.mock("../../utils/getEnvVariable", () => ({
  ...(jest.requireActual("../../utils/getEnvVariable") as {}),
  supportedChainId: 1,
   }))
   ```
- or we can create a new file `.env.test` where we define the mocked address for the `Multicall` contract- so if we run test `yarn test` the env variables from `.env.test` file will be fetched.
   ```
   REACT_APP_SUPPORTED_CHAIN_ID=1337
   REACT_APP_MULTICALL_ADDRESS=0x086813525A7dC7dafFf015Cdf03896Fd276eab60
   ```

2023-04-07 10:52 UTC, michalsmiarowski commented
> Let's fix `useFetchTvl` tests. The issue here is that the `Multicall` class from `threshold-ts` uses the zero address for chain id `1337`(chain id fetched from `.env` file) because the `REACT_APP_MULTICALL_ADDRESS` env is missed and then the `getContract` function throws an error if the address is zero. See:
> 
> * https://github.com/threshold-network/token-dashboard/blob/main/src/threshold-ts/multicall/index.ts#L51-L60
> * https://github.com/threshold-network/token-dashboard/blob/main/src/threshold-ts/utils/contract.ts#L27-L29
> 
> So we can fix test in 2 ways:
> 
> * mock the `supportedChainId` variable(because this variable is passed to the `Threshold` class constructor.
>   `useFetchTvl.test.tsx`
>   ```ts
>   jest.mock("../../utils/getEnvVariable", () => ({
>   ...(jest.requireActual("../../utils/getEnvVariable") as {}),
>   supportedChainId: 1,
>   }))
>   ```
> * or we can create a new file `.env.test` where we define the mocked address for the `Multicall` contract- so if we run test `yarn test` the env variables from `.env.test` file will be fetched.
>   ```
>   REACT_APP_SUPPORTED_CHAIN_ID=1337
>   REACT_APP_MULTICALL_ADDRESS=0x086813525A7dC7dafFf015Cdf03896Fd276eab60
>   ```

That's awesome! Thanks for figuring that out because I wasn't sure why this test doesn't passing through. I've choosen the second solution as it looks like more global one so it will be also helpful for the future tests in which we will use `Multicall` class from `threshold-ts` lib. You can see the fix here: 6c04e845afac8f55a63eaeabf58606a2c881e80a

2023-04-07 10:53 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +}))
86b950b592e6adba04532133c7d808efe038f87e

2023-04-07 10:53 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/__test__/tbtc.test.ts
> +}))
86b950b592e6adba04532133c7d808efe038f87e

2023-04-07 10:58 UTC, r-czajkowski approved these changes
LGTM!

2023-04-07 11:20 UTC, merged