🔎 📄  Track transaction confirmations
threshold-network/token-dashboard pull request #444
Opened 2023-02-10 18:55 UTC by michalsmiarowski

Closes: #429

2023-02-11 02:18 UTC, mhluongo commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +  }, [dispatch, JSON.stringify(utxo)])
Why the `stringify` here? Not familiar with the codebase, just curious!

2023-02-14 12:49 UTC, r-czajkowski requested changes

2023-02-14 12:49 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +    let minConfrimations = 6
Non-blocking: looks like we can return number directly because we're not doing anything else with the `minConfrimations` variable.
```
return 1
...
return 3
...
return 6
```

2023-02-14 12:49 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +  }, [utxo.value])
Looks like the `utxo.value` is a `BigNumber`. Let's extract value from utxo `const value = utxo.value.toString()`and use it in the dependency array.

2023-02-14 12:56 UTC, r-czajkowski requested changes

2023-02-14 12:56 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +  }, [utxo.value])
I wonder if we really need this useEffect. The `minimumNumberOfConfirmationsNeeded` is not an async method so we can just:
```ts
const minimumNumberOfConfirmationsNeeded = threshold.tbtc.minimumNumberOfConfirmationsNeeded(
      utxo.value
    )
```

If we want to memoized value we can just use `useMemo` hook but IMO it's unnecessary because the `minimumNumberOfConfirmationsNeeded` returns `number` and doesn't do any complicated operations.

2023-02-16 10:38 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +  }, [dispatch, JSON.stringify(utxo)])
In `fetchUtxoConfirmations` we use the utxo data to fetch the confirmations so we want it to re-fetch if the utxo changes. Dependency array in `useEffect` uses referential equality to compare values. This means that if we just put object in a dependency array it will still unnecessary re-render.  To avoid that I've put `JSON.stringify` there to compare if the content of the object changes and only then dispatch the `fetchUtxoConfrimations`. 

I think Rafał proposed awesome solution though here: https://github.com/threshold-network/token-dashboard/pull/444#discussion_r1105772794. So I will refactor this. Thanks for pointing that out!

2023-02-16 13:57 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +  minimumNumberOfConfirmationsNeeded(amount: BigNumberish): number
6a9f7104b885509730dd463e64a88a48b70ed130

2023-02-16 13:58 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    if (amountInBN.lt(10000000)) {
6a9f7104b885509730dd463e64a88a48b70ed130

2023-02-16 13:58 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    } else if (amountInBN.lt(100000000)) {
6a9f7104b885509730dd463e64a88a48b70ed130

2023-02-16 13:58 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    let minConfrimations = 6
bd4d0f0b12e806d93dc06da420c434315eb04198

2023-02-16 13:58 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +  }, [dispatch, JSON.stringify(utxo)])
7a54f8bb4a82a3e082a462f7465b71feb05d159e

2023-02-16 13:59 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +  }, [utxo.value])
That's a good point! Fixed it in f56040d51186b00c97e6f5a3a13de8ed8aeef7d5

2023-02-16 13:59 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +  }, [utxo.value])
See https://github.com/threshold-network/token-dashboard/pull/444#discussion_r1108513134

2023-02-17 10:32 UTC, r-czajkowski requested changes

2023-02-17 10:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +          </Text>
As I remember it's only true for deposits greater than 1BTC. Shouldn't we use `minConfirmationsNeeded` instead of `6` here?

2023-02-17 10:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +        <Skeleton isLoaded={txConfirmations !== undefined}>
Maybe let's extract this condition to a variable because we use the same condition in other places. Eg. `const areConfirmationsLoaded = txConfirmations !== undefined`.

2023-02-17 10:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +              isLoaded={txConfirmations !== undefined}
Same here if you agree with the comment above.

2023-02-17 10:32 UTC, r-czajkowski commented on src/tbtc/mock-bitcoin-client.ts
> +
Why can't we call this function in `getTransactionConfirmations` method and just increment the confirmation for a given transaction hash after the delay/timeout? The transaction is not confirmed immediately so I think we should increment the confirmation inside the `getTransactionConfirmations` to better reflect the "real" flow. It works ok because we do not use `await` here. Ofc non blocking because it's mock implementation.

2023-02-17 10:32 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +    return 0
Shouldn't be `6` here ?

2023-02-17 10:35 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +    let minConfrimations = 6
See https://github.com/threshold-network/token-dashboard/pull/444#discussion_r1109595820

2023-02-17 13:09 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +          </Text>
c96b83238c874efb25d1f9a0e8dc8d7a99ccc5da

2023-02-17 13:09 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +        <Skeleton isLoaded={txConfirmations !== undefined}>
702958e6228608574a647b11435686deafcc0bff

2023-02-17 13:10 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +              isLoaded={txConfirmations !== undefined}
702958e6228608574a647b11435686deafcc0bff

2023-02-17 13:10 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    return 0
a5f661c0315f608562a704d611640dea54ab8125

2023-02-20 09:53 UTC, michalsmiarowski commented on src/tbtc/mock-bitcoin-client.ts
> +
065787bba782c359162920e4efaf70c1745ed047

2023-02-20 13:28 UTC, r-czajkowski approved these changes

2023-02-20 13:48 UTC, merged