tBTC- show links to all ETH and BTC transactions on sucess page
threshold-network/token-dashboard pull request #446
Opened 2023-02-14 12:19 UTC by r-czajkowski

Closes: #430 

This PR adds the following links to the deposit success page:
- Bitcoin deposited (transaction on Bitcoin),
- Deposit revealed  (transaction on Ethereum),
- Optimistic minting requested (transaction on Ethereum),
- Optimistic minting finalized (transaction on Ethereum).

The last 2 of them are not displayed immediately - it takes time for the minter to request the optimistic minting and about 3 hours to finalize the optimistic minting. To display these links we subscribe to `OptimisticMintingRequested` and `OptimisticMintingFinalized` events and save the transaction hash in redux store. When the dapp catches event the link will be displayed.

2023-02-16 09:53 UTC, michalsmiarowski requested changes
Looking great! Tested it locally and it works fantastic 🔥 

Left some minor comments to look at before the merge

2023-02-16 09:53 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +        )}
Non-blocking:

I think that from the UX perspective it would be nice to print those links at the beginning, but grayed out (with some questionmar-like icon next to it and a tooltip describing why it's grayed out and when the transactions will be available to see on block explorer). It's a non-blocking issue, just a thought.

2023-02-17 11:58 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/MintingSuccess.tsx
> +        )}
Since we are going to implement #448 I think we can leave it as is now

2023-02-17 12:03 UTC, r-czajkowski commented on src/types/tbtc.ts
> +  ethGasCost: number
6363a0f

2023-02-17 12:55 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-02-17 12:55 UTC, merged