External pool component
threshold-network/token-dashboard pull request #473
Opened 2023-03-02 09:00 UTC by michalsmiarowski

Closes: #455

2023-03-06 16:07 UTC, mhluongo commented
This looks awesome. Could we get screenshots in the description going forward? Makes it easier for those of us who aren't as deep in the repo.

2023-03-08 20:12 UTC, mhluongo commented
@r-czajkowski can you give this a look? Hoping to get a meaningful dashboard update out this week :pray:

2023-03-10 10:45 UTC, r-czajkowski requested changes
Left a few minor comments. Overall LGTM.

2023-03-10 10:45 UTC, r-czajkowski commented on src/store/tbtc/tbtcSlice.ts
> +}
Can we rename it to be more abstract eg. `ExternalPoolData`? And maybe let's move this type to `types` dir?

2023-03-10 10:45 UTC, r-czajkowski commented on src/types/tbtc.ts
> +  curveTBTCPool: CurvePoolData
IMO it's unnecessary to store this data in redux. I think we can create a hook that will fetch the pool data based on the Pool type(Curve, Uniswap) and by pool ID(eg. `tBTC/WBTC/SBTC`, `tBTC/USD`).

2023-03-10 10:45 UTC, r-czajkowski commented on src/store/tbtc/tbtcSlice.ts
> +  },
Same as above.

2023-03-10 10:45 UTC, r-czajkowski commented on src/store/tbtc/tbtcSlice.ts
> +  })
Same as above.

2023-03-15 10:44 UTC, michalsmiarowski commented on src/store/tbtc/tbtcSlice.ts
> +}
Fixed in 099344f36b929dd2a62428c41c55f72349558123 and b70f471f9bcb8e0fe2841ed4bcde5aa6c37ed933

2023-03-15 10:45 UTC, michalsmiarowski commented on src/store/tbtc/tbtcSlice.ts
> +  },
2f46605e6593a4b511d934ce392b79de71b110fc

2023-03-15 10:45 UTC, michalsmiarowski commented on src/store/tbtc/tbtcSlice.ts
> +  })
2f46605e6593a4b511d934ce392b79de71b110fc

2023-03-15 11:47 UTC, mhluongo commented on src/components/tBTC/ExternalPool.tsx
> +                    {!!tvl && <BodyXs>{formatNumeral(tvl)}</BodyXs>}
If TVL is in USD, we should show that. Seeing the raw number is confusing as it could be in BTC for example

2023-03-15 12:12 UTC, michalsmiarowski commented on src/components/tBTC/ExternalPool.tsx
> +                    {!!tvl && <BodyXs>{formatNumeral(tvl)}</BodyXs>}
Fixed in 8a659d7d72779bf88a77444b5a54dcdf24779ca7

I've added a dollar sign (`$`) at the beginning similarly as it is in curve:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/40306834/225305564-b5ccf3fb-aa76-4fa7-b218-0a46585a7417.png">

Implementation:
<img width="146" alt="image" src="https://user-images.githubusercontent.com/40306834/225305608-5640cf9e-276d-4f62-b401-958ce338f4d2.png">

Let me know if that's enough

2023-03-15 12:57 UTC, r-czajkowski requested changes

2023-03-15 12:57 UTC, r-czajkowski commented on src/hooks/useFetchExternalPoolData.ts
> +      }
Non-blocking

Maybe we could do it in `useEffect` hook?

2023-03-15 12:57 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/index.tsx
> +  }, [fetchTBTCWBTCSBTCPoolData])
If you agree with the comment above, it will be unnecessary.

2023-03-15 12:57 UTC, r-czajkowski commented on src/hooks/useFetchExternalPoolData.ts
> +  poolId: CurveFactoryPoolId
Let's say the `ExternalPoolType` will be `UNISWAP` so then the `CurveFactoryPoolId` is too specific. It should be `ExternalPoolId` and it should depend on the `type` argument. Eg:

```ts
const pools = {
  curve: ["id1", "id2"],
  uniswap: ["id3", "id4"],
} as const

type ExternalPool = keyof typeof pools
type ExternalPoolId<T extends ExternalPool> = typeof pools[T][number]

const useFetchExternalPoolData = <T extends ExternalPool>(type: T, poolId: ExternalPoolId<T>) => {
  ...
}

useFetchExternalPoolData("uniswap", "id3")
```

2023-03-15 13:15 UTC, r-czajkowski requested changes

2023-03-15 13:15 UTC, r-czajkowski commented on src/hooks/useFetchExternalPoolData.ts
> +      }
If we add more pools there will be lots of if statements. If think we could implement a kind of strategy pattern something like this:

```ts
type ExternalPoolData = {}

const fetchCurvePool: (poolId: ExternalPoolId<"curve">) => ExternalPoolData = (
  poolId
) => {
  return {}
}

const fetchUniswapPool: (
  poolId: ExternalPoolId<"uniswap">
) => ExternalPoolData = (poolId) => {
  return {}
}

const fetchPoolDataStrategy: {
  [key in ExternalPool]: (poolId: ExternalPoolId<key>) => ExternalPoolData
} = {
  curve: fetchCurvePool,
  uniswap: fetchUniswapPool,
}
```

and then in hook:
```ts
const fetchPoolData = fetchPoolDataStrategy[type]
const data = fetchPoolData(poolId)
```

2023-03-15 13:57 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/index.tsx
> +  }, [fetchTBTCWBTCSBTCPoolData])
e8d2579cb6547177500a2024fe6209d3403fe6f8

2023-03-15 13:57 UTC, michalsmiarowski commented on src/hooks/useFetchExternalPoolData.ts
> +  poolId: CurveFactoryPoolId
64318b6b52fe18fa9027b14fef59d58aa5941b60

2023-03-15 13:57 UTC, michalsmiarowski commented on src/hooks/useFetchExternalPoolData.ts
> +      }
f448fb6c2d8761a231297bc45c57df4647e723cf

2023-03-15 16:35 UTC, r-czajkowski approved these changes
Left a minor comment. LGTM! 🚀

2023-03-15 16:35 UTC, r-czajkowski commented on src/hooks/useFetchExternalPoolData.ts
> +  }, [type, poolId, fetchPoolDataStrategy])
`fetchPoolDataStrategy` is unnecessary because it's hoisted outside of the hook scope.

2023-03-15 16:44 UTC, michalsmiarowski commented on src/hooks/useFetchExternalPoolData.ts
> +  }, [type, poolId, fetchPoolDataStrategy])
7e9e8526559927498daa9e38cb1e2120ecb50dbb

2023-03-15 17:15 UTC, r-czajkowski approved these changes
:shipit:

2023-03-15 17:18 UTC, merged