Show the minting progress
threshold-network/token-dashboard pull request #475
Opened 2023-03-10 10:21 UTC by r-czajkowski

Closes: #448 
Ref: #456 

- [ ] check UI on smaller screens and fix,
- [ ] add the tBTC external pool card to the deposit details page see #473,
- [ ] update `tx history` table- redirect to the deposit details page on row click(I'll address it in a separate PR).

2023-03-10 18:22 UTC, michalsmiarowski reviewed
First part of the review done! As of now only non-blocking comments. More to come... (probably)

2023-03-10 18:22 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchDepositDetails.ts
> +        }
Non-blocking:

Maybe it would be worth it to create separate method that returns `Promise<string>` in our tbtc interface for `deposits`? This would get rid of that type cast.

2023-03-10 18:22 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchDepositDetails.ts
> +        const btcTxHash = TransactionHash.from(deposit.fundingTxHash).reverse()
Non-blocking:

After a while I forgot why we reverse the transaction hash in some cases and in some not. If that's the issue only for the `fundingTxHash` that is returned from tbtc-related events then maybe it would be worth creating a separate methods calle `extractBtcTransactionHashFromEvent` or `getTransactionHashFromFundingTx` and do the whole reversing inside it?

2023-03-10 18:22 UTC, michalsmiarowski commented on src/hooks/tbtc/useSubscribeToOptimisticMintingFinalizedEvent.ts
> +  useSubscribeToOptimisticMintingFinalizedEventBase(
Non-blocking:

There are some unused variables below. If not needed then let's remove `miner`, `depositor` and `optimisticMintingDebt`

2023-03-10 18:22 UTC, michalsmiarowski commented on src/hooks/tbtc/useSubscribeToOptimisticMintingRequestedEvent.ts
> +  useSubscribeToOptimisticMintingRequestedEventBase(
Non-blocking:

Same as abov we have unused variables here. Let's remove `minter`, `depositor`, `amount`, `fundingTxHash` and`fundingOutputIndex` if they are not needed.

2023-03-10 20:12 UTC, r-czajkowski commented on src/hooks/tbtc/useSubscribeToOptimisticMintingFinalizedEvent.ts
> +  useSubscribeToOptimisticMintingFinalizedEventBase(
I think we need to "extract" all values because we need the last param `event`. I don't know a better solution for that other than that:
```
(...args) => {
      const [, depositKey, , , event] = args
      ...
}
```
but IMO the readability is worse.

2023-03-10 20:12 UTC, r-czajkowski commented on src/hooks/tbtc/useSubscribeToOptimisticMintingRequestedEvent.ts
> +  useSubscribeToOptimisticMintingRequestedEventBase(
See https://github.com/threshold-network/token-dashboard/pull/475#discussion_r1132831477

2023-03-10 20:27 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchDepositDetails.ts
> +        }
We actually have the `getRevealedDeposit` method but it accepts only the utxo- in this case, we only have the deposit key. I would like to keep the tbtc interface simple(but actually is not as simple as I wish 😆) so adding a new method like `getDepositorByDepositKey` doesn't sound like a good idea. We use the `depositor` to determine if a given deposit exists if not depositor is a zero address. We could also use other values from the [DepositRequest](https://github.com/keep-network/tbtc-v2/blob/main/solidity/contracts/bridge/Deposit.sol#L81) struct eg. `amount` and check is equal to `0`.

2023-03-14 10:08 UTC, michalsmiarowski requested changes
Left some additional review comments

2023-03-14 10:08 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/DepositDetails.tsx
> +}
Non-blocking and open to discussion (and it is probably to do in future PRs, not this one):

The routes seems hidden everywhere. I wouldn't know where to look at them (but maybe thats just me) and not every component in `pages` directory have it. I would think of a way to keep it simple and in one file, maybe in `index` of each directory? For example all links for tbtc would be in `pages/tBTC/index.tsx` or even in a separate files. Not sure if it's possible to extract them to a separate file tho and didn't think of a way to do so yet, but it's just an idea to think about.

2023-03-14 10:08 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintUnmintNav.tsx
> +  // TODO: set the proper selectedTabId based on the current location.
Let's not forget about this TODO

2023-03-14 10:08 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/DepositDetails.tsx
> +      return <Step4 onComplete={onComplete} />
I think we should improve the way those steps are shown. When we have a deposit with minting process completed then it would print a completed `Step2` for 10 secs, then completed `Step3` for 10secs, and then complete `Step4`. I believe it should immidietaly show step4 in such case.

Similarly if the minting was requested but not finished yet then we should immidietaly show `Step3` when going into it from a link. No need to display completed `Step2` in such case.

Bear in mind that i meant it for someone who goes to the page from the url. For someone who is doing the minting process we should keep displaying the completed steps for x seoncds before moving to the next one.

2023-03-14 10:08 UTC, michalsmiarowski commented on src/theme/DotsLoadingIndicator.ts
> +const baseStyle: SystemStyleFunction = (props) => {
If you agree with , then we could move this theme to `@threshold-network/components` too.

2023-03-15 08:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/components/DepositDetailsStep.tsx
> +export const Step1: FC<
We are in the `DepositDetailsStep` file so I think it's necessary. Also when we import components the path is `../components/DepositDetailsStep` so I think it's clear. We can also use aliases if needed eg. `import { Step1 as DepositDetailsStep1 } from "../components/DepositDetailsStep"`.

2023-03-15 08:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/components/DepositDetailsStep.tsx
> +export const Step2: FC<CommonStepProps> = ({ txHash, onComplete }) => {
https://github.com/threshold-network/token-dashboard/pull/475#discussion_r1136693841

2023-03-15 08:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/components/DepositDetailsStep.tsx
> +export const Step3: FC<CommonStepProps> = ({ txHash, onComplete }) => {
https://github.com/threshold-network/token-dashboard/pull/475#discussion_r1136693841

2023-03-15 08:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/components/DepositDetailsStep.tsx
> +export const Step4: FC<CommonStepProps> = ({ txHash, onComplete }) => {
https://github.com/threshold-network/token-dashboard/pull/475#discussion_r1136693841

2023-03-15 09:05 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/components/DepositDetailsStep.tsx
> +      subtitle={`The Bitcoin Deposit transaction needs to get ${requiredConfirmations} confirmations on the Bitcoin Network before the minting is initialised.`}
1313558

2023-03-15 09:07 UTC, r-czajkowski commented on src/components/DotsLoadingIndicator/index.tsx
> +export const DotsLoadingIndicator: FC<DotsLoadingIndicatorProps> = ({
Yep definitely. I'll address it in a separate PR.

2023-03-15 09:17 UTC, r-czajkowski commented on src/components/Timeline/Timeline.tsx
> +export const Timeline: FC = ({ children, ...props }) => {
`Timline` is a common component for displaying a list of events in chronological order so I don't think so it's too generic. The Timeline can be `horizontal` or `vertical` so we can use `orientation` prop from the Chakra `ThemingProps` type to define orientation of timeline instead of a specific name. The current implementation doesn't support it but once we move it to the https://github.com/threshold-network/components repo we can add it.

We should reverse your thinking 😆- if we should rename it should be a timeline component from tBTC card because this component's name is too generic.

2023-03-15 09:21 UTC, r-czajkowski commented on src/components/Timeline/Timeline.tsx
> +export const Timeline: FC = ({ children, ...props }) => {
Actually, the timeline in tbtc card is `MintingTimeline` so in my opinion the name is OK and describes the purpose of the component well.

2023-03-15 09:29 UTC, r-czajkowski commented on src/components/Timeline/Timeline.tsx
> +export const TimelineItem: FC<TimelineItemProps> = ({
See https://github.com/threshold-network/token-dashboard/pull/475#discussion_r1136749816 If I had to rename something, it would be the `TimelineItem` from `src/pages/tBTC/Bridge/components/TimelineItem`.

Regarding the timeline in tBTC card- I believe we should build the tBTC timeline using this component(from `src/components/Timeline`) with `orientation="vertical"` prop. But it's out of scope of this PR so let's address it in a separate PR.

2023-03-15 09:40 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/DepositDetails.tsx
> +      return <Step4 onComplete={onComplete} />
Probably you tested it out with the mocked bitcoin client. It's because we save the confirmations by `txHash` in the `MockBitcoinClient` class field so when you refresh the page this class is recreated and loses its state. Then `useFetchDepositDetails` hook returns `0` in `confirmations` field so the flow will start from step 1. It should work ok with the "real" Electrum client.

2023-03-15 16:58 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchDepositDetails.ts
> +        const btcTxHash = TransactionHash.from(deposit.fundingTxHash).reverse()
31e47a6 here is a hook that wraps the whole reversing.

2023-03-16 10:49 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintUnmintNav.tsx
> +  // TODO: set the proper selectedTabId based on the current location.
66427ff

2023-03-16 10:50 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/DepositDetails.tsx
> +// TODO: Update link and copy for subtitle!
48f933b

2023-03-16 12:07 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/DepositDetails.tsx
> +      return <Step4 onComplete={onComplete} />
You are right! Thanks for catching this. Fixed in 5cf4978.

2023-03-16 12:14 UTC, michalsmiarowski commented on src/hooks/tbtc/useSubscribeToOptimisticMintingFinalizedEvent.ts
> +  useSubscribeToOptimisticMintingFinalizedEventBase(
Got it! Let's keep it as it is now then

2023-03-16 12:18 UTC, michalsmiarowski commented on src/components/Timeline/Timeline.tsx
> +export const Timeline: FC = ({ children, ...props }) => {
Ah i see! Yes, you definitely right about this, now i see it 😅  Gonna resolve this conv.

2023-03-16 12:19 UTC, michalsmiarowski commented on src/components/Timeline/Timeline.tsx
> +export const TimelineItem: FC<TimelineItemProps> = ({
> Regarding the timeline in tBTC card- I believe we should build the tBTC timeline using this component(from src/components/Timeline) with orientation="vertical" prop. But it's out of scope of this PR so let's address it in a separate PR.

Gonna keep this convi as unresolved  then (even though we resolved the initial issue) to not forget about that. It's probably very low prority though

2023-03-16 12:39 UTC, michalsmiarowski approved these changes
LGTM 👍

2023-03-16 12:39 UTC, michalsmiarowski commented on src/theme/index.ts
> +    // TODO: move color to components repo.
Non-blocking:

Let's not forget to address this in the future

2023-03-16 12:41 UTC, merged