tBTC activity history list
threshold-network/token-dashboard pull request #477
Opened 2023-03-12 12:52 UTC by r-czajkowski

Depends on: #475

This PR updates the activity history item styles and renders a link that redirects to the deposit details page on item click.

<details>
  <summary>Screenshots</summary>
  
![obraz](https://user-images.githubusercontent.com/57687279/224545831-a6b51fcf-2807-40a6-97bd-6c28e29534c2.png)

</details>

2023-03-16 12:56 UTC, michalsmiarowski requested changes
Left some minor comments but overall looks very good. I would like test it out also after you merge the newest changes from `main`, because right now I have if deposit is minted I have to wait 20 seconds to see it (but it was fixed here: https://github.com/threshold-network/token-dashboard/pull/475#discussion_r1138549645)

2023-03-16 12:56 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/TransactionHistory/index.tsx
> +export const TransactionHistory: FC<{
Do you mind changing the component to `TransactionActivity` (and also this file to `TransactionActivity/index.tsx`)? Of course are related components to it too (like `TransactionHistoryCard` and `TransactionHistoryTabel`.

In our current designs Transaction History is now something else:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/40306834/225621781-b463ac65-46c4-42d6-aa14-7fe69ea4d165.png">

2023-03-16 12:56 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/TransactionHistory/index.tsx
> +export const TransactionHistory: FC<{
Optionally we could also change the `bridgeTxHistory` method  in `threshold-ts` lib to `bridgeTxActivity` and related `BridgeTxHisotry` interface to` BridgeTxActivity` if you wish.

2023-03-16 12:56 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/TransactionHistory/index.tsx
Non-blocking:

I also noticed that the Transaction History doesn't look good on smaller screen (but not that bad either, it's readable):
<img width="555" alt="image" src="https://user-images.githubusercontent.com/40306834/225622451-19ff8865-4549-449e-a089-62989449e4d8.png">


This one is more related to #475, but it's already merged so if it's easy to center that out for lower resolution then you can address it in this PR. If not, then let's addres it in the future.

2023-03-16 14:51 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/TransactionHistory/index.tsx
> +export const TransactionHistory: FC<{
> Optionally we could also change the `bridgeTxHistory` method in `threshold-ts` lib to `bridgeTxActivity` and related `BridgeTxHisotry` interface to` BridgeTxActivity` if you wish.

Now I'm wondering if we should keep this method in the tBTC interface... 🤔 I think it's too specific for our T dapp to keep it in the tBTC interface. But I'll update and we can revisit it in the future.

2023-03-17 12:00 UTC, michalsmiarowski requested changes

2023-03-17 12:00 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/index.tsx
>    const isBridgeTxHistoryFetching = useAppSelector(
We should rename it to `isBridgeActivityFetching`

2023-03-17 12:19 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/index.tsx
>    const isBridgeTxHistoryFetching = useAppSelector(
ad2692f

2023-03-17 12:19 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/index.tsx
>            {isBridgeTxHistoryFetching ? (
ad2692f

2023-03-17 12:29 UTC, michalsmiarowski approved these changes
LGTM

2023-03-17 12:40 UTC, merged