Improve readability on BTC recovery address
threshold-network/token-dashboard pull request #478
Opened 2023-03-12 13:40 UTC by r-czajkowski

Closes: #436 
BTC Recovery Addresses need to be P2PKH or P2WPKH - this is a clunky and technical explanation both in the error message and on the How it Works page.

2023-03-28 09:16 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge

2023-03-28 09:16 UTC, michalsmiarowski commented on src/utils/forms.ts
> +      network === Network.mainnet ? "bc" : "t"
Elaborating on my thought from the post above:

This address (`mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn`) that i took from https://en.bitcoin.it/wiki/List_of_address_prefixes passes the validation check on testnet and doesn't start with `t`

2023-03-28 10:54 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +const resolvedBTCAddressPrefix = supportedChainId === "1" ? "bc" : "t"
cc @sashatanase

2023-03-30 10:53 UTC, r-czajkowski commented on src/utils/forms.ts
> +      network === Network.mainnet ? "bc" : "t"
519f040

2023-03-30 10:53 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +const resolvedBTCAddressPrefix = supportedChainId === "1" ? "bc" : "t"
519f040

2023-03-31 07:09 UTC, michalsmiarowski approved these changes
LGTM 🥼

2023-03-31 07:12 UTC, merged