tBTC stats on overview page
threshold-network/token-dashboard pull request #490
Opened 2023-04-06 14:54 UTC by r-czajkowski

Closes: #428 
Closes: #458 

This PR adds the tBTC stats to the overview page and tBTC bridge page as an empty state before the user connects with a wallet.

<details>
  <summary>Screenshots</summary>

![obraz](https://user-images.githubusercontent.com/57687279/230417040-4dc42218-37ed-4f51-9c4e-c66469f188d1.png)

![obraz](https://user-images.githubusercontent.com/57687279/230417121-fa6921f6-e28e-430a-bfbe-44d2c8af79a6.png)

</details>

2023-04-06 15:08 UTC, pdyraga commented
Sweet! 🚀

2023-04-12 10:36 UTC, michalsmiarowski requested changes
First part of the review

2023-04-12 10:36 UTC, michalsmiarowski commented on src/components/tBTC/Stats.tsx
> +export const DefaultProtocolHistory: FC<ProtocolHistoryProps> = ({
Non-blocking:

Why `DefaultProtocolHistory` and not just `ProtocolHistory`?

2023-04-12 10:36 UTC, michalsmiarowski commented on src/hooks/__tests__/useFetchTvl.test.tsx
> +        [Token.TBTCV2]: tBTCContext,
Non-blocking:

I think we should decide which naming convention we want to use for both tbtc tokens and stick to use. We can either use [`tBTC` and `tBTCv2`] or [`tBTCv1` and `tBTC`]. Messing them up here and there might be problematic later.

We don't have to do it in this PR though. It's just something that will have to be resolved sooner or later and the code needs to be checked for those occurences.

2023-04-12 10:36 UTC, michalsmiarowski commented on src/hooks/__tests__/useFetchTvl.test.tsx
> +    // The `toUsdBalance` and `spyOnFormatUnits` function was called 2x times because it was called
```suggestion
    // The `toUsdBalance` and `spyOnFormatUnits` function were called 2x times because they were called
```

2023-04-12 10:36 UTC, michalsmiarowski commented on src/utils/subgraphAPI.ts
> +const fetchRecenttBTCDeposits = async (numberOfDeposits = 4) => {
Non-blocking:

I believe we should write `TBTC` (started with capital T) when it's in the middle of the word that is writtne in camelCase convention. Everywhere else we should stick to `tBTC`.

```suggestion
const fetchRecentTBTCDeposits = async (numberOfDeposits = 4) => {
```

2023-04-12 10:36 UTC, michalsmiarowski commented on src/utils/subgraphAPI.ts
> +  // Actually transacion hash where the tbtc tokens were minted.
```suggestion
  // Actual transacion hash where the tbtc tokens were minted.
```

2023-04-12 10:36 UTC, michalsmiarowski commented on src/utils/subgraphAPI.ts
> +  timestamp: string
Non-blocking:

We could add in the comment that this `timestamp` is in seconds/miliseconds.

2023-04-12 10:43 UTC, michalsmiarowski requested changes

2023-04-12 10:43 UTC, michalsmiarowski commented on src/pages/Overview/Network/tBTCBridgeStats.tsx
> +export const TBTCBrdigeStats: FC<TBTCBrdigeStatsProps> = ({
```suggestion
export const TBTCBridgeStats: FC<TBTCBridgeStatsProps> = ({
```

2023-04-12 10:44 UTC, michalsmiarowski commented
Also, let's resolve conclifts 📄 ✍️

2023-04-13 07:36 UTC, michalsmiarowski requested changes

2023-04-13 07:36 UTC, michalsmiarowski commented on src/hooks/__tests__/useFetchTvl.test.tsx
> +
Could you double-check if all the tests pass? For me they don't (on your branch) but on `main` all have passed

2023-04-14 11:14 UTC, r-czajkowski commented on src/hooks/__tests__/useFetchTvl.test.tsx
> +        [Token.TBTCV2]: tBTCContext,
We discussed this here https://github.com/threshold-network/token-dashboard/pull/300 as well and #300 covers this. We need to revisit this PR and finally merge.

2023-04-14 11:15 UTC, r-czajkowski commented on src/hooks/__tests__/useFetchTvl.test.tsx
> +
Once we merge main should be all good 🤞

2023-04-17 10:31 UTC, r-czajkowski commented on src/components/tBTC/Stats.tsx
> +export const DefaultProtocolHistory: FC<ProtocolHistoryProps> = ({
e794f29

2023-04-17 10:31 UTC, r-czajkowski commented on src/hooks/__tests__/useFetchTvl.test.tsx
> +    // The `toUsdBalance` and `spyOnFormatUnits` function was called 2x times because it was called
197bd1d

2023-04-17 10:32 UTC, r-czajkowski commented on src/utils/subgraphAPI.ts
> +  // Actually transacion hash where the tbtc tokens were minted.
197bd1d

2023-04-17 10:32 UTC, r-czajkowski commented on src/utils/subgraphAPI.ts
> +  timestamp: string
713bf2f

2023-04-17 10:32 UTC, r-czajkowski commented on src/utils/subgraphAPI.ts
> +const fetchRecenttBTCDeposits = async (numberOfDeposits = 4) => {
c0b941f

2023-04-17 10:33 UTC, r-czajkowski commented on src/pages/Overview/Network/tBTCBridgeStats.tsx
> +export const TBTCBrdigeStats: FC<TBTCBrdigeStatsProps> = ({
4324da8

2023-04-19 08:38 UTC, michalsmiarowski approved these changes
LGTM 🚋

2023-04-19 08:38 UTC, merged