Posthog improvements
threshold-network/token-dashboard pull request #494
Opened 2023-04-10 20:07 UTC by michalsmiarowski

Refs: #479 

Enables posthog tracking by default and adds additional posthog events to some of the buttons related to tbtc deposit flow.

2023-04-11 08:11 UTC, r-czajkowski requested changes

2023-04-11 08:11 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +        data-ph-capture-attribute-button-name={`Generate Deposit Address (Deposit flow)`}
Looks like we should create a common component eg. `PosthogButton` or `TrackingButton`(to be more abstract in case we use a different product than posthog) which wraps this common logic. Eg:
```tsx
type TrackingButtonProps = {
 captureButtonName: string // or wathever
}
const TrackingButton: FC<ButtonProps & TrackingButtonProps> = ({ captureButtonName, onClick, ...restProps}) => {
const captureOnButtonClick = useCapture(PosthogEvent.ButtonClicked)

const _onClick =  () => {
 captureOnButtonClick({buttonName:  captureButtonName})
 onClick()
} // Consider using `useCallback`

return <Button {...restProps} onClick={_onClick} data-ph-capture-attribute-button-name={captureButtonName}/>
}
```

2023-04-13 13:21 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/components/CoinbaseStatusAlert.tsx
> +    captureWalletConnected({ walletType: WalletType.Coinbase })
e422097aa79fb030ddf5dd18a423c02157bf5571

2023-04-13 13:21 UTC, michalsmiarowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +            capture(PosthogEvent.ButtonClicked, {
7706ce09a0d42b0e55c919c831407004992c1f28

2023-04-13 13:22 UTC, michalsmiarowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +            capture(PosthogEvent.ButtonClicked, {
7706ce09a0d42b0e55c919c831407004992c1f28

2023-04-13 13:22 UTC, michalsmiarowski commented on src/components/Modal/TbtcRecoveryFileModal/index.tsx
> +              capture(PosthogEvent.ButtonClicked, {
7706ce09a0d42b0e55c919c831407004992c1f28

2023-04-13 13:22 UTC, michalsmiarowski commented on src/components/Modal/tBTC/NewTBTCApp.tsx
> +            capture(PosthogEvent.ButtonClicked, {
7706ce09a0d42b0e55c919c831407004992c1f28

2023-04-13 14:14 UTC, r-czajkowski commented on .env
> +REACT_APP_FEATURE_FLAG_POSTHOG=true
Probably an unnecessary change.

2023-04-13 14:18 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/components/TrezorStatusAlert.tsx
> +
Same as above.

2023-04-13 14:19 UTC, r-czajkowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +import { useCapture } from "../../../hooks/posthog"
Unnecessary imports.

2023-04-13 14:20 UTC, r-czajkowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +  const captureButtonClick = useCapture(PosthogEvent.ButtonClicked)
Same as above.

2023-04-13 14:20 UTC, r-czajkowski commented on src/components/Modal/TbtcRecoveryFileModal/index.tsx
> +  const captureButtonClick = useCapture(PosthogEvent.ButtonClicked)
Same as above.

2023-04-13 14:20 UTC, r-czajkowski commented on src/components/Modal/tBTC/NewTBTCApp.tsx
> +import { useCapture } from "../../../hooks/posthog"
Same as above.

2023-04-13 14:24 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/InitiateMinting.tsx
> +import { useCapture } from "../../../../hooks/posthog"
Unnecessary imports.

2023-04-13 14:24 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +import { useCapture } from "../../../../hooks/posthog"
Same as above.

2023-04-14 09:39 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
> +    captureWalletConnected({ walletType: WalletType.Coinbase })
b55be4df9c1c8e920fd802d16e8902bbd48e2e74

2023-04-14 09:39 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
>    }, [activate, connector])
b55be4df9c1c8e920fd802d16e8902bbd48e2e74

2023-04-14 09:39 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/components/MetamaskStatusAlert.tsx
> +
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:39 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/components/TrezorStatusAlert.tsx
> +
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:39 UTC, michalsmiarowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +import { useCapture } from "../../../hooks/posthog"
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:40 UTC, michalsmiarowski commented on src/components/Modal/TbtcMintingConfirmationModal/index.tsx
> +  const captureButtonClick = useCapture(PosthogEvent.ButtonClicked)
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:40 UTC, michalsmiarowski commented on src/components/Modal/TbtcRecoveryFileModal/index.tsx
> +import { useCapture } from "../../../hooks/posthog"
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:40 UTC, michalsmiarowski commented on src/components/Modal/TbtcRecoveryFileModal/index.tsx
> +  const captureButtonClick = useCapture(PosthogEvent.ButtonClicked)
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:40 UTC, michalsmiarowski commented on src/components/Modal/tBTC/NewTBTCApp.tsx
> +import { useCapture } from "../../../hooks/posthog"
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:40 UTC, michalsmiarowski commented on src/components/Modal/tBTC/NewTBTCApp.tsx
> +  const captureButtonClick = useCapture(PosthogEvent.ButtonClicked)
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:41 UTC, michalsmiarowski commented on src/components/TrackingButton/TrackingButton.tsx
I've got rid of `TrackingButton` since we don't need it anymore after updating the posthog version. See 83fd5e2a8fb1abcc74fbdbb0908ea4eae5df9b1d and fba3cd18afa76370b5e3cc624ef4ae53ade9a8ed

2023-04-14 09:41 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/InitiateMinting.tsx
> +import { useCapture } from "../../../../hooks/posthog"
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:41 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/InitiateMinting.tsx
> +  const captureButtonClick = useCapture(PosthogEvent.ButtonClicked)
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:41 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +import { useCapture } from "../../../../hooks/posthog"
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:41 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +  const captureButtonClick = useCapture(PosthogEvent.ButtonClicked)
1d1dd9c36f3a44ff71d25c9905795e7ca8646d6f

2023-04-14 09:46 UTC, michalsmiarowski commented on src/posthog/index.ts
> +}
We don't. Removed in cc425a2f9eb71affd3dfc9df12dc50c06a734990

2023-04-14 10:02 UTC, michalsmiarowski commented on .env
> +REACT_APP_FEATURE_FLAG_POSTHOG=true
fb495b36895b94f6c9fc60e4de9642bef91a0cdc

2023-04-17 10:01 UTC, r-czajkowski requested changes

2023-04-17 10:46 UTC, michalsmiarowski commented on src/pages/Overview/AnalyticsBanner.tsx
> +// export AnalyticsBanner
70e41cc1b1c85251dc4c4a324776231138d95b86

2023-04-17 11:55 UTC, michalsmiarowski commented on src/pages/Overview/AnalyticsBanner.tsx
> +// export AnalyticsBanner
70e41cc1b1c85251dc4c4a324776231138d95b86

2023-04-18 08:16 UTC, r-czajkowski requested changes
Let's revisit the `AnalyticsBanner` component because there are links to pages that do not actually exist and here we can turn on/off the analytics flag which actually doesn't work.

2023-04-18 08:16 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
> +  }, [activate, connector, captureWalletConnected])
Let's add `walletType` to dependency array.

2023-04-18 08:16 UTC, r-czajkowski commented on src/pages/Overview/index.tsx
> +      <AnalyticsBanner />
Shouldn't we remove `View details` button from this banner? In this flow, there are links to pages that do not actually exist and here we can turn on/off the analytics flag which actually doesn't work.

2023-04-18 08:16 UTC, r-czajkowski commented on src/hooks/posthog/useCapture.ts
> -  const { isAnalyticsEnabled } = useAnalytics()
As I mentioned above we should remove `View details` from `AnalyticsBanner` component or we should set the  `isAnalyticsEnabled` to true by default but a user can turn it off once click `View details` button in `AnalyticsBanner` component.

2023-04-18 08:16 UTC, r-czajkowski commented on src/hooks/posthog/useCapturePageview.ts
> -  const { isAnalyticsEnabled } = useAnalytics()
Same as above.

2023-04-18 08:16 UTC, r-czajkowski commented on src/hooks/posthog/useIdentify.ts
> -  const { isAnalyticsEnabled } = useAnalytics()
Same as above.

2023-04-18 08:16 UTC, r-czajkowski commented on src/hooks/posthog/usePosthog.ts
> -  const { isAnalyticsEnabled } = useAnalytics()
Same as above.

2023-04-18 12:34 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/MintingCard/ProvideData.tsx
> +        data-ph-capture-attribute-button-name={`Generate Deposit Address (Deposit flow)`}
We dedided that we don't need the `TrackingButton` component because we bumped the posthog version. Thanks to that we can just use `data-ph-capture-attribute` 

fba3cd18afa76370b5e3cc624ef4ae53ade9a8ed

2023-04-18 12:53 UTC, michalsmiarowski commented on src/pages/Overview/index.tsx
> +      <AnalyticsBanner />
8ca7cf81ccc8cd882cb803138a586d08cbbd3d7d

2023-04-18 12:53 UTC, michalsmiarowski commented on src/hooks/posthog/useCapture.ts
> -  const { isAnalyticsEnabled } = useAnalytics()
I think `AnalyticsBanner` shouldn't be displayed at all so I've removed it in 955674af772191b6c486ed2596e090790690ec0b

2023-04-18 13:24 UTC, r-czajkowski approved these changes
LGTM!

2023-04-18 13:24 UTC, merged