Resume deposit
threshold-network/token-dashboard pull request #495
Opened 2023-04-13 14:03 UTC by r-czajkowski

Ref: #457
Closes: #447 

This PR adds support for resuming a deposit based on the uploaded recovery file. The user can resume a deposit at `/tBTC/mint/continue` page and needs to upload the recovery file. After uploading a file and submitting a form a user is redirected to the correct step of the flow or to the success page(if the deposit is already revealed). The connected wallet must match the address of the depositor in the recovery file because to reveal a deposit the transaction must be called by the same Ethereum address as the one used in the P2(W)SH BTC deposit transaction as a depositor.

### Main changes
- add a new page where user can resume a deposit,
- update the minting page routing to share the same layout in different URL,
- update `Tooltip` component theme- we are going to move theme to a component repo in a follow-up work,
- update the `@threshold-network/components` dependency to use the fixed version of the `FileUploader` component,
- fix some UI bugs and update copy based on the [coda docs](https://coda.io/d/Building-Keep_d-fmEgBNFVH/Sasha-2023-27-03-QA-Template-tBTC-v2_suu17#_lueD-)

<details>
  <summary>Screenshots</summary>
  
![obraz](https://user-images.githubusercontent.com/57687279/231784213-2d253a1d-1aef-42a1-839f-265f17d1cb13.png)
  
</details>

2023-04-24 09:59 UTC, michalsmiarowski requested changes
First round of review done. Probably more to come soon. Overall looks very good!

2023-04-24 09:59 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      const result = (await parseJsonFile(file)) as DepositDetails
I think we should also check if uploaded file is a JSON file before using `parseJsonFILE`. When uploading different file the dApp crashes:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/40306834/233960398-ee0f7a7a-8780-48f6-b60a-54318fc9d54d.png">

2023-04-24 09:59 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      />
Non-blocking:

Related to above but we could also hide all the files that are not of a JSON type when we click `Choose File`. But it's not mandatory if we will check type of the file after upload so if it's something hard to implement the I would not stress about it.

2023-04-24 09:59 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      errors.depositParameters = "Invalid JSON. file."
```suggestion
      errors.depositParameters = "Invalid .JSON file."
```

2023-04-24 09:59 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      {isError && error}
I think it would look better if we set the color of the error to a red one

2023-04-24 09:59 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      const result = (await parseJsonFile(file)) as DepositDetails
We could also check if the JSON inside this file is valid.

2023-04-24 09:59 UTC, michalsmiarowski commented on src/web3/utils/files.ts
> +export async function parseJsonFile(file: File) {
Non-blocking:

Maybe:
```suggestion
export async function parseJSONFile(file: File) {
```
?

2023-04-26 08:13 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      const result = (await parseJsonFile(file)) as DepositDetails
> I think we should also check if uploaded file is a JSON file before using `parseJsonFILE`. When uploading different file the dApp crashes:
> 
> <img alt="image" width="864" src="https://user-images.githubusercontent.com/40306834/233960398-ee0f7a7a-8780-48f6-b60a-54318fc9d54d.png">

I noticed that we save the recovery file as plain text so it's probably impossible to check if this file is in JSON format Probably to achieve that we should save the recovery file as `application/json`. But IMO we are ok and checking that content inside the file is a valid JSON should be enough.

2023-04-26 08:20 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      />
See https://github.com/threshold-network/token-dashboard/pull/495#discussion_r1177505856 we save the recovery file as text so tbh I don't know how to hide other files probably we should save the file as `application/json`.

2023-04-26 08:24 UTC, r-czajkowski commented on src/web3/utils/files.ts
> +export async function parseJsonFile(file: File) {
35a1cc6

2023-04-26 08:24 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      errors.depositParameters = "Invalid JSON. file."
35a1cc6

2023-04-26 08:25 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      const result = (await parseJsonFile(file)) as DepositDetails
> We could also check if the JSON inside this file is valid.

35a1cc6

2023-04-26 08:26 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +      helperLabelText="ACTION ON BITCOIN"
bf08a52

2023-04-28 06:12 UTC, michalsmiarowski requested changes
Left some more comment but overall looks very good and it works wonderful!

2023-04-28 06:12 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +  }, [updateState])
I'm not sure why we need that `useEffect` here to be honest. Can you explain it to me why we need it and why we set the initial step here to `InitiateMinting`?

2023-04-28 06:12 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +    updateState("mintingStep", MintingStep.ProvideData)
Do we need to update the `mintingStep` to `ProvideData` here if we actually update it in a cleanup function in the `useEffect` above?

2023-04-28 06:12 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +  path: "continue",
I think it won't be easy to implement displaying unrevealed mints in `my activity` tab and we might not implement it in this PR. In such case It would be a wise idea to put a resume link someweher in the dApp. WYT?

2023-04-28 06:12 UTC, michalsmiarowski commented on src/theme/Tooltip.ts
> +// TODO: move to the components repo.
Let's not forget about that. We can merge it now and fix it in separate PR if you want.

2023-04-28 06:12 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +        <FileUploader onFileUpload={onFileUpload} headerHelperText="Required" />
Let's update the `@threshold-network/components` repo in `yarn.lock` so that we are using the newest version of the `FileUploader`:

1. Delete the `@threshold-network/components` package from `package.json`
2. `yarn install` (this should remove it from `yarn.lock` )
3. Add the `@threshold-network/components` package back with the `development` tag
4. `yarn install`

2023-04-28 06:20 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +  }, [updateState])
To display the correct step on the timeline. This should be step 3 according to Figma views.

2023-04-28 06:26 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +  path: "continue",
Yeah, I agree but I need Sasha here. We can merge as is and even release to allow users to resume deposits through the link and the ship improvements later. I mentioned unrevealed mints in `my activity` card [here](https://github.com/threshold-network/token-dashboard/issues/457#issuecomment-1525803287).

2023-04-28 06:45 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +        <FileUploader onFileUpload={onFileUpload} headerHelperText="Required" />
86c9ea1

2023-04-28 06:45 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +    updateState("mintingStep", MintingStep.ProvideData)
44e6a1b

2023-05-10 09:25 UTC, michalsmiarowski approved these changes
Left one non-blocking comment but overall I think we can merge.

2023-05-10 09:25 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      <TbtcMintingCardTitle />
Non-blocking but good to have:

Could we add a back arrow here so that the user can go back to the main minting page from the `tbtc/mint/continue`?

Designs:
<img width="276" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/aa3d6980-1aca-4fb5-a2b5-75876bcb07b1">

https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?type=design&node-id=8604-249512&t=TVSv26q2a4z87ey4-0

2023-05-10 09:39 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      <TbtcMintingCardTitle />
f7018bc

2023-05-10 10:25 UTC, michalsmiarowski approved these changes

2023-05-10 10:26 UTC, merged