Clenup unused components and unnecessary dependencies
threshold-network/token-dashboard pull request #506
Opened 2023-04-28 11:51 UTC by r-czajkowski

WIP...

2023-05-12 18:12 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge but overall very good job with the code cleaning 🔥 🧹

2023-05-12 18:12 UTC, michalsmiarowski commented on src/pages/Overview/AuthorizeApplicationsBanner.tsx
> -import authorizeAppsFingerPrint from "../../static/images/AuthorizeAppsFingerPrint.png"
Looks like we don't use this image anymore so I think we can remove it.

2023-05-12 18:12 UTC, michalsmiarowski commented on src/pages/Overview/AuthorizeApplicationsBanner.tsx
> -import authorizeAppsFingerPrintDark from "../../static/images/AuthorizeAppsFingerPrintDark.svg"
Same as above.

2023-05-22 10:39 UTC, r-czajkowski commented on src/pages/Overview/AuthorizeApplicationsBanner.tsx
> -import authorizeAppsFingerPrintDark from "../../static/images/AuthorizeAppsFingerPrintDark.svg"
84c1daf

2023-05-22 10:40 UTC, r-czajkowski commented on src/pages/Overview/AuthorizeApplicationsBanner.tsx
> -import authorizeAppsFingerPrint from "../../static/images/AuthorizeAppsFingerPrint.png"
84c1daf

2023-05-22 10:40 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintingCard/UnmintingFlowRouter.tsx
> -  const { unmintingStep } = useTbtcState()
553d326

2023-05-22 10:43 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/ConnectTrezor/index.tsx
> -import { WalletConnectionModalProps } from "../../../../types"
c73d4f3 imo there is no need to update the `Props` to `WalletConnectionModalProps` because we do not export this type. Also it lives in the `WalletConnectionModal` domain so it's clear for which component these props are for.

2023-05-22 10:43 UTC, r-czajkowski commented on src/pages/Staking/StakesTable/StakeActionsCell.tsx
> -import { StakeCellProps } from "../../../types/staking"
e21c5bb

2023-05-22 11:38 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintingCard/UnmintingFlowRouter.tsx
> -  const { unmintingStep } = useTbtcState()
I would also remove `unmintingStep` from `TbtcMintingType` and enums: `UnmintingStep` and `UnmintingSteps`. Unless you will use those in your redemption PR.

2023-05-22 12:02 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintingCard/UnmintingFlowRouter.tsx
> -  const { unmintingStep } = useTbtcState()
a98c5c3 650a697

2023-05-22 12:21 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-05-22 12:21 UTC, merged