tBTC Explorer page
threshold-network/token-dashboard pull request #511
Opened 2023-05-05 12:52 UTC by r-czajkowski

Closes: #469 

This PR adds the tBTC Explorer page. Here we display:
- the tBTC total supply,
- tBTC TVL in USD,
- total mints,
- total tBTC holders,
- recent deposits.

<details>
  <summary>Screenshots</summary>
  
  
![obraz](https://user-images.githubusercontent.com/57687279/236462470-342a8a4d-6859-4720-b1a1-baeca1706e07.png)

</details>

2023-05-05 14:54 UTC, michalsmiarowski requested changes
Looking good! Left some comments to look at before the merge

2023-05-05 14:54 UTC, michalsmiarowski commented on src/pages/tBTC/Explorer/index.tsx
We should fix this page in mobile view. It looks bad when the width is less than 1280 px:

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/40306834/236490329-2c6cf2d3-1076-4614-83ea-e780890bcb2d.png">

2023-05-05 14:54 UTC, michalsmiarowski commented on src/pages/tBTC/Explorer/index.tsx
> +          </BodySm>
Are we planning to add arrows so that we are able to see more all mints instead of last ten?

Designs:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/40306834/236491349-747f6db5-6167-4c2d-8509-3c52eb2bb0f2.png">

2023-05-05 14:54 UTC, michalsmiarowski commented on src/pages/tBTC/Explorer/index.tsx
> +                </Th>
Non-blocking:

I believe it would be more user-friendly if we add some color (like gray-ish) on gover of each row. This way the user will know that he is clicking on the exact mint.

Same thing would be useful for `tBTC BRIDGE STATS` in Overview page.

2023-05-08 12:27 UTC, r-czajkowski commented on src/pages/tBTC/Explorer/index.tsx
> +          </BodySm>
Yes, it's on my plate. Probably I'll open a separate PR.

2023-05-12 09:11 UTC, michalsmiarowski requested changes
Left one small comment to look at before the merge and we are good to go

2023-05-12 09:11 UTC, michalsmiarowski commented on src/pages/tBTC/Explorer/index.tsx
> +          <BodySm color="gray.500" mt="10">
```suggestion
          <BodySm color="gray.500" mt="10" mb="2">
```

I think we could add some margin-bottom here so that it looks better on smaller screens when there is a horizontal scroll in the table.

Current implementation:
<img width="265" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/f1f0d2c6-5c05-4fb5-91f0-5feecd515d24">

After adding margin-bottom:
<img width="283" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/0c8f06b2-7d62-47a2-bd77-7275ea885087">

2023-05-12 09:32 UTC, r-czajkowski commented on src/pages/tBTC/Explorer/index.tsx
> +          <BodySm color="gray.500" mt="10">
7654dfb

2023-05-12 09:51 UTC, michalsmiarowski submitted a review, later dismissed
LGTM 🎋

2023-05-12 11:23 UTC, michalsmiarowski approved these changes
LGTM

2023-05-12 11:23 UTC, merged