Legacy Keep Stake- take into account `OwnerRefreshed` event
threshold-network/token-dashboard pull request #514
Opened 2023-05-12 12:45 UTC by r-czajkowski

WIP...

2023-09-06 11:43 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge

2023-09-06 11:43 UTC, michalsmiarowski commented on src/threshold-ts/staking/index.ts
> +    // Staking provideres are owned by the `owner` address.
I'm not sure but I believe this comment is describing what `stakingProviders` variable is. If so the I would change it to:

```suggestion
    // Staking provideres that are owned by the `owner` address.
```

2023-09-06 11:43 UTC, michalsmiarowski commented on src/threshold-ts/staking/index.ts
> +      .map((_, index) => possibleStakingProviders[index])
I haven't test it but I'm not sure if this would work for every case 🤔 

Let's say we have two stakes:
```
Stake 1
owner: 0x1
stakingProvider: 0x1

Stake 2
Owner: 0x2
StakingProvider: 0x11
```

Now let's say we have those `OwnerRefreshed(stakingProvider, oldOwner, newOwner)` events (order is from oldest to newest):
```
OwnerRefreshed(0x1, 0x1, 0x3)
OwnerRefreshed(0x11, 0x2, 0x3)
OwnerRefreshed(0x1, 0x3, 0x4)
```
Now we call `findRefreshedKeepStakes` function for the owner `0x3`.

`possibleStakingProviders` would equal `[0x1, 0x11]` (assuming the events `ownerRefreshedEvents` would be fetched from the oldest to newest one).

Now we check `rolesOf` for all the `possibleStakingProviders` to check what are the owners of those two. THe acutal situation is:
```
stakingProvider: 0x1
owner: 0x4

stakingProvider: 0x11
owner: 0x3
```

Now here, in the code that I marked, we defined the variable `stakingPorivers`. First we filter out the `rolesOf` to have only those whose owner is the one that we passed to this function, which in this case is `0x3`. After filter we will only have one element:

```
stakingProvider: 0x11
owner: 0x3
```

And doing the `map` function we now use the only index of the only one element in array, which is `0` and get the same index from `possibleStakingProvider`. As i mentioned before the `possibleStakingProvider` array right now looks like this:
`[0x1, 0x11]`
So it will take the first element of this array which is actually wrong. In this case the only owner of stakingProvider `0x11` is the `0x11` address not `0x1`.

So i believe the line with the `.map` might not work correctly for every scenario. I'm not sure though because I haven't test it yet in the code, only on paper 😅 Can you check if what I'm talking makes sense? Maybe I missed something down the road?

2023-09-06 11:43 UTC, michalsmiarowski commented on src/threshold-ts/staking/index.ts
> +      .filter(({ stakingProvider }) => !outdated.includes(stakingProvider))
Do we actually need to have the exclamation mark (`!`) next to the `outdated` word? When I remove it I don't see any errors in my IDE.

2023-09-06 11:43 UTC, michalsmiarowski commented on src/threshold-ts/staking/__test__/staking.test.ts
> +    test("should return outdated staking providers if the owner was updated multiple times", async () => {
If may assumption in <link to comment> would be correct then maybe we could also write a test for such case

2023-09-06 11:43 UTC, michalsmiarowski commented on src/threshold-ts/staking/index.ts
> +    })
Doesn't this return events where both `oldOwner` AND `newOwner` is equal to `owner`? I think the docs (https://docs.ethers.org/v5/concepts/events/#events--filters) indicates that it's an `AND` condition, not `OR`.

2023-09-21 14:00 UTC, r-czajkowski commented on src/threshold-ts/staking/index.ts
> +      .filter(({ stakingProvider }) => !outdated.includes(stakingProvider))
It's logical NOT/negation https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_NOT

2023-09-21 14:59 UTC, r-czajkowski commented on src/threshold-ts/staking/index.ts
> +    // the stake is indeed the one we are looking for(the `owner` argumment).
9539bfa

2023-09-21 14:59 UTC, r-czajkowski commented on src/threshold-ts/staking/index.ts
> +    // Outdated staking providers- the `owner` address is no longer an owner of
9539bfa

2023-09-21 14:59 UTC, r-czajkowski commented on src/threshold-ts/staking/index.ts
> +    // Staking provideres are owned by the `owner` address.
9539bfa

2023-09-21 15:00 UTC, r-czajkowski commented on src/threshold-ts/staking/index.ts
> +    })
6ca4ce9

2023-09-22 15:00 UTC, r-czajkowski commented on src/threshold-ts/staking/index.ts
> +      .map((_, index) => possibleStakingProviders[index])
Unit test updates: ee7a182

2023-09-26 09:15 UTC, michalsmiarowski commented on src/threshold-ts/staking/index.ts
> +      .filter(({ stakingProvider }) => !outdated.includes(stakingProvider))
Ahhh, I'm not sure why but I thought it was [non-null assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) 😅  My bad!

2023-09-27 14:14 UTC, michalsmiarowski requested changes
Left some more comments below.

2023-09-27 14:14 UTC, michalsmiarowski commented on src/threshold-ts/staking/index.ts
> +    const rolesOf: { owner: string }[] = await this._multicall.aggregate(
I think we can use [Role Of interface](https://github.com/threshold-network/token-dashboard/blob/main/src/threshold-ts/staking/index.ts#L40) here.

```suggestion
    const rolesOf: RolesOf[] = await this._multicall.aggregate(
```

2023-09-27 15:29 UTC, r-czajkowski commented on src/threshold-ts/staking/index.ts
> +    const rolesOf: { owner: string }[] = await this._multicall.aggregate(
2a2d714

2023-09-27 15:29 UTC, r-czajkowski commented on src/threshold-ts/staking/__test__/staking.test.ts
> +      expect(result).toEqual({ current: [], outdated: [] })
3a1a958

2023-09-27 22:02 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-09-27 22:03 UTC, merged