Ledger live implementation
threshold-network/token-dashboard pull request #515
Opened 2023-05-15 13:35 UTC by michalsmiarowski

2023-05-18 08:37 UTC, r-czajkowski requested changes

2023-05-18 08:37 UTC, r-czajkowski commented on src/static/icons/LedgerLight.tsx
> +})
Looks like the svg is the same we only swap colors in `<rect fill={}` and `<path fill={} />`. So we can create one file
`LedgerLive.tsx` and create an custom icon using Icon component see https://chakra-ui.com/docs/components/icon#using-the-icon-component:
```tsx
const LedgerLive = ({ bgColor, iconColor }) => {
 <Icon viewBox >
        <rect width="160" height="160" rx="16" fill={bgColor} />
      <path
        d="M93.1482 119.207V125H135V98.8769H128.902V119.207H93.1482ZM93.1482 33V38.792H128.902V59.1231H135V33H93.1482ZM74.0104 59.1231H67.9125V98.8769H95.4153V93.6539H74.0104V59.1231ZM26 98.8769V125H67.8518V119.207H32.0979V98.8769H26ZM26 33V59.1231H32.0979V38.792H67.8518V33H26Z"
        fill="{iconColor}"
      />
 </Icon>
}

export const LedgerLiveDark = () => <LedgerLive bgColor={#00000D} iconColor={white} />

export const LedgerLiveLight = () => <LedgerLive bgColor={white} iconColor={#00000D} />
```

2023-05-18 08:37 UTC, r-czajkowski commented on src/web3/connectors/ledger_live.ts
Why `ledger_live`? Can't we rename to `ledgerLive` to keep the same convention for all connectors?

2023-05-18 08:37 UTC, r-czajkowski commented on src/web3/connectors/ledger_live.ts
> +  private provider?: EthereumProvider | undefined
unnecessary `undefined` because the `provider` is optional (`?`).

2023-05-18 08:37 UTC, r-czajkowski commented on src/web3/connectors/ledger_live.ts
> +    }
Shouldn't we let components catch errors? In that case if something happens we can't render an error state in wallet component because we catch an error and do not throw any error.

2023-05-18 08:37 UTC, r-czajkowski commented on src/web3/connectors/ledger_live.ts
> +      console.log("Error: ", err)
If we want to log errors we should use `console.error`.

2023-05-18 08:37 UTC, r-czajkowski commented on src/web3/connectors/ledger_live.ts
> +}
Imo we should check if the `this.provider` is not undefined and then do other stuff eg:

```tsx
public async getChainId(): Promise<number> {
 if(!this.provider) throw new Error("Connector not activated!") // or we can create a custom error eg. ConnectorNotAcivatedError and throw it here.
 
 return this.provider.request({ method: "eth_chainId" })
}
```

2023-05-18 08:37 UTC, r-czajkowski commented on src/web3/connectors/ledger_live.ts
> +const rpcUrl = getEnvVariable(EnvVariable.ETH_HOSTNAME_HTTP)
Can we add an empty line between lines 94-95?

2023-05-18 08:37 UTC, r-czajkowski commented on src/web3/connectors/ledger_live.ts
> +        chainId: 1,
We should use the `chainId` passed to the constructor(see `supportedChainIds` args in `AbstractConnector`). Otherwise, the `chainId` for testnet will be invalid.

2023-05-18 08:37 UTC, r-czajkowski commented on src/web3/connectors/ledger_live.ts
> +        },
Same as above. We shouldn't hardcode rpc like here. We should pass rpc as construct args and save to a private field.

```tsx
interface LedgerLiveConnectorArguments {
 rpc: {
  [chainId: number]: string
 }
}

private this.rpc: LedgerLiveConnectorArguments["rpc"]

constructor({ rpc }: Required<LedgerLiveConnectorArguments>) {
    super({ supportedChainIds: Object.keys(rpc).map(chainId => Number(chainId)) })
    this.rpc = rpc // now we can pass the rpc to the `connectKit.checkSupport` fn.
    
    this.handleNetworkChanged = this.handleNetworkChanged.bind(this)
    this.handleChainChanged = this.handleChainChanged.bind(this)
    this.handleAccountsChanged = this.handleAccountsChanged.bind(this)
    this.handleClose = this.handleClose.bind(this)

    this.connectKitPromise = loadConnectKit()
  }
```

2023-05-30 14:09 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectLedgerLive.tsx
> +  }, [activate, connector, captureWalletConnected, walletType])
fixed in f936566d121aeabbe7ec3e3e6954bc52e95760d5

2023-05-30 14:09 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectLedgerLive.tsx
> +  const walletType = WalletType.LedgerLive
I removed in completely in f936566d121aeabbe7ec3e3e6954bc52e95760d5

2023-05-30 14:10 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectLedgerLive.tsx
> +      WalletIcon={MetaMaskIcon}
c235c98e989ded43d85a6b9408fa9d9ddbeabf86

2023-05-30 14:11 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectLedgerLive.tsx
> +    ></WalletConnectionModalBase>
c235c98e989ded43d85a6b9408fa9d9ddbeabf86

2023-05-30 14:12 UTC, michalsmiarowski commented on src/web3/connectors/ledger_live.ts
1149fa54a07584eab2a579a330a788fd75e5cb3b

2023-05-30 14:12 UTC, michalsmiarowski commented on src/web3/connectors/ledger_live.ts
> +  private provider?: EthereumProvider | undefined
f1fac17e00109a99c9f1e0ae0d3b182c0a9ce89c

2023-05-30 14:12 UTC, michalsmiarowski commented on src/web3/connectors/ledger_live.ts
> +      console.log("Error: ", err)
d7ed01be79acc3b97caf66f23d64b0c094662b71

2023-05-30 14:13 UTC, michalsmiarowski commented on src/web3/connectors/ledger_live.ts
> +const rpcUrl = getEnvVariable(EnvVariable.ETH_HOSTNAME_HTTP)
869f9ac7f75166072a6e86c6564a2fe7fa133d9a

2023-06-02 21:07 UTC, r-czajkowski requested changes

2023-06-02 21:07 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/ConnectLedgerLive.tsx
> +  const walletIcon = colorMode === ColorMode.DARK ? LedgerDark : LedgerLight
We can make it simpler- let's use `useColorModeValue` hook.

2023-06-12 09:53 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/ConnectLedgerLive.tsx
> +  const walletIcon = colorMode === ColorMode.DARK ? LedgerDark : LedgerLight
6f909fc347516f499388768651d9435b2e111d2d

2023-06-12 09:53 UTC, michalsmiarowski commented on src/web3/connectors/ledger_live.ts
> +        },
225800e31c6d025dfbd9ab7a2a58c137881af6e8

2023-06-12 09:54 UTC, michalsmiarowski commented on src/web3/connectors/ledger_live.ts
> +        chainId: 1,
225800e31c6d025dfbd9ab7a2a58c137881af6e8

2023-06-12 09:54 UTC, michalsmiarowski commented on src/web3/connectors/ledger_live.ts
> +    }
Great catch! I've fixed it here: f6ff7f5fbeae2a3b355e842726266211a75a25be

2023-06-15 08:26 UTC, r-czajkowski requested changes

2023-06-15 08:26 UTC, r-czajkowski commented on src/web3/connectors/ledgerLive.ts
> +    const chainId = Number(Object.keys(this.rpc)[0])
We can use `this.supportedChainIds[0]`- I think it will be more readable.

2023-06-15 08:26 UTC, r-czajkowski commented on src/components/Navbar/WalletConnectionAlert.tsx
> +    if (error) {
Looks like we need only the error message so maybe let's:
```ts
const errorMessage = error?.message

 useEffect(() => {
    if (errorMessage) {
      setAlertDescription(errorMessage)
      setHideAlert(false)
      return
    }

    if (!account || (account && isSupportedNetwork(chainId))) {
      setHideAlert(true)
      return
    }

    if (!isSupportedNetwork(chainId)) {
      setAlertDescription(
        `Your wallet is on an unsupported network. Switch to the ${chainIdToNetworkName(
          supportedChainId
        )} network`
      )
      setHideAlert(false)
      return
    }
  }, [account, chainId, errorMessage])
```

2023-06-15 08:26 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
> +    activate(connector, onError)
I think we can pass `setError` from `useWeb3React` hook directly since we do not provide our logic for handling errors. Otherwise, we should wrap the `onError` with `useCallback` and pass it as a dependency of `useEffect` hook.

2023-06-15 08:26 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
> +    if (walletType === WalletType.LedgerLive) closeModal()
Why do we need it? IMO the `WalletConnectionModalBase` component is a wrapper/abstract component for other wallets so we should not use a specific type of wallet in the implementation. Can't we pass `onContinue` prop to `WalletConnectionModalBase` in `ConnectLedgerLive` component?

2023-07-03 16:22 UTC, mhluongo commented
Calling out that if this is helpful for our WalletConnect v2 push, we should probably merge and revisit the dangling review comments! cc @r-czajkowski @michalsmiarowski

2023-07-24 09:19 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
> +    activate(connector, onError)
I removed the `onError` from there completely when I was resolving the conflicts after mergin the `main` branch - eaaa1b656492b57a08ed87f916a3e32cd44affb4. It looks like it's not needed.

2023-07-24 09:19 UTC, michalsmiarowski commented on src/web3/connectors/ledgerLive.ts
> +    const chainId = Number(Object.keys(this.rpc)[0])
aaacbe72b73ae0c398073fb2e0510a19f91ff0f4

2023-07-24 09:20 UTC, michalsmiarowski commented on src/components/Navbar/WalletConnectionAlert.tsx
> +    if (error) {
ab114c9d6dc19abb851a8c6d6dfa2864025ccdc4

2023-07-24 09:21 UTC, michalsmiarowski commented
I've updated the `@ledgerhq/connect-kit-loader` version to `1.1.0` so that it supports wallet connect v2. You can see the changes in df848ca7d01d200832cf98081bb55d40d24f0813 and 66224b1139e80a2e77087aa6a0b0f1131c655def.

2023-07-26 06:05 UTC, r-czajkowski approved these changes
Left one minor comment. Let's fix it and I'm good to merge.

2023-07-26 06:05 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
>    }, [activate, connector, captureWalletConnected, walletType])
Let's add `shouldForceCloseModal` as a dependency.

2023-07-26 06:06 UTC, r-czajkowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
> +    if (walletType === WalletType.LedgerLive) closeModal()
Fixed in 3bf7da1.

2023-07-26 07:55 UTC, michalsmiarowski commented on src/components/Modal/SelectWalletModal/components/WalletConnectionModalBase.tsx
>    }, [activate, connector, captureWalletConnected, walletType])
98a6086b27adae48a99887e52bf4cbbf92e645e3

2023-07-27 07:58 UTC, r-czajkowski commented on src/web3/connectors/ledgerLive.ts
> +      projectId: getEnvVariable(EnvVariable.WALLET_CONNECT_PROJECT_ID),
Can we pass project Id to a constructor instead of a hardcoded value?

2023-07-27 08:51 UTC, michalsmiarowski commented on src/web3/connectors/ledgerLive.ts
> +      projectId: getEnvVariable(EnvVariable.WALLET_CONNECT_PROJECT_ID),
Great idea! Fixed in 0853ce8b9358bbddfe4af9d9d38f75855046784f

2023-08-14 13:54 UTC, r-czajkowski approved these changes
LGTM!

2023-08-16 07:43 UTC, merged