Unminting
threshold-network/token-dashboard pull request #521
Opened 2023-05-23 12:34 UTC by r-czajkowski

This PR adds the Unmint page where users can request redemption. Here we only implement UI this PR doesn't cover contract integration- we are going to address it in a separate PR.

### Main changes
- create Unmint page- display a unmint form where users can request a redemption,
- create `InitiateUnminting` modal- confirmation modal where users can validate the redemption details before signing the transaction,
- extract the `Step` component (previously `TimelineItem` component from `src/pages/tBTC/Bridge/components/TimelineItem.tsx`) to the shared `components` dir. Implemented using the compound component pattern so we can keep the same style but we have more flexibility in terms of positioning some parts of this component (eg. 2 badges instead of only one). It's a component from the [Threshold Design System](https://www.figma.com/file/zZi2fYDUjWEMPQJWAt8VWv/Threshold-DS?type=design&node-id=874-18470&t=5ynOWzbkUwXIn9AT-0),
- extract `TransactionDetails` components to a shared `components` dir,
- rename some components from `Minting...` to `BridgeProcess...` so we can use them in both contexts- `mint` and `unmint`.

<details>
  <summary>Screenshots</summary>
  
![obraz](https://github.com/threshold-network/token-dashboard/assets/57687279/9a871fc3-cec0-456f-bab8-b192c64e98c0)

![obraz](https://github.com/threshold-network/token-dashboard/assets/57687279/ab882bb9-197a-4894-a46a-382fcf424def)

</details>

2023-05-30 10:14 UTC, michalsmiarowski requested changes
Looking great 🔥 Left some comments to look at before the merge

2023-05-30 10:14 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Unmint.tsx
> +          // `TokenAmountForm` and `UnstakingFormLabel` components.
Let's not forget about this TODO

2023-05-30 10:14 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Unmint.tsx
> +        // TODO: add BTC addresse prefixes
I think this TODO can be removed

2023-05-30 10:14 UTC, michalsmiarowski commented on src/components/Modal/tBTC/InitiateUnminting.tsx
> +  }
I assume those two will be implemented in a separate PR, but let's not forget about those two TODOs

2023-05-30 13:51 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/Unmint.tsx
> +          subTitle="Unmint your tBTC tokens"
Yeah. We can probably use the same empty state as for the `Mint` section but I have to ask designers. I think we can address it in a separate PR.

2023-05-30 13:58 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/Unmint.tsx
> +    console.log("on submittttt")
I'll implement the submit functions in a separate PR- I'm currently working on the contract integration.

2023-05-30 19:39 UTC, r-czajkowski commented on src/utils/tBTC.ts
> +const getSupportedAddressPrefixes = (
84761d1

2023-05-30 19:39 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/Unmint.tsx
> +        // TODO: add BTC addresse prefixes
ef78736

2023-06-09 13:58 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-06-09 14:00 UTC, merged