Redemptions details page
threshold-network/token-dashboard pull request #523
Opened 2023-05-25 13:45 UTC by r-czajkowski

Depends on: #521

WIP...

2023-06-02 07:19 UTC, michalsmiarowski requested changes
Looking good 🔥 Take a look at the comments before we merge

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +import { ONE_SEC_IN_MILISECONDS } from "../../../utils/date"
I think we could just create an `index` file in the `utils` folder so that we can avoid multiple imports from `utils`. Unless there is a specific reason we haven't done that yet 😛 What do you think? 

It should be done in a separate PR though since it will require refactor in a lot of files probably

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +        />
Maybe we could add an ability to copy it?

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +        <Timeline>
There is also `USUAL DURATION` text in the `Timeline` on Figma that we it's not present in the implementation. Are you planning to add that or are we ditching it for now?

Designs:
<img width="394" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/c85ae012-f9ac-4a9b-b8c1-b07ccdd9fc0e">

Implementation:
<img width="507" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/86257c1a-16b9-4a1e-8e51-d9fa319dcb5a">

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +          />
Let's not forget about that before the merge

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +            icon={<IoCheckmarkSharp />}
Same as above

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +      </ButtonLink>
There is a discussion on figma about the `New Mint` button - https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV?node-id=9031:259793#444501151

It looks like we decided to remove the `New Mint` button from unminting flow since the user just did the opposite.

2023-06-02 07:19 UTC, michalsmiarowski commented on src/components/Modal/tBTC/InitiateUnminting.tsx
> +    closeModal()
Maybe I'll just point out each TODO in comment section so that it will be easier to track them and we can discuss each of them if for example we would want to merge the PR without doing the specific TODO and address it later. Let me know if you think it's unnecessary

So here's another one ⬆️

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +    useState(false)
TODO 📨

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +  }, [])
TODO 📨

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +  const fee = "20000000000000000"
TODO 📨

2023-06-02 07:19 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +    : {}
TODO 📨

2023-06-02 16:32 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +      </ButtonLink>
We display this button only on the success page as in Figma. We do not show it in the pending redemptions state.

2023-06-02 16:34 UTC, r-czajkowski commented on src/components/Modal/tBTC/InitiateUnminting.tsx
> +    closeModal()
I'll implement all submit and fetch functions in a separate PR- that's why I left so many TODOs. This PR includes only UI.

2023-06-02 16:35 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +          />
We do not have copy for that. I think we can merge and update later.

2023-06-02 16:36 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +        <Timeline>
I'm not sure how to implement this- looks like this text should not be a part of the `Timeline` component. I think we should set `position: absolute` for it. WDYT?

2023-06-02 16:39 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +import { ONE_SEC_IN_MILISECONDS } from "../../../utils/date"
Yep, I agree. Let's refactor it in a separate PR.

2023-06-02 20:55 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +              <BodyXs whiteSpace="pre-line">tBTC unwrapped</BodyXs>
3508a6d- we do not have a dark mode version of this component but used the `<colorSchema>.700`. Looks better but we need to sync with designers about it.

2023-06-02 20:55 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +        />
049a440

2023-06-02 20:56 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +        </BodyLg>
e6a7cd0

2023-06-02 20:56 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +        <Timeline>
e25a5de

2023-06-02 20:57 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +            icon={<IoCheckmarkSharp />}
50d01bf

2023-06-02 20:57 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +    : {}
40d4a30

2023-06-02 20:59 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +    useState(false)
See https://github.com/threshold-network/token-dashboard/pull/523#discussion_r1214588787

2023-06-02 20:59 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +  }, [])
See https://github.com/threshold-network/token-dashboard/pull/523#discussion_r1214588787

2023-06-02 20:59 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +  const fee = "20000000000000000"
See https://github.com/threshold-network/token-dashboard/pull/523#discussion_r1214588787

2023-06-22 14:20 UTC, michalsmiarowski approved these changes
LGTM 🔥 Let's make it `Ready for review` and I will merge

2023-06-22 14:41 UTC, merged