Fix two active navigation pills
threshold-network/token-dashboard pull request #524
Opened 2023-05-26 08:39 UTC by michalsmiarowski

Closes: #501 

There was a UI bug where it displayed two navigation pills as active instead of one. For example when clicking on `How it works` link in tbtc both `Bridge` and `How it works` links were active.

We've fixed that by adding a new method - `addActiveStatusToPills` - which adds `isActive` property to each of the link. If there are two or more links that are active (based on `useMatch` hook) then we only keep the active status for the last one.

<details>
  <summary>Screenshot of the fix</summary>
 
<img width="411" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/6ffc6c57-bb92-48be-ad17-e9b5035df481">

</details>

2023-05-30 04:10 UTC, r-czajkowski requested changes

2023-05-30 04:10 UTC, r-czajkowski commented on src/components/SubNavigationPills/index.tsx
> +    const match = useMatch({ path: resolved.pathname, end: true })
We should not call hooks in loops see https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level. We can use [`match-path`](https://reactrouter.com/en/main/utils/match-path) and [`resolvePath`](https://reactrouter.com/en/main/utils/resolve-path).

2023-05-30 04:10 UTC, r-czajkowski commented on src/components/SubNavigationPills/index.tsx
> +const SubNavigationPills: FC<SubNavigationPillsProps> = ({ links }) => {
Can we also fix sub-navigation in staking pages?

![obraz](https://github.com/threshold-network/token-dashboard/assets/57687279/e94ced6e-552b-4ecc-9846-b2c3cdd5057a)

2023-07-17 11:01 UTC, r-czajkowski commented
Looks like it doesn't work on Staking How it works page.

![obraz](https://github.com/threshold-network/token-dashboard/assets/57687279/9e55fc24-ed7d-432d-902c-07f98fb40023)

2023-07-17 11:02 UTC, r-czajkowski requested changes
Looks like it doesn't work on Staking How it works page.

![obraz](https://github.com/threshold-network/token-dashboard/assets/57687279/9e55fc24-ed7d-432d-902c-07f98fb40023)

2023-07-25 14:42 UTC, michalsmiarowski commented
> Looks like it doesn't work on Staking How it works page.

@r-czajkowski It should be fixed now in 780e85913fdbf4f6d85ae3056bdcf901d15422d9

2023-07-26 13:58 UTC, r-czajkowski commented on src/App.tsx
> +  parentPathBase: string = ""
Shouldn't we use `PageComponent["parentPathBase"]`? IMO it's more clear that it's the same type as in the page component.

2023-07-26 13:58 UTC, r-czajkowski commented on src/App.tsx
> +        {pages.map((page) => renderPageComponent(page))}
Unnecessary change - `parentPathBase` is optional so we can still use `pages.map(renderPageComponent)`

2023-07-26 13:58 UTC, r-czajkowski commented on src/components/SubNavigationPills/index.tsx
> +  parentPathBase: string
Same as above.

2023-07-26 13:58 UTC, r-czajkowski commented on src/types/page.ts
> +    parentPathBase: string
Why is it outside of `RouteProps`? It's related to the routing so I think we can keep it in the `route` object 🤔

2023-08-16 08:13 UTC, michalsmiarowski commented on src/types/page.ts
> +    parentPathBase: string
I see your point but I believe it should not be in `RouteProps`. Yes, it is related to routing but the path itself has to be created in `renderPageComponent` function which uses `PageComponent` object (containing `route` property of a type `RouteProps`) to render the pages. Placing it in `RouteProps` might be misleading when defining a `route` props for a given page because we can't define it at the point of `route` property initialization. We can only create it later when we gather all routes together so we can reproduce the tree nature of the routes step by step (which is inside `renderPageComponent`). What do you think? 🤔

2023-08-16 09:22 UTC, michalsmiarowski commented on src/App.tsx
> +  parentPathBase: string = ""
After I've moved `parentPathBase` to `RouteProps` we don't have to pass the `parentPathBase` as a separate parameter now. See https://github.com/threshold-network/token-dashboard/pull/524#discussion_r1295540700

2023-08-16 09:22 UTC, michalsmiarowski commented on src/components/SubNavigationPills/index.tsx
> +  parentPathBase: string
See https://github.com/threshold-network/token-dashboard/pull/524#discussion_r1295623207

2023-08-16 09:23 UTC, michalsmiarowski commented on src/App.tsx
> +        {pages.map((page) => renderPageComponent(page))}
12b40c9800bcb33be8541fe38bc88d9a427890fa

2023-08-16 14:24 UTC, r-czajkowski approved these changes

2023-08-16 14:26 UTC, merged