Fetch redemption details
threshold-network/token-dashboard pull request #561
Opened 2023-07-04 13:50 UTC by r-czajkowski

This PR adds support for fetching the redemption details data from the chain. Based on that data we render different states of the unminting process on the Redemption Details page.

## Main changes:

### Add new methods to the `TBTC` interface from `threshold-ts` lib
Add methods that fetch the redemption request and redemption-related events. Here we also noticed a bug in the `ethers.js` lib- the `ethers.js` lib encodes the `bytesX` param in the wrong way. It uses the left-padded rule but based on the Solidity docs it should be a sequence of bytes in X padded with trailing zero-bytes to a length of 32 bytes(right-padded). See https://docs.soliditylang.org/en/v0.8.17/abi-spec.html#formal-specification-of-the-encoding
Consider this wallet public key hash
`0x03B74D6893AD46DFDD01B9E0E3B3385F4FCE2D1E`:
- `ethers.js` returns
  `0x00000000000000000000000003b74d6893ad46dfdd01b9e0e3b3385f4fce2d1e`
- should be:
  `0x03b74d6893ad46dfdd01b9e0e3b3385f4fce2d1e000000000000000000000000`
  
In that case, in methods that fetch the past events by indexed param which has `bytesX` type(`RedemptionsCompleted`, `RedemptionRequested`, `RedemptionTimedOut`) we build the filter topics manually.

### Hook that fetches the redemption details
This hook fetches the redemption request details based on the:
- **redemption requested tx hash**-  We also need to find an event by
  transaction hash because it's possible that there can be multiple
  `RedemptionRequest` events with the same redemption key but created at
  different times eg:
    - redemption X requested,
    - redemption X was handled successfully and the redemption X was
      removed from `pendingRedemptions` map,
    - the same wallet is still in `live` state and can handle the
      redemption request with the same `walletPubKeyHash` and
      `redeemerOutputScript` pair,
    - now 2 `RedemptionRequested` events exist with the same redemption
      key(the same `walletPubKeyHash` and `redeemerOutputScript` pair).

      In that case, we must know exactly which redemption request we
      want to fetch.
- **wallet public key hash**- we need to find `RedemptionRequested` event by
  wallet public key hash to get all necessary data and make sure that
  the request actually happened. It's also used to build the redemption key,
- **redeemer**-  We need `redeemer` address as well to reduce the number of
  records- any user can request redemption for the same wallet.
- **redeemer output script**- we need this param to build the redemption key
  and find the Bitcoin transfer for this redeemer output script.
  
### Hook that fetches the block details such as `timestamp`
We need timestamps for a given block umber to calculate the total time it took to complete a redemption or how long a redemption request takes.

<details>
  <summary>Screenshots</summary>
  
  Pending Redemption:
  ![obraz](https://github.com/threshold-network/token-dashboard/assets/57687279/bda3f58c-1945-48b6-b1b5-20335290a931)

Completed Redemption:
![obraz](https://github.com/threshold-network/token-dashboard/assets/57687279/211123fe-4491-4892-8e4a-b88cb509dcf7)
</details>

2023-07-07 11:53 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge. 

Overall looks great 💪 Love how earch step in the `useFetchRedemptionDetails` hook is commencted ❤️

2023-07-07 11:53 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
Non-blocking/to discuss:

The `TBTC` class is slowly getting bigger and bigger. I believe we could split it up somehow like in `tbtc-v2.ts` lib so that we have parts that are responsible for deposits, parts that are responsible for redemptions, parts that are responsible for sweeping (in the future), generic parts etc. We shouldn't of course do that in this PR but i believe we could discuss it and address it so that it will be easier for us to implement new things to that class and find the old ones 😅 

I found some resources that might be helpful:
- https://stackoverflow.com/a/67837778 - the guy proposed to use `mixins`. I've never used them but some people in the comments say that it created some circular import references when they tried to implement this so I believe this solution might be complicated
- https://stackoverflow.com/questions/23876782/how-do-i-split-a-typescript-class-into-multiple-files - here I found some simpler solutions.

Curious what you think. If you don't think such refactor is needed then let me know. Like I said - this convo is only for discuss this. It should not be implemented in this PR.

2023-07-07 11:53 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +      treasuryFee: event.args?.redeemer.toString(),
Why do we assign `event.ergs?.redeemer` to the `reasuryFee` here? Shouldn't be `event.args?.treasuryFee.toString()`?

2023-07-07 11:53 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    }))
I believe this is also a workaround until the fix in `ethers.js` is ready so I would add a `TODO` here too.

2023-07-07 11:53 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    }))
Same as above

2023-07-07 11:53 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +          })
Shouldn't we also set `btcAddress` here?

2023-07-07 11:53 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +}
I know we use this function only in that hook, but it seems too specified to be placed here (and also it's too hard to find it IMO). Let's assume that in the future someone (and that someone is not me or you 😛 ) will need to prefix the output script with `0x` and its own length in some other place in our dApp. I doubt that he will found it here. Mybe we could move it to our `TBTC` class?

2023-07-07 21:05 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
`Unmint` and `UnmintDetails` are page components so they are at the top. We probably should move `BridgeLayout`, `MintUnmintNav`, `TBTCBalanceCard` components to `src/pages/Bridge/components` dir.

2023-07-07 21:07 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
Agree, we need to take a closer look at this.

2023-07-07 21:10 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +    // })
I'm going to open a PR in `ethers.js` repo next week. I have fix for that just need to add tests and open a PR with an explanation of the problem.

2023-07-07 21:28 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +          })
As I can see on Figma we need the Bitcoin address only on the success page so I think it's not mandatory. But up to you I can add, just let me know.

2023-07-07 21:37 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +}
febbedc

2023-07-07 21:37 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +    }))
1cac4b9

2023-07-07 21:37 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +    }))
1cac4b9

2023-07-07 21:37 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +      treasuryFee: event.args?.redeemer.toString(),
275749d

2023-07-07 21:38 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +                bg={useColorModeValue("white", "brand.800")}
990ea35

2023-07-07 21:39 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
8d50c6d984e0e1f6e6a852facf3b81a34893bc08

2023-07-07 21:39 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +        // and `reedemer` address to get all necessary data and make sure that
a7e1384

2023-07-07 21:39 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +        // same wallet.
a7e1384

2023-07-07 21:39 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +            // redemption key can be created in the same transaction- it means
a7e1384

2023-07-07 21:39 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +          // - redemption X was handled sucesfully and the redemption X was
a7e1384

2023-07-07 21:39 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +        // If we are here it menas that the redemption request was handled
a7e1384

2023-07-07 21:39 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +        // that happend after `redemptionRequest` block and filter by
a7e1384

2023-07-11 12:12 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +          })
No, not needed. I was juts afraid of a situation where we could have some old `btcAddress` saved in state bu since we set the data as a whole object, and replace the whole `RedemptionDetails` then it looks like it will neeve be such situation and this `btcAddress` will be undefined in this case.

2023-07-11 12:57 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +        // same wallet.
9776847

2023-07-11 12:57 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +  ): Promise<RedemptionsCompletedEvent[]>
ed3e3c4

2023-07-11 13:17 UTC, michalsmiarowski requested changes
Left one comment to point out the `TODO` but overall looking good. I'm ready to merge it

2023-07-11 13:17 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +              btcAddress: "2Mzs2YNphdHmBoE7SE77cGB57JBXveNGtae",
Let's not forget about this TODO

2023-07-11 13:40 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +              btcAddress: "2Mzs2YNphdHmBoE7SE77cGB57JBXveNGtae",
We need https://github.com/keep-network/tbtc-v2/pull/646 first. Once we merge this PR I'll update on the dapp side.

2023-07-11 14:26 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-07-11 14:28 UTC, merged

2023-07-13 07:29 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +              btcAddress: "2Mzs2YNphdHmBoE7SE77cGB57JBXveNGtae",
Resolved in #568