Get redemption params from url to fetch details
threshold-network/token-dashboard pull request #566
Opened 2023-07-10 11:37 UTC by r-czajkowski

Depends on: #561 

Get the redemption params from url to fetch the redemption details on the Redemption details page. Also add validation in the `useFetchRedemptionDetails` hook to make sure all params are in correct format.

2023-07-11 12:21 UTC, michalsmiarowski commented on src/components/Modal/tBTC/InitiateUnminting.tsx
> +    // https://github.com/threshold-network/token-dashboard/pull/537
Let's remove that (although it will probably be removed when you pull the changes from `main` since https://github.com/threshold-network/token-dashboard/pull/537 is already merged.

2023-07-11 12:27 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +  redeemer: FetchRedemptionDetailsParamType
Can't we just keep the types as string and make all the propeties optional?

```suggestion
  redemptionRequestedTxHash?: string,
  walletPublicKeyHash?: string,
  redeemerOutputScript?: string,
  redeemer?: string
```

2023-07-11 13:04 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +  redeemer: FetchRedemptionDetailsParamType
I decided to add `null` and create a custom type because `searchParams.get` from [here](https://github.com/threshold-network/token-dashboard/pull/566/files#diff-c0362ebe68a4f572dd5a124a7d56f3abc9086c667f2513883bcbe783181596beR74) returns `string | null` but optional param is meaning "type X or **undefined**" so I got a ts error w/o `null`.

2023-07-11 13:06 UTC, r-czajkowski commented on src/components/Modal/tBTC/InitiateUnminting.tsx
> +    // https://github.com/threshold-network/token-dashboard/pull/537
I'll remove once we merge #561 and then merge the main branch into `get-redemption-params-from-url`.

2023-07-12 12:42 UTC, michalsmiarowski requested changes
There is an error that I found with `redeemerOutputScript`. Please see the comments below:

2023-07-12 12:42 UTC, michalsmiarowski commented on src/utils/tBTC.ts
>    queryParams.set("redeemerOutputScript", redeemerOutputScript)
When doing a redemption I've got `Error: Redemption not found...`. I think there is a mistake of how we create `redeemerOutputScript` here:
https://github.com/threshold-network/token-dashboard/blob/5fd3f64eeb555fde9791939a47ef419f055000b2/src/components/Modal/tBTC/InitiateUnminting.tsx#L62

The `redeemerOutputScript` itself is correct but we only add `0x` prefix at the beginning and I velieve we should also prefix it with a byte length. For example for address `2NBDAoFXUvdFZhvaQ5DxZjKCRHdMBnjRBTq` the `redeemerOutputScript` from this call is `0xa914c50ec4e54c362b7bd64ce136e967dd58fe907ef787`.

The problem is that here:
https://github.com/threshold-network/token-dashboard/blob/5fd3f64eeb555fde9791939a47ef419f055000b2/src/hooks/tbtc/useFetchRedemptionDetails.ts#L101-L104
the redemption keys comparison fails, because `event.redeemerOutputScript` is also prefixed with the byte length so the actual values of it is `0x17a914c50ec4e54c362b7bd64ce136e967dd58fe907ef787` (notice the `17` after the `0x`).

2023-07-12 12:42 UTC, michalsmiarowski commented on src/utils/tBTC.ts
>    queryParams.set("redeemerOutputScript", redeemerOutputScript)
Similarly this piece of code also doesn't work properly:
https://github.com/threshold-network/token-dashboard/blob/5fd3f64eeb555fde9791939a47ef419f055000b2/src/hooks/tbtc/useFetchRedemptionDetails.ts#L116-L122

because we pass the `redeemerOutputScript` that is not prefixed with length. After using `redemptionRequest.redeemerOutputScript` (which is prefixed with `0x` and length) it correclty finds the redemption request.

2023-07-12 13:07 UTC, r-czajkowski commented on src/utils/tBTC.ts
>    queryParams.set("redeemerOutputScript", redeemerOutputScript)
81875f9

2023-07-12 15:01 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-07-12 15:01 UTC, merged