Calculate Threshold Fee for redemption
threshold-network/token-dashboard pull request #569
Opened 2023-07-12 16:37 UTC by michalsmiarowski

WiP...

2023-07-13 12:06 UTC, r-czajkowski requested changes

2023-07-13 12:06 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +                estimatedAmountToBeReceived={estimatedAmountToBeReceived}
On the success step, I think we can get the final value from the Bitcoin transaction and display fees in this way `requestedAmount - btcReceivedAmount` and we can rename the props just to `amount`.

2023-07-13 12:06 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +    .toString()
Maybe we can calculate it in the `useFetchRedemptionDetails` hook to keep the logic inside this hook?

2023-07-13 12:06 UTC, r-czajkowski commented on src/hooks/tbtc/useRedemptionEstimatedFees.ts
> +  const [thresholdNetworkFee, setThresholdNetworkFee] = useState<string>("0")
Not sure if the `thresholdNetworkFee` can be zero but if can let's set the default value to `undefined` so we will be able to render the skeleton while fetching data.

2023-07-14 11:07 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +                estimatedAmountToBeReceived={estimatedAmountToBeReceived}
Fixed in 904fa824c41e989df722b052506ecba00d942e62. Also renamed `redemptionRequest` variable here: fc2b7a7f7f3152a7849a5d6167cfbcf786389d8f

2023-07-14 11:08 UTC, michalsmiarowski commented on src/hooks/tbtc/useRedemptionEstimatedFees.ts
> +  const [thresholdNetworkFee, setThresholdNetworkFee] = useState<string>("0")
e2db51d718379f7eea83d7cee919c0dc6f2c7775

2023-07-14 11:08 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +    .toString()
This calculation was removed in 904fa824c41e989df722b052506ecba00d942e62 since we now get the value of received bitcoins from the transaction.

2023-07-14 11:09 UTC, michalsmiarowski commented on src/utils/formatAmount.ts
> +  isEstimated = false // adds tilde to the amount no matter the value
2a479ff5db280461a06d44493ddd27f3a00ec42d

2023-07-14 12:07 UTC, r-czajkowski requested changes

2023-07-14 12:07 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +          higherPrecision={8}
See comments above regarding unit mismatch in the `requestedAmount` field.

2023-07-14 12:07 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
>            tokenAmount={thresholdNetworkFee}
Maybe let's calculate fees based on the `requestedAmount` and `receivedAmount` on the success page: `requestedAmount - receivedAmount`?

2023-07-14 12:07 UTC, r-czajkowski commented on src/threshold-ts/tbtc/index.ts
> +      await this.bridgeContract.redemptionParameters()
We could create a cache for this value to reduce the number of requests. Eg.

```ts
private redemptionTreasuryFeeDivisor: BigNumber | undefined

private getRedemptionTreasuryFeeDivisor = () => {
if(!this.redemptionTreasuryFeeDivisor) {
 this.redemptionTreasuryFeeDivisor =  await this.bridgeContract.redemptionParameters()
}

return this.redemptionTreasuryFeeDivisor
}
```

2023-07-14 13:00 UTC, michalsmiarowski commented on src/components/TokenBalance.tsx
> +      displayTildeBelow
7817fcabfdc039bcc2ffa613ce19dedb1385139e

2023-07-14 13:01 UTC, michalsmiarowski commented on src/components/TokenBalance.tsx
> +      label={`${isEstimated ? "~" : ""}${_tokenAmountWithHigherPrecision}`}
7817fcabfdc039bcc2ffa613ce19dedb1385139e

2023-07-14 13:01 UTC, michalsmiarowski commented on src/components/TokenBalance.tsx
> +      <Box as="span" {...restProps}>{`${isEstimated ? "`" : ""}${_tokenAmount}${
It should be `~` here. I put ` by mistake (did not click shift 😅 ). We want to display tilde both in the amount and in the tooltip.

2023-07-14 13:02 UTC, michalsmiarowski commented on src/components/TokenBalance.tsx
> +      <Box as="span" {...restProps}>{`${isEstimated ? "`" : ""}${_tokenAmount}${
Fixed in 7817fcabfdc039bcc2ffa613ce19dedb1385139e

2023-07-14 13:03 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +                .toString(),
2c5be5433d26910b854c3357ce28e7a3879ba4ce

2023-07-14 13:04 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +            requestedAmount: redemptionRequestedEvent.amount,
2c5be5433d26910b854c3357ce28e7a3879ba4ce

2023-07-14 13:04 UTC, michalsmiarowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +  receivedAmount?: string
2c5be5433d26910b854c3357ce28e7a3879ba4ce

2023-07-14 13:04 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +                tokenSymbol="BTC"
d11a57edaeb92ee8f51fe2ad942829c2ee102f91

2023-07-14 13:06 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +          tokenDecimals={8}
Good catch - e1bd20984cc264b19d002ae28a6071f7aaac93a7

2023-07-14 13:07 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +          higherPrecision={8}
Those are proper values after changin the `requestedAmount` to tbtc in token unit.

2023-07-14 13:37 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +      await this.bridgeContract.redemptionParameters()
316f5618aea9a01047a01e7fee227596bbbf5828

2023-07-14 13:38 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +          tokenSymbol="TBTC"
696139be3debefb3e4c3abf0006f4bfc0249004b

2023-07-14 14:23 UTC, r-czajkowski approved these changes

2023-07-14 14:27 UTC, merged