Improve UX in redemption details page
threshold-network/token-dashboard pull request #594
Opened 2023-08-09 13:20 UTC by r-czajkowski

WIP...

Redirect to a success step when the redemption is complete. Here we subscribe to the `RedemptionsCompleted` event and check if this event is related to a given redemption request by checking the wallet public key hash. If yes, we are looking for a Bitcoin transfer to a given redeemer output script in a given bitcoin tx hash (we can get this transaction hash from the `RedemptionsCompleted` event). If we are able to find that transfer it means this `RedemptionsCompleted` events is related to a given redemption request and we should redirect user to a success step.

2023-09-05 14:04 UTC, michalsmiarowski requested changes
Overall looking very good. Left small non-blocking comments to look at before the merge

2023-09-05 14:04 UTC, michalsmiarowski commented on src/hooks/tbtc/useSubscribeToRedemptionsCompletedEvent.ts
> +export const useSubscribeToRedemptionsCompletedEventBase = (
Can you explain why you put base word at the end of the hook name? Wouldn't `useSubscribeToRedemptionsCompletedEvent` be enough?

2023-09-07 13:27 UTC, r-czajkowski commented on src/hooks/tbtc/useSubscribeToRedemptionsCompletedEvent.ts
> +export const useSubscribeToRedemptionsCompletedEventBase = (
We usually use `useSubscribeToXEvent` when updating the redux store based on the events. This hook is to share a common logic where we reverse the `redemptionTxHash` param to represent the Bitcoin transaction hash in the same byte order used by the Bitcoin block explorers. That's why I use `base` word at the end. Eg https://github.com/threshold-network/token-dashboard/blob/main/src/hooks/tbtc/useSubscribeToOptimisticMintingRequestedEvent.ts#L19

2023-09-07 13:27 UTC, r-czajkowski commented on src/pages/tBTC/Bridge/UnmintDetails.tsx
> +  const shoudlForceIsProcessCompleted =
37e6ef3

2023-09-07 13:27 UTC, r-czajkowski commented on src/hooks/tbtc/useFetchRedemptionDetails.ts
> +            btcAddress: redemptionBitcoinTransfer.btcAddress,
1881695

2023-09-12 10:24 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-09-12 10:24 UTC, merged