Fix WalletConnection alert
threshold-network/token-dashboard pull request #598
Opened 2023-08-21 10:51 UTC by michalsmiarowski

There was a bug that caused the walletconnection alert to not show up the second time if the error message stays the same.

This commit fixes that.

<img width="460" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/4ea945f9-d9fe-4ae3-960e-4cb34f02d6a3">

To see if it works you can:
1. Click "Connect  Wallet"
2. Choose "WalletConnect"
3. Close the WalletConnect modal with `X` button
4. The "Connection request reset. Please try again" alert should appear in the top right corner.
5. Close the alert
6. Repeat steps 1-3
7. The "Connection request reset. Please try again" alert should appear again

2023-08-22 19:47 UTC, r-czajkowski requested changes

2023-08-22 19:47 UTC, r-czajkowski commented on src/components/Navbar/WalletConnectionAlert.tsx
> +    if (error) error.message = ""
We should never change or update the state directly. `error` is a state variable see https://github.com/Uniswap/web3-react/blob/v6/packages/core/src/manager.ts#L117. We should probably use `setError` eg:
```ts
const { error, setError } = useWeb3React()
...
setError(null)
```

or we should call `deactivate` fn from `useWeb3React` hook to clear the state (see https://github.com/Uniswap/web3-react/blob/v6/packages/core/src/manager.ts#L168 and https://github.com/Uniswap/web3-react/blob/v6/packages/core/src/manager.ts#L90)

2023-09-06 13:04 UTC, michalsmiarowski commented on src/components/Navbar/WalletConnectionAlert.tsx
> +    if (error) error.message = ""
Great catch! Fixed in 779f5ae0daa5fb4548469288df986558db7524a8

2023-09-12 09:42 UTC, r-czajkowski approved these changes

2023-09-12 09:43 UTC, merged