Coverage Pools balance
threshold-network/token-dashboard pull request #613
Opened 2023-09-15 13:55 UTC by michalsmiarowski

Closes: https://github.com/threshold-network/website/issues/88

Implements the Coverage Pools balance in the dashboard.

Note: In the project ([on release branch](https://github.com/threshold-network/token-dashboard/blob/releases/mainnet/v1.10.0/package.json#L14)) we are using `v1.0.0` version of `@keep-network/coverage-pools` which has contracts related to Keep. The T Coverage Pools are in `v2.0.0` version. Since we still use `v1.0.0` version in our dApp to display it in the TVL I've decided to isntall `v2.0.0` version next to the first one anc call it `@threshold-network/coverage-pools`.

On the `main` branch they both have `development` tag but on the release one we should set the correct version accordingly.

2023-09-15 15:18 UTC, michalsmiarowski commented
@r-czajkowski I've also created another PR related to this one with some small code cleaning - #614

2023-09-15 15:37 UTC, r-czajkowski requested changes

2023-09-15 15:37 UTC, r-czajkowski commented on src/web3/hooks/useKeepAssetPoolContract.ts
> +}
Hmmm looks like we should import `AssetPool` artifact from `"@keep-network/coverage-pools/artifacts/AssetPool.json"` but in the `useAssetPoolContract` hook from `"@threshold-network/coverage-pools/artifacts/AssetPool.json"` 🤔

2023-09-15 15:37 UTC, r-czajkowski commented on src/components/StatHighlightCard.tsx
> +    <HStack>
IMO it's unnecessary and always forces the title to be inside a flex container. We can use `HStack` in the parent component if needed.

2023-09-15 15:37 UTC, r-czajkowski commented on src/components/StatHighlightCard.tsx
> +    <H1 mt="10" mb="9" textAlign="center" {...restProps}>
Shouldn't we add `as={Link}` to render the link as `a` tag?

2023-09-15 15:43 UTC, r-czajkowski requested changes

2023-09-15 15:43 UTC, r-czajkowski commented on src/components/StatHighlightCard.tsx
> +    <H1 mt="10" mb="9" textAlign="center" {...restProps}>
It also seems unnecessary- we do not use it anywhere.

2023-09-15 16:44 UTC, michalsmiarowski commented on src/components/StatHighlightCard.tsx
> +    <H1 mt="10" mb="9" textAlign="center" {...restProps}>
I've pushed this component by mistake. I've removed it in 203a931ed0a9e97c7d74060620519546d1430b4e

2023-09-18 12:38 UTC, michalsmiarowski commented on src/components/StatHighlightCard.tsx
> +    <HStack>
Hmm I'm not sure about that, because the `<HStack>` is only in `StatHighlightTitle`. Any children here should be related to the title and title in this card is usually one-horizonal-liner thus this `<HStack>` here.

If the user would need to add something below/above title he could just create that outside of the `<Stat Highlight Title> component. What do you think about that approach? @r-czajkowski

2023-09-18 12:41 UTC, michalsmiarowski commented on src/web3/hooks/useKeepAssetPoolContract.ts
> +}
772aaf55ff25f6e59b0973472e6eef41e05d92fb

2023-09-19 12:28 UTC, r-czajkowski requested changes

2023-09-19 12:28 UTC, r-czajkowski commented on src/pages/tBTC/CoveragePools/CoveragePoolsTVLCard.tsx
> +        <LearnMoreLink m={"0 auto"}>
We can use `mx="auto"` - I believe this will improve readability.

2023-09-19 12:28 UTC, r-czajkowski commented on src/hooks/useFetchTvl.ts
Let's update unit tests for this hook.

2023-09-22 10:17 UTC, r-czajkowski approved these changes

2023-09-22 12:32 UTC, r-czajkowski approved these changes

2023-09-22 12:32 UTC, merged