Add Taco application to dashboard
threshold-network/token-dashboard pull request #625
Opened 2023-09-22 15:15 UTC by theref

Builds on top of https://github.com/threshold-network/token-dashboard/pull/624

Fixes #678 #680 #675 #673

2023-10-02 13:25 UTC, therealsphinx approved these changes

2023-10-11 12:28 UTC, manumonti requested changes
This is a great work 🙌

What is the plan with the TODOs created in commit #7eb5030? Are you planning to address them in other PR?

2023-10-11 13:07 UTC, theref commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +// import tacoAppIllustrationLight from "../../../../static/images/tacoAppIllustrationLight.png"
no it's a reminder that we might end up with new images

2023-10-11 15:01 UTC, derekpierre commented on src/enums/externalHref.ts
> +  tacoStakingProvidersList = "https://docs.nucypher.com/en/latest/pre_application/node_providers.html", // TODO THEREF
Can we point to docs.threshold.network instead? That information should be available now.

2023-10-11 15:06 UTC, derekpierre commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +                TACO Node Docs
```suggestion
                TACo Node Docs
```

2023-10-11 15:10 UTC, derekpierre commented on src/types/staking.ts
> +  // TODO THEREF
Do we need to address this before merging, or is there a follow-up?

2023-10-11 15:13 UTC, derekpierre commented on .env.production
> +REACT_APP_TACO_NETWORK=mainnet
Can we rename these to use "DOMAIN" instead of "NETWORK" i.e. `REACT_APP_TACO_DOMAIN`?

2023-10-12 10:12 UTC, theref commented on src/components/StakingApplicationOperationIcon/index.tsx
> +    decrease: tbtcDecrease,
yeah there are a few images that will need updating, Manu commented on another above.

2023-10-12 12:26 UTC, derekpierre commented on src/enums/externalHref.ts
> +  tacoStakingProvidersList = "https://docs.nucypher.com/en/latest/pre_application/node_providers.html", // TODO THEREF
These are probably sufficient and already live:
- setup: https://docs.threshold.network/staking-and-running-a-node/running-a-node/self-managed/taco-node-setup
- providers: https://docs.threshold.network/staking-and-running-a-node/running-a-node/staking-providers

2023-10-12 12:27 UTC, derekpierre commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +  randomBeacon: getThresholdLib().multiAppStaking.randomBeacon.address,
@theref , What's the resolution here?

2023-10-12 12:28 UTC, derekpierre commented on .env.example
> +REACT_APP_TACO_DOMAIN=dashboard
🚀

2023-10-12 12:28 UTC, derekpierre commented on .env.production
> +REACT_APP_TACO_DOMAIN=mainnet
🚀

2023-10-12 12:30 UTC, derekpierre commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +  randomBeacon: getThresholdLib().multiAppStaking.randomBeacon.address,
nvm. I see it now 😅

2023-10-18 08:27 UTC, theref commented
ok, current bugs:
TACo app authorization not showing correctly

<img width="389" alt="Screenshot 2023-10-18 at 10 23 53" src="https://github.com/threshold-network/token-dashboard/assets/4128101/3b32e615-f04c-417f-ab68-81f492d76c30">
<img width="527" alt="Screenshot 2023-10-18 at 10 25 26" src="https://github.com/threshold-network/token-dashboard/assets/4128101/643aa9ab-5d0d-4647-8727-efc2402cc82a">
<img width="1091" alt="Screenshot 2023-10-18 at 10 25 44" src="https://github.com/threshold-network/token-dashboard/assets/4128101/b9793f1f-210c-4401-976e-6671bef08c16">

Staking provider is showing an authorized stake of 40K on the contract, but that's not displaying properly in a couple of places

2023-10-18 08:34 UTC, theref commented
On the production app, we have this box:
<img width="550" alt="Screenshot 2023-10-18 at 10 33 28" src="https://github.com/threshold-network/token-dashboard/assets/4128101/9cde6860-7ead-4a59-a2d9-a916757ce94a">
But this isn't showing on my dev version and I can't find anywhere to go through the Operator mapping process

2023-12-05 22:59 UTC, cygnusv commented on docker-compose.yml
> +    command: bash -c "yarn format:fix && yarn start"
why the `yarn format:fix` part?

2023-12-06 08:38 UTC, theref commented on docker-compose.yml
> +    command: bash -c "yarn format:fix && yarn start"
otherwise it refuses to start if the code isn't correctly formatted

2023-12-07 20:23 UTC, michalsmiarowski reviewed
Reviewed only the code related to https://github.com/threshold-network/token-dashboard/issues/678. Here are my thoughts:

2023-12-07 20:23 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>      }
I think opening modal based on `appName` might be little bit problematic if we want to use the same confirmation modal for all the apps (and I assume we do). The `appName` indicates that we would need to open separate modal for each app 🤔 

Instead of that I would pass two operators, one for tbtc + random beacon and a second one for taco. Based on that, and on the rest parameters, we could display the proper information in the confirmation modal. For example if user input only operator for tbtc + random beacon we will pass the value here, and the operator value for taco as undefined. Remember that there are cases where users can have tbtc operator mapped without random beacon. Such cases can be covered here too.

2023-12-07 20:23 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +  const formRefTaco =
`formRefTbtc` should have a name that also covers random beacon, because it might get confused. I would propose to come up with some better name for that 🤔 Either use both app names in such cases or maybe just mention them as `keepApps` or `thresholdApps` so:
1. `formRefTbtcRandomBeacon
2. `formRefKeepApps`
3. `formRefThresholdApps` (but this might be confusing too, because Taco is also a threshold app).

2023-12-07 20:23 UTC, michalsmiarowski commented on src/pages/Staking/index.tsx
> +            ))}
I think the brackets here are in wrong places, because now the `OperatorAddressMappingCard` is displayed when the user did not connect the wallet, where it should be the opposite 😬 :

<img width="1429" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/a90c272e-ea63-4608-9c63-ebcb41afe2e2">

2023-12-07 20:23 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
> +          await checkIfOperatorIsMappedToAnotherStakingProvider(values.operator)
I think we should refactor `checkIfOperatorIsMappedToAnotherStakingProvider` function so that we can provide either an app name parameter or app type flag (where type is either `Keep` (random beacon + tbtc) or `nu` (taco)) so that we can check if the operator is mapped to another staking provider for current app.

Right now, when we call this function here, it fires for taco form validation and inside we check if the staking provider is mapped for tbtc + random beacon, where this should not matter (because keep and nu apps are independent of each other) so we actually should check it for taco.

2023-12-08 09:48 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>      }
> Remember that there are cases where users can have tbtc operator mapped without random beacon.

Interesting, I didn't know that. I thought they had to be mapped to the same thing.

2023-12-08 09:50 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
>        )
ah ok! this makes sense :) whilst they're not _supposed_ to be mapped to different things, due to user error they might be

2023-12-08 09:51 UTC, theref commented on src/pages/Staking/index.tsx
> +            ))}
hmmm, that's not what the behaviour I've seen when testing, but i'll take a close look

2023-12-13 10:47 UTC, michalsmiarowski requested changes
Left some comments regarding the `MapOperatorToStaking` form

2023-12-13 10:47 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +    })
This won't work properly, because changes made by setState (in this case `setSelectedApps`) are not reflected in the current submit function (in `selectedApps` variable). The reason is that the state is not expected to be changed in the same render. The state values are used by functions based on their current closures, and state updates will reflect in the next re-render by which the existing closures are not affected, but new ones are create.

Here is a [stack overflow thread](https://stackoverflow.com/questions/54069253/the-usestate-set-method-is-not-reflecting-a-change-immediately) that I found about the exact issue you have, it explains a lot.

I would propose to select the apps based on the operator value (check if it's empty or not), and then just store it in an array inside the submit function. Something like this:

```
const submitMapping = async () => {
    const operatorTbtc = formRefTbtc.current?.values?.operator
    const operatorRandomBeacon = formRefRandomBeacon.current?.values?.operator
    const operatorTaco = formRefTaco.current?.values?.operator

    const applications = []
    if (operatorTbtc) {
      await formRefTbtc.current?.validateForm()
      formRefTbtc.current?.setTouched({ operator: true }, false)
      applications.push({
        appName: "tbtc",
        operator: operatorTbtc,
      })
    }
    if (operatorRandomBeacon) {
      await formRefRandomBeacon.current?.validateForm()
      formRefRandomBeacon.current?.setTouched({ operator: true }, false)
      applications.push({
        appName: "randomBeacon",
        operator: operatorRandomBeacon,
      })
    }
    if (operatorTaco) {
      await formRefTaco.current?.validateForm()
      formRefTaco.current?.setTouched({ operator: true }, false)
      applications.push({
        appName: "taco",
        operator: operatorTaco,
      })
    }
    openModal(ModalType.MapOperatorToStakingProviderConfirmation, {
      applications: applications,
    })
  }
  ```
  
  Note tha validation for each form should also be done only if the operator value is set.

2023-12-13 10:47 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +    useRef<FormikProps<MapOperatorToStakingProviderFormValues>>(null)
One more thing - I don't think we should separate tbtc and random beacon. Instead of 3 forms I would keep it as two forms - one for tbtc + random beacon (as it was before) and second one for taco. This is what I meant here: https://github.com/threshold-network/token-dashboard/pull/625#discussion_r1419550685 and here: https://github.com/threshold-network/token-dashboard/pull/625#discussion_r1419548789.

The reason is that the tbtc and random beacon should always (from what I know) have the same operator address, so keeping it in one form makes more sense.

2023-12-13 19:48 UTC, cygnusv reviewed
Looking good! Made a first pass, will make a second pass tomorrow

2023-12-13 19:48 UTC, cygnusv commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
> +        console.log("taco")
There's a few console.log statements around. I don't think it's much of an issue, but maybe some of them can be cleaned up

2023-12-13 19:48 UTC, cygnusv commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +          {/*  JAMES TODO JAMES THEREF do we need another input for tbtc/rb */}
Is this still pending?

2023-12-13 19:48 UTC, cygnusv commented on src/components/Modal/TACoCommitmentModal/index.tsx
> +            the same unlock horizon before the bonus deadline (12/30/23) , but
```suggestion
            the same unlock horizon before the bonus deadline (December 30th, 2023), but
```

2023-12-13 19:48 UTC, cygnusv commented on src/components/Modal/TACoCommitmentModal/index.tsx
> +            head to [link to documentation].
Missing documentation link (cc @arjunhassard )

2023-12-13 19:48 UTC, cygnusv commented on src/components/StakingTimeline/index.tsx
> +            tBTC, TACo, and Random Beacon, go to the{" "}
```suggestion
            tBTC, Random Beacon, and TACo, go to the{" "}
```

2023-12-13 19:48 UTC, cygnusv commented on src/hooks/staking-applications/useRegisterMultipleOperatorsTransaction.ts
> +          throw new Error("TACo app already have mapped operator!")
```suggestion
          throw new Error("TACo app already has mapped operator!")
```

2023-12-13 19:48 UTC, cygnusv commented on src/pages/Staking/StakeDetailsPage/index.tsx
> +            <NodeStatusLabel isAuthorized={tacoApp.isAuthorized} />
This should be changed to either represent "Authorization status" rather than "Node status", or check different events (e.g., operator bonded). However, given that it seems the same happens to tBTC/RB below, so we may discuss this for a later, unified change.

2023-12-13 19:48 UTC, cygnusv commented on src/threshold-ts/applications/index.ts
> +      }
This should be tackled as part of a later refactor that doesn't assume methods that are only relevant to TBTC (see https://github.com/threshold-network/token-dashboard/issues/627).

2023-12-14 14:15 UTC, derekpierre commented on src/hooks/staking-applications/useRegisterMultipleOperatorsTransaction.ts
>            throw new Error("Tbtc app already have mapped operator!")
```suggestion
          throw new Error("Tbtc app already has mapped operator!")
```

2023-12-14 14:15 UTC, derekpierre commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +                    tBTC and Random Beacon apps and 180 days for TACo.
Should we be consistent with what we have in other places i.e. 6 months. Technically it is 182 days I believe.
```suggestion
                    tBTC and Random Beacon apps and 6 months for TACo.
```

2023-12-14 14:15 UTC, derekpierre commented on src/pages/Staking/HowItWorks/StakingApplications/index.tsx
> +          description="TACo is a plug-in access control layer and cryptographic primitive, operationally distributed across a cohort of Threshold nodes. Private data are encrypted by a data owner alo
```suggestion
          description="TACo is a plug-in access control layer and cryptographic primitive, operationally distributed across a cohort of Threshold nodes. Private data is encrypted by a data owner along with embedded access conditions. The data remains encrypted until it reaches the device of a condition-satisfying recipient."
```

2023-12-14 14:15 UTC, derekpierre commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +    const resultTacoLabel = getStakingAppLabelFromAppName(randomBeaconName)
```suggestion
    const resultTacoLabel = getStakingAppLabelFromAppName(tacoName)
```

2023-12-14 14:17 UTC, cygnusv commented on package.json
> +    "@nucypher/nucypher-contracts": "0.13.0",
It's not necessary, since all contracts and relevant ABIs are in 0.13.0

2023-12-14 19:02 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge. Still not finished with the review, might come back with more comments once I test it more.

2023-12-14 19:28 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>              mappedOperatorTbtc={mappedOperatorTbtc}
Also I think we should make sure with @lukasz-zimnoch if the operator mapped for tbtc and random-beacon apps should be the same or they can be completely different. We implemented it in such way on the front end back in the day, but based on my testing I think it's possible to use different operators on the contract side 🤔 I did a transaction with my wallet and it didn't throw any error. Maybe that was a design decision to do that in the dApp?

2023-12-15 13:22 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>              mappedOperatorTbtc={mappedOperatorTbtc}
Confirmed with @lukasz-zimnoch that operator mapped for tbtc and random-beacon apps should be the same so we should keep the validation on the front end.

2023-12-15 15:58 UTC, theref commented on package.json
> +    "@nucypher/nucypher-contracts": "0.13.0",
marking resolved

2023-12-18 10:45 UTC, michalsmiarowski requested changes
Left some important comments that should be addressed before the merge.

2023-12-18 10:45 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
>          mappedOperatorRandomBeacon
5. Improve validation here:

```
  if (values.operator) {
    errors.operator = validateETHAddress(values.operator)
    if (!errors.operator) {
      errors.operator = await validateInputtedOperatorAddress(
        values.operator,
        checkIfOperatorIsMappedToAnotherStakingProvider,
        mappedOperatorTbtc,
        mappedOperatorRandomBeacon
      )
    }
  }
```

Note that we've added `if (values.operator)` condition at the top, before `validateETHAddress` call. This is neede so that we don't run validation if the input is empyt (so that we can submit either RandomBeaconTbtc or Taco).

2023-12-18 10:45 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>    }
6. Split this into three cases based on the `appName`:

```
  const checkIfOperatorIsMappedToAnotherStakingProvider: (
    operator: string,
    appName: string
  ) => Promise<boolean> = async (operator: string, appName: string) => {
    let stakingProviderMapped
    switch (appName) {
      case "tbtc":
        const stakingProviderMappedEcdsa =
          await threshold.multiAppStaking.ecdsa.operatorToStakingProvider(
            operator
          )
        return (
          !isAddressZero(stakingProviderMappedEcdsa) &&
          !isSameETHAddress(stakingProviderMappedEcdsa, account!)
        )
      case "randomBeacon":
        const stakingProviderMappedRandomBeacon =
          await threshold.multiAppStaking.randomBeacon.operatorToStakingProvider(
            operator
          )
        return (
          !isAddressZero(stakingProviderMappedRandomBeacon) &&
          !isSameETHAddress(stakingProviderMappedRandomBeacon, account!)
        )
      case "taco":
        stakingProviderMapped =
          await threshold.multiAppStaking.taco.operatorToStakingProvider(
            operator
          )
        return (
          !isAddressZero(stakingProviderMapped) &&
          !isSameETHAddress(stakingProviderMapped, account!)
        )
      default:
        throw new Error(`Unsupported app name: ${appName}`)
    }
  }
```

2023-12-18 10:45 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>    }
7. The `applications` type here should be the same as the `applications` type in `MapOperatorToStakingProviderConfirmation`. Besides that we shouldn't push two applications (`randomBeacon` and `tbtc`) in all cases because it will throw an errror if user has only tbtc app validated. I propose this:

```
const submitMapping = async () => {
    const operatorTbtcRb = formRefTbtcRb.current?.values?.operator
    const operatorTaco = formRefTaco.current?.values?.operator

    const applications: ApplicationForOperatorMapping[] = []
    let isValid = true
    if (operatorTbtcRb) {
      await formRefTbtcRb.current?.validateForm()
      formRefTbtcRb.current?.setTouched({ operator: true }, false)
      if (mappedOperatorTbtc && isAddressZero(mappedOperatorTbtc)) {
        applications.push({
          appName: "tbtc",
          operator: operatorTbtcRb,
          stakingProvider: account!,
        })
      }
      if (
        mappedOperatorRandomBeacon &&
        isAddressZero(mappedOperatorRandomBeacon)
      ) {
        applications.push({
          appName: "randomBeacon",
          operator: operatorTbtcRb,
          stakingProvider: account!,
        })
      }
      isValid = isValid && formRefTbtcRb.current?.isValid
    }
    if (operatorTaco) {
      await formRefTaco.current?.validateForm()
      formRefTaco.current?.setTouched({ operator: true }, false)
      applications.push({
        appName: "taco",
        operator: operatorTaco,
        stakingProvider: account!,
      })
      isValid = isValid && formRefTaco.current?.isValid
    }
    if (applications.length > 0 && isValid) {
      openModal(ModalType.MapOperatorToStakingProviderConfirmation, {
        applications: applications,
      })
    }
  }
```

I've also introduced new interface here: `ApplicationForOperatorMapping` - see next point

2023-12-18 10:45 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +    }[]
8. Based on the point aboe - extract it to a separate type and export it:

```
export interface ApplicationForOperatorMapping {
  appName: string
  operator: string
  stakingProvider: string
}

const MapOperatorToStakingProviderConfirmationModal: FC<
  BaseModalProps & {
    applications: ApplicationForOperatorMapping[]
  }
  ```

2023-12-18 10:45 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +            />
9. Change this form for tbtcRb:

```
              <MapOperatorToStakingProviderForm
                innerRef={formRefTbtcRb}
                formId="map-operator-to-staking-provider-form-tbtc"
                initialAddress={
                  isOperatorMappedOnlyInRandomBeacon
                    ? mappedOperatorRandomBeacon
                    : isOperatorMappedOnlyInTbtc
                    ? mappedOperatorTbtc
                    : ""
                }
                checkIfOperatorIsMappedToAnotherStakingProvider={async (
                  operator: string
                ) => {
                  const isOperatorAlreadyMappedTbtc =
                    await checkIfOperatorIsMappedToAnotherStakingProvider(
                      operator,
                      "tbtc"
                    )
                  const isOperatorAlreadyMappedRandomBeacon =
                    await checkIfOperatorIsMappedToAnotherStakingProvider(
                      operator,
                      "tbtc"
                    )
                  return (
                    isOperatorAlreadyMappedTbtc &&
                    isOperatorAlreadyMappedRandomBeacon
                  )
                }}
                mappedOperatorRandomBeacon={mappedOperatorRandomBeacon}
                mappedOperatorTbtc={mappedOperatorTbtc}
              />
```

Here we add `initialAddress` and we pass a callback funtion to `checkIfOperatorIsMappedToAnotherStakingProvider` where we call `checkIfOperatorIsMappedToAnotherStakingProvider` with a proper app arguments.

2023-12-18 10:45 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +            />
10. (final step) Refactor this form:

```
            <MapOperatorToStakingProviderForm
              innerRef={formRefTaco}
              formId="map-operator-to-staking-provider-form-taco"
              checkIfOperatorIsMappedToAnotherStakingProvider={async (
                operator: string
              ) => {
                return await checkIfOperatorIsMappedToAnotherStakingProvider(
                  operator,
                  "taco"
                )
              }}
              mappedOperatorTaco={mappedOperatorTaco}
            />
```

SImilarly to above we will call `checkIfOperatorIsMappedToAnotherStakingProvider` but this time with `taco` as an app name.

And that should be it. I belive that this is not an ideal solution though. Ideally we would want to further separate those two forms (RandomBeaconTbtc and Taco) and just extract similar logic to a shared component, but considering how much time we have then I think this would be enough for now.

2023-12-18 11:35 UTC, michalsmiarowski requested changes
two more comments below

2023-12-18 11:35 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +        {isEmptyOrZeroAddress(mappedOperatorTbtc) && (
Actually this is wrong condition. The prettier removed the brackets for me 😬  Should be:

```suggestion
        {(isEmptyOrZeroAddress(mappedOperatorTbtc) ||
          isEmptyOrZeroAddress(mappedOperatorRandomBeacon)) && (
```

2023-12-18 11:35 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +                : "tBTC & Random Beacon"}
Let's rever it to previous implementation, because it shows wrong values right now:

```suggestion
          {isOperatorMappedOnlyInRandomBeacon ? (
            <LabelSm>tBTC app</LabelSm>
          ) : isOperatorMappedOnlyInTbtc ? (
            <LabelSm>random beacon app</LabelSm>
          ) : (
            <LabelSm>tBTC + Random Beacon apps (requires 2txs)</LabelSm>
          )}
```

2023-12-18 11:49 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>            withIcon={false}
https://github.com/threshold-network/token-dashboard/pull/625/commits/17b3668529cd43c75f4e64d8641ea8541332fdf9

2023-12-18 11:50 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
>      console.error("`MapOperatorToStakingProviderForm` validation error.", error)
https://github.com/threshold-network/token-dashboard/pull/625/commits/7897c853021d0280902d0b9444653ae843ff6924

2023-12-18 11:50 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
>  } & ComponentProps
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 11:50 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
> -  }),
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 11:50 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
>  }
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 11:50 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/MapOperatorToStakingProviderForm.tsx
>          mappedOperatorRandomBeacon
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 11:50 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>    }
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 11:50 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>    }
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 11:51 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +    }[]
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 11:51 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +            />
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 11:51 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +            />
https://github.com/threshold-network/token-dashboard/pull/625/commits/50fd0c87c787d079509eb083d894e51b74419681

2023-12-18 13:10 UTC, michalsmiarowski requested changes

2023-12-18 13:10 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +                    )
I think I've done a mistake here: https://github.com/threshold-network/token-dashboard/pull/625#discussion_r1429891983

We should use OR (`||`) operator here instead of AND {`&&`}. The condition should work the same as here:
https://github.com/threshold-network/token-dashboard/blob/17afd96148b72593c20d2c487bd79047f874a927/src/components/Modal/MapOperatorToStakingProviderModal/index.tsx#L79-L84
and we use the OR operator there.

```suggestion
                    return (
                      isOperatorAlreadyMappedTbtc ||
                      isOperatorAlreadyMappedRandomBeacon
                    )
```

2023-12-18 14:18 UTC, michalsmiarowski requested changes
Left some comments regarding TACo commitment

2023-12-18 14:18 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +          break
There is not information in the dApp that you have to `Commit to Taco` first before mapping the operator. WIthout the commitment it throws an error:

`Not owner or provider`

<img width="1144" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/c9111c2c-2394-4527-91f6-ce7c7ff4e8cc">

2023-12-18 14:27 UTC, theref commented on src/components/Modal/TACoCommitmentModal/index.tsx
> +              </Tr>
that is expected on development due to the version of the contract that is deployed

2023-12-18 14:31 UTC, michalsmiarowski requested changes

2023-12-18 14:44 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +    }[]
The type is more related to `MapOperatorToStakingProviderConfirmationModal` so it would be better if it was moved there, just above the component.

2023-12-18 14:48 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +          break
Actually, after further testing, it looks it's not commit that is required but authorization. The stake should be authorized for Taco first with the minimum amount of T tokens (which is 40k). Only then the mapping is allowed.

Here is where the error is thrown in the contract: https://github.com/nucypher/nucypher-contracts/blob/2f7b241aa216ff85ebdea3b796285ef35ae57768/contracts/contracts/TACoApplication.sol#L276
It checks if `stakingProviderInfo[_stakingProvider].authorized` value greater than 0 [here](https://github.com/nucypher/nucypher-contracts/blob/2f7b241aa216ff85ebdea3b796285ef35ae57768/contracts/contracts/TACoApplication.sol#L653-L655). I believe that the `authorized` amount is set during the autorization, authorizationIncrease and deauthorization.

Maybe we should reflect that the authorization is needed to map the operator in the UI? 🤔

2023-12-18 14:49 UTC, michalsmiarowski commented on src/components/Modal/TACoCommitmentModal/index.tsx
> +              </Tr>
I see. In this case I'm resolving the issue.

2023-12-18 15:11 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +                : "tBTC & Random Beacon"}
https://github.com/threshold-network/token-dashboard/pull/625/commits/d1c18620ceb3a34e1ae7ab4a5ed176470eace2a6

2023-12-18 15:15 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +                : "tBTC & Random Beacon"}
https://github.com/threshold-network/token-dashboard/pull/625/commits/ed0535912603406365af2a8e3f4457b5fce39d72

2023-12-18 15:21 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
> +        {isEmptyOrZeroAddress(mappedOperatorTbtc) && (
Addresed in d1c18620ceb3a34e1ae7ab4a5ed176470eace2a6

2023-12-18 15:40 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +          break
if i make the Button only appear if TACo has already been authorized, would that suffice?

2023-12-18 15:43 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +          break
https://github.com/threshold-network/token-dashboard/pull/625/commits/d174a384aeb25eca1a47cf7d347f8774fa9b69c7

2023-12-18 15:50 UTC, cygnusv submitted a review, later dismissed
LGTM, this is a massive piece of work @theref and essential for taco release.

2023-12-18 15:52 UTC, cygnusv commented on src/components/Modal/TACoCommitmentModal/index.tsx
> +        </Button>
Can we compromise here?

2023-12-18 16:27 UTC, michalsmiarowski requested changes

2023-12-18 16:27 UTC, michalsmiarowski commented on src/store/account/selectors.ts
>  )
We have to refactor it a little bit. `isOperatorMappedOnlyInTbtc` and `isOperatorMappedOnlyInRandomBeacon` helper variables were created with the thought of bundled rewards from tbtc + random beacon. We shouldn't add taco app here because it will then displays the `tbtc + random beacon` label when we have tbtc and taco apps mapped. My proposal would be to:

1. Refactor `selectMappedOperators` selector:

```
export const selectMappedOperators = createSelector(
  [selectAccountState],
  (accountState: AccountState) => {
    const { randomBeacon, tbtc, taco } = accountState.operatorMapping.data
    const isOperatorMappedOnlyInTbtcForBundledRewards =
      !isAddressZero(tbtc) && isAddressZero(randomBeacon)
    const isOperatorMappedOnlyInRandomBeaconForBundledRewards =
      isAddressZero(tbtc) && !isAddressZero(randomBeacon)

    return {
      mappedOperatorTbtc: tbtc,
      mappedOperatorRandomBeacon: randomBeacon,
      mappedOperatorTaco: taco,
      isOperatorMappedOnlyInTbtcForBundledRewards,
      isOperatorMappedOnlyInRandomBeaconForBundledRewards,
      isOperatorMappedInAllApps:
        !isAddressZero(randomBeacon) &&
        !isAddressZero(tbtc) &&
        !isAddressZero(taco),
    }
  }
)
```

We will remove `isOperatorMappedOnlyInTaco` and `isOneOfTheAppsNotMapped` properties completely adn rename those two:

`isOperatorMappedOnlyInTbtc` -> `isOperatorMappedOnlyInTbtcForBundledRewards`
`isOperatorMappedOnlyInRandomBeacon` -> `isOperatorMappedOnlyInRandomBeaconForBundledRewards`

2023-12-18 16:27 UTC, michalsmiarowski commented on src/pages/Staking/OperatorAddressMappingCard.tsx
>    } = useAppSelector(selectMappedOperators)
Destructurize `isOperatorMappedOnlyInRandomBeaconForBundledRewards` and `isOperatorMappedOnlyInTbtcForBundledRewards` here:

```
  const {
    mappedOperatorTbtc,
    mappedOperatorRandomBeacon,
    mappedOperatorTaco,
    isOperatorMappedOnlyInRandomBeaconForBundledRewards,
    isOperatorMappedOnlyInTbtcForBundledRewards,
  } = useAppSelector(selectMappedOperators)
```

Then create a helper variable `isOneOfTheBundledAppsNotMapped`:

```
  const isOneOfTheBundledAppsNotMapped =
    isOperatorMappedOnlyInRandomBeaconForBundledRewards ||
    isOperatorMappedOnlyInTbtcForBundledRewards
```

and change all the occurences of  `isOneOfTheAppsNotMapped` to (->)`isOneOfTheBundledAppsNotMapped`.

2023-12-18 16:27 UTC, michalsmiarowski commented on src/hooks/staking-applications/useRegisterMultipleOperatorsTransaction.ts
> +          throw new Error("TACo app already has mapped operator!")
3. Change those conditions to:

```
        if (!isEmptyOrZeroAddress(mappedOperatorRandomBeacon))
          throw new Error("Random beacon app already has mapped operator!")

        if (!isEmptyOrZeroAddress(mappedOperatorTbtc))
          throw new Error("Tbtc app already has mapped operator!")

        if (!isEmptyOrZeroAddress(mappedOperatorTaco))
          throw new Error("TACo app already has mapped operator!")
```

and then remove those 3 variables (`isOperatorMappedOnlyInRandomBeacon`, `isOperatorMappedOnlyInTbtc` and `isOperatorMappedOnlyInTaco`) from `useAppSelector` which is few lines above.

2023-12-18 16:27 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>    } = useAppSelector(selectMappedOperators)
4. Refactor this `useAppSelector` destructuring:

```
const {
  const {
    mappedOperatorTbtc,
    mappedOperatorRandomBeacon,
    mappedOperatorTaco,
    isOperatorMappedOnlyInTbtcForBundledRewards,
    isOperatorMappedOnlyInRandomBeaconForBundledRewards,
    isOperatorMappedInAllApps,
  } = useAppSelector(selectMappedOperators)
```

Then, in this file, change all occurences of:
1. `isOperatorMappedOnlyInRandomBeacon` to `isOperatorMappedOnlyInTbtcForBundledRewards`
2. `isOperatorMappedOnlyInTbtc` to `isOperatorMappedOnlyInRandomBeaconForBundledRewards`

2023-12-18 16:27 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>              </H5>
5. Last thing is to change this condition to:

```
          {isOperatorMappedInAllApps ? (
            <H5>
              We noticed you've not mapped Operator Address to some
              applications.
            </H5>
```

We should display a complete new subtitle here, because we've got 3 applictions now. I proposed the one above, which is:
"We noticed you've not mapped Operator Address to some  applications."
which should be displayed when not all of the apps have mapped operators.

2023-12-18 17:00 UTC, theref commented on src/store/account/selectors.ts
>  )
https://github.com/threshold-network/token-dashboard/pull/625/commits/3915d2d88cc07e25c2fe36bc0f6f3f76614dae9a

2023-12-18 17:00 UTC, theref commented on src/pages/Staking/OperatorAddressMappingCard.tsx
>    } = useAppSelector(selectMappedOperators)
https://github.com/threshold-network/token-dashboard/pull/625/commits/3915d2d88cc07e25c2fe36bc0f6f3f76614dae9a

2023-12-18 17:00 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>    } = useAppSelector(selectMappedOperators)
https://github.com/threshold-network/token-dashboard/pull/625/commits/3915d2d88cc07e25c2fe36bc0f6f3f76614dae9a

2023-12-18 17:00 UTC, theref commented on src/components/Modal/MapOperatorToStakingProviderModal/index.tsx
>              </H5>
https://github.com/threshold-network/token-dashboard/pull/625/commits/3915d2d88cc07e25c2fe36bc0f6f3f76614dae9a

2023-12-18 17:22 UTC, michalsmiarowski requested changes
Two more comments

2023-12-19 10:17 UTC, michalsmiarowski commented on src/components/Modal/TACoCommitmentModal/index.tsx
> +        </Button>
Was addressed in b1dc9f8b2c2e4113234da8877058425ee69feaf4

2023-12-19 10:19 UTC, michalsmiarowski commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +          break
Not sure if this change is needed? @theref @cygnusv 

Do you want to have the commit button available only when taco app is authorised?

2023-12-19 10:20 UTC, michalsmiarowski submitted a review, later dismissed
LGTM

2023-12-19 10:35 UTC, cygnusv submitted a review, later dismissed

2023-12-19 10:36 UTC, cygnusv commented on src/components/Modal/MapOperatorToStakingProviderConfirmationModal/index.tsx
> +          break
Yes, only after authorized

2023-12-19 14:27 UTC, cygnusv approved these changes
Approving again after the rebase due to the need of signed commits. As seen here, https://github.com/threshold-network/token-dashboard/compare/524f0b8b2b07f1f57343a061820954fb9579c525..a188adf344fced8ef2c17cce9c594ac6052e79d2, no actual changes happened

2023-12-19 14:27 UTC, michalsmiarowski approved these changes
Adding approve again after rebase to make all commits verified 👍

2023-12-19 14:36 UTC, merged