Added conditional rendering for authorization alert
threshold-network/token-dashboard pull request #628
Opened 2023-09-29 12:48 UTC by kpyszkowski

Closes: https://github.com/threshold-network/token-dashboard/issues/573

Aggregated authorization apps statuses into an `isFullyAuthorized` boolean indicating if the authorization process is fulfilled and used this boolean to conditionally render the `AlertBox` component.

2023-09-29 15:05 UTC, michalsmiarowski requested changes
Overall looking good 🔥 I've just proposed some slight improvement to `isFullyAuthorized` condition.

2023-09-29 15:05 UTC, michalsmiarowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  )
We need to modify this condition. A stake only requires 40k of its tokens authorized to be considered 'authorized.' If we have a stake of 100k T and authorize only 40k T, it will still be labeled 'authorized,' but in reality, it's not fully authorized.

Since it is mentioned in [the issue](https://github.com/threshold-network/token-dashboard/issues/573) that the info bubble should be hidden only after the app is 100% authorized, we should refine this condition accordingly:

```suggestion
  const isFullyAuthorized = Object.values(appsAuthData).every(
    ({ status, percentage }) =>
      (status === "authorized" && percentage === 100) ||
      status === "authorization-not-required"
  )
```

2023-09-29 15:27 UTC, kpyszkowski commented on src/pages/Staking/AuthorizeStakingApps/index.tsx
> +  )
c8a8577cf041c04bb411544ba715c03977d275e0

2023-10-02 07:38 UTC, michalsmiarowski approved these changes
LGTM

2023-10-02 07:39 UTC, merged