New tBTC app modal refinements
threshold-network/token-dashboard pull request #630
Opened 2023-10-02 12:26 UTC by kpyszkowski

Closes: https://github.com/threshold-network/token-dashboard/issues/547

Added "How it works" button for `NewTBTCApp` modal component. Reordered subnavigation links by implementing `order` prop.

2023-10-04 08:39 UTC, michalsmiarowski requested changes
Left some comments to look at down below 👇

2023-10-04 08:39 UTC, michalsmiarowski commented on src/components/SubNavigationPills/index.tsx
> +  const linksWithTitle = reorderedLinks.filter((link) => !!link.title)
This algorithm for ordering pages in unnecessary. To change the order of the sub-navigation in tBTC page you just have to change the order of `pages` property here:

https://github.com/threshold-network/token-dashboard/blob/58e4dc839bb9d02765e1ccce837e200eb74b5b51/src/pages/tBTC/index.tsx#L15

2023-10-04 08:39 UTC, michalsmiarowski commented on src/components/SubNavigationPills/index.tsx
> +  }
Similar to above this code is also unnecessary

2023-10-04 08:39 UTC, michalsmiarowski commented on src/components/SubNavigationPills/index.tsx
> +  order?: string[]
Same with the order property here. It also breaks the `Upgrade` page, because the `order` property was not passed there:

<img width="825" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/fa2d1620-67ba-4aee-ade7-d724af4849ec">

2023-10-04 08:41 UTC, michalsmiarowski commented
We should also make "How it works" subpage a primary page when you click "tBTC" on the left navigation. Right now when you click it it automatically goes to "Bridge" subpage.

2023-10-04 11:27 UTC, kpyszkowski commented on src/components/SubNavigationPills/index.tsx
> +  const linksWithTitle = reorderedLinks.filter((link) => !!link.title)
done

2023-10-04 11:27 UTC, kpyszkowski commented on src/components/SubNavigationPills/index.tsx
> +  }
reverted

2023-10-04 11:28 UTC, kpyszkowski commented on src/components/SubNavigationPills/index.tsx
> +  order?: string[]
resolved by reverting changes

2023-10-18 08:57 UTC, michalsmiarowski requested changes
Works great now 🔥 Left some comments to look at before the merge though

2023-10-18 08:57 UTC, michalsmiarowski commented on src/components/SubNavigationPills/index.tsx
> +import { FC } from "react"
Hmmm, I think those changes are unnecessary. They just reorder the imports

2023-10-18 08:57 UTC, michalsmiarowski commented on src/components/Modal/tBTC/NewTBTCApp.tsx
> +import withBaseModal from "../withBaseModal"
Similar to above there are also unnecessary changes here

2023-10-18 09:03 UTC, michalsmiarowski commented
@kpyszkowski Let's also merge the newest changes from `main` branch to fix the build

2023-10-24 08:17 UTC, kpyszkowski commented on src/components/SubNavigationPills/index.tsx
> +import { FC } from "react"
Seems like Prettier reorders imports alphabetically for me. I don't use any other code formatters. Perhaps my local config overlaps project-based Prettier rules. In my opinion such refinement is more like improvement rather than something i should revert. Nevertheless, for now I reverted it to keep the consistency but I highly encourage to refine imports globally in the future.

2023-10-24 08:17 UTC, kpyszkowski commented on src/components/Modal/tBTC/NewTBTCApp.tsx
> +import withBaseModal from "../withBaseModal"
As above, ref: https://github.com/threshold-network/token-dashboard/pull/630#discussion_r1369785795

2023-10-24 08:19 UTC, kpyszkowski commented on src/components/Modal/tBTC/NewTBTCApp.tsx
> +        </Button>
Applied, ref commit: b80ca38b868350c605df2389210a7708d0dc60ff

2023-10-24 08:19 UTC, kpyszkowski commented on src/pages/tBTC/HowItWorks/index.tsx
> +  title: "How it works",
Applied, ref commit: d8058d3e711ff7b4831245044ad2610382889593

2023-10-24 08:20 UTC, kpyszkowski commented
@michalsmiarowski The `main` branch has been merged into feature branch, ref commit: d17d9b3883c3b2f79ac6e183c664bad33ac507bb

2023-10-27 09:51 UTC, michalsmiarowski commented on src/components/SubNavigationPills/index.tsx
> +import { FC } from "react"
> In my opinion such refinement is more like improvement rather than something i should revert

I agree, I think we could format it like this, but I like keeping the things clear and separate from each toher rather than doing everythin o half of it in one PR 😅 If we want to introduce such thing, then let's address it in a separate PR and change it accross the whole app.

2023-10-27 10:09 UTC, michalsmiarowski requested changes
Left one small issue to fix before the merge

2023-10-27 10:09 UTC, michalsmiarowski commented on src/components/Modal/tBTC/NewTBTCApp.tsx
> +import { TakeNoteList } from "../../tBTC"
Let's remove last point from `TakeNoteList` component as it in designs.

Designs:
<img width="484" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/1bc4d85c-9918-4481-9c84-8be523511f80">

Implementation:
<img width="510" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/ac308f73-1995-4eda-a985-b3993e19ccf3">

2023-10-30 10:51 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-10-30 10:51 UTC, merged