Staking user flow enhancements - running node acknowledgement
threshold-network/token-dashboard pull request #632
Opened 2023-10-03 08:55 UTC by kpyszkowski

Ref: https://github.com/threshold-network/token-dashboard/issues/567

Added running node alert box and adjusted modal labeling. Added acknowledgement checkbox and conditionally disabled *Continue* button.

2023-10-04 10:05 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge

2023-10-04 10:05 UTC, michalsmiarowski commented on src/components/Modal/StakingChecklistModal/index.tsx
>            <StakingTimeline />
Based on designs I think we should also remove the purple bar and purple arrows from timeline here

2023-10-04 10:55 UTC, kpyszkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +        </Checkbox>
fixed

2023-10-04 10:55 UTC, kpyszkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +            href="https://docs.threshold.network/staking-and-running-a-node/running-a-node"
added

2023-10-04 10:58 UTC, kpyszkowski commented on src/components/Modal/StakingChecklistModal/index.tsx
>  } from "@chakra-ui/react"
If chakra components are exported from the components library and that's the rule we stick to, I don't see any reason to import anything from `@chakra-ui/react`. I refactored imports in modified files to use `@threshold-network/components` instead.

2023-10-04 11:00 UTC, kpyszkowski commented on src/components/Modal/StakingChecklistModal/index.tsx
>            <StakingContractLearnMore mt="4rem !important" />
done, now it's (possibly) pixel-perfect

2023-10-04 11:03 UTC, kpyszkowski commented on src/components/Modal/StakingChecklistModal/index.tsx
>            <StakingContractLearnMore mt="4rem !important" />
adjusted

2023-10-04 11:03 UTC, kpyszkowski commented on src/components/Modal/StakingChecklistModal/index.tsx
>            <StakingTimeline />
adjusted

2023-10-17 16:36 UTC, michalsmiarowski requested changes
Looking good! Left some comments to look at before the merge though.

2023-10-17 16:36 UTC, michalsmiarowski commented on src/components/Modal/StakingChecklistModal/index.tsx
> +          <AlertDescription>
Let's add proper color to the alert description:

```suggestion
          <AlertDescription color={useColorModeValue("gray.700", "white")}>
```

2023-10-17 16:36 UTC, michalsmiarowski commented on src/components/Modal/SubmitStake/index.tsx
>            <H5>You are about to make a deposit into the T Staking Contract.</H5>
Based on the Figma we shouldn't end this sentence with a dot.

2023-10-17 16:36 UTC, michalsmiarowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
Instead of specyfying the `fontSize` here can we wrap the children text in `<BodySm>` component?

2023-10-17 16:36 UTC, michalsmiarowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
Same as above

2023-10-17 16:36 UTC, michalsmiarowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
Same as above

2023-10-18 08:10 UTC, michalsmiarowski commented
@kpyszkowski Let's also merge the newest changes from `main` branch to fix the build

2023-10-23 09:41 UTC, kpyszkowski commented on src/components/StakingTimeline/index.tsx
> +          &nbsp;
That's true, there is actually double whitespace - my fault. Generally speaking `{" "}` is not a recommended way to adjust text flow in a document. HTML whitespace is sometimes truncated or moved between lines of text. The JSX parser itself handles whitespace in its own mysterious way 🤔  The use of HTML entities ensures that characters are intentionally in place where they are meant to be. 
I noticed you are widely using `{" "}` in many components - in fact [Prettier adds it for you](https://github.com/prettier/prettier/issues/4223). In this case it seems to be working as expected but it's not necessarily the case. Let's leave it as is in this case/codebase but from my point of view "nbsp", which stands for "non-breaking space", is much more readable than space string dropped "randomly" in JSX with possibility of unexpected behavior on mind.

Reverted changes commit: 6b8bc3cfdb950aafe34d64b93ae33527a1363d70

2023-10-23 09:42 UTC, kpyszkowski commented on src/components/StakingTimeline/index.tsx
> +          Staking Provider, here is &nbsp;
As above, ref: https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1356910199

2023-10-23 09:44 UTC, kpyszkowski commented on src/components/StakingTimeline/index.tsx
> +          <Link to={APPLICATION_DOCS_URL}>here</Link> or contact a &nbsp;
As above, ref: https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1356910199

2023-10-23 09:45 UTC, kpyszkowski commented on src/components/Link/SharedLinks.tsx
> +        Read the&nbsp;
As above, ref: https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1356910199

2023-10-23 10:13 UTC, kpyszkowski commented on src/components/Modal/StakingChecklistModal/index.tsx
> +          </BodyLg>
I've done a mistake. It should be `as="h6"`. Fixed. 
The `<H5 />` component is used for the sake of styling. However I interpolated `h6` tag in terms of accessibility and HTML semantics. As said in [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) HTML heading elements are not about the text sizing/styling but the structure. In this particular case the whole modal is labeled by H5 heading and by the rule of thumb all descending heading elements should be greater than fifth index - so `h6` in this case. Also that's how assistive devices like screen readers interpret the document structure. If headings and HTML semantics are incorrect, assistive devices will give faulty instructions to users with disabilities.

2023-10-23 10:41 UTC, kpyszkowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
Wrapping element in extra HTML element only for styling is not a good idea. That's what Chakra atomic style props are for.

2023-10-23 10:41 UTC, kpyszkowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
As above: https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1368469091

2023-10-23 10:41 UTC, kpyszkowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
As above: https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1368469091

2023-10-23 10:42 UTC, kpyszkowski commented on src/components/Modal/SubmitStake/index.tsx
>            <H5>You are about to make a deposit into the T Staking Contract.</H5>
Correct, removed. I also changed it into paragraph element as elaborated in https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1368436037.

2023-10-23 10:54 UTC, kpyszkowski commented on src/components/Modal/StakingChecklistModal/index.tsx
> +          <AlertDescription>
Applied 🙇🏼 
Ref commit: cebf705a7f63a13d3d1a0e5dfdbcc543390fc6a8

2023-10-23 10:57 UTC, kpyszkowski commented on src/components/Modal/SubmitStake/index.tsx
> +            <chakra.p fontSize="md">
Ref commit: faedc85ca0a233796a033f32a8eb86d614bd71af

2023-10-25 08:18 UTC, michalsmiarowski commented on src/components/StakingTimeline/index.tsx
> +          &nbsp;
From what I understood, a non-breaking space has two main goals:
- prevents an [automatic line break](https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap) at its position
- prevents consecutive [whitespace characters](https://en.wikipedia.org/wiki/Whitespace_character) from collapsing into a single space

I don't think we need any of this in this place. If anywhere, it could be used between "Staking page" words to not break the link to the new line, but even there I think it's not THAT needed IMO:

<img width="246" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/4e8fc88b-d548-424b-b418-6670aada43ef">

I agree that using `{" "}` or `&nbsp` is not a matter of preference, but not for the same reasons as you 😛 It's just two different things, and replacing one with another is bad idea imo. The {" "} is a replacement for a normal space in html, while `&nbsp` is mainly used to prevent word-break. When going to the new line in code, our formatter removes any spaces that are at the end of the line, which is good because it would be hard to say if there is a space at the end without selecting it with a mouse. That's why we replace it with `{" "}` - to indicate that there should be a space at the end. Let's take this code for example:
https://github.com/threshold-network/token-dashboard/blob/39a0be63ac70994e97118dec87a20884a4ed6b6e/src/pages/Staking/HowItWorks/StakingOverview/ThresholdStakesCard.tsx#L20-L28

Replacing both occurences of `{" "}` with normal space would not work, because those would be removed by our formatter. Replacing it with `&nbsp` is unnecessary, because it would not break those five words into a new line:
`The Threshold Staking Contract supports`
which could make it look worse on smaller resolutions.

There are some places in the project that could benefit from that replacement though. For example:
https://github.com/threshold-network/token-dashboard/blob/39a0be63ac70994e97118dec87a20884a4ed6b6e/src/pages/tBTC/Bridge/Unmint.tsx#L129-L137
Making `0.01 BTC` or even `min. 0.01 BTC` not breakable could be better for readability here. 

Those two examples should clarify when one or another should be used. If we need non-breaking space, then, by all means, use `&nbsp`. If not, and it's an end of the line, then use `{" "}`.

The `{" "}` is also widely used in [React repository](https://github.com/search?q=repo%3Afacebook%2Freact%20%7B%27%20%27%7D&type=code) and [React documntation](https://github.com/search?q=repo%3Areactjs%2Freact.dev%20%7B%27%20%27%7D&type=code).

As for readability I definitely don't agree here 😃 I wouldn't ever say that `Threshold&nbsp;` or `Threshold&nbsp;Network` is more readable than `Threshold{" "}` or `Threshold{" "}Network` 😛

2023-10-25 08:19 UTC, michalsmiarowski commented on src/components/StakingTimeline/index.tsx
> +          Staking Provider, here is &nbsp;
Described my point of view in https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1371342686

2023-10-25 08:19 UTC, michalsmiarowski commented on src/components/StakingTimeline/index.tsx
> +          <Link to={APPLICATION_DOCS_URL}>here</Link> or contact a &nbsp;
Described my point of view in https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1371342686

2023-10-25 08:19 UTC, michalsmiarowski commented on src/components/Link/SharedLinks.tsx
> +        Read the&nbsp;
Described my point of view in https://github.com/threshold-network/token-dashboard/pull/632#discussion_r1371342686

2023-10-25 08:22 UTC, michalsmiarowski commented on src/components/StakingTimeline/index.tsx
> +          &nbsp;
> Reverted changes commit: [faedc85](https://github.com/threshold-network/token-dashboard/commit/faedc85ca0a233796a033f32a8eb86d614bd71af)

Small correction: 3f54fc9115a1a1ca68a8238e69eb98c376ac4d6e <- this is the right commit

2023-10-27 10:17 UTC, michalsmiarowski commented on src/components/Modal/StakingChecklistModal/index.tsx
> +          </BodyLg>
I see. Thanks, that's a great explanation 🔥

2023-10-27 10:54 UTC, michalsmiarowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
Hmmm, but in my case we are wrapping up a text (not element) with an element for styling, and then wrapping it with another element (`<FlowStep>`) component to add things necessary for FlowStep (for example divider, arrow or whatever we need there).

In the designs it is specified as `BodySm`: 
<img width="114" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/a7bbfae6-ea46-4509-b588-60acc480df9b">
It adds additional styles here, not only fontSize, but for example color is different too.

See the difference here:
<img width="492" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/f36cb1af-0c45-4042-8a03-30d03020843f">
The description from step one has different color than from the step 2.

We don't want to use chakra atomic style props here, because if we decide to change the color, size or anything else for `BodySm` component we would want to make this change only in [BodySm component](https://github.com/threshold-network/components/blob/main/src/components/Typography/index.tsx#L108-L119) and expect to see the changes across the whole app. In your case we would want to also look for occurences where we decided to use atomic chakra props instead our `BodySm` component and change the props there.

My proposition is to implement the children text, like this:
```
<FlowStep
  size="sm"
  title="Stake Tokens"
  preTitle="Step 1"
  status={statuses[0] ?? FlowStepStatus.active}
  isDescriptionArrowHidden
>
  <BodySm>
    Enter the Provider, Beneficiary, and Authorizer addresses. These
    will be automatically set to your wallet address. If you want to use
    a Staking Provider, here is{" "}
    <Link to={STAKING_PROVIDER_URL}>a list</Link>.
  </BodySm>
</FlowStep>
```

What do you think?

2023-10-30 10:56 UTC, kpyszkowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
Done, ref commit: [1a41547](https://github.com/threshold-network/token-dashboard/pull/632/commits/1a41547752c17b22c23686ef30c38e3b0f3ea511)

2023-10-30 10:59 UTC, kpyszkowski commented on src/components/StakingTimeline/index.tsx
> +          fontSize="sm"
Additional commit: d4bb13b3c76828437b5adb09e9260890fd2a3e23

2023-10-30 11:15 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-10-30 11:15 UTC, merged