Update contract for AuthorizationIncreased event
threshold-network/token-dashboard pull request #636
Opened 2023-10-03 14:48 UTC by kpyszkowski

Replaced contract-providing hook (useStakingAppContract to useTStakingContract).

2023-10-03 14:51 UTC, kpyszkowski commented
@michalsmiarowski please let me know if we should update contracts for remaining authorization-related events

2023-10-05 10:40 UTC, michalsmiarowski requested changes
Left some comments to look at down below 👇 

Please also test it out and see if the data returned from events after you increase the authorization is similar to the data returned from the events after your changes 😉

2023-10-05 10:40 UTC, michalsmiarowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
> +  const contract = useTStakingContract()
Since we remove the `appName` here then I think we should also remove `appName` from the arugments of `useSubscribeToAuthorizationIncreasedEvent` hook. The `appName` that is needed for dispatching the `authorizationIncreased` below should be extracted from the event here:

https://github.com/threshold-network/token-dashboard/blob/89da14d7b6faee081498f88ddd721f129721ee89/src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts#L19

2023-10-05 10:40 UTC, michalsmiarowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
We pass different arguments to `TokenStaking` event comparing to the event in the app contract:

Token Staking event:
https://github.com/threshold-network/solidity-contracts/blob/47268908a1aa92ab215b76e5f26730519643b663/contracts/staking/TokenStaking.sol#L130-L134

App event (in this case it's random beacon):
https://github.com/keep-network/keep-core/blob/742e3739a87852e6bb76e1b042909d927150a42e/solidity/random-beacon/contracts/RandomBeacon.sol#L316-L321

Those changes should be reflected here:
https://github.com/threshold-network/token-dashboard/blob/89da14d7b6faee081498f88ddd721f129721ee89/src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts#L19

2023-10-05 10:40 UTC, michalsmiarowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
>  export const useSubscribeToAuthorizationIncreasedEvent = (
If you apply the changes that I've mentioned above then you should aldo remove one of the hook call in `App.tsx`:

https://github.com/threshold-network/token-dashboard/blob/89da14d7b6faee081498f88ddd721f129721ee89/src/App.tsx#L71-L72

2023-10-05 15:51 UTC, kpyszkowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
>  export const useSubscribeToAuthorizationIncreasedEvent = (
done

2023-10-05 15:54 UTC, kpyszkowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
i don't understand what do you mean
i suppose there is a difference between `operator` and `application`?

2023-10-06 08:56 UTC, michalsmiarowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
Yes, those are two different things. `operator` is the address, related to the application (random beacon or tbtc), that you can map to your stake's staking provider address. `application` is the address of the application contract (random beacon or tbtc) on the chain. In the actual code we don't use `operator` address anywhere, but we need the `application` address to get the application name and pass it to `authorizationIncreased` action few lines below.

You just have to change `operator` to `application` here and change that address to an app name using `stakingAppAddressToName` function.

2023-10-06 09:05 UTC, kpyszkowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
done 🙇🏼‍♂️

2023-10-09 10:02 UTC, michalsmiarowski requested changes
Works good, but left some comments down below with the proposition for refactor

2023-10-09 10:02 UTC, michalsmiarowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
> +}
This works good, but I think we can refactor it and put it inside [getStakingAppLabel.ts](https://github.com/threshold-network/token-dashboard/blob/main/src/utils/getStakingAppLabel.ts).

First of all it would be good to refactor whole `getStakingAppLabel.ts` file as it seems the function names there are a little confusing. We have to distinguish the staking app name from the staking app label. Staking app name is the name of the application that we use in our redux store to get the data ("randomBeacon", "tbtc"). Staking app label is the label for a given application that we use on front-end ("Random Beacon", 'tBTC").

My proposition for refactoring:
- `stakingAppAddressToName` should return app name instead of the label. Let's also rename it to `stakingAppAddressToAppName`
- `getStakingAppNameFromAddress` should also return the app name instead of the label and it should use the name returned from `stakingAppAddressToAppName` function. The `getStakingAppNameFromAddress` will be the function that you will use in `useSubscribeToAuthorizationIncreasedEvent` event. I think we should also rename it to `getStakingAppLabelFromAppAddress`.
- create a new function `getStakingAppLabelFromAppAddress` that will return either staking label from `getStakingAppLabelFromAppAddress` function or just "App" string
- rename `getSakingAppLabel` to `getStakingAppLabelFromAppName` function

In a separate commit you could also write some tests for that and put them in `stc/utils/__tests__`.

2023-10-09 13:18 UTC, kpyszkowski commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
> +}
done

2023-10-10 07:38 UTC, cygnusv reviewed
Great seeing this fix. Thanks, friends.

2023-10-10 07:38 UTC, cygnusv commented on src/utils/getStakingAppLabel.ts
> +  [threshold.multiAppStaking.randomBeacon.address]: "randomBeacon",
@theref 👀 🌮

2023-10-10 07:38 UTC, cygnusv commented on src/hooks/staking-applications/useSubscribeToAuthorizationIncreasedEvent.ts
> +  const contract = useTStakingContract()
yay!

2023-10-12 07:36 UTC, michalsmiarowski requested changes
Looking good. Added just few more comments here

2023-10-12 07:36 UTC, michalsmiarowski commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +    const resultTbtcName = getStakingAppNameFromAppAddress(tbtcAddress)
Let's also write a test to cover the case when you pass an address that is different than `tbtcAddress` and `rbAddress`

2023-10-12 07:36 UTC, michalsmiarowski commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +const MOCK_APP_NAMES: StakingAppName[] = ["tbtc", "randomBeacon"]
Let's rename those mock variable to camelCase

2023-10-12 09:33 UTC, kpyszkowski commented on src/utils/getStakingAppLabel.ts
> +  return stakingAppNameToAppLabel[stakingAppName] || "App"
correct, removed

2023-10-12 09:33 UTC, kpyszkowski commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +  const [tbtcName, rbName] = MOCK_APP_NAMES
updated 🙇🏼

2023-10-12 09:34 UTC, kpyszkowski commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +  const rbAddress = MOCK_ADDRESSES[rbName]
updated 🙇🏼

2023-10-12 09:34 UTC, kpyszkowski commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +const MOCK_APP_NAMES: StakingAppName[] = ["tbtc", "randomBeacon"]
updated 🙇🏼

2023-10-12 09:56 UTC, kpyszkowski commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +    const resultRbLabel = getStakingAppLabelFromAppAddress(rbAddress)
added

2023-10-12 10:02 UTC, kpyszkowski commented on src/utils/__tests__/getStakingAppLabel.test.ts
> +    const resultTbtcName = getStakingAppNameFromAppAddress(tbtcAddress)
since this fallback has been removed, such test seems to be redundant
I moved fallback value to the `getStakingAppLabelFromAppAddress` function level

2023-10-17 14:04 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-10-17 14:20 UTC, merged