Improve staking form user experience
threshold-network/token-dashboard pull request #643
Opened 2023-10-05 10:21 UTC by kpyszkowski

Ref: https://github.com/threshold-network/token-dashboard/issues/634

Added validation if user wallet is empty, simplified and made validation error messages more descriptive, improved readability of validation function, disabled form if wallet is not connected.

2023-10-18 08:08 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge

2023-10-18 08:08 UTC, michalsmiarowski commented on src/utils/forms.ts
>        : options.greaterThanValidationMsg
I think we can simplify this condition. If you agree with renaming types in <this comment> (TODO: I should've put a link to my comment there. I'm sorry if I didn't 😬 ), then I propose the solution below:

```
  if (!isMinimumValueFulfilled) {
    return getAmountInRangeValidationMessage(
      options.greaterThanValidationMsg,
      minValue
    )
  }
  if (isBalanceInsufficient) {
    return options.insufficientBalanceMsg
  }

  if (isMaximumValueExceeded) {
    return getAmountInRangeValidationMessage(
      options.lessThanValidationMsg,
      maxValue
    )
  }
```

The condition should work exactly the same (but feel free to test it out). We first check if the minimum value is exceeded. If not then there is no need to check the other condition and we can return the validation message. Then we should check if the user balance is 

`getAmountInRangeValidationMessage` would be a new function in the same file just above this function:
```
const getAmountInRangeValidationMessage = (
  validationMessage: AmountValidationMsg,
  value: string
) => {
  return typeof validationMessage === "function"
    ? validationMessage(value)
    : validationMessage
}
```

2023-10-23 07:48 UTC, kpyszkowski commented on src/pages/Staking/NewStakeCard.tsx
> +        isDisabled={!isWalletConnected}
Are you sure? It's not disabled for me. That's what the `shouldDisableButton` prop is for. I've only disabled the input.
<img width="616" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/11503879/9a721e40-3b65-4d3e-bee7-e8322b32fbc5">

2023-10-23 07:54 UTC, kpyszkowski commented on src/pages/Staking/NewStakeCard.tsx
> +        shouldDisableButton={false}
It actually changes. I've introduced this prop to keep the initial behavior (as it was before my changes, that's why it defaults to `true`). As you can see in [`TokenAmountFormBase` component](https://github.com/threshold-network/token-dashboard/pull/643/files#diff-ef626b3cf180c264556c01e935798ace3e685fbe953e893a016da23325097a7dR84) it conditonally sets `isDisabled` prop value of the submit button.

2023-10-23 08:15 UTC, kpyszkowski commented on src/utils/forms.ts
>  }
I'd like to change the "msg" into "message". A few more letters but huge improvement for readability. I don't like using abbreviations unless they are mandatory or undoubtedly well known.

About the `ValidationMsg` - it's not a big deal if its used locally scoped (not exported elsewhere). However it's a good point to rename it as well. I've introduced these changes to the options type/variable as well since it shares the same naming convention.

2023-10-23 09:06 UTC, kpyszkowski commented on src/utils/forms.ts
>        : options.greaterThanValidationMsg
Great, thanks for proposing solution. Applied changes.

2023-10-23 09:12 UTC, kpyszkowski commented on src/utils/forms.ts
> +  const isValueMissing = !value
Agree 🙇
Commit: ec07679ad45778d0453f06058af6d1a1ed4f63e2

2023-10-23 09:13 UTC, kpyszkowski commented on src/utils/forms.ts
>        : options.greaterThanValidationMsg
Commit: 9ad18d04a46162e7e911d725ef7fc3376e17177d

2023-11-21 15:10 UTC, michalsmiarowski commented on src/pages/Staking/NewStakeCard.tsx
> +        isDisabled={!isWalletConnected}
Ah, you are right, my bad. It works properly. I might have removed one of the new properties (either `shouldDisableButton` or `isDisabled`) to test things out and it behaves in such way 😅

2023-11-21 15:45 UTC, michalsmiarowski commented on src/components/Forms/TokenAmountForm.tsx
> +  shouldDisableButton = true,
The idea behind this property is great, but I think the property itself is too confusing, because when i set it to true my expectation would be that the button is disabled no matter what, when in this case it also relies on `isDisabled` property.

I would propose those changes:
1. Remove ` shouldDisableButton` prop completely
2. Refactor `SubmitTxButton` from this:
https://github.com/threshold-network/token-dashboard/blob/ec07679ad45778d0453f06058af6d1a1ed4f63e2/src/components/SubmitTxButton.tsx#L28-L38

to this:

```
  return (
    <Button
      mt={6}
      isFullWidth
      onClick={() => openModal(ModalType.SelectWallet)}
      {...buttonProps}
      type="button"
      isDisabled={false}
    >
      Connect Wallet
    </Button>
  )
```

It just set `isDisabled` property to false and overrides the `isDisabled` property from `...buttonProps`. I think in this case we don't want to have `Connect wallet` button disabled in any case, because if the wallet is connected, then the proper button will be returned, that actually will use `isDisblaed` property from `...buttonProps`.

3. Remove `shouldDisableButton` from here:

https://github.com/threshold-network/token-dashboard/blob/ec07679ad45778d0453f06058af6d1a1ed4f63e2/src/pages/Staking/NewStakeCard.tsx#L44-L45

But keep the `isDisabled={!isWalletConnected}` line. This should disable the form when the wallet is connected, but thanks to point 2, the ConnectButton will be active.

2023-11-21 15:57 UTC, michalsmiarowski commented on src/pages/Staking/NewStakeCard.tsx
> +        shouldDisableButton={false}
I might have tested it wrongly. Anyway I think it would be best to remove that property - see https://github.com/threshold-network/token-dashboard/pull/643#discussion_r1400800495 for more details.

2023-11-21 17:24 UTC, michalsmiarowski commented on src/pages/Staking/NewStakeCard.tsx
> +  const { active: isWalletConnected } = useWeb3React()
Fixed in ed3ae670abc6efd3a4090535432f8d3debeb2cc5

2023-11-21 17:24 UTC, michalsmiarowski commented on src/components/Forms/TokenAmountForm.tsx
> +  shouldDisableButton = true,
Fixed in bb143c48034b30f9fae4db7d5934b8a4dddee857

2023-11-21 17:36 UTC, michalsmiarowski approved these changes
LGTM 🔥

2023-11-21 17:39 UTC, merged