tBTC minting redesign - Phase I - part 1/4
threshold-network/token-dashboard pull request #651
Opened 2023-10-24 08:48 UTC by kpyszkowski

Ref: https://github.com/threshold-network/token-dashboard/issues/590

I've accomplished the first part of ongoing changes in Phase I. The current progress status and PR scope are presented in this [objectives checklist](https://github.com/threshold-network/token-dashboard/issues/590#issuecomment-1755270349).
I've also left some comments on Figma to inform and explain about the unapplied changes I will implement in future parts/phases.

2023-11-13 16:33 UTC, mhluongo commented
@michalsmiarowski can we get a review here?

2023-12-04 13:11 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/InitiateMinting.tsx
> +        <BodyLg>
Let's add some margin between those two

2023-12-04 13:15 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/MakeDeposit.tsx
> +      <Stack spacing={4} mt="5" mb="16">
Do we need that much margin at the bottom? The `BridgeContract` link seems to be closer to the content in the deisngs than in the implementation.

2023-12-04 13:20 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +      }}
Non-blocking but good to have:

Most of the syles here (if not all of them) can be applied using [chakra's style props](https://v1.chakra-ui.com/docs/styled-system/features/style-props) instead of [`sx` property](https://v1.chakra-ui.com/docs/styled-system/features/the-sx-prop#use-cases).

2023-12-04 13:21 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +      >
Same as above

2023-12-04 13:21 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +      <LabelSm sx={{ lineHeight: "6", pb: isActive ? "3" : "0" }}>
And same as above.

2023-12-04 13:23 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +          Provide an ETH address and a BTC Return address to generate an unique
We should also change the label for the BTC Recovery Address in ProvideData form, so that it's synced with the `MintingTImeline`.

2023-12-04 13:26 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +      <UnorderedList ml="-2.5" listStyleType="none">
The list below has a clear order so I think we should use `OrderedList`.

Do we actually have to remove `Steps` from here? The `Steps` component use `OrderedList` inside it.

2023-12-04 15:26 UTC, michalsmiarowski requested changes
And some more comments down below 😉

2023-12-06 20:02 UTC, kpyszkowski commented on src/utils/setTimeout.ts
> +}
Generally speaking `setTimeout` can block event loop when something time consuming is happening on the execution thread. `requestAnimationFrame` when is used with Animation API ensures smooth, 60 fps of performant animations but also can be used to mimic `setTimeout` in a more performant way.
Some reading if you are interested: https://freedium.cfd/https://javascript.plainenglish.io/better-understanding-of-timers-in-javascript-settimeout-vs-requestanimationframe-bf7f99b9ff9b

I will remove it alongside with `useToast` hook if it becomes unnecessary.

2023-12-06 20:02 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/index.tsx
> -        <TbtcBalanceCard gridArea="balance-card" mb="5" />
Brought back, ref commit: edce2a85

2023-12-06 20:02 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Minting/ProvideData.tsx
> +  const onSubmit = useCallback(
Yup, we don't have to redefine the callback on every rerender. It uses memoized value unless the checkbox value is updated.

2023-12-06 20:02 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +          Provide an ETH address and a BTC Return address to generate an unique
Ref commit: 16ef5a78

2023-12-06 20:02 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +      <LabelSm sx={{ lineHeight: "6", pb: isActive ? "3" : "0" }}>
Ref commit: ccf10798

2023-12-06 20:02 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +      >
As I said it's a matter of preference. In this case I don't use any selectors so I applied styles with style props.
Ref commit: ccf10798

2023-12-06 20:04 UTC, kpyszkowski commented on src/components/Toast/Toast.tsx
> +const Toast = (props: AlertProps) => {
That's the price of tech debt :D
With v2 of Chakra I would use standalone toasts but with v1 i had to implement it myself.
That's a good point to try Alerts instead of self made `useToast` hook. I will give it try. 

I wouldn't like to create another "alert-ish" component. In my opinion it also hits the idea of components where you define a component for one specific use case. `AccountSuccessAlert`, `WalletInitializeAlert`, `WalletRejectedAlert` and a few more has exact the same structure and differ in content, icon and color which could be defined with props.

2023-12-06 20:04 UTC, kpyszkowski commented on src/components/DurationWidget/DurationWidget.tsx
> +  const durationPrefix = Number.isInteger(duration) ? "~" : ""
Ref commit: 826eacfa

2023-12-06 20:04 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Minting/MakeDeposit.tsx
> +      />
If you name component the way you requested (prefixed by 'Mint') you indicate that the component is limited to be used in correlation with minting only. 
That's a good point to remove the confirmation calculations from the component itself and keep it in presentiontal role only but that way I would revert the name change. Components are reusable by definition, non-reusable component is not a component at all.

About component API - array of objects with strongly typed structure is not a dealbreaker, especially if you are using TypeScript. It's crucial to find a proper balance between reusability and overengineering. The problem is when props are eg. polymorphic or deeply nested with unspecified structure which can lead to misunderstandings when consuming component. With type safety and documentation (which I should add :D) it's not a big deal. TypeScript gives much more opportunities, so why don't use it? If it was JavaScript I wouldn't go for it.

My suggestion is:
1. Revert name change of components.
2. Remove duration/confirmation calculations from components so its roles will be strictly presentational (it gets data, and displays data).
3. Calculate duration and/or confirmations one step before the render of component and pass it as props as you suggested.
4. Add JSDoc documentation for component.

2023-12-06 20:04 UTC, kpyszkowski commented on src/components/DurationWidget/DurationWidget.tsx
Same as above, ref commit: 8f7468f1

2023-12-06 20:04 UTC, kpyszkowski commented on src/components/DurationWidget/DurationWidget.types.ts
> +}
Same as above, ref commit: 8f7468f1

2023-12-06 20:06 UTC, kpyszkowski commented on src/components/DurationTiers/DurationTiers.types.ts
> +}
Exactly, that's why I moved them to separate file. Also that's how there are files with hundreds of lines in a project.
It's pointless to reorganize the whole project but I'd highly recommend to stop propagating the same mistakes.

2023-12-06 20:06 UTC, kpyszkowski commented on src/components/DurationTiers/DurationTiers.tsx
> +function DurationTiers(props: DurationTiersProps) {
Ref commit: 5d36e5fc

2023-12-06 20:06 UTC, kpyszkowski commented on src/components/DurationTiers/DurationTiers.tsx
> +          amount + (rangeOperator.includes("greater") ? 0.01 : -0.01)
Left comments in code
Ref commit: 4cb092e9 & 52e291fb

2023-12-06 20:07 UTC, kpyszkowski commented on src/utils/tBTC.ts
> +}
Ref commit: 6b4bafb4

2023-12-06 20:07 UTC, kpyszkowski commented on src/utils/tBTC.ts
> +}
Ref commit: 25338022

2023-12-07 11:20 UTC, kpyszkowski commented on src/components/Toast/Toast.tsx
> +const Toast = (props: AlertProps) => {
Okay, I gotta admit - the `useToast` was a vast presentation of overengineering in this case XD
I removed it, rendered `Toast` component itself and refactored it's functionality to be dismissable if desired.
Ref commit: 7760b195

2023-12-08 13:18 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/MintingTimeline.tsx
> +      }}
It is stated [that `sx` property is considered an "escape hatch"](https://v1.chakra-ui.com/docs/styled-system/features/the-sx-prop#use-cases) which I understand it as use only when it's needed. We usually have it that way across the app too, so we should stick to so that the codebase is consistent. We should only use it for more complex CSS selectors, exactly as you did in  ccf107981cea0a596d5891f1c969b0b87404b788 👍

2023-12-08 13:48 UTC, michalsmiarowski commented on src/components/DurationTiers/DurationTiers.types.ts
> +}
I wouldn't call it mistake, but rather a preference. I would prefer to keep the code consistent across the app.

2023-12-09 13:17 UTC, kpyszkowski commented on src/components/MintDurationWidget/MintDurationWidget.tsx
> +  getThresholdLib().tbtc
Ref commit: d196e23e

2023-12-09 13:17 UTC, kpyszkowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +  getThresholdLib().tbtc
Ref commit: d196e23e

2023-12-09 13:18 UTC, kpyszkowski commented on src/components/DurationTiers/DurationTiers.types.ts
> +}
As discussed, removed the file. Ref commit: cbb00fdc, 050f1c01

2023-12-09 13:20 UTC, kpyszkowski commented on src/components/DurationTiers/DurationTiers.tsx
> +function DurationTiers(props: DurationTiersProps) {
<img width="268" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/11503879/fa0ca45b-29c0-4f8c-b8a1-911b9192646f">

2023-12-11 09:52 UTC, michalsmiarowski commented on src/components/DurationTiers/DurationTiers.tsx
I see your point and I'm ok with both approaches here as long as we use `index` file inside our component folders and export everything there. Don't have a strong opinion here which is better, I think for small components it might be not worth it to separate it to different file. As an example, this approach is used also [in react codebase](https://github.com/facebook/react/blob/main/fixtures/dom/src/components/fixtures/suspense/index.js), and they separate it to different files (while still exporting all in `index` file) if it's necessary for bigger components.

Like I said, I'm ok with keeping it in `DurationTiers.tsx` file too like it is now.

2023-12-11 09:57 UTC, michalsmiarowski requested changes

2023-12-11 09:57 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Minting/ProvideData.tsx
> -    openModal(ModalType.TbtcRecoveryJson, {
Can we also remove that modal? It is not used anywhere now.

2023-12-11 10:03 UTC, michalsmiarowski commented
Non-blocking:

@kpyszkowski We could also add a `Resume Deposit` to the navigation as it is in the [designs](https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-dApp?type=design&node-id=9741-32561&mode=design&t=T5q6FB1j5N2Idrds-0). It shouldn't be much of a work I believe, but if it is then let's ditch it for now. I'm also not sure if it's related to phase I or II, but looks like we could do it now because we already have resume page at `/mint/continue`.

2023-12-11 12:29 UTC, kpyszkowski commented
Ref: https://github.com/threshold-network/token-dashboard/pull/651#issuecomment-1849720646
Added "Resume Deposit" page. Ref commit: 88caaf04

2023-12-11 12:29 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Minting/ProvideData.tsx
> -    openModal(ModalType.TbtcRecoveryJson, {
Ref commit: 7d4c5153

2023-12-11 12:29 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Minting/ProvideData.tsx
> +        downloadFile(JSON.stringify(finalData), fileName, "text/json")
Ref commit: 53bfca0e

2023-12-11 12:29 UTC, kpyszkowski commented on src/components/MintDurationWidget/MintDurationWidget.tsx
> +export interface MintDurationWidgetProps extends BoxProps {
Ref commit: fca3a60b

2023-12-11 12:29 UTC, kpyszkowski commented on .env
Ref commit: f970330f

2023-12-12 10:25 UTC, michalsmiarowski requested changes

2023-12-12 10:25 UTC, michalsmiarowski commented on src/pages/tBTC/index.tsx
> +  pages: [HowItWorksPage, TBTCBridge, ExplorerPage, ResumeDepositPage],
ResumeDeposit was used as a subpage of Mint page, which is a subpage ot TBTCBridge. Placing it like that does not show the full layout of the mint page. It's little problematic, but we can work that out. I propose this solution:

1. Change `ResumeDepositPage.route` to:
```
ResumeDepositPage.route = {
  title: "Resume Deposit",
  path: "resume-deposit",
  index: false,
  isPageEnabled: true,
}
```

The reason is that after your changes, the link to resume deposit is now `/tbtc/continue` instead of `/tbtc/mint/continue` and it looks bad becuase it doesn't say what we actually continuing. I propose to change it to `tbtc/resume-deposit`.

2. Wrap `ResumeDepositPage` component with a `<Card>` component and detect if the user is active:
```
export const ResumeDepositPage: PageComponent = () => {
  (...)
  const { account, active } = useWeb3React()
  (...)
  return (
    <Card maxW="640px" m={"0 auto"}>
      {active ? (
        <>
          <BridgeProcessCardTitle /> // notice that we also remove properties here, to remove back arrow
          <BodyLg>
            <Box as="span" fontWeight="600" color="brand.500">
              Resume Minting
            </Box>{" "}
            - Upload .JSON file
          </BodyLg>
          <BodyMd mt="3" mb="6">
            To resume your minting you need to upload your .JSON file and sign
            the Minting Initiation transaction triggered in the dApp.
          </BodyMd>
          <ResumeDepositFormik address={account!} onSubmitForm={onSubmit} />
          <Box as="p" textAlign="center" mt="10">
            <BridgeContractLink />
          </Box>
        </>
      ) : (
        <BridgeProcessEmptyState title="Want to resume deposit?" />
      )}
    </Card>
  )
}
```

Result:
<img width="1103" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/1ffcf0e4-6643-4989-95d7-507f697321b0">

Pinging also @SorinQ here, so that you know what it will look like now.

2023-12-12 10:25 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
>  export const ResumeDepositPage: PageComponent = () => {
The resume deposit page does not work as expected. It throws error after uploading a file. The reasons is the useEffect below, i think it does not work as expected and it does not change `mintingStep` from `InitiateMinting` to `ProvideData` fast enough which result in executing this piece of code in `InitiateMinting`:
https://github.com/threshold-network/token-dashboard/blob/88caaf04d563503a5aa6e408ea923a5dbada352d/src/pages/tBTC/Bridge/Minting/InitiateMinting.tsx#L33-L45

As a quick workaround I propose to just set that step manually before navigating to `/tBTC/mint` in `navigatetoMintPage` function:
```
  const navigateToMintPage = () => {
    updateState("mintingStep", MintingStep.ProvideData)
    navigate("/tBTC/mint")
  }
  ```

2023-12-12 10:37 UTC, kpyszkowski commented on src/pages/tBTC/index.tsx
> +  pages: [HowItWorksPage, TBTCBridge, ExplorerPage, ResumeDepositPage],
Ref commit: b4a54658

2023-12-12 10:37 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
>  export const ResumeDepositPage: PageComponent = () => {
Applied workaround here.
Ref commit: b4a54658

2023-12-12 10:41 UTC, michalsmiarowski requested changes
Probably one of the last comments:

2023-12-12 10:41 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +          here, to remove back arrow
Remove this line 😜

2023-12-12 10:43 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +          here, to remove back arrow
XD
Ref commit: 73aabfbd

2023-12-12 11:27 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Mint.tsx
> +            <DurationWidget amount={["less", 1, "BTC"]} /> // TODO: Read prop values from the store
Ref commit: 075f94ae

2023-12-12 11:35 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Minting/MakeDeposit.tsx
> +      <Stack spacing={4} mt="5" mb="16">
Ref commit: 8d79591a

2023-12-12 11:52 UTC, michalsmiarowski requested changes

2023-12-12 11:52 UTC, michalsmiarowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +        )
I think it would be nice to distinguish the time between the number of confirmations a little bit more. RIght now it shows the same time for 3 confirmations and 6 confirmations, because we round the value to the nearest integer:
<img width="562" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/412dfa35-fa2a-4340-8070-6c4d3e64875a">


We could round the value to half hours to distinguish the duration of mint more between 3 and 6 confirmations:
```
const durationInMinutes =
          getDurationByNumberOfConfirmations(confirmations)
        // Round up the minutes to the nearest half-hour
        const hours = (Math.round(durationInMinutes / 30) * 30) / 60
        const formattedAmount = amount.toFixed(2)
```

Result:
<img width="563" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/99c7779a-bce0-4577-9092-b6f9f106a656">

2023-12-12 11:52 UTC, michalsmiarowski commented on src/components/MintDurationWidget/MintDurationWidget.tsx
> +  )
Same as above if you agree with it.

2023-12-12 11:52 UTC, michalsmiarowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +        // when comparing BigNumber values.
Comment exceeds 80 characters margin

```suggestion
        // The amount is corrected by adding or subtracting 0.01 to the given
        // amount depending on the range operator. This is done to avoid
        // floating-point errors when comparing BigNumber values.
```

2023-12-12 11:52 UTC, michalsmiarowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +        // If the amount is already a safe integer, it is returned as is.
```suggestion
        // Only safe integers (not floating-point numbers) can be transformed to
        // BigNumber. Converting the given amount to a safe integer if it is not
        // already a safe integer. If the amount is already a safe integer, it
        // is returned as is.
```

2023-12-12 11:52 UTC, michalsmiarowski commented on src/components/MintDurationWidget/MintDurationWidget.tsx
> +  // when comparing BigNumber values.
```suggestion
  // The amount is corrected by adding or subtracting 0.01 to the given amount
  // depending on the range operator. This is done to avoid floating-point
  // errors  when comparing BigNumber values.
```

2023-12-12 11:52 UTC, michalsmiarowski commented on src/components/MintDurationWidget/MintDurationWidget.tsx
> +  // If the amount is already a safe integer, it is returned as is.
```suggestion
  // Only safe integers (not floating-point numbers) can be transformed to
  // BigNumber. Converting the given amount to a safe integer if it is not
  // already a safe integer. If the amount is already a safe integer, it is
  // returned as is.
```

2023-12-12 12:24 UTC, kpyszkowski commented on src/components/MintDurationWidget/MintDurationWidget.tsx
> +  // If the amount is already a safe integer, it is returned as is.
Ref commit: 7f8e2357

2023-12-12 12:24 UTC, kpyszkowski commented on src/components/MintDurationWidget/MintDurationWidget.tsx
> +  // when comparing BigNumber values.
Ref commit: 7f8e2357

2023-12-12 12:24 UTC, kpyszkowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +        // If the amount is already a safe integer, it is returned as is.
Ref commit: 7f8e2357

2023-12-12 12:24 UTC, kpyszkowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +        // when comparing BigNumber values.
Ref commit: 7f8e2357

2023-12-12 12:24 UTC, kpyszkowski commented on src/components/MintDurationWidget/MintDurationWidget.tsx
> +  )
Ref commit: f06041ce

2023-12-12 12:24 UTC, kpyszkowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +        )
Ref commit: f06041ce

2023-12-12 12:49 UTC, michalsmiarowski requested changes

2023-12-12 12:49 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Mint.tsx
> +          <MintDurationWidget amount={["less", utxo?.value || 0, "BTC"]} />
I think it should be "greaterOrEqual" for the value greater/equal to 1 BTC

2023-12-12 12:49 UTC, michalsmiarowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +          : Math.floor((correctedAmount as number) * 1e8)
After those changes:
https://github.com/threshold-network/token-dashboard/pull/651/commits/075f94ae7d60ea2afd21566f68cc18c6f1c28b30

we now pass the amount as satoshi already so we don't need to multiple it by `1e8` anymore. Right now, because of that, it gives wrong hour duration for amount that is less than 0.01 btc:
<img width="247" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/c89fae46-14ed-43c9-bf03-4a80c715e3fa">


Should be 1 hour (1 confirmation neede) but it returns 2 hours (6 confirmations needed)

2023-12-12 12:49 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/Mint.tsx
> +  ].includes(mintingStep)
Let's also add undefined here to not display the `MintDurationWidget` at the loading step:

![image](https://github.com/threshold-network/token-dashboard/assets/40306834/1b433e8b-a74a-4079-b345-6b5b5cdb1d74)


```suggestion
  const shouldRenderDurationWidget = ![
    MintingStep.ProvideData,
    MintingStep.Deposit,
    undefined,
  ].includes(mintingStep)
```

2023-12-12 13:02 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Mint.tsx
> +          <MintDurationWidget amount={["less", utxo?.value || 0, "BTC"]} />
Ref commit: 3b075624

2023-12-12 13:02 UTC, kpyszkowski commented on src/components/MintDurationTiers/MintDurationTiers.tsx
> +          : Math.floor((correctedAmount as number) * 1e8)
Ref commit: 3b075624

2023-12-12 13:02 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/Mint.tsx
> +  ].includes(mintingStep)
Ref commit: 3b075624

2023-12-12 13:58 UTC, michalsmiarowski requested changes

2023-12-12 13:58 UTC, michalsmiarowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +    updateState("mintingStep", MintingStep.ProvideData)
Let's actually change it to 

```
updateState("mintingStep",  undefined)
```

and move it to `onSubmit` function just above `setDepositDataInLocalStorage`:
https://github.com/threshold-network/token-dashboard/blob/888c17ae044cb5ecfe93dee5a9cda5ff717cf065/src/pages/tBTC/Bridge/ResumeDeposit.tsx#L57-L59

The reason is that after uploading a file and clicking `Resume` it navigates the user to Mint page and it shows the Provide Data step for 2 seconds (because we set the ProvideData) step above instead of loading state. Setting it to`undefined` just before setting the values in local storage and navigating to the mint page makes more sense.

2023-12-12 14:04 UTC, kpyszkowski commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +    updateState("mintingStep", MintingStep.ProvideData)
Ref commit: 1b6e033a

2023-12-12 14:16 UTC, michalsmiarowski approved these changes
LGTM

2023-12-12 14:29 UTC, merged