Draft: SDK 2.0.0 integration
threshold-network/token-dashboard pull request #654
Opened 2023-10-31 15:07 UTC by kpyszkowski

2023-11-15 16:49 UTC, michalsmiarowski requested changes
Left first round of review. More to come (probably)

2023-11-15 16:49 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    return this._bitcoinClient.getTransaction(Hex.from(transactionHash))
I think we should add await here since `getTransaction` return a Promise :thinking:

2023-11-16 14:48 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
> +  getTransactionConfirmations(transactionHashString: string): Promise<number>
Ref commit: 739dc6b8

2023-11-16 14:48 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
> +    const transactionHash = Hex.from(transactionHashString)
Ref commit: 8fc58d98

2023-11-16 14:49 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
> +    depositReceipt: HexOrString<DepositReceipt>
Ref commit: 6a440dbb

2023-11-16 14:49 UTC, kpyszkowski commented on src/threshold-ts/utils/bitcoin.ts
> +  return Hex.from(txHash).reverse().toString()
Ref commit: 1ebe83c0

2023-11-16 14:49 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
>     * @param transactionHash Hash of the transaction.
You must have made a mistake. The parameter of this method is not a type of `string`.

2023-11-16 14:49 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
> -
Ref commit: 690bf22c

2023-11-16 14:49 UTC, kpyszkowski commented on src/threshold-ts/utils/bitcoin.ts
> +  return isPublic
Ref commit: 6ebdc85d

2023-11-16 14:49 UTC, kpyszkowski commented on src/threshold-ts/utils/bitcoin.ts
>  export const isPayToScriptHashTypeAddress = (address: string): boolean => {
🙌🏼

2023-11-16 14:49 UTC, kpyszkowski commented on src/utils/getThresholdLib.ts
> +    getEnvVariable(EnvVariable.USE_GOERLI_DEVELOPMENT_CONTRACTS) === "true"
Ref commit: da9d15e1

2023-11-16 14:49 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
> +    return this._bitcoinClient.getTransaction(Hex.from(transactionHash))
Not really, the `getTransaction` method returns a Promise and it's resolved asynchronously one level above - when calling `getBitcoinTransaction` just like [here](https://github.com/threshold-network/token-dashboard/blob/main/src/hooks/tbtc/useFindRedemptionInBitcoinTx.ts#L19-L21)

2023-11-17 12:16 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    depositReceipt: HexOrString<DepositReceipt>
Looks like it works now! Resolving the conversation

2023-11-17 12:17 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    return this._bitcoinClient.getTransaction(Hex.from(transactionHash))
Ahh, that's correct

2023-11-17 12:42 UTC, michalsmiarowski requested changes
Left some more comments to look at before the merge

2023-11-17 12:42 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +    const hasMockedBitcoinClient = clientFromConfig && !credentialsFromConfig
The bitcoin client should be mocked if we pass the client through the config regardless of whether we provide credentails or not. Having client in config means that the flag `MOCK_BITCOIN_CLIENT` is set to true, which means that the the client should be mocked adn we don't care if the user passes credentails or not.

If you want we can simplify it to:
```suggestion
    const hasMockedBitcoinClient = clientFromConfig 
```

But I would probably remove that variable and just use `clientFromConfig`.

2023-11-17 12:42 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +      )
We can actually remove that `bitcoinClient` and use `this.bitcoinClient`, which we initialized in the constructor already:

https://github.com/threshold-network/token-dashboard/blob/bbdc89047f2f32905cf35ccbb07ac414dc9b0ab2/src/threshold-ts/tbtc/index.ts#L453-L458

As you can see it's basically the same piece of code (+ additionally we pass `clientOption` there).

2023-11-17 12:42 UTC, michalsmiarowski commented on package.json
> +    "tbtc-sdk-v2": "npm:@keep-network/tbtc-v2.ts@2.3.0-dev.2",
Let's install the newest 2.3.0 version.

Besides that I was thinking that we could install it as `@keep-network/tbtc-v2.ts` package, and remove `tbtc-sdk-v2` completely. We also need to replace all imports from `tbtc-sdk-v2` to  `@keep-network/tbtc-v2.ts`.

Of course some of the imports will be underlined as red in `tbtc.test.ts` file, but it doesn't affect the dashbaord itself. We will address the tests in a separate PR anyway.

2023-11-17 12:50 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
>     * @param transactionHash Hash of the transaction.
Yup, I think it was my mistake. Sorry 🙏 😅

2023-11-17 12:54 UTC, michalsmiarowski commented on src/threshold-ts/utils/bitcoin.ts
>  export const isPayToScriptHashTypeAddress = (address: string): boolean => {
To be more clarified: By `let's do it in a separate PR` I meant that we could remove `bitcoin-address-validation` but that would require some testing and code tweaks, so it goes to a separate PR. We still should improve `isPayToScriptHashTypeAddress` so that it uses `BitcoinScriptUtils` (see my code above).

2023-11-17 13:09 UTC, michalsmiarowski requested changes
Left some docs improvements

2023-11-17 13:09 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +   */
```suggestion
 /**
   * Initiates a deposit object from DepositScriptParameters object. Most of the
   * parameters are passed as strings and converted to hexes inside the
   * function.
   * @param depositScriptParameters DepositScriptParameters object that contains
   * all the data related to the deposit we want to re-initiate.
   * @returns Deposit object
   */
```

2023-11-17 13:09 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
>     * Calculates the deposit address from the deposit script parameters
```suggestion
  /**
   * Calculates the deposit address from the deposit object stored in
   * this._deposit. Throws error if deposit object is not initiated.
```

2023-11-17 13:09 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
>     * @returns Transaction object.
```suggestion
   * @param transactionHash Hash of the transaction as a string.
   * @returns Bitcoin Transaction object.
```

2023-11-17 14:01 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
>     * @returns Transaction object.
Ref commit: 14a24b76

2023-11-17 14:02 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
>     * Calculates the deposit address from the deposit script parameters
Ref commit: 9ba5edff

2023-11-17 14:02 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
> +   */
Ref commit: aa0f672a

2023-11-17 14:02 UTC, kpyszkowski commented on package.json
> +    "tbtc-sdk-v2": "npm:@keep-network/tbtc-v2.ts@2.3.0-dev.2",
Ref commit: e83f2926

2023-11-17 14:02 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
> +      )
Ref commit: b338239f

2023-11-17 14:02 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
> +    const hasMockedBitcoinClient = clientFromConfig && !credentialsFromConfig
Ref commit: 23c8cb83

2023-11-17 14:03 UTC, kpyszkowski commented on src/threshold-ts/tbtc/index.ts
>     * @returns Transaction object.
Ref commit: 14a24b76

2023-11-17 15:36 UTC, kpyszkowski commented on yarn.lock
> +  integrity sha512-qU0FYH339pa7EY+q6R8lB/cHS8dzJScWR8uRW4aROW8f9QbGRmiXCy82xQxlNgnhtQNmTKP3kv+vubAxNELlxg==
Ref commit: fd430c8b

2023-11-17 16:35 UTC, michalsmiarowski requested changes

2023-11-17 16:35 UTC, michalsmiarowski commented on package.json
>      "@keep-network/tbtc-v2": "development",
Oh, and actually I think we can remove the `@keep-network/tbtc-v2` lib. Sorry i didn't mention it earlier but I forgot that we don't need it anymore and that was one of the main points of this migration 😅

2023-11-20 09:27 UTC, lukasz-zimnoch commented on .env
> +REACT_APP_USE_GOERLI_DEVELOPMENT_CONTRACTS=false
Let's call this `DAPP_DEVELOPMENT_TESTNET_CONTRACTS`. We are soon migrating from Goerli to Sepolia. In the future, we may need to migrate from Sepolia to Holesky. Do you want to upgrade all this naming every time we switch our testnet chain? 😅 

Also, this is the name used in the CI workflow.

2023-11-20 09:28 UTC, lukasz-zimnoch commented on package.json
>      "@keep-network/tbtc-v2": "development",
Can we also remove `@keep-network/ecdsa`?

Secondly, we need to update CI accordingly:

1. Remove `@keep-network/tbtc-v2.ts`, `@keep-network/tbtc-v2`, and `@keep-network/ecdsa` from here:  https://github.com/threshold-network/token-dashboard/blob/bbdc89047f2f32905cf35ccbb07ac414dc9b0ab2/.github/workflows/dashboard-ci.yml#L77
2. Do the same here (also clear the "Set packages versions" step accordingly): https://github.com/threshold-network/token-dashboard/blob/bbdc89047f2f32905cf35ccbb07ac414dc9b0ab2/.github/workflows/reusable-build-and-publish.yml#L154

BTW, doing point 2 will solve the observed CI job failure.

2023-11-20 09:28 UTC, lukasz-zimnoch commented on package.json
> +    "@keep-network/tbtc-v2.ts": "2.3.0",
Let's allow for minor versions upgrades:
```suggestion
    "@keep-network/tbtc-v2.ts": "^2.3.0",
```

2023-11-20 10:04 UTC, kpyszkowski commented on .env
> +REACT_APP_USE_GOERLI_DEVELOPMENT_CONTRACTS=false
Ref commit: 29853e3c

2023-11-20 10:04 UTC, kpyszkowski commented on package.json
> +    "@keep-network/tbtc-v2.ts": "2.3.0",
Ref commit: 29853e3c

2023-11-20 10:33 UTC, kpyszkowski commented on package.json
>      "@keep-network/tbtc-v2": "development",
Ref commit: 8b061f2a

2023-11-20 10:38 UTC, lukasz-zimnoch commented on src/threshold-ts/utils/contract.ts
> +  }
I think we should orient this switch around `chainId` to make it more readable and maintainable:
```
  switch (chainId.toString()) {
    case "1":
        return {
            "Bridge": BridgeArtifactMainnet,
            "TBTC:" TbtcTokenArtifactMainnet,
            "TBTCVault": TbtcVaultArtifactMainnet, 
        }[artifactName]
    case "5":
        return {
            "Bridge": shouldUseGoerliDevelopmentContracts ? BridgeArtifactDappDevelopmentGoerli : BridgeArtifactGoerli,
            "TBTC:" shouldUseGoerliDevelopmentContracts ? TbtcTokenArtifactDappDevelopmentGoerli : TbtcTokenArtifactGoerli,
            "TBTCVault": shouldUseGoerliDevelopmentContracts ? TbtcVaultArtifactDappDevelopmentGoerli : TbtcVaultArtifactGoerli, 
        }[artifactName]
    default:
      throw new Error("Can't get tbtc-v2 artifacts!")
  }
```

2023-11-20 10:38 UTC, lukasz-zimnoch commented on src/threshold-ts/utils/bitcoin.ts
> +import { Network, validate } from "bitcoin-address-validation"
Do we still need this?

2023-11-20 10:38 UTC, lukasz-zimnoch commented on src/utils/getThresholdLib.ts
> +  const useGoerliDevelopmentContractsFlag =
Remember that we are moving to Sepolia soon so I'd recommend something more generic, e.g.: `useDappDevelopmentTestnetContracts`. If this is problematic now, we can make that change later but I just wanted to flag the problem.

2023-11-20 10:38 UTC, lukasz-zimnoch commented on src/utils/getThresholdLib.ts
> +    shouldUseGoerliDevelopmentContracts:
Same problem with `Goerli` used as part of the name.

2023-11-20 10:45 UTC, lukasz-zimnoch commented on src/utils/getThresholdLib.ts
> +  const useGoerliDevelopmentContractsFlag =
Nevermind, I see you already addressed this 👌

2023-11-20 10:45 UTC, michalsmiarowski commented on src/threshold-ts/tbtc/index.ts
> +export type DepositScriptParameters = {
It's actually not the same type, because `DepositReceipt` uses `Hex` now for `blindingFactor`, `walletPublicKeyHash`, `refundPublicKeyHash` and `refundLocktime`, while our `DepositScriptParameters` type uses strings.

We decided that the Hex conversion should happen inside our threshold-ts lib just before calling the methods from SDK (if needed) and we should operate on string values (like we did with the old SDK) across the dApp, because we use those for json recovery file and for our redux store.Since the `threshold-ts` is our wrapper for our dApp, we've decided to create a new type (with the old name) for this.

2023-11-20 10:49 UTC, michalsmiarowski commented on src/threshold-ts/utils/bitcoin.ts
> +import { Network, validate } from "bitcoin-address-validation"
Yes, we've decided that this will be addressed in a separate PR to not prolong the merge of this one. See https://github.com/threshold-network/token-dashboard/pull/654#discussion_r1397256966

2023-11-20 12:18 UTC, lukasz-zimnoch commented on src/threshold-ts/tbtc/index.ts
> +export type DepositScriptParameters = {
Got it! It makes sense if we are considering `threshold-ts` to be an adapter layer between dApp and SDK. For the future, please consider using `Hex` everywhere as it greatly facilitates the work with hexadecimal values used across the SDK.

2023-11-20 16:09 UTC, kpyszkowski commented on src/threshold-ts/utils/contract.ts
> +  // TODO: Update this function with goerli development artifact.
correct 👍🏼 comment is already removed

2023-11-20 16:16 UTC, kpyszkowski commented on src/threshold-ts/utils/contract.ts
> +export const getGoerliDevelopmentContracts = (
Ref commit: ac61a427

2023-11-20 16:18 UTC, lukasz-zimnoch approved these changes

2023-11-20 16:20 UTC, lukasz-zimnoch commented
Amazing work @kpyszkowski @michalsmiarowski 🤌 Let's merge it!

2023-11-20 16:22 UTC, michalsmiarowski approved these changes

2023-11-20 16:22 UTC, merged