Ledger Live App [WiP]
threshold-network/token-dashboard pull request #655
Opened 2023-11-01 17:35 UTC by michalsmiarowski

2023-11-29 11:22 UTC, kkosiorowska requested changes
I haven't tested it yet.  But I had a quick look and left a few minor comments.

I wonder if you have noticed, but some applications remember the connected account. I think it would be good to do that as well.

**Current behaviour**

https://github.com/threshold-network/token-dashboard/assets/23117945/4f131fc9-f73a-4a82-8c6f-ee503491c022

**Good behaviour**

https://github.com/threshold-network/token-dashboard/assets/23117945/b5974ef0-89cc-4005-94a8-b7819b1d13fb

2023-12-06 10:46 UTC, r-czajkowski requested changes

2023-12-06 10:46 UTC, r-czajkowski commented on manifest-ledger-live-app.json
> +  "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAD40lEQVR4AayXAWRVYRTH32sBAGCEspHqBQEFAAEFAAYmElK1giIAaEstULYRUU1tFSAEJDDYaxsqGBS59pRZe+/ddzo/3zv83btdt3T47zvvnPP9v/Pd79
Can we get the icon from url? Eg. `https://dashboard.threshold.network/favicon-T.png` to get the img from `public` dir.

2023-12-06 10:46 UTC, r-czajkowski commented on manifest-ledger-live-app.json
> +  "permissions": [
I can't find it in the docs only in the code: https://github.com/LedgerHQ/wallet-api/blob/0bd66f57e23e0f5704e2b780bd8e6eae7b1eba25/apps/wallet-api-tools/manifest.json#L23-L40

2023-12-06 10:46 UTC, r-czajkowski commented on src/components/Navbar/index.tsx
> +  }, [ledgerLiveAccount])
```suggestion
  const ledgerLiveAccountAddress = ledgerLiveAccount.address
  
  useEffect(() => {
    if (ledgerLiveAccountAddress) {
      dispatch(walletConnected(ledgerLiveAccountAddress))
    }
  }, [ledgerLiveAccountAddress, dispatch])
```

2023-12-06 10:46 UTC, r-czajkowski commented on src/components/SubmitTxButton.tsx
> +  }
We do the same in the `src/components/Navbar/index.ts`. I would consider creating a new hook like `useConnectWallet` or `useRequestAccount` to hanlde this logic.

2023-12-08 11:19 UTC, michalsmiarowski commented on manifest-ledger-live-app.json
> +  "categories": ["buy"],
a65ca816d757c2667fbd98fa1a2ddbfe7e1ca2d7

2023-12-08 11:19 UTC, michalsmiarowski commented on manifest-ledger-live-app.json
> +  "branch": "main",
a65ca816d757c2667fbd98fa1a2ddbfe7e1ca2d7

2023-12-08 11:20 UTC, michalsmiarowski commented on src/App.tsx
> +  }
03fc8c455ff217d8d9adfd4d31532cb8e4bde001 - was that what you mean?

2023-12-08 11:21 UTC, michalsmiarowski commented on src/components/TokenBalance.tsx
> +  const shouldRenderTokenAmount = isActive
af42575cf15f249c43360df6587150ab34a3158f

2023-12-08 11:21 UTC, michalsmiarowski commented on src/contexts/TransportProvider.tsx
> +  // }
f65103a5d62ec581d15cee2df70f84358d7f82a5

2023-12-08 11:21 UTC, michalsmiarowski commented on manifest-ledger-live-app.json
> +  "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAD40lEQVR4AayXAWRVYRTH32sBAGCEspHqBQEFAAEFAAYmElK1giIAaEstULYRUU1tFSAEJDDYaxsqGBS59pRZe+/ddzo/3zv83btdt3T47zvvnPP9v/Pd79
1958cfa76029c02bef54196fb684d8c32e52d2dd

2023-12-08 11:21 UTC, michalsmiarowski commented on src/components/Navbar/index.tsx
> +  }, [ledgerLiveAccount])
683115e2bdf9e6f186f6ba07ad79b9e6d35b0655

2023-12-08 11:21 UTC, michalsmiarowski commented on src/components/SubmitTxButton.tsx
> +  }
84a6bf7613cf1bcd18ffd0c40fc2097dab54ec3d

2023-12-08 11:44 UTC, michalsmiarowski commented
> I haven't tested it yet. But I had a quick look and left a few minor comments.
> 
> I wonder if you have noticed, but some applications remember the connected account. I think it would be good to do that as well.
> 
> **Current behaviour**
> 
>  Screen.Recording.2023-11-29.at.12.07.37.mov 
> **Good behaviour**
> 
>  Screen.Recording.2023-11-29.at.12.18.20.mov

I believe this is how our dApp works right now on the website too. When you refresh the page you are not automatically connected to the wallet again. I don't remember why we've changed it, but I think there were some bugs that were happening and we implemented it as a workaround 🤔 

I think this could be a separate issue - to implement an automatic wallet connection with the previously used account once the page is refreshed @lukasz-zimnoch

2023-12-08 11:47 UTC, michalsmiarowski commented on manifest-ledger-live-app.json
> +  "homepageUrl": "http://localhost:3000?embed=true",
Changing the URL won't fire the embed flg unfortunately 😞 Can I ask where that screenshot comes from though? 😅  I didn't find any occurences of the website link in our tbtc section of the dApp.

2023-12-11 14:03 UTC, kkosiorowska commented on manifest-ledger-live-app.json
> +  "homepageUrl": "http://localhost:3000?embed=true",
Oh sorry I missed that message. You have to click the below icon.
<img width="1444" alt="Screenshot 2023-12-11 at 15 02 23" src="https://github.com/threshold-network/token-dashboard/assets/23117945/b7650d71-67ef-42bb-b5fa-a99be511a05a">

2023-12-11 15:16 UTC, kkosiorowska reviewed
Overall it looks good to me. ✨Only small non-blocking comments.

However, it would be good if @r-czajkowski also took a look at this solution to make sure that this PR doesn't break anything. He knows the app better.

2023-12-11 15:16 UTC, kkosiorowska commented on src/contexts/TokenContext.tsx
> +  const { chainId } = useWeb3React()
Non-blocking comment
`chainId` can be also take from `useIsActive`

2023-12-12 09:34 UTC, r-czajkowski submitted a review, later dismissed

2023-12-13 14:58 UTC, michalsmiarowski commented on manifest-ledger-live-app.json
> +  "homepageUrl": "http://localhost:3000?embed=true",
Thanks! Great catch! Fixed it here: 790c240c59bd3ba3422e6423381083d17862e070

2023-12-13 14:59 UTC, michalsmiarowski commented on src/App.tsx
> +  }
I'm unresolving the conversation because I've acually changed it a little. See 6903e9030aa8bd9db36369c3a503f47a1bbe51d9

2023-12-13 14:59 UTC, michalsmiarowski commented on src/components/Navbar/index.tsx
> +  }, [ledgerLiveAccountAddress])
aa77615b5854065f868189231ccb5630e4ef2415

2023-12-13 15:00 UTC, michalsmiarowski commented on src/components/Navbar/index.tsx
> +      dispatch(walletConnected(ledgerLiveAccountAddress || ""))
I think you're right. Thanks! Fixed in aa77615b5854065f868189231ccb5630e4ef2415

2023-12-13 15:02 UTC, michalsmiarowski commented on src/components/SubmitTxButton.tsx
> -  if (active && isSdkInitializedWithSigner) {
I've actually didn't remove it. It's [right there](https://github.com/threshold-network/token-dashboard/pull/655/files/84a6bf7613cf1bcd18ffd0c40fc2097dab54ec3d#diff-9bffa157d0de0d9b2b6c0d255b374afe06eef491d3dee3b07f773032a9adb308R25) 😇 It looks like this in the diff because I've also added `onConnectWalletClick` funcion above it.

2023-12-13 15:06 UTC, michalsmiarowski commented on src/contexts/TokenContext.tsx
> +  const { chainId } = useWeb3React()
2e5ce7d943599a9662811d28ee7b93f68df3ebb0

2023-12-13 20:24 UTC, r-czajkowski approved these changes

2023-12-14 09:50 UTC, kkosiorowska approved these changes

2023-12-14 09:50 UTC, merged