Add No Bridge Dees annoucement banner.
threshold-network/token-dashboard pull request #702
Opened 2023-12-19 09:05 UTC by michalsmiarowski

Ref: #695 

TODO:
- [ ] Add gradient overflay to the banner

2023-12-19 16:13 UTC, kpyszkowski commented on src/static/images/santa-is-coming.svg
Please optimize the file. It it  >6 MB, causing delay between page load and image load.
You can use https://jakearchibald.github.io/svgomg/

2023-12-19 16:23 UTC, kpyszkowski commented on src/static/images/santa-is-coming.svg
I have analyzed it with designs and it turned out to be raster graphics so it is pointless to export it as an SVG file.
Please export the file as PNG, update asset file and update imports.

2023-12-19 17:25 UTC, kpyszkowski commented on src/pages/Overview/NoBridgeFeesBanner.tsx
> +      backgroundSize={"cover"}
It turns out Figma interprets blending modes its own way - not exact the same as CSS implementations so it's impossible to achieve pixel perfect effect.
```suggestion
           backgroundImage={`url(${santaIsComing}),linear-gradient(8deg, hsla(269, 100%, 50%, 100%) 20%, hsla(269, 100%, 50%, 35%) 70%)`}
      backgroundBlendMode={"color-dodge"}
      filter={"contrast(1.05) saturate(1.05) brightness(1.02)"}
```
With help of CSS filters I was able to finetune the effect. Not pixel perfect but quite decent.

2023-12-19 17:41 UTC, SorinQ commented
I don't think we need to recreate the gradient from code. 
Please just export the image as a .png and include the effect on the image.

<img width="1040" alt="Final" src="https://github.com/threshold-network/token-dashboard/assets/37292909/b4c20ac3-7f70-4ed1-8497-817aa1fb1de9">

On Mobile, please align content to left, in-line with "tBTC Bridge Stats, Total supply..."

2023-12-19 17:42 UTC, SorinQ commented
Also, please note the height of the banner has been reduced.

2023-12-20 00:50 UTC, kpyszkowski commented on src/pages/Overview/NoBridgeFeesBanner.tsx
> +          Start minting
```suggestion
          Start Minting
```

2023-12-20 13:34 UTC, michalsmiarowski commented on src/static/images/santa-is-coming.svg
I've exported is as PNG: 0f1a69d3448041695d2d1586f137b0059622bc92. Thanks! 

The size of it is now 965 kb, so ~6 times lower than before. Do you think it's good enough?

2023-12-20 13:35 UTC, michalsmiarowski commented on src/pages/Overview/NoBridgeFeesBanner.tsx
> +      backgroundSize={"cover"}
That's a great solution, but I've actually implemented Sorin solution from https://github.com/threshold-network/token-dashboard/pull/702#issuecomment-1863218510. I've exported the image with already applied overlay. See fbeda3dea950a4458212bad0bd5f1e5bbfd385d2

If you think that there are any cons of that solution please let me know.

2023-12-20 13:36 UTC, michalsmiarowski commented
> I don't think we need to recreate the gradient from code. Please just export the image as a .png and include the effect on the image.
> 
> <img alt="Final" width="1040" src="https://private-user-images.githubusercontent.com/37292909/291669236-b4c20ac3-7f70-4ed1-8497-817aa1fb1de9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzg1MTcsIm5iZiI6MTcwMzA3ODIxNywicGF0aCI6Ii8zNzI5MjkwOS8yOTE2NjkyMzYtYjRjMjBhYzMtN2Y3MC00ZWQxLTg0OTctODE3YWExZmIxZGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEzMTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YTk2Mzc5MmFlNzc0NjZiZDU5NTI4Y2I4OTNjNzgyZDNkOTc5N2YxYmI3OTY5ODdmNDQ0MTM2ZDU4Y2Q4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hh6BkbaFsXV_FmtPwpzMpn_BhR5FS7_b9254Pme127I">
> On Mobile, please align content to left, in-line with "tBTC Bridge Stats, Total supply..."

Applied the solution:
Exported the image with the overlay already applied: 0f1a69d3448041695d2d1586f137b0059622bc92
Aligned the content to the left: 0b42838d32e8ddc48555340f355a1247ecf48d16

2023-12-20 13:37 UTC, michalsmiarowski commented
> Also, please note the height of the banner has been reduced.

I've decreased the height of the banner here: 846512a416a03a36b686d14e28a207d89926454e

2023-12-20 13:37 UTC, michalsmiarowski commented on src/pages/Overview/NoBridgeFeesBanner.tsx
> +          Start minting
e2cc3092ae009bc0fae96aba7d8c528da9b31170

2023-12-20 13:59 UTC, kpyszkowski commented on src/static/images/santa-is-coming.svg
Much better but it can be even better 😄  - every kilobyte matters
I processed the image with [tinypng](https://tinypng.com) (the best I know) - 
and it's 230 kB 🤯
Attached the file here so you can replace it. Near zero quality loss, unnoticeable.

![santa-is-coming](https://github.com/threshold-network/token-dashboard/assets/11503879/8b795161-2d03-4732-8db1-6e43c38b03ad)

2023-12-20 14:02 UTC, kpyszkowski commented on src/pages/Overview/NoBridgeFeesBanner.tsx
> +      backgroundSize={"cover"}
Yup, in fact it doesn't make sense to do it with code if we don't manipulate it (effects, animations etc). 
You proposed solution with CSS overlay and I wanted to keep it but the image with overlay already applied is more suitable. GJ 💪🏻

2023-12-20 14:06 UTC, kpyszkowski requested changes

2023-12-20 14:23 UTC, michalsmiarowski commented on src/static/images/santa-is-coming.svg
Nice! Addresed it in 26da303b7fed2fade534e01be4e180f8226dadc1

2023-12-20 14:23 UTC, michalsmiarowski commented on src/static/images/santa-is-coming.png
https://github.com/threshold-network/token-dashboard/pull/702#discussion_r1432779549

2023-12-20 14:27 UTC, kpyszkowski approved these changes

2023-12-20 14:27 UTC, merged