Implement trm wallet screening integration
threshold-network/token-dashboard pull request #736
Opened 2024-02-22 14:13 UTC by evandrosaturnino

2024-04-05 16:06 UTC, michalsmiarowski requested changes
Left two commenta (for now). One is non-blocking so we can leave it for now.

I haven't tested it yet as I need an api key for testing purposes

2024-04-05 16:06 UTC, michalsmiarowski commented on src/components/UpgradeCard/UpgradeCardTemplate.tsx
>          />
I'm wondering if instead of searching for all the buttons that are firing the transaction in the wallet we couldn't just do it at the transaction sending level.

I think in all of those buttons we use [`useSendTransactionFromFn` hook](https://github.com/threshold-network/token-dashboard/blob/main/src/web3/hooks/useSendTransaction.ts#L41), so we could probably just throw an error there before sending the transaction. The problematic thing though, is that the status could be fetching at the moment of clicking the button, so it wouldn't be the best user experience if we would throw an error when the data is still fetching (this would require the user to click the button again, which might be confusing). We could add an alert that we are checking the TRM status of the current address.

We can stick with your solution too, but there is a possibility we will miss out some of the buttons. For example I can se that we've missed the "Authorize Increase" button and some others 🤔 

Regardless, if we want to block users from doing any contract integrations in the dApp when their wallet is flagged as severe risk, we shoudl still throw an error at `useSendTransactionFromFn` hook.

2024-04-08 09:53 UTC, evandrosaturnino commented on src/components/UpgradeCard/UpgradeCardTemplate.tsx
>          />
Thanks for the review! I agree on implementing TRM validation in the useSendTransactionFromFn hook, which has been addressed in  detailed in the [add trm validation to the send transaction hook](https://github.com/threshold-network/token-dashboard/pull/736/commits/6280f15d2220718e3f1e2ea10fa7ff513633816c)

Additionally, for a better user experience, I propose we also include validation at the button level. This way, we can handle validations more effectively while maintaining user convenience. This button-level validation has been centralized in the refactored SubmitTxButton component, addressed in [add trm validation to transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/9ee4918ce8f732d1849a11d8b96edf8cc83bd382) commit. This approach should ensure we don't miss any buttons and enhance overall usability. Appreciate your feedback on this combined strategy!

2024-04-09 09:01 UTC, evandrosaturnino commented on src/web3/hooks/useSendTransaction.ts
> +            ? "We're currently assessing the security details of your wallet."
Addressed in [refactor send transaction hook error handling](https://github.com/threshold-network/token-dashboard/pull/736/commits/43838bec19725708917a7792eacd908cde48f537)

2024-04-09 09:02 UTC, evandrosaturnino commented on src/components/Navbar/WalletConnectionAlert.tsx
> +    if (isBlocked) {
Addressed in [add exclusive alert for trm wallet screening](https://github.com/threshold-network/token-dashboard/pull/736/commits/d6ee24c48aa04db99d23eb970dc1ea466230639e)

2024-04-09 09:02 UTC, evandrosaturnino commented on src/components/Navbar/WalletConnectionAlert.tsx
>    }
Addressed in [add exclusive alert for trm wallet screening](https://github.com/threshold-network/token-dashboard/pull/736/commits/d6ee24c48aa04db99d23eb970dc1ea466230639e)

2024-04-09 09:03 UTC, evandrosaturnino commented on src/components/SubmitTxButton.tsx
> +  isDisabled?: boolean
Addressed in [refactor submit transaction button props](https://github.com/threshold-network/token-dashboard/pull/736/commits/18cd2e0b3159b1657e211134673130be806b753e)

2024-04-09 09:03 UTC, evandrosaturnino commented on src/web3/hooks/useSendTransaction.ts
>          return
Good catch! Addressed in [refactor send transaction hook error handling](https://github.com/threshold-network/token-dashboard/pull/736/commits/43838bec19725708917a7792eacd908cde48f537)

2024-04-09 09:23 UTC, evandrosaturnino commented on src/components/SubmitTxButton.tsx
> +  if (account) {
Understood! Addressed in [add sdk with signer validation in tx button](https://github.com/threshold-network/token-dashboard/pull/736/commits/9747ea960085233cc909fb643064265a79a63576)

Worth mentioning that related to this, I fixed a bug on how the SDK was being initialized in `useInitializeTbtcSdk` hook. To understand the issue, you can replicate it by visiting the production website's page at https://dashboard.threshold.network/upgrade/nu. This page utilizes the `isSdkInitializedWithSigner` validation in the `SubmitTxButton`. Upon loading the page and connecting your wallet (The wallet should be connected soon after the page is loaded), you'll observe that the "Upgrade" button reverts to "Connect your wallet" after a while.

To resolve this, I refactored the hook to avoid concurrent states in the asynchronous function. This enhancement allows the SDK to initialize even if an initialization process is already underway. In such cases, the state set during the first interaction is cancelled. This fix has been applied in [fix sdk initialization hook concurrent issue](https://github.com/threshold-network/token-dashboard/pull/736/commits/e14a0117ff3b92ff27d8d0ad02cb480dc9e7c1e3)

Addressing this issue will enhance the stability of the `SubmitTxButton` component, essential for its repeated use throughout the app from this PR onwards.

2024-04-09 15:55 UTC, michalsmiarowski commented on src/components/Navbar/NavbarComponent.tsx
> +        >
Good idea moving the styles here to the `VStack` 👍 I would just slightly improve it, because it looks little off when two errors are displayed at the same time:

<img width="1052" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/eb179f65-4c67-4863-b5bb-f089141a81bb">

and on smaller resolution:

<img width="1028" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/525d83af-2df7-42a4-8e5d-8910b60aba1b">


Here, let's add `maxWidth` property to ensure it looks good on smaller screens. We should also align the items to the right because we are removing the `w="fit-content"` here which we will add it to each alert (so they will have different width.

```suggestion
        <VStack
          position="absolute"
          paddingRight="40px"
          top="94px"
          right="5.25rem"
          zIndex="10"
          ml="4rem"
          maxWidth={{ base: "38rem", xl: "100%" }}
          alignItems={"flex-end"}
        >
```

2024-04-09 15:55 UTC, michalsmiarowski commented on src/components/Navbar/WalletConnectionAlert.tsx
>        <AlertIcon />
Let's add `w="fit-content"` to the `Alert` component here and `alignSelf="center"` to the `AlertIcon` component (for some reason we set the `alginSelf` to `flex-start` in Chakra theme in `@threshold-network/components`):

```suggestion
    <Alert status={alertStatus} variant="solid" w="fit-content">
      <AlertIcon alignSelf="center" />
```

2024-04-09 15:55 UTC, michalsmiarowski commented on src/components/Navbar/TrmWalletScreeningAlert.tsx
> +      <AlertIcon />
Same as above for this alert

```suggestion
    <Alert status="error" variant="solid" width="fit-content">
      <AlertIcon alignSelf="center" />
```

2024-04-09 15:55 UTC, michalsmiarowski commented on src/components/SubmitTxButton.tsx
> +  isDisabled?: boolean
Non blocking but we could just removed it from the interface like i wrote and destructure it in the parameters like it was before 😛 No need to additionaly destructure it from `...buttonProps` if we keep it in component parameters:

```
const SubmitTxButton: FC<SubmitTxButtonProps> = ({
  onSubmit,
  isLoading,
  isDisabled,
  children,
  ...buttonProps
}) => {
```

2024-04-09 17:11 UTC, michalsmiarowski requested changes

2024-04-09 17:11 UTC, michalsmiarowski commented on src/components/Forms/TokenAmountForm.tsx
> +  isLoading = false,
I think we don't need `isLoading` property in `TokenAmountFormBase`? It looks like we don't pass such property anywhere 🤔

2024-04-10 01:48 UTC, evandrosaturnino commented on src/components/SubmitTxButton.tsx
> +  if (account) {
https://github.com/threshold-network/token-dashboard/assets/60587527/7789a5c2-556b-42d8-8201-37836c8279e7
For you to be able to reproduce the issue, you should refresh the app and connect your wallet right after, then you will see the "Connect Wallet" change to "Upgrade" on connection, then regressing to "Connect Wallet" after a few seconds.

I can definitely apply this fix on a separate PR, however worth mentioning I'm a bit concerned on getting this PR merged without addressing this because this same button that is being affected by the `useInitializeTbtcSdk ` is being implemented multiple times over the app, so all contract interactions will have this same issue.

2024-04-10 01:54 UTC, evandrosaturnino commented on src/utils/trmAPI.ts
> +      "https://api.trmlabs.com/public/v2/screening/addresses",
Yes, we have a link to their documentation but it has exclusive access, so I sent you the credentials privately in Discord.

2024-04-10 01:57 UTC, evandrosaturnino commented on src/store/account/effects.ts
> +    )
Yes, this has been discussed in Integrations's guild call, and it has been collectively decided to be using `Severe` as the blocking parameter following some DeFi examples usage, e.g. Balancer: https://github.com/balancer/balancer-api/blob/ca1ad6158096f6674a55baacbafdd1117a724c18/src/lambdas/check-wallet.ts

2024-04-10 08:06 UTC, evandrosaturnino commented on src/components/Navbar/WalletConnectionAlert.tsx
>        <AlertIcon />
Addressed in [apply styling to alert related components](https://github.com/threshold-network/token-dashboard/pull/736/commits/39e6e2d006412856ad90c9c80e4f9d712ea3d6e6)

2024-04-10 08:07 UTC, evandrosaturnino commented on src/components/Navbar/NavbarComponent.tsx
> +        >
Addressed in [apply styling to alert related components](https://github.com/threshold-network/token-dashboard/pull/736/commits/39e6e2d006412856ad90c9c80e4f9d712ea3d6e6)

2024-04-10 08:07 UTC, evandrosaturnino commented on src/components/Navbar/TrmWalletScreeningAlert.tsx
> +      <AlertIcon />
Addressed in [apply styling to alert related components](https://github.com/threshold-network/token-dashboard/pull/736/commits/39e6e2d006412856ad90c9c80e4f9d712ea3d6e6)

2024-04-10 08:07 UTC, evandrosaturnino commented on src/pages/tBTC/Bridge/components/BridgeProcessEmptyState.tsx
> +      </SubmitTxButton>
Addressed in [update text and add comments to transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/66453cdd408be87fe7e8e34effca5eb698aa20c9)

2024-04-10 08:07 UTC, evandrosaturnino commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      <SubmitTxButton
Addressed in [update text and add comments to transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/66453cdd408be87fe7e8e34effca5eb698aa20c9)

2024-04-10 08:07 UTC, evandrosaturnino commented on src/pages/tBTC/Bridge/Minting/ProvideData.tsx
> +      <SubmitTxButton
Addressed in [update text and add comments to transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/66453cdd408be87fe7e8e34effca5eb698aa20c9)

2024-04-10 08:08 UTC, evandrosaturnino commented on src/components/Forms/TokenAmountForm.tsx
> +  isLoading = false,
Addressed in [remove unused loading prop](https://github.com/threshold-network/token-dashboard/pull/736/commits/83bafb461e97ae9da4c449c6e30b183dfd7d6414)

2024-04-10 08:09 UTC, evandrosaturnino commented on src/components/SubmitTxButton.tsx
> +  isDisabled?: boolean
Addressed in [refactor button props destructure in transaction button](https://github.com/threshold-network/token-dashboard/pull/736/commits/d546631fa8c5491bbfee9c4bc06269712f368b31)

2024-04-11 07:00 UTC, evandrosaturnino commented on src/components/SubmitTxButton.tsx
> +  if (account) {
Understood, thank you for the detailed explanation.
Reverted the fix in: [revert initialize sdk hook fix for racing condition](https://github.com/threshold-network/token-dashboard/pull/736/commits/69bb360d82ffada143853ecbac648866a0bc670b)
Added `isTbtcTransaction` validation in [add tbtc transaction validation in tx button](https://github.com/threshold-network/token-dashboard/pull/736/commits/cfe6851ab7cf1650d44608c0abb06b2d729b77eb)

And opened the issue for the bug: https://github.com/threshold-network/token-dashboard/issues/749

2024-04-11 23:11 UTC, michalsmiarowski requested changes
Looking quite good except one last thing. I've added (probably) last comments

2024-04-15 07:14 UTC, evandrosaturnino commented on src/pages/tBTC/Bridge/Unmint.tsx
> +      <SubmitTxButton
Addressed in [update tbtc validation in transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/18a74c5248703b1cb3b6e59d541cfd72b7853a09)

2024-04-15 07:14 UTC, evandrosaturnino commented on src/pages/tBTC/Bridge/ResumeDeposit.tsx
> +      <SubmitTxButton
Addressed in [update tbtc validation in transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/18a74c5248703b1cb3b6e59d541cfd72b7853a09)

2024-04-15 07:15 UTC, evandrosaturnino commented on src/pages/tBTC/Bridge/Minting/ProvideData.tsx
> +      <SubmitTxButton
Addressed in [update tbtc validation in transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/18a74c5248703b1cb3b6e59d541cfd72b7853a09)

2024-04-15 07:15 UTC, evandrosaturnino commented on src/components/UpgradeCard/UpgradeCardTemplate.tsx
> +          isTbtcTransaction
Addressed in [update tbtc validation in transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/18a74c5248703b1cb3b6e59d541cfd72b7853a09)

2024-04-15 07:15 UTC, evandrosaturnino commented on src/components/Forms/TokenAmountForm.tsx
> +        isTbtcTransaction
Addressed in [update tbtc validation in transaction buttons](https://github.com/threshold-network/token-dashboard/pull/736/commits/18a74c5248703b1cb3b6e59d541cfd72b7853a09)

2024-04-18 14:00 UTC, michalsmiarowski commented on src/components/SubmitTxButton.tsx
> +  if (account) {
@evandrosaturnino I've addressed the issue in https://github.com/threshold-network/token-dashboard/pull/751

2024-04-18 14:10 UTC, michalsmiarowski commented
Everything looking good to me 👍 I will wait with an approve until we test it on mainnet

2024-06-07 12:10 UTC, michalsmiarowski requested changes
Left some comments to look at before the merge

2024-06-07 12:10 UTC, michalsmiarowski commented on src/components/Modal/withBaseModal.tsx
> +        <ModalContent alignSelf="center">
This change is a little bit problematic when we have browser console opened. We are not able to scoll to the top to click an `X` button in a modal. I would revert it unless it's needed for something important.


The problem:
<img width="1787" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/5ce331e0-2e1c-4c8f-be20-ee8a395956f3">

_Notice the scroll bar is at the max height and the header is not visible when the chrom console is big enough_

2024-06-07 12:10 UTC, michalsmiarowski commented on src/blocked-wallets/blocklist.json
> +]
Do we want to push this json to production and block these accounts?

2024-06-07 12:26 UTC, michalsmiarowski commented on src/components/Navbar/TrmWalletScreeningAlert.tsx
> +  const [hideAlert, setHideAlert] = useState(false)
152bf000116542ac6d88c6f2a9eb1865b31c0e4e

2024-06-07 12:27 UTC, michalsmiarowski commented on src/components/Modal/withBaseModal.tsx
> +        <ModalContent alignSelf="center">
8f4519aef8efc56d0e40d18cc7e20c748c56844e

2024-06-07 12:27 UTC, michalsmiarowski commented on src/blocked-wallets/blocklist.json
> +]
c881163e515a808b861478c5327f980414462e7e

2024-06-07 12:47 UTC, michalsmiarowski submitted a review, later dismissed
LGTM

2024-06-07 13:23 UTC, michalsmiarowski approved these changes
LGTM 🔥

2024-06-07 13:41 UTC, merged

2024-06-07 13:49 UTC, evandrosaturnino commented on src/blocked-wallets/blocklist.json
> +]
Yes, these wallets have been provided internally as been involved on hack events.

2024-06-07 14:01 UTC, michalsmiarowski commented on src/blocked-wallets/blocklist.json
> +]
Got it! Reverted it in #761