Remove No Bridge Fees annoucement banner
threshold-network/token-dashboard pull request #738
Opened 2024-02-22 14:31 UTC by evandrosaturnino

## Description 

- [X] - [Remove no bridge fees banner](https://github.com/threshold-network/token-dashboard/commit/413140adda129061de935652bfb4a0b81f6bea84)

## Notice 

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change? 

## Pull Request Type 

- [x] New Feature (Breaking/Non-breaking Change) 

## Issue (if applicable)

Closes issue #737

2024-02-23 15:30 UTC, michalsmiarowski requested changes
Left some changes to look at before the merge

2024-02-23 15:30 UTC, michalsmiarowski commented on src/pages/Overview/index.tsx
> -      {featureFlags.TBTC_V2 && <NoBridgeFeesBanner mb={"4"} />}
It looks like it only remove `NoBridgeFees` banner from overview page, but doesn't remove the badge from tbtc subpage:

<img width="516" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/0f74ab88-ed37-4456-8fbd-362e6f57d898">

Please take a look at #702 and #711. Ideally most of the changes applied there (or even all of them, not sure) should be reversed.

2024-02-23 15:30 UTC, michalsmiarowski commented on src/pages/Overview/index.tsx
> -      {featureFlags.TBTC_V2 && <NoBridgeFeesBanner mb={"4"} />}
I'm just wondering - do we want to remove the banner completely? Or revert to the old banner which was "The new tBTC app is here"?

<img width="1175" alt="image" src="https://github.com/threshold-network/token-dashboard/assets/40306834/0d447c4b-da40-4391-a24a-2c7538230ccd">

2024-02-23 18:46 UTC, evandrosaturnino commented on src/pages/Overview/index.tsx
> -      {featureFlags.TBTC_V2 && <NoBridgeFeesBanner mb={"4"} />}
Thanks for bringing that up, addressed in https://github.com/threshold-network/token-dashboard/pull/738/commits/947d8818d745429bb6d4a029e37981cf774e9b78

2024-02-23 18:49 UTC, evandrosaturnino commented on src/pages/Overview/index.tsx
> -      {featureFlags.TBTC_V2 && <NoBridgeFeesBanner mb={"4"} />}
Good point, would like to know your opinions @erdogan and @SorinQ

2024-02-27 20:18 UTC, erdogan commented on src/pages/Overview/index.tsx
> -      {featureFlags.TBTC_V2 && <NoBridgeFeesBanner mb={"4"} />}
Let's reinstate the banner, with a copy revision:  
- Replace "The NEW tBTC dApp is here!" with "Get your Bitcoin to work!" 
- Replace button label "Start Minting" with "Mint tBTC"

2024-02-27 23:10 UTC, evandrosaturnino commented on src/pages/Overview/index.tsx
> -      {featureFlags.TBTC_V2 && <NoBridgeFeesBanner mb={"4"} />}
Thanks, addressed in [Add mint tbtc banner back](https://github.com/threshold-network/token-dashboard/pull/738/commits/059e0c979e19938e52d81d6b60fa5a3e1329c7b1)

2024-02-28 09:10 UTC, michalsmiarowski approved these changes
LGTM 🔥

2024-02-28 09:25 UTC, merged