Fix update handler validation
threshold-network/token-dashboard pull request #769
Opened 2024-07-19 08:56 UTC by evandrosaturnino

## Description

A bug was identified when connecting WalletConnect to Gnosis Safe via the wc pairing API: Shortly after a user connects their Gnosis Safe vault to the app, the connection was disconnected. 
Upon investigation, it was discovered that the connection between WalletConnect and Gnosis Safe was being interrupted due to the chainId format generated after connecting to Gnosis Safe. This triggered an update that disrupted the connection because of the way the update validation was structured in App.tsx.

Depending on the format in which the chainId is being passed by a 3rd party service, it may trigger an update. To handle these edge cases, this PR aims to add a more comprehensive validation method similarly to what has already been done previously in the commit [@3ca72b93ca72b9](https://github.com/threshold-network/token-dashboard/pull/565/commits/3ca72b9f9739ccda2bf365b31ab17f588f3b7f57).

- [X] - [fix update handler validation](https://github.com/threshold-network/token-dashboard/commit/5d0e4556a9c6f631891cc16fa757b025c7219a6b)

## Type of change

- [x] 🐛 Bug fix (Non-breaking Change: Fixes an issue)
- [ ]  🛠️ Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ]  💅 New Feature (Breaking/Non-breaking Change)

## Notice

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Issue (if applicable)

closes https://github.com/threshold-network/token-dashboard/issues/768

## Pull Request Type

- [x] New Feature (Breaking/Non-breaking Change)

2024-07-24 16:53 UTC, somaweb3 commented
LGTM

2024-07-26 17:00 UTC, michalsmiarowski requested changes

2024-07-26 17:00 UTC, michalsmiarowski commented on src/web3/utils/address.ts
> +
This probably will work for mainnet but doesn't work for Sepolia. The id returned from gnosis is in hex value so it's not enough to prefix it wit h`0x` (although for mainnet it's probably enough because 1 as hex is 0x1). For Sepolia, the returned value from Gnosis is `0xaa36a7`, and the int value is `11155111`. You can also check those values in https://chainlist.org/?chain=11155111&testnets=true&search=sepolia for example. 

Besides the function name nad it's variable names are counter intuitive IMO. Here we assume that `chainId1` will be the value in hex while `chainId2` is just normal value, without `0x` prefix (that's why we add it in the end). I believe the names should indicate which is which, but tbh it should not matter, and it should properly check if it's the same chain id without the need to worry about shich should i pass first. 

I think that we should first detect if any of this numbers is a hex by checking if it's starts with `0x` (there might be better ways to check it so please check it out).

If not, then we just compare those two as string.

If both of them are, then we can also compare them as strings.

But if only one of them is hex, then we should convert the other one to hex first. `ethers` provides a function for that:

```
ethers.utils.hexlify(Number(value))
 ```

2024-07-29 20:51 UTC, evandrosaturnino commented on src/web3/utils/address.ts
> +
@michalsmiarowski After further investigation, I found that the `hexlify` method in the `@ethersproject/bytes` library already performs acomprehensive validation on the value type passed as a parameter. It accept and check strings, numbers, and hex values (returning them as they were originally provided). The method also converts the input to a lowercase hex format. Given that chainId can be in string, number, or hex format, I believe the best way to ensure their equivalence is by passing them through the hexlify function: [refactor chain ID validation commit](https://github.com/threshold-network/token-dashboard/pull/769/commits/c2acee58f8b72d1b5f0299581cbf870aad8d4b51).

You can find the implementation of the hexlify function in Ethers v5.4.7 [here](https://github.com/ethers-io/ethers.js/blob/32a6b2a362815eb85ce3f3abad5adf92f2b80e10/packages/bytes/src.ts/index.ts#L193).

Please let me know if you think additional redundancy checks are necessary in this function.

2024-07-30 14:38 UTC, michalsmiarowski commented on src/web3/utils/address.ts
> +
Looking good now 🔥

2024-07-30 14:39 UTC, michalsmiarowski approved these changes
LGTM 🔥

2024-07-30 14:40 UTC, merged