check if provider has been used before staking
threshold-network/token-dashboard pull request #88
Opened 2022-02-10 18:52 UTC by georgeweiler

2022-02-10 18:58 UTC, georgeweiler commented
@r-czajkowski This implementation works without formik async validation. If it's okay with you I will add formik validation in a separate PR so I can do all of our forms at once and keep new web3 logic out of the pull request

2022-02-17 12:46 UTC, r-czajkowski requested changes

2022-02-17 12:46 UTC, r-czajkowski commented on src/web3/hooks/useCheckDuplicateProviderAddress.ts
> +      // TODO Add Check for Nu/PRE stakes
As I can see in [`stake` function](https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/TokenStaking.sol#L265-L307) there are no restrictions on using the same provider address as on Nu or PRE side. So I think that's all we need. cc @Battenfield

2022-02-17 12:46 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +  }, [isProviderInUse])
Missing dependency: `onToggle`.

2022-03-02 20:26 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +    [isProviderUsedForKeep, isProviderUsedForT]
Good call, I tend to get carried away with `useMemo`

2022-03-02 21:00 UTC, georgeweiler commented on src/web3/hooks/useCheckDuplicateProviderAddress.ts
> +      const isProviderUsedForKeep = createdAt.gt(BigNumber.from(0))
Hey @r-czajkowski  yes I love that multicall hook and I tried using it here, but the problem is that the stakingProvider is not available in the scope of the checkIfProviderUsed func that is returned, and the useMutlicall hook cannot be called inside of the `checkIfProviderUsed` func because of stupid react rules.

The caller creates the function like ```const checkIfProviderUsed = useCheckDuplicateProviderAddress()``` At this point the `stakingProvider` is not available, so we can't pass it to the hook to build the checkIfProviderUsed method. Instead we need to pass it to the `checkIfProviderUsed` func when it is invoked.

`checkIfProviderUsed` has the interface ```(provider: string) => Promise<{
    isProviderUsed: boolean
    isProviderUsedForKeep: boolean
    isProviderUsedForT: boolean
  }>```


I will try to find a way to make it work, but it might be easiest to avoid the multicall hook. Any thoughts?

2022-03-11 08:50 UTC, r-czajkowski submitted a review, later dismissed

2022-03-21 14:20 UTC, michalinacienciala commented
If you're wondering why the tests are failing - it's because GH has changed how it handles nmp/yarn dependencies downloaded using `git://` protocol (and we use that when we're updating some of our packages). Workaround for that will be delivered in https://github.com/threshold-network/token-dashboard/pull/93. After it gets merged, the `DAPP-565-check-provider-before-staking` branch will need to be updated to include latest changes from `main`.
After that the tests should no longer fail due to `unauthenticated git protocol` error.

2022-03-23 13:01 UTC, r-czajkowski commented
Closing this issue because most of the changes are unnecessary because we added a `formik` lib in #91. Just copied the hook implementation from [0990653](https://github.com/threshold-network/token-dashboard/pull/88/commits/0990653d6bab917e0bdd8d711b282c3da3c00fe6). Please see [dd09e70](https://github.com/threshold-network/token-dashboard/pull/91/commits/dd09e70dc2ff464acd60b302ce638c4cd24a2fc5)

2022-03-23 13:02 UTC, r-czajkowski commented
Closing this issue because most of the changes are unnecessary because we added a `formik` lib in #91. Just copied the hook implementation from [0990653](https://github.com/threshold-network/token-dashboard/pull/88/commits/0990653d6bab917e0bdd8d711b282c3da3c00fe6). Please see [dd09e70](https://github.com/threshold-network/token-dashboard/pull/91/commits/dd09e70dc2ff464acd60b302ce638c4cd24a2fc5).

2022-03-23 13:02 UTC, closed without merging