Legacy stakes
threshold-network/token-dashboard pull request #91
Opened 2022-03-03 16:15 UTC by r-czajkowski

WIP...

2022-03-03 16:33 UTC, georgeweiler commented on src/components/CopyToClipboard/index.tsx
> +  textCopiedMsg = "Copied!",
just a thought... a toast could be nice for this. Not sure if we have designs to follow.

https://chakra-ui.com/docs/feedback/toast

2022-04-21 14:39 UTC, georgeweiler commented on src/pages/Staking/StakeCard/index.tsx
> +      <Flex mt="4" alignItems="center">
Should we remove this commented code?

2022-04-21 14:40 UTC, georgeweiler commented on src/pages/Staking/StakeCard/index.tsx
> +        <NotificationPill colorScheme="brand" mr="2" variant="gradient" />
I am getting a typescript error on this component because of the variant:

```
Type 'string' is not assignable to type 'undefined'.  TS2322

    66 |           {isInActiveStake ? "inactive" : "active"}
    67 |         </Badge>
  > 68 |         <NotificationPill colorScheme="brand" mr="2" variant="gradient" />
       |                                                      ^
    69 |         <Label3 textTransform="uppercase" mr="auto">
    70 |           stake - {stakeType}
    71 |         </Label3>
```

2022-04-21 14:44 UTC, georgeweiler commented on src/components/ExternalLink/SharedLinks.tsx
> +      <Body3 color={color} textAlign="center" {...props}>
we dropped the `mt={4}` from the previous version. Let's add it back. Or maybe add top margin for each instance? up to you.
![Screen Shot 2022-04-21 at 8 42 11 AM](https://user-images.githubusercontent.com/15269424/164483755-cab3ad1d-4d0b-410f-b8a1-643e4c1cb835.png)

2022-04-21 14:50 UTC, georgeweiler commented on src/components/Forms/SimpleTokenAmountForm.tsx
> +  label = "Stake Amount",
I think this label is too specific for the component. Could we use `Token Amount` instead? and pass `Stake Amount` where it's needed?

2022-04-21 14:51 UTC, georgeweiler commented on src/components/Forms/SimpleTokenAmountForm.tsx
> +                {maxTokenAmount ? formatTokenAmount(maxTokenAmount) : "--"} T
Is it okay to hard-code `T` as the token? Same for the placeholder below. It might be best to make this more generic so it can be used with Keep and Nu, or other tokens.

2022-04-21 14:53 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +    <Form id={formId}>
wow this is so much cleaner!  😍

2022-04-21 14:53 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +        label="Authrozier Address"
typo: `Authorizer`

2022-04-21 16:32 UTC, georgeweiler commented on src/utils/forms.ts
> +  return `The value should be less than or equal ${formatTokenAmount(
Is the logic for these strings backwards? I think we want to say 

- `value should be *more* than min`
- `value should be *less* than max

2022-04-21 16:33 UTC, georgeweiler commented on src/components/ChecklistItem/index.tsx
> +import { BsFillArrowRightCircleFill as Icon } from "react-icons/all"
can you link the designs for this change? just curious

2022-04-21 16:38 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +        helperText="This authorizer will authorize applications."
Did sasha provide this copy? If no, can we change to `This address will authorize applications.`?

2022-04-21 16:40 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +          await checkIfProviderUsed(values.stakingProvider)
we have no way to check for NU, right?

2022-04-21 16:44 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  })
Are we sure we want this effect to run on every single render? I think we are missing some dependencies like `hasBeenValidatedOnMount`. Or perhaps using `[]` as the dependency array could achieve the same result rather than saving and updating the `hasBeenValidatedOnMount` value?

2022-04-21 16:46 UTC, georgeweiler commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +            Staking uses an ApproveAndCall function which requires one
is this right?

2022-04-21 16:55 UTC, georgeweiler commented on src/components/Modal/StakingSuccessModal/index.tsx
> +            <Body3 mt="2.5rem !important" align="center">
no change required. I just want to say that I hate that the `<Stack>` component forces us to use `!important`. I really disagree with how they built it.

https://github.com/chakra-ui/chakra-ui/issues/1121#issuecomment-655352939

2022-04-21 16:57 UTC, georgeweiler commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +    return `Unstake legacy ${hasKeepStake && hasNuStake ? token : ""} stake`
is this logic right? Don't we want the `hasLegacyStake` var?

2022-04-21 17:03 UTC, georgeweiler commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +            {hasNuStake && (
Have you QA'd a wallet that has all 3 stakes? I don't have one but wondering what the tabs look like if there are 3 of them

2022-04-21 17:06 UTC, georgeweiler commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +                <SimpleTokenAmountForm
flagging that the props passed to these legacy forms are quite different.  (no helper text for NU, disabled for keep, no `hasLegacyStake` for keep, etc.) Is that intentional? Shouldn't they have fairly similar user interfaces?

2022-04-21 17:09 UTC, georgeweiler commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +  const getUnstakeAllBtnHelperText = () => {
I think this is a good usecase for `useMemo` instead of a function that is invoked on every render in the JSX:

```
const getUnstakeAllBtnHelperText = useMemo(() => {
  const suffix =
      hasNuStake && hasKeepStake ? "KEEP + NU" : hasKeepStake ? "KEEP" : "NU"
    return `Unstakes max of both native tokens and legacy tokens (${suffix} + T)`
}, [hasNuStake, hasKeepStake])
```

2022-04-21 18:13 UTC, georgeweiler commented on src/web3/hooks/useUnstakeTransaction.ts
> +          : [stakingProvider]
is this omitting the amount from KEEP unstakes? Is that because it's always a 100% unstake?

2022-04-21 18:20 UTC, georgeweiler commented on src/web3/hooks/useCheckDuplicateProviderAddress.ts
> +  isProviderUsedForT: boolean
I might have already asked, but why can't we include NU here?

2022-04-21 18:36 UTC, georgeweiler commented on src/pages/Staking/RewardsCard.tsx
> +          retroactively for March and April.
This copy will become stale shortly. Wonder if we should revise or determine the month programmatically?

2022-04-21 18:37 UTC, georgeweiler commented on src/enums/externalHref.ts
> +  nuDapp = "URL needed",
Flagging that this is still needed

2022-04-22 09:50 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/index.tsx
> +        <NotificationPill colorScheme="brand" mr="2" variant="gradient" />
You have to run `yarn`. I added support for generating types for new components or new variants of components. Please see https://github.com/threshold-network/token-dashboard/pull/91/commits/d4a9374c52c954c9a384c9c74231b2afdbbc198f.

2022-04-22 10:22 UTC, r-czajkowski commented on src/components/Forms/SimpleTokenAmountForm.tsx
> +                {maxTokenAmount ? formatTokenAmount(maxTokenAmount) : "--"} T
Yeah great suggestion! I'll update!

2022-04-22 10:57 UTC, r-czajkowski commented on src/components/ChecklistItem/index.tsx
> +import { BsFillArrowRightCircleFill as Icon } from "react-icons/all"
https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=2276%3A107185

2022-04-22 11:17 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +          await checkIfProviderUsed(values.stakingProvider)
I think nope. According to the source code of the staking contract, there are no limitations for NU https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/TokenStaking.sol#L276-L285.

2022-04-22 11:32 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +  })
I decided to set up the guard `hasBeenValidatedOnMount` because we use `onOpen` function from `useDisclosure` in the `useEffect` hook so we can't (actually, we can but the react docs says:  if any variable is used inside the hook but is defined outside of it, then it should go in the dependency array.) use an empty dependency array. Inside `forceFormValidation` is a guard `if (hasBeenValidatedOnMount || !formRef.current) return` so the form validation will  be triggered only once.

2022-04-22 11:34 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +            Staking uses an ApproveAndCall function which requires one
Good catch! Nope! This is a two step flow (`TTokenContract.approve` then `TStakingContract.stake`).

2022-04-22 11:45 UTC, r-czajkowski commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +    return `Unstake legacy ${hasKeepStake && hasNuStake ? token : ""} stake`
I think is OK because we want to add the `token` prefix only if user has NU and KEEP stake. Otherwise we want to skip. eg:
- `T + KEEP` -> `Unstake T | Unstake legacy stake`,
- `T + NU` -> `Unstake T | Unstake legacy stake`,
- `T + KEEP + NU` -> `Unstake T | Unstake legacy KEEP stake | Unstake legacy NU stake`,
- `KEEP + NU` -> `Unstake legacy KEEP stake | Unstake legacy NU stake`.

2022-04-22 11:51 UTC, r-czajkowski commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +            {hasNuStake && (
I just set `hasNuStake` to `true` here is a preview:

![image](https://user-images.githubusercontent.com/57687279/164708952-557dd563-1069-4f83-8fc3-d8adada5bc37.png)

2022-04-22 11:52 UTC, r-czajkowski commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +                  isDisabled
Because we can only unstake the all legacy KEEP stake, so user can't type the amount to unstake.

2022-04-22 11:55 UTC, r-czajkowski commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +                <SimpleTokenAmountForm
Yes it is intentional. Regarding KEEP - we want to inform users that they can only unstake KEEP legacy stake in full amount. Regarding NU there are no helper text in design.

2022-04-22 11:56 UTC, r-czajkowski commented on src/web3/hooks/useUnstakeTransaction.ts
> +          : [stakingProvider]
Exactly, you can only unstake the legacy KEEP stake in full amount.

2022-04-22 12:02 UTC, r-czajkowski commented on src/web3/hooks/useCheckDuplicateProviderAddress.ts
> +  isProviderUsedForT: boolean
Please see https://github.com/threshold-network/token-dashboard/pull/91#discussion_r856130915.

2022-04-22 12:04 UTC, r-czajkowski commented on src/pages/Staking/RewardsCard.tsx
> +          retroactively for March and April.
Hm... we don't have the rewards contract yet and I was taking it as a placeholder 🤔

2022-04-22 12:08 UTC, r-czajkowski commented on src/enums/externalHref.ts
> +  nuDapp = "URL needed",
[4dc8cbb](https://github.com/threshold-network/token-dashboard/pull/91/commits/4dc8cbb1351db51ddb32ce6bcbb94fbc8f2c03d7)

2022-04-22 12:09 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/index.tsx
> +      <Flex mt="4" alignItems="center">
[bb7c4fc](https://github.com/threshold-network/token-dashboard/pull/91/commits/bb7c4fca88a182cc1b65a9bd2c8b1df36d603a32)

2022-04-22 12:09 UTC, r-czajkowski commented on src/components/ExternalLink/SharedLinks.tsx
> +      <Body3 color={color} textAlign="center" {...props}>
[0fd1883](https://github.com/threshold-network/token-dashboard/pull/91/commits/0fd18835a8d8754a1eadd5da850c78210c6db32b)

2022-04-22 12:10 UTC, r-czajkowski commented on src/components/Forms/SimpleTokenAmountForm.tsx
> +type SimpleTokenAmountFormProps = {
[37f91f8](https://github.com/threshold-network/token-dashboard/pull/91/commits/37f91f814c79dcc0cf5cebc2aefed2b96e1b2fca)

2022-04-22 12:10 UTC, r-czajkowski commented on src/components/Forms/SimpleTokenAmountForm.tsx
> +                {maxTokenAmount ? formatTokenAmount(maxTokenAmount) : "--"} T
[0b950d9](https://github.com/threshold-network/token-dashboard/pull/91/commits/0b950d9872b7ad1a750c2c5c150d6a0e0047427c)

2022-04-22 12:10 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +        label="Authrozier Address"
[81ee74c](https://github.com/threshold-network/token-dashboard/pull/91/commits/81ee74c3cccd9674196093f0b2c43f1f8a9b07a3)

2022-04-22 12:11 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/AdvancedParamsForm.tsx
> +        helperText="This authorizer will authorize applications."
[cd29e38](https://github.com/threshold-network/token-dashboard/pull/91/commits/cd29e38b8837c2d5965b38501282c27a7c2d2fab)

2022-04-22 12:11 UTC, r-czajkowski commented on src/components/Modal/ConfirmStakingParams/index.tsx
> +            Staking uses an ApproveAndCall function which requires one
[5fccd5a](https://github.com/threshold-network/token-dashboard/pull/91/commits/5fccd5aa93a3cc08100a9420db84f3d7218154bf)

2022-04-22 12:12 UTC, r-czajkowski commented on src/components/Modal/UnstakeTModal/Step1.tsx
> +  const getUnstakeAllBtnHelperText = () => {
[a9f5cb1](https://github.com/threshold-network/token-dashboard/pull/91/commits/a9f5cb17bd102647ab6a335320f6a26f9b6f1674)

2022-04-22 12:20 UTC, r-czajkowski commented on src/components/CopyToClipboard/index.tsx
> +  textCopiedMsg = "Copied!",
I think we don't have designs for this case at least I can't find them in Figma. I used a `Tooltip` component to indicate a copy action.

![obraz](https://user-images.githubusercontent.com/57687279/164712912-f0c3b233-2173-4cae-9869-51f7237649ce.png)

![obraz](https://user-images.githubusercontent.com/57687279/164713123-be360cfb-824b-479b-9431-953ef208aec6.png)

2022-05-11 10:48 UTC, michalsmiarowski requested changes
Overall looking good. Left some comments to look at. I will test it locally now and give some more comments if needed.

2022-05-12 09:42 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/index.tsx
> +          label="Unstake Amount"
Shouldn't this be dynamic base on the tab we choose? For `Stake` it should be `Stake Amount` and for `Unstake` it should be `Unstake Amount`.


<img width="546" alt="image" src="https://user-images.githubusercontent.com/40306834/168041758-8b52b9a9-c219-4533-ab60-e7b0fe5155d6.png">
_Stake tab is choosen on top, but Unstake amount is shown_

2022-05-12 09:44 UTC, r-czajkowski commented on src/pages/Staking/StakeCard/index.tsx
> +          label="Unstake Amount"
Fixed here fefff9d.

2022-05-12 10:21 UTC, r-czajkowski commented on src/components/Modal/TopupTModal/index.tsx
> +              your initial stake.
I think this UI is not the latest iteration of legacy top-up flow. Here is the latest iteration for legacy top ups https://www.figma.com/file/Tx1lZc7us4SqCeAgbt1hBV/Threshold-Dapp?node-id=2890%3A115788 and I think we should address it in a separate PR.

2022-05-12 10:36 UTC, r-czajkowski commented on src/components/Modal/UnstakeTModal/Step2.tsx
> +              toppped up anytime you want.
5b70ffe

2022-05-12 10:37 UTC, r-czajkowski commented on src/components/TokenBalanceInput/index.tsx
> +          {...inputProps}
e9bc6b2

2022-05-12 10:37 UTC, r-czajkowski commented on src/components/TokenBalanceInput/index.tsx
> +    <FormControl isInvalid={hasError} isDisabled={inputProps.isDisabled}>
e9bc6b2

2022-05-12 10:37 UTC, r-czajkowski commented on src/components/TokenBalanceInput/index.tsx
>    ...inputProps
e9bc6b2

2022-05-12 10:37 UTC, r-czajkowski commented on src/components/NumberInput/index.tsx
> +      disabled={props.isDisabled}
e9bc6b2

2022-05-12 10:37 UTC, r-czajkowski commented on src/components/StakingStats/index.tsx
>          <TokenBalance
7771422

2022-05-12 10:40 UTC, r-czajkowski commented on src/pages/Staking/RewardsCard.tsx
> +          retroactively for March and April.
see https://github.com/threshold-network/token-dashboard/pull/107 we display here the total staking bonus reward.

2022-05-12 10:48 UTC, michalsmiarowski requested changes
Some more comments to look at:

2022-05-12 10:48 UTC, michalsmiarowski commented on src/pages/Staking/index.tsx
> +      >
Non-blocking:

Something to discuss on desing/dev sync is maybe the positioning of the cards. I think the current position doesn't look very appealing to the user's eye in some cases, because of some unoccupied space. It is happening because legacy stake cards have different height than native stake cards. Example:


![image](https://user-images.githubusercontent.com/40306834/168044613-d6d2adeb-c73a-4105-852b-d4fbe70801a2.png)

I think [Masonry Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Masonry_Layout) would fit better here. Something like this:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/40306834/168045672-aa6b3ad1-6f27-45a2-a255-0f10966f7f10.png">

2022-05-12 10:48 UTC, michalsmiarowski commented on src/pages/Staking/StakeCard/index.tsx
> +        </Button>
On Figma we also have `Expand View` button, but i'm not sure what it should do exactly. Are we planning to add this?

<img width="431" alt="image" src="https://user-images.githubusercontent.com/40306834/168049416-157747f7-eb56-4834-92ba-de428ae0ce4e.png">

2022-05-12 10:48 UTC, michalsmiarowski commented on src/web3/hooks/useUnstakeTransaction.ts
> +  type: UnstakeType,
Non-blocking:

@sashatanase Maybe it could be a good idea to inform the user that he won't be able to un-stake for the first 24 hours after doing the stake, before he actually do the stake? Right now we inform him only after he tries to un-stake:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/40306834/168051892-bb605622-6252-4686-9abe-078abc2be1d6.png">

2022-05-12 11:02 UTC, r-czajkowski commented on src/pages/Staking/index.tsx
> +      >
@sashatanase

2022-05-12 11:20 UTC, michalsmiarowski approved these changes
LGTM! Tested it locally and it looks good!

2022-05-12 11:23 UTC, merged